### ISSUE TITLE
[Bug]: github action: vulkan-tools does not compile

### ISSUE THREAD

**Issue by Maxython** [termux/termux-packages#10059]
### Problem description

https://github.com/termux-pacman/termux-packages/actions/runs/2181030422

### What steps will reproduce the bug?

auto update

### System information

This is github actions

**Comment by MrAdityaAlok** [comment]
Please try again. I tested with docker image and it compiles successfully.
Even it compiled when I recently updated it : https://github.com/termux/termux-packages/actions/runs/2180903948

**Comment by MrAdityaAlok** [comment]
Most probably it was because when you pushed changes to your repo, new version of vulkan-headers was still not available in termux repo (evident from `Downloading vulkan-headers@1.3.205` in your CI logs) which caused problems.

In my update case both were updated simultaneously therefore both had same version during build and hence compiled successfully.

Re-run your CI and it should compile successfully.

I will add a version constraint in both packages, so that this doesn't occur again.

**Comment by Maxython** [comment]
Everything compiled successfully.  Thank you.
