### ISSUE TITLE
[Package]: qt5-opengl

### ISSUE THREAD

**Issue by strikersix23** [termux/termux-packages#10120]
### Package description

QT5 module that uses opengl
Even though it is depreciated it is still used by a lot of programs written in qt5 especially certain emulators 
It would be nice to add it even if it can be stubbed 

### Home page URL

https://www.qt.io/

### Source code URL

https://www.qt.io/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/x11-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Mrestof** [comment]
@librehat, @xtkoba, Hello. Joining onto the thread. I use termux with graphics by running just wayland server without proot. I want to use qutebrowser, which needs qt opengl. I looked at the related thread and it seems like opengl support in qtbase doesn't break anything. Should I wait for the support to be added in the future?
And for the time being, could you suggest the correct way to tweak my setup to enable opengl support? I was thinking about smth like this, locally recompiling qtbase, repackaging it and replacing the stock package with the custom one. Thanks in advance.

**Comment by mzen17** [comment]
I am wondering what the status of this package request is.

The [PR](https://github.com/termux/x11-packages/pull/588) to merge it seemed to have been closed because the package would break the qt builds, but what if it was a separate package like qt5-base-opengl (that replaces qt5-base if installed)? The artifacts in the PR seemed to work, so it would be an easy way to add support for such packages without changing/breaking any existing QT installations.

**Comment by spz2020** [comment]
https://github.com/spz2020/termux-packages/actions/workflows/packages.yml Try this
