### ISSUE TITLE
Consider using pacman and PKGBUILD ?

### ISSUE THREAD

**Issue by franciscod** [termux/termux-packages#104]
There is a project similar to termux, that instead of targeting Android targets Windows.

Check its packages here: https://github.com/Alexpux/MSYS2-packages

MSYS2 uses the Arch Linux format for package building, and also uses its package manager: `pacman`.

Maybe pacman could serve useful to this project too :)

Any thoughts?

**Comment by franciscod** [comment]
Also: PKGBUILD usually require md5 or sha1 checksums so they are a bit more secure!

Nowadays most termux packages are downloading stuff via http with no verification whatsoever :-1:

**Comment by cptMikky** [comment]
Hashes aren't a "security" feature, yet I would also like to see pacman as the package manager, purely because I'm used to it :) It is simple, lightweight and secure and it's **much** easier for contributors to create new packages (the aforementioned PKGBUILDs) than for apt or its derivates (such as opkg). This alone could be a good reason to switch.

**Comment by fornwall** [comment]
Apt starts by downloading a GPG-signed file [InRelease](http://apt.termux.com/dists/stable/InRelease) file containing containing SHA-256 hashes for the [Package](http://apt.termux.com/dists/stable/main/binary-all/Packages) files, which themselves contains hashes for listed package. So as long as the trusted GPG key (`$PREFIX/etc/apt/trusted.gpg`) used by apt to verify `InRelease` is not tampered with (which will be guaranteed once the [bootstrap package is downloaded over https soon](https://github.com/termux/termux-packages/issues/89)), both the integrity and security of packages are validated by apt as well!

With that said, I'm open to try out pacman (I've never used it myself)! An initial step would be in creating a `pacman` package in Termux, which would be a normal package that would (at least initially) live alongside apt to install packages itself. Once this is done it can be evaluated as a potential apt replacement for the main Termux repo!

**Comment by franciscod** [comment]
That sounds great!

**Comment by cptMikky** [comment]
Not making any promises but is there some kind of a "package dev/maintainer guideline"? Maybe (or maybe not) I'll have some time during holiday I can put into creating the package.

**Comment by fornwall** [comment]
The README in this project is the best starting point available, as well as following what `build-package.sh` does.

Just ask here or create an issue if you run into any problem!

**Comment by franciscod** [comment]
I'm trying to build pacman on this branch: https://github.com/franciscod/termux-packages/tree/pacman

Currently getting this:
```
../../lib/libalpm/.libs/libalpm.so: error: undefined reference to '__android_log_vprint'
../../lib/libalpm/.libs/libalpm.so: error: undefined reference to '__android_log_print'
```

Any ideas? @fornwall

**Comment by fornwall** [comment]
@franciscod Yes, it's due to Termux [patching &lt;syslog.h&gt;](https://github.com/termux/termux-packages/blob/master/ndk_patches/syslog.patch) to redirect syslog calls (which doesn't do anything on Android) to the system logging system (as used by logcat). However, this requires that the system library `liblog.so` is linked in.

A fix could be either:

1. Remove the syslog calls if it's not very important or used (by patching or using configure), or
2. Add `-llog` when linking so that `liblog.so` is linked in.

**Comment by franciscod** [comment]
great! searched for `liblog` and found this, which i pasted into the `build.sh` and worked!

```
export LDFLAGS="$LDFLAGS -llog" # liblog for android logging in syslog hack
```

now it complains about `glob.h`:
```
ini.c:21:18: fatal error: glob.h: No such file or directory
 #include <glob.h>
```

**Comment by fornwall** [comment]
Great! The `export LDFLAGS="$LDFLAGS -llog"` is a bit of a hack, since it will cause everything to link against liblog, not only the binaries or libraries that need them (but that is not very important at this stage).

For the `glob.h` file: Normally this is provided by the system libc, but the android libc does not support it. However, in Termux you may build the `libandroid-glob` package, which installs `include/glob.h` and `lib/libandroid-glob.so`. So to fix the problem:

1. Build the required package with `./build-package.sh libandroid-glob`.
2. Add libandroid-glob as a dependency for the new pacman package.
3. Add `-landroid-glob` in the same way you added `-llog`.

**Comment by franciscod** [comment]
awesome! I'm starting to get all these patterns... :dancer:

**Comment by franciscod** [comment]
now it has errors on `ctermid`, I see it hardcoded to "/dev/tty" in many packages... (should this be abstracted into a library? maybe libtermux?)

**Comment by fornwall** [comment]
Nice to see your quick progress :)!

For `ctermid`, I think patching `<stdio.h>` to define something like

    static char* ctermid(char* s) {
        if (s == 0) return "/dev/tty";
        strcpy(s, "/dev/tty");
        return s;
    }

should be enough (by adding it to [the stdio.h patch](https://github.com/termux/termux-packages/blob/master/ndk_patches/stdio.h.patch)). Then the patching in `fish` and `perl` could also be removed.

**Comment by franciscod** [comment]
okay, that should be a different issue, right? i'll try to patch stdio :)

now pacman seems to build but i have certain nesting of TERMUX_PREFIX... when i fix this I'll try to compile a basic pkgbuild :D

**Comment by franciscod** [comment]
okayyyyyy:

```
$ makepkg
/data/data/com.termux/files/usr/bin/makepkg: line 2483: /dev/fd/62: No such file or directory
/data/data/com.termux/files/usr/bin/makepkg: line 2483: /dev/fd/62: No such file or directory
/data/data/com.termux/files/usr/bin/makepkg: line 2483: /dev/fd/62: No such file or directory
/data/data/com.termux/files/usr/bin/makepkg: line 2483: /dev/fd/62: No such file or directory
/data/data/com.termux/files/usr/bin/makepkg: line 2483: /dev/fd/62: No such file or directory
/data/data/com.termux/files/usr/bin/makepkg: line 2483: /dev/fd/62: No such file or directory
/data/data/com.termux/files/usr/bin/makepkg: line 2483: /dev/fd/62: No such file or directory
/data/data/com.termux/files/usr/bin/makepkg: line 2483: /dev/fd/62: No such file or directory
/data/data/com.termux/files/usr/bin/makepkg: line 2483: /dev/fd/62: No such file or directory
/data/data/com.termux/files/usr/bin/makepkg: line 2483: /dev/fd/62: No such file or directory
/data/data/com.termux/files/usr/bin/makepkg: line 2483: /dev/fd/62: No such file or directory
/data/data/com.termux/files/usr/bin/makepkg: line 2483: /dev/fd/62: No such file or directory
/data/data/com.termux/files/usr/bin/makepkg: line 2483: /dev/fd/62: No such file or directory
==> Making package: p7zip 9.38.1-4 (Thu Dec 24 01:29:49 ART 2015)
==> Checking runtime dependencies...
bionic/libc/upstream-netbsd/lib/libc/regex/regfree.c:110: regfree: assertion "preg->re_magic == MAGIC1" failed
==> ERROR: 'pacman' returned a fatal error (134): 
$ 
```

no clue on how to continue :D

**Comment by fornwall** [comment]
@franciscod Well that looks strange. You are welcome to submit what you have as `disabled-packages/pacman`, so that I and others can look and try it out more easily!

**Comment by franciscod** [comment]
done. hope this helps!

**Comment by 4679** [comment]
When I try to build pacman,it says "configure:3850: error: C compiler cannot create executables"

This is a part of config.log.
https://pastebin.mozilla.org/8856829

**Comment by fornwall** [comment]
@4679 The errors

    ld: error: cannot find -landroid-glob
    ld: error: cannot find -landroid-support

means that you have to build these requirements first:

    apt install libandroid-support
    apt install libandroid-glob

**Comment by 4679** [comment]
@fornwall Thanks,I'll try.

**Comment by fornwall** [comment]
@franciscod The `/dev/fd/62: No such file or directory` was probably due to process substitution (using `<(...)`) not working in bash under Termux. This has just been fixed in version `4.3.42-7` of the bash package which is available as an update. Can you try if `makepkg` works better now?

**Comment by franciscod** [comment]
@fornwall I'll try it!

**Comment by bricewge** [comment]
`makepkg` doesn't throw the `/dev/fd/62` error anymore.

**Comment by sdrausty** [comment]
These utilities should be available through PRoot Arch Linux in Termux.  Tapping this link https://sdrausty.github.io/TermuxArch/setupTermuxArch.sh will transfer `setupTermuxArch.sh` to your device. Simply run `bash setupTermuxArch.sh` to install Arch Linux in Termux on your device.  Enjoy 🎼

**Comment by xeffyr** [comment]
For now there no plans to change package manager. But we have apk-tools (package manager from Alpine Linux) packaged, though there no repository for it: https://github.com/termux/termux-packages/tree/master/packages/apk-tools.
Abuild is available too: https://github.com/termux/termux-packages/tree/master/packages/abuild. It is similar to ArchLinux's `makepkg`, even syntax for APKBUILDs is similar. That's if someone want to try `apk` package manager. But as I wrote above - package manager won't be changed until there will be significant reason to do so.

**Comment by Maxython** [comment]
Hi @franciscod.  I want to tell you that it is already possible to install (compile) pacman on termux.  It is still in development and is not completely set up, but there are already some successes.

**Comment by danog** [comment]
Personally, I'm all for switching to pacman in termux, for the following reasons:
- Extreme simplicity of the PKGBUILD file
- Extreme simplicity of the package itself, consisting of a single (!) tarfile (instead of an ar archive containing a versionfile, and two tarfiles compressed with gzip).
- Pacman packages are usually compressed with the new [zstandard compression](https://github.com/facebook/zstd), which offers [insanely high decompression speeds](https://archlinux.org/news/now-using-zstandard-instead-of-xz-for-package-compression/): 1300% decompression speed compared to xz, with the same compression ratio as xz.
- I also noticed that pacman itself is also insanely fast compared to apt (practically no waiting time for package database parsing).

I'd love to help out in a porting/migration to pacman, possibly a bit more into July as my exams ease up ;)
