### ISSUE TITLE
[Bug]: Could not use php7-apache

### ISSUE THREAD

**Issue by yucho123987** [termux/termux-packages#10624]
### Problem description

httpd: Syntax error on line 67 of /data/data/com.termux/files/usr/etc/apache2/httpd.conf: Cannot load /data/data/com.termux/files/usr/libexec/apache2/libphp7.so into server: dlopen failed: cannot locate symbol "EVP_PKEY_id" referenced by "/data/data/com.termux/files/usr/libexec/apache2/libphp7.so"...

### What steps will reproduce the bug?

Follow this article:
https://parzibyte.me/blog/en/2019/04/28/install-apache-php-7-android-termux/

### System information

termux-info:
Latest version from the F-Droid
```

```

**Comment by xtkoba** [comment]
Thanks for the report.

I have found something interesting:

```
$ readelf -Wa libexec/apache2/libphp7.so | grep "NEEDED.*libcrypto"
 0x0000000000000001 (NEEDED)             Shared library: [libcrypto.so.3]
```

Note that `php7` package is configured to build against `openssl-1.1`, as per `build.sh`:

https://github.com/termux/termux-packages/blob/15fe94ce9743e211e0e8feb09a0b387846627dac/packages/php7/build.sh#L12

So I suppose this should be fixed by linking `libexec/apache2/libphp7.so` against `openssl-1.1`. I will look into this.

**Comment by vikramv20** [comment]
how can i solve this error

**Comment by TomJo2000** [comment]
> how can i solve this error

PHP `7.x` has since been superseded by PHP `8.x`.
The functionality should be available in the current version.

[php7-apache](https://github.com/termux-user-repository/tur/blob/master/tur/php7/php7-apache.subpackage.sh) has since been moved to the [Termux User Repository](https://github.com/termux-user-repository/tur/tree/master#subscribe-tur).
Please verify that your program will not work in PHP `8.x` before resorting to installing PHP `7.x` from the TUR.
