### ISSUE TITLE
Dropbear installation fails

### ISSUE THREAD

**Issue by sebastian-de** [termux/termux-packages#1082]
Setting up dropbear (2017.75) ...
Generating key, this may take a while...
Failed moving key file to /data/data/com.termux/files/usr/etc/dropbear/dropbear_rsa_host_key: Permission denied
Exited: Failed to generate key.

Generating key, this may take a while...
Failed moving key file to /data/data/com.termux/files/usr/etc/dropbear/dropbear_dss_host_key: Permission denied
Exited: Failed to generate key.

Generating key, this may take a while...
Failed moving key file to /data/data/com.termux/files/usr/etc/dropbear/dropbear_ecdsa_host_key: Permission denied
Exited: Failed to generate key.

I'm using Termux 0.51 on LineageOS 14.1

**Comment by fornwall** [comment]
Thanks - this has now been fixed in version 2017.75-1 of the dropbear package that is now available!

Also, note that for most use cases you are better of with using the `openssh` package, containing the standard ssh client and server, rather than `dropbear`, that is more for smaller embedded devices.

**Comment by sebastian-de** [comment]
Thank you for this quick fix!

Am 14. Juni 2017 00:06:09 MESZ schrieb Fredrik Fornwall <notifications@github.com>:
