### ISSUE TITLE
Audacity features (ffmpeg and sound output).

### ISSUE THREAD

**Issue by Anonymous2716** [termux/termux-packages#10870]
Audacity is pretty good GUI application for audio editing. I was trying to open a ```.m4a``` file which it reported me that needs ```ffmpeg``` libraries. I have ffmpeg installed but it can't find it or do I need to import? after searching I saw in preferences it says ffmpeg libraries support not compiled in :

https://github.com/termux/termux-packages/blob/df2d533b4fdea3ea74dada39c871deab734855f4/x11-packages/audacity/build.sh#L19

And I opened a ```.wav``` file I was gonna try to listen (play) but it reported again that 
```error opening sound device try changing audio host ,playback device or project sample rate``` .
 Without listening to the audio editing is hard even for crop and join .

**Comment by rallg** [comment]
On my device (Samsung tablet), a number of *.ogg files are in /system/media/audio/ringtones. Probably your device, too.

Copy an *.ogg file to your home directory. Try to open and play it in Audacity.

If that works: Until ffmpeg and mp3 support are built into Audacity, you can use ffmpeg to convert your file to *.ogg format, edit the *.ogg in Audacity and export the edited file to another *.ogg, then use ffmpeg to convert format.

**Comment by macerg** [comment]
Audacity in termux has no sound output with ANY codec. ogg files 'play', as such but with no actual sound being output. Same with .wav, m4a etc.

**Comment by zairullahdev** [comment]
Compile by urself, due ffmpeg 5.x.x not supported at audacity

**Comment by DLC01** [comment]
For sound output we could use [this](https://github.com/Gundersanne/portaudio_opensles) patched version of portaudio which adds an opensles hostapi, for ffmpeg support we could probably take an similar approach as to what the archlinux package maintainers has taken by providing an [seperate package](https://archlinux.org/packages/extra/x86_64/ffmpeg4.4/) for ffmpeg4.4 and compile the application against that version of ffmpeg

**Comment by rallg** [comment]
I will have a look at the portaudio patch. In any case, building Audacity is not easy. It uses dependencies that are not common, and it wrongly detects the compiler version: It asks gcc version, but in Termux gcc symlinks to clang, which reports an unacceptable version to python `conan` package, used by the Audacity code. Obviously that can be hacked, but it is a nuisance.

Portaudio, and some other media programs, require `realtime` privilege, which must be granted by the kernel. It is my understanding that the Android kernel will not grant realtime privilege, in most cases. Actually, realtime privilege is not essential for programs that are not used for live performance, so maybe there is a way to build without it? Above my skill level.

**Comment by rallg** [comment]
I was able to build the portaudio patch suggested by @DCL01. Installed to $PREFIX instead of the pkg portaudio. I was able to build the older version 4.4.2 of ffmpeg, and install it to $PREFIX/opt (because I have the pkg version installed, and some other programs rely on it). I can launch the built 4.4.2 using a wrapper script that puts LD_LIBRARY_PATH=$PEFIX/opt/lib in front. It appears to work on command line, but I have not tested it much.

The ffmpeg configure script is funky. Instead of showing many lines of output as it goes along, it remains silent for a minute or two, then abruptly prints its summary.

During make, you will encounter errors that can be easily fixed, even if you do not know much programming. Files `aaccoder.c` and `hevc_mvs.c` and `opus_pvq.c` contain alphanumeric variables such as B0, a2, and others. Apparently the clang compiler does not like that. So, edit them to something strictly alphabetic. Finally, file `xcbgrab.c` refers to shared memory functions (shm) that are likely to fail. If so, just edit out all code referring to shared memory. There is a configure option that can do that for you, but I did not try it.

Whether any of that helps Audacity, I do not yet know.

**Comment by Anonymous2716** [comment]
Thanks @2096779623

**Comment by zairullahdev** [comment]
We need to compile old ffmpeg, this should be added to termux-packages as ffmpeg-old

**Comment by wmcbtech30** [comment]
Maintaining 2 package versions is not our job unless there's a critical reason for it, best ways is to patch the package to work with specific package version or to add support for it

**Comment by xtkoba** [comment]
Two separate topics in one issue. Duplicate of #10412 (audio devices) and #10665 (FFmpeg). Further discussions should go there.
