### ISSUE TITLE
[Bug]: Failed to fetch termux-tools_1.16_all.deb  404  Not Found

### ISSUE THREAD

**Issue by Dmole** [termux/termux-packages#11091]
### Problem description

```
pkg update -y                               
Checking availability of current mirror:        
[*] (4) https://termux.sahilister.in/apt/termux-main: ok
Hit:1 https://termux.sahilister.in/apt/termux-main stable InRelease
Reading package lists... Done                   
Building dependency tree... Done                
Reading state information... Done
12 packages can be upgraded. Run 'apt list --upgradable' to see them.                           
Reading package lists... Done                   
Building dependency tree... Done                
Reading state information... Done               
Calculating upgrade... Done
The following NEW packages will be installed:     
libtheora                                     
The following packages will be upgraded:          
apt command-not-found curl ffmpeg glib
  libaom libc++ libcurl libnghttp2 libvpx perl
  termux-tools
12 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.                                 
Need to get 202 kB/29.1 MB of archives.
After this operation, 1749 kB of additional disk space will be used.                            
Err:1 https://termux.sahilister.in/apt/termux-main stable/main aarch64 curl aarch64 7.84.0
  404  Not Found [IP: 161.97.134.132 443]
Err:2 https://termux.sahilister.in/apt/termux-main stable/main aarch64 termux-tools all 1.16      
404  Not Found [IP: 161.97.134.132 443]       
E: Failed to fetch https://termux.sahilister.in/apt/termux-main/pool/main/c/curl/curl_7.84.0_aarch64.deb  404  Not Found [IP: 161.97.134.132 443]                                               
E: Failed to fetch https://termux.sahilister.in/apt/termux-main/pool/main/t/termux-tools/termux-tools_1.16_all.deb  404  Not Found [IP: 161.97.134.132 443]                                     
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

### What steps will reproduce the bug?

pkg update -y

### What is the expected behavior?

exit 0

### System information

termux-info:

```
termux-info                                 
Termux Variables:
TERMUX_API_VERSION=0.50.1                       
TERMUX_APK_RELEASE=F_DROID                      
TERMUX_APP_PACKAGE_MANAGER=apt                  
TERMUX_APP_PID=9344
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0                          
Packages CPU architecture:                      
aarch64
Subscribed repositories:                        
# sources.list                                  
deb https://termux.sahilister.in/apt/termux-main/ stable main                                   
Updatable packages:
apt/stable 2.5.0-1 aarch64 [upgradable from: 2.5.0]                                             
command-not-found/stable 2.0 aarch64 [upgradable from: 1.75]                                    
curl/stable 7.84.0 aarch64 [upgradable from: 7.83.1]                                            
ffmpeg/stable 5.0.1-2 aarch64 [upgradable from: 5.0.1-1]                                        
glib/stable 2.72.2 aarch64 [upgradable from: 2.72.1-1]                                          
libaom/stable 3.4.0 aarch64 [upgradable from: 3.3.0]                                            
libc++/stable 23c aarch64 [upgradable from: 23b-3]                                              
libcurl/stable 7.84.0 aarch64 [upgradable from: 7.83.1]                                         
libnghttp2/stable 1.48.0 aarch64 [upgradable from: 1.47.0]
libvpx/stable 1.12.0-rc1-0 aarch64 [upgradable from: 1.11.0]                                    
perl/stable 5.36.0 aarch64 [upgradable from: 5.34.1-1]
termux-tools/stable 1.16 all [upgradable from: 0.184]
termux-tools version:                           
0.184                                           
Android version:
12                                              
Kernel build information:                       
Linux localhost 4.4.302-lineage-g5e6be5cee15e #1 SMP PREEMPT Tue Jun 7 01:00:11 UTC 2022 aarch64 Android
Device manufacturer:
Google                                          
Device model:                                   
Pixel 2

```

**Comment by Dmole** [comment]
```
curl -s "https://termux.sahilister.in/apt/termux-main/dists/stable/main/binary-aarch64/Packages" \
    | grep -A 5 -P "Package: curl\b" \
    | grep Version
Version: 7.84.0

curl -s "https://termux.sahilister.in/apt/termux-main/pool/main/c/curl/" \
    | grep -P "curl_.*_aarch64.deb" \
    | tail -n 1 \
    | perl -pe 's/<[^<>]*>//g'
curl_7.83.1_aarch64.deb                            11-May-2022 12:24              174004
```

**Comment by agnostic-apollo** [comment]
The `Packages` list on contains `termux-tools` `v1.16` but its `deb` doesn't exist on the server. Run `termux-change-repo` switch to different mirror for now and update again.

https://termux.sahilister.in/apt/termux-main/dists/stable/main/binary-aarch64/

https://termux.sahilister.in/apt/termux-main/pool/main/t/termux-tools/

@Grimler91 Issues similar to this are going to occur with `termux-change-repo`/`pkg` new mirror group design, all repos are unlikely to be in sync with our main repo and user now won't be able to select our default or grimler repo to quickly get latest updates. There should be an option to select a single mirror as well if user wants.

Also there is an `http` only mirror now, that may automatically be selected for users who select `europe` mirror group, which is unsafe. I think it should be removed until `https` is enabled on it by hoster.

**Comment by 2096779623** [comment]
> Also there is an `http` only mirror now, that may automatically be selected for users who select `europe` mirror group, which is unsafe. I think it should be removed until `https` is enabled on it by hoster.

I'll write an email asking about this and if I get a response I'll forward the content to you.

**Comment by Dmole** [comment]
Could also use https://aria2.github.io/ to make better use of mirrors...

**Comment by agnostic-apollo** [comment]
> I'll write an email asking about this and if I get a response I'll forward the content to you.

Issue maybe russian sanctions. Since outside companies cannot deal/process payments with russian companies/customers, they weren't being issued certs. At least, DigiCert had paused issuance for russia entirely. LetsEncrypt seems to be still issuing certs to normal people but not banned entities. Russian govt apparently has its own CA, but that wouldn't be trustable, and users won't have its root certs either, unless added and would also risk MITM. Possibly, creating a separate russian mirror group could be done.

https://amp.thehackernews.com/thn/2022/03/russian-pushing-its-new-state-run-tls.html

https://www.bleepingcomputer.com/news/security/russia-creates-its-own-tls-certificate-authority-to-bypass-sanctions/

https://www.gogetssl.com/news/27.html

https://knowledge.digicert.com/solution/Embargoed-Countries-and-Regions.html

https://community.letsencrypt.org/t/cert-issuance-to-russia/176750/5

Maybe we should also add conditions that all mirrors must sync every 12/24hrs or be removed/down-weighted from selection.

Faster download of old packages is less important than getting latest packages, unless its an archive repo.

**Comment by Dmole** [comment]
> aria2

eg;
```

#/data/data/com.termux/files/usr/bin/bash

#
# aria2apt.sh
#

set -e
P="$1"
apt-get -q update
INFO="$(apt-cache show "$P" 2>/dev/null \
        | grep -P "^(Version|SHA256|Size): ")"
V="$(echo "$INFO" \
        | grep "Version:" \
        | perl -pe 's/.* //g')"
if [ "$V" == "" ] ; then
        echo "Package $P not found."
        exit 1
fi
H="$(echo "$INFO" \
        | grep "SHA256:" \
        | perl -pe 's/.* //g')"
S="$(echo "$INFO" \
        | grep "Size:" \
        | perl -pe 's/.* //g')"
ARCH="$(uname -m)"
DIR="pool/main/$(echo "$P" | perl -pe 's/^(.).*/$1/g')/$P"
TMP="$(mktemp --tmpdir aria2apt.XXXXXXXXXX)"
finalize() {
        rm "$TMP"
}
trap finalize EXIT
{
        echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
        echo "<metalink xmlns=\"urn:ietf:params:xml:ns:metalink\">"
        F="${P}_${V}_$ARCH.deb"
        echo "<file name=\"$F\"><size>$S</size><hash type=\"sha-256\">$H</hash>"
        while read -r URL ; do
                echo "<url>$URL/$DIR/$F</url>"
        done < <(grep -RP "https:.*termux-main" /data/data/com.termux/files/usr/etc/termux/mirrors/ \
                | perl -pe 's/.*="//g;s/"//g' \
                | grep -Pv "\\.(cn|ru)/")
        echo "</file></metalink>"
} > "$TMP"
aria2c --quiet=true -s 1 "$TMP"
apt install "./$F"
```

**Comment by Grimler91** [comment]
Moving the Russian mirrors into a separate group seems like a good idea to start with: https://github.com/termux/termux-packages/pull/11093

I guess we'll always have the type of error in this issue as long as some repos sync more often than others.

**Comment by Grimler91** [comment]
As for how to lock into a single mirror, I have two ideas:

---

1. add a new prompt to termux-change-repo that says something like

```
 _______________________
|                                              |
|   Select an individual mirror  |
|                                              |
|   Select a group of mirrors    |
|_______________________|
```
where first option leads to a screen similar to the one used in old version of termux-change-repo, and it then uses TERMUX_PKG_NO_MIRROR_SELCT to lock into a single mirror. (And second option leads to current screen)

2. Give users the ability to edit weights conveniently, and thereby disable all mirrors except one if they want to. First screen shows something like
 
```
 _______________________
|                                              |
|   Edit mirror weights              |
|                                              |
|   Select a group of mirrors    |
|_______________________|
```
And first option leads to a screen containing something like:

```
 _______________________
|                                              |
|   4  grimler.se                        |
|   1  termux.librehat.com        |
|   1  cdn.lumito.net                 |
|   ...                                        |
|_______________________|
```

Where 4, 1, 1 and so on are editable. 

---

Second option seems more flexible, although it's a bit more annoying to select just a single mirror in that case.

What do you'all think? Any other ideas?

**Comment by agnostic-apollo** [comment]
Go with option `1` and no need to use `TERMUX_PKG_NO_MIRROR_SELECT`, just create a `chosen_mirrors` symlink to the mirror regular file like `north_america/package.termux.org` and add following in `pkg` script.

https://github.com/termux/termux-packages/blob/fa9c6c1ce5dc814b5d5ebc04e98bbb8a55132816/packages/termux-tools/pkg#L105-L107

```
if [ -d "@TERMUX_PREFIX@/etc/termux/chosen_mirrors" ]; then
    mirrors=($(find @TERMUX_PREFIX@/etc/termux/chosen_mirrors/ -type f ! -name "*\.dpkg-old" ! -name "*~"))
if [ -f "@TERMUX_PREFIX@/etc/termux/chosen_mirrors" ]; then
    mirrors=($(readlink @TERMUX_PREFIX@/etc/termux/chosen_mirrors))
elif [ -L "@TERMUX_PREFIX@/etc/termux/chosen_mirrors" ]; then
...
```

The rest of the logic can stay same since then `mirrors` array will only have a single mirror. What is missing is a check if mirrors array actually has any mirrors left after `check_mirror`. There should be an error+exit `else` for `if [ -n "$selected_mirror" ]; then` statement.

https://github.com/termux/termux-packages/blob/fa9c6c1ce5dc814b5d5ebc04e98bbb8a55132816/packages/termux-tools/pkg#L251

Also you should add a check in `get_mirror_weight` for whether weight is actually a positive integer. Shouldn't trust blind input and do maths on it considering user can modify the values, we already had to do the f2f4bead fix when values were hardcoded in `pkg` script itself. I added the check earlier, which you removed in new design.

https://github.com/termux/termux-packages/blob/fa9c6c1ce5dc814b5d5ebc04e98bbb8a55132816/packages/termux-tools/pkg#L97

On the `termux-change-repo` side, for `Select an individual mirror` option, I guess you can create an associative array for all mirrors with the format `[mirror_group/mirror_name]=/path/to/mirror/file`. Show the keys to the user and on selection, create symlink for array value for the key selected.

I don't like option `2` since probably most users won't have understanding of what weight is.

>(github butchered my nice ascii-art, but I think you can imagine how it's suppose to look)

What do you mean? Looks fine to me! ;)

Github comment typing field does not use monospace font while markdown code block does use it when rendered. You should type comments in monospaced font text editor for such stuff and there shall be no butchering.

**Comment by agnostic-apollo** [comment]
Single mirror selection support to select upto date mirrors has been added in termux/termux-tools#1
