### ISSUE TITLE
[Package]: Pet - Bookmark your favorite command

### ISSUE THREAD

**Issue by OilSubjectLoss7** [termux/termux-packages#11119]
### Package description

Save snippets or your favorite command

### Home page URL

https://github.com/knqyf263/pet

### Source code URL

https://github.com/knqyf263/pet

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by rallg** [comment]
Not sure whether this will work on Termux without major hacking, but then I am not a Termux dev.

Dependency fzf is already available on Termux. But the pet code (whether from git master, or release) seems hard-coded for installation to directory /usr/local, which will not work in Termux. I hunted through the source code, and found no place to edit the prefix. As with many other golang programs, this one grabs components from other places, meaning that all of those other places would need their code re-compiled for Termux.

Although it has less capability than pet, I put my favorite commands as aliases in `.bashrc`. For example, alias `gui` launches the xfce4 desktop. I use `nano` instead of `vi`, and have alias `edit` launch nano with a specific set of options.

**Comment by OilSubjectLoss7** [comment]
> Not sure whether this will work on Termux without major hacking, but then I am not a Termux dev.
> 
> Dependency fzf is already available on Termux. But the pet code (whether from git master, or release) seems hard-coded for installation to directory /usr/local, which will not work in Termux. I hunted through the source code, and found no place to edit the prefix. As with many other golang programs, this one grabs components from other places, meaning that all of those other places would need their code re-compiled for Termux.
> 
> In the downloaded `pet` directory, I ran `make install` and all it did (AFAIK) was give a one-line reply, without error. But I did not find program `pet` installed anywhere, and it was not anywhere in the downloaded directory.
> 
> Although it has less capability than pet, I put my favorite commands as aliases in `.bashrc`. For example, alias `gui` launches the xfce4 desktop. I use `nano` instead of `vi`, and have alias `edit` launch nano with a specific set of options.

Oh well, i guess i have to stick to

`command arg operator #bookmark1`
`#bookmark2 command arg operator`

**Comment by 2096779623** [comment]
I successfully built it on Termux and it works fine.
