### ISSUE TITLE
[Bug]: mkvtoolnix build failed

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#11176]
### Problem description

[mkvtoolnix.txt](https://github.com/termux/termux-packages/files/9056996/mkvtoolnix.txt)

### What steps will reproduce the bug?

build package

### System information

termux-info:

```

```

**Comment by licy183** [comment]
https://github.com/termux/termux-packages/issues/11175#issuecomment-1179659151. So I think there is no need to rebuild `mkvtoolnix`.
In the future, `mkvtoolnix` may be moved to `x11-packages` because `qt5` or `qt6` is required to sucessfully build `mkvtoolnix` since `v59.0.0`  (https://www.bunkus.org/blog/2021/07/mkvtoolnix-v59-0-0-released/).
