### ISSUE TITLE
[Package]: Cosmopolitan

### ISSUE THREAD

**Issue by 2096779623** [termux/termux-packages#11173]
### Package description

[Cosmopolitan Libc](https://justine.lol/cosmopolitan/index.html) makes C a build-once run-anywhere language, like Java, except it doesn't need an interpreter or virtual machine. Instead, it reconfigures stock GCC and Clang to output a POSIX-approved polyglot format that runs natively on Linux + Mac + Windows + FreeBSD + OpenBSD + NetBSD + BIOS with the best possible performance and the tiniest footprint imaginable.

### Home page URL

https://justine.lol/cosmopolitan/index.html

### Source code URL

https://github.com/jart/cosmopolitan/archive/refs/tags/1.0.tar.gz

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by twaik** [comment]
Should we have it? In the case if we are planning to update `targetSdkVersion` we will not be able to run statically compiled binaries or use custom linkers and it will make this project pretty much useless. Also since it is a custom libc building project for it will require patching sources, our patches may be incompatible.
