### ISSUE TITLE
Using 'proot' instead of building all packages

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#11449]
### Problem description

I tried to search and find an answer but couldn't get one.
My question is why building packages when we can use 'proot' to install Linux distribution.
I mean is there any limitations for using prooted distro and what are the advantages of building packages specially for termux.

### What steps will reproduce the bug?

No Issue

### System information

termux-info:

```

```

**Comment by Grimler91** [comment]
I mean, you can use proot-distro if you want to, but I guess you are asking why we don't just login straight into such an environment

Some reasons why we compile our packages for android instead of relying on proot are:

1. Saving disk space, we use android components like libc where possible, instead of downloading additional libraries/resources

2. proot slows things down, since it intercepts system calls and translates them (if necessary)

3. proot also isn't working perfectly for all devices, see [open issue](https://github.com/termux/proot/issues)

@michalbednarski might have more to say

**Comment by sylirre** [comment]
[UserLAnd](https://github.com/CypherpunkArmory/UserLAnd) does that and it's terminal is based on Termux. There is no need to go by road of another project, especially if it based on Termux in some way.

> I mean is there any limitations for using prooted distro

* Performance penalty.
* Device-specific issues (e.g. crashes).
* Program isn't running natively, its execution flow is greatly messed up by proot. In certain cases this could be potentially unwanted (e.g. when using `gdb`, `frida`, etc).

> what are the advantages of building packages specially for termux.

Close to 100% compatibility with Android. No need to have root or use emulators to run a foreign environment.

***

Termux is quite generic utility, a **terminal emulator app** for Android. I think putting additional layers between environment and the rest of operating system isn't good. If user needs specifically Linux distribution, a `proot-distro` package or alternative can be used.

**Comment by rallg** [comment]
I have frequently used GIMP and Fontforge in proot-distro Archlinux, and directly in Termux. The direct packages are MUCH faster. May depend on the application, since some complex applications require dependencies that are not (yet) built directly for Termux.

**Comment by johndebia2022** [comment]
closing the question as the answer is sufficient enough. thank you all
