### ISSUE TITLE
[Package]: libreoffice

### ISSUE THREAD

**Issue by T-Dynamos** [termux/termux-packages#11467]
### Package description

Open Source Office (Adding it seems joke)

### Home page URL

https://github.com/LibreOffice

### Source code URL

https://github.com/LibreOffice/core/archive/refs/tags/cp-22.05.5-2.tar.gz

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

is it possible to add it?

**Comment by rallg** [comment]
Is it possible to un-request someone else's requirest?!

I have tried LibreOffice in Termux using proot-distro Archlinux. It works. But because of the large size and system requirements, parts of LibreOffice are too stressful for anything but the highest-end systems. If you need much more than the word processor, then LibreOffice may be to much. Also, as with many other programs, multimedia content may be hard to do in Termux.

Consider the "Collabra" app (free from Google Play) which has a native-build, free word processor built on LibreOffice (but with limited capability). If you need other features, such as database, then you should use a cloud service.

**Comment by T-Dynamos** [comment]
>  Consider the "Collabra" app (free from Google Play) which has a native-build, free word processor built on LibreOffice (but with limited capability). If you need other features, such as database, then you should use a cloud service.

I use termux on Android x86 os ( bliss os ). Controlling that app with mouse will be difficult

**Comment by mguinhos** [comment]
Also interested in having an GUI office suite inside termux

This would be great

**Comment by avidseeker** [comment]
I'm interested in the `soffice` utility from Libreoffice that makes it possible to convert .docx and .pptx files to PDF and view these extensions on phone.

**Comment by knyipab** [comment]
Interested in this package but seems to be long way to go. Libreoffice seems to require KF5 which seems to need OpenGL-supported Qt5. Remaking Qt5 with opengl support may risk breaking existing packages (otherwise I don't know why we still don't have that). Probably wait until one day we libreoffice uses KF6 (Qt6-based) or perhaps building KF5 on Qt6 (feasible??). But still need to wait for Qt6 packages in Termux.

**Comment by knyipab** [comment]
Correct my previous comment.
Archlinux seems to build libreoffice by `--disable-kf5`: https://gitlab.archlinux.org/archlinux/packaging/packages/libreoffice-still/-/blob/main/PKGBUILD?ref_type=heads
And this TUR minimal libreoffice package does not even uses qt or gtk (perhaps don't run GUI at all but still a good reference for starting point): https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libreoffice-slim-git

**Comment by TomJo2000** [comment]
> What is the likelihood of this becoming a reality? I'd love to have this. However, if it's not going to happen after all these years, perhaps it should be closed.

There is 2 major issues regarding LibreOffice as a package.
- 1.) It has [***a lot*** of dependencies](https://gitlab.archlinux.org/archlinux/packaging/packages/libreoffice-still/-/blob/main/PKGBUILD?ref_type=heads#L19), and is an extremely complex set of applications.
It is very likely that it will require extensive patches to various parts of LibreOffice.
- 2.) The package is huge.
149.9MiB for Arch's package.
And that gets multiplied by 4 architectures we build for.
So we're charitably looking at 600MiB of mirror space, for a single package.
On top of that, the installed size for LibreOffice is 400+ MiB, not even accounting for any spellchecking or translation packages.

It would be a major ongoing cost, both in terms of maintainer time, and mirror space to package and maintain a LibreOffice package.
I wouldn't oppose it from a Maintainer standpoint if someone gets it working, but it's still gonna put a lot of strain on our resources.

**Comment by natebragg** [comment]
I don't disagree.  It sounds like it might be good to close this as won't fix, just so folks like me don't get false hope.  It could always be opened back up if there was sufficient motivation.

**Comment by TomJo2000** [comment]
I think you are probably right about that.
I'll close the issue and put a `help wanted` tag on it.
