### ISSUE TITLE
Webkit2gtk: GLib-GObject-CRITICAL **: 08:19:05.518: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

### ISSUE THREAD

**Issue by Yonle** [termux/termux-packages#11550]
```
(<unknown>:22137): GLib-GObject-WARNING **: 08:19:05.516: invalid (NULL) pointer instance

(<unknown>:22137): GLib-GObject-CRITICAL **: 08:19:05.518: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
web process terminated: crashed
Segmentation fault
```

Affected packages: `surf`, `epiphany`

**Comment by xtkoba** [comment]
Not happening to me as of now. Both `epiphany` and `surf` can open and view <a href="https://github.com/termux">our GitHub homepage</a>, with environment being Android 8.1.0 aarch64.

Can anyone else reproduce this?

**Comment by michaelBiochemist** [comment]
I'm running surf on a fresh gentoo install. No problems accessing Github, but surf crashes with that error the moment I open a page with videos on it, e.g. youtube. I also observed that I can enter a search in google, and it will pull up links (with thumbnails) to youtube videos. Scrolling the mouse _near_ the image causes it to crash with that error.

**Comment by xtkoba** [comment]
I encountered a similar issue when opening a page that contains embedded videos (e.g. https://github.com/termux/termux-packages/discussions/12320) with GNOME Web (Epiphany):

```
GStreamer element autoaudiosink not found. Please install it

(<unknown>:14600): GLib-GObject-WARNING **: 06:40:09.751: invalid (NULL) pointer instance

(<unknown>:14600): GLib-GObject-CRITICAL **: 06:40:09.752: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(epiphany:12927): epiphany-WARNING **: 06:40:09.899: Web process crashed
```

Not exactly the same because it did not cause a segmentation fault, just crashing a single tab.

The "GStreamer element autoaudiosink" is contained in `gst-plugins-good` package. Installing it manually resolved the issue for me. I plan to make `webkit2gtk{,-4.1}` depend on it.
