### ISSUE TITLE
[Bug]: transmission build failed ndk25

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#11597]
### Problem description

creating libtransmission/version.h
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
ERROR: 'IT_PROG_INTLTOOL' must appear in configure.ac for intltool to work.
autoreconf: error: intltoolize failed with exit status: 1

[transmission.txt](https://github.com/termux/termux-packages/files/9333840/transmission.txt)

### What steps will reproduce the bug?

build

### System information

termux-info:

```

```

**Comment by alive4ever** [comment]
This build failure happened because of the changes introduced with autoconf 2.70. See [upstream bug report](/transmission/transmission/issues/1573).

My pull request adds a patch so that transmission can be built with autoconf 2.70. The patch originated from buildroot and it is carried by several distributions such as Debian and Ubuntu.

**Comment by johndebia2022** [comment]
Issues fixed per #b6ba8502a6d46a8246a27c22553331a40eba5b9a
