### ISSUE TITLE
CMAKE Error.

### ISSUE THREAD

**Issue by ItzZyann** [termux/termux-packages#11611]
So uh, im trying to connect cmake toolchain to my android ndk, but it keeps sending me this error. Even tho i put the correct path.

Is there anyways to fix this?
Thanks for reading and answering!
![Screenshot_2022-08-15-21-41-51-02_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/85970053/184647098-f7ae18a3-7905-486d-841f-30918d61e0e4.jpg)

**Comment by Grimler91** [comment]
1. Hard to tell what you are trying to do from just this cropped screenshot. Not sure what "connect cmake toolchain to my android ndk" means.
2. To silence the warning, specify a source and/or build directory as the message says I guess, see `cmake --help`:
```
$ cmake --help
Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>
  cmake [options] -S <path-to-source> -B <path-to-build>
```
3. Closing since help on how to use cmake (and really all other software we have) are off-topic in termux's bug tracker. Try [github discussions](https://github.com/termux/termux-packages/discussions) or one of the [community channels](https://wiki.termux.com/wiki/Community) for future questions
