### ISSUE TITLE
[Bug]: new starship build failed for arm

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#11664]
### Problem description

  Compiling libz-sys v1.1.8
error: failed to run custom build command for `sha1-asm v0.5.1`

Caused by:
  process didn't exit successfully: `/home/builder/.termux-build/starship/src/target/release/build/sha1-asm-aaac5ad30ef4c605/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Unsupported target architecture', /home/builder/.cargo/registry/src/github.com-1ecc6299db9ec823/sha1-asm-0.5.1/build.rs:14:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `starship v1.10.2 (/home/builder/.termux-build/starship/src)`, intermediate artifacts can be found at `/home/builder/.termux-build/starship/src/target`
builder@c82232995622:~/termux-packages$

[errr.txt](https://github.com/termux/termux-packages/files/9387213/errr.txt)

### What steps will reproduce the bug?

build

### System information

termux-info:

```

```

**Comment by Dalmater** [comment]
Yep, it's the time that didn't work for me. I'll get this response as long as i have the time enabled.

![Screenshot_20220820-203856_Termux](https://user-images.githubusercontent.com/77870538/185763088-f8449e65-b7f1-48fd-a23a-fbd27eaf6352.jpg)

What steps will reproduce the bug?
Enable the time in starship.toml

System information: 
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=18637
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device
Updatable packages:
All packages up to date
termux-tools version:
1.27.0
Android version:
9
Kernel build information:
Linux localhost 3.18.91-16968401 #1 SMP PREEMPT Thu May 20 14:16:26 KST 2021 armv8l Android
Device manufacturer:
samsung
Device model:
SM-J701F

P.s. Maybe i should have opened a new issue because mine is not a build and it seems to be a different issue. But i'm not sure, maybe it's related.

**Comment by Dalmater** [comment]
There is more.

Just recognized that all the git repos/folders are not shown at all. The prompt is empty. Sometimes i get this response when i press ctrl-c.

$(/data/data/com.termux/files/usr/bin/starship prompt --terminal-width="$COLUMNS" --keymap="${KEYMAP:-}" --status="$STARSHIP_CMD_STATUS" --pipestatus="${STARSHIP_PIPE_STATUS[*]}" --cmd-duration="${STARSHIP_DURATION:-}" --jobs="$STARSHIP_JOBS_COUNT")

To make commands or key bindings work i had to press ctrl-c after every command. 
I had to disable the git_commit git_status and git_metrics settings in starship.toml.

**Comment by licy183** [comment]
> (There is more.
> 
> Just recognized that all the git repos/folders are not shown at all. The prompt is empty. Sometimes i get this response when i press ctrl-c.
> 
> (/data/data/com.termux/files/usr/bin/starshipprompt−−terminal−width="{KEYMAP:-}" --status="$STARSHIP_CMD_STATUS" --pipestatus="${STARSHIP_PIPE_STATUS[*]}" --cmd-duration="${STARSHIP_DURATION:-}" --jobs="$STARSHIP_JOBS_COUNT")
> 
> To make commands or key bindings work i had to press ctrl-c after every command. I had to disable the git_commit git_status and git_metrics settings in starship.toml to make it work properly again.

Hello, can you add `export RUST_BACKTRACE=1` in `.bashrc` and provide the backtrace? Actually, I cannot reproduce this error on my device.

**Comment by TomJo2000** [comment]
Same issue over here.
`$RUST_BACKTRACE=full` wasn't being of much help either.

![IMG_20220822_145248.jpg](https://user-images.githubusercontent.com/43716232/185925723-256c78bf-036a-49c5-b1bf-3b01e4a7d933.jpg)

**Comment by licy183** [comment]
Seems a bug from rust package `chrono`, so let's wait.

**Comment by Dalmater** [comment]
> > (There is more.
> > Just recognized that all the git repos/folders are not shown at all. The prompt is empty. Sometimes i get this response when i press ctrl-c.
> > (/data/data/com.termux/files/usr/bin/starshipprompt−−terminal−width="{KEYMAP:-}" --status="$STARSHIP_CMD_STATUS" --pipestatus="${STARSHIP_PIPE_STATUS[*]}" --cmd-duration="${STARSHIP_DURATION:-}" --jobs="$STARSHIP_JOBS_COUNT")
> > To make commands or key bindings work i had to press ctrl-c after every command. I had to disable the git_commit git_status and git_metrics settings in starship.toml to make it work properly again.
> 
> Hello, can you add `export RUST_BACKTRACE=1` in `.bashrc` and provide the backtrace? Actually, I cannot reproduce this error on my device.

Hey there, i just got an update for starship and  the only problem that is left is the git_commit setting. Everything else works just fine. I don't get any error message though  but in git repos there is no prompt at all.

In had to disable the git_commit setting. If i enable it with `disabled = false` i just got no prompt but everything else works.

I used the command `starship module git_commit` in an git folder/repo and it says bus error, but i got no output with export RUST_BACKTRACE=1 in .bashrc or .zshrc.

**Comment by Dalmater** [comment]
Yeah, they said they fixed some issues with git repositories in version 1.10.2. 
So lets wait then.

**Comment by johndebia2022** [comment]
for some reason build succeeded now
