### ISSUE TITLE
[Bug]: Commands in generated bootstrap with additional packages do not work without `chmod 0777`-ing the entire $PREFIX directory

### ISSUE THREAD

**Issue by shrihanDev** [termux/termux-packages#11844]
### Problem description

The bootstrap in question can be downloaded from [here](https://github.com/reisxd/termux-app/actions/runs/3008478869) (artifacts).

Running `java` or `node` from the built apps (also present in the artifacts above) returns EPERM. However, `chmod`-ing the entire `$PREFIX` directory recursively with mode 0777 and running the commands work.

This is why reisxd/termux-app modified the login script to do the chmod: https://github.com/reisxd/termux-app/blob/master/bootstrap/login#L22

The `generate-bootstraps.sh` is modified _a little_, sure, but that shouldn't apply, imnsho. If it does matter, please tell (implemented the idea after asking here: #11770).

Also, for some weird reason, a certain binary (`aapt2` from [revanced/aapt2](https://github.com/revanced/aapt2)), downloaded later to `$HOME`, also threw EPERM without changing the modes in `$PREFIX`.

### What steps will reproduce the bug?

1. Generate bootstrap using `./generate-bootstraps.sh --architectures aarch64 --add nodejs-lts,openjdk-17` (using the modified script from [here](https://github.com/reisxd/termux-app/blob/master/bootstrap/generate-bootstraps.sh)).
2. Build `termux-app` with the custom bootstrap.
3. Run a binary from the custom packages (`node`, `npm` or `java`).
4. See `Permission denied`.

### What is the expected behavior?

The commands should run regardless of the exclusion / inclusions of the packages (building the ones with the default set of packages of course work).

### System information

N/A?

**Comment by tomty89** [comment]
It's not exactly a bug:
https://github.com/termux/termux-app/blob/a2df7d791a5c09f9ed16e5755bb15ab871cee9e6/app/src/main/java/com/termux/app/TermuxInstaller.java#L197-L201
As you can see, because the official bootstrap *zip* (which does NOT carry unix permission information) does not ship packages like openjdk (which has the real executables somewhere under $PREFIX/opt/), so it's only natural that you bumped into the problem. (For your information, btw, `Permission denied` is actually `EACESS`, while `Operation not permitted` is `EPERM`.)

It might be possible to generally improve it for a bit at the SYMLINKS.txt processing stage, by e.g. also chmod 0700 for symlink targets of symlinks in $PREFIX/bin. (I don't know if there are any packages that actually ship profile scripts that add path to the PATH env var though.)

**Comment by shrihanDev** [comment]
> As you can see, because the official bootstrap _zip_ (which does NOT carry unix permission information) does not ship packages like openjdk (which has the real executables somewhere under $PREFIX/opt/), so it's only natural that you bumped into the problem.

...
> It might be possible to generally improve it for a bit at the SYMLINKS.txt processing stage, by e.g. also chmod'ing 0700 symlink targets (that are not in $PREFIX/bin) of symlinks in $PREFIX/bin.

Believe it or not, I actually thought that might be the default behaviour 😰 Gotta do some introspection before creating issues...

> (For your information, btw, `Permission denied` is actually `EACESS`, while `Operation not permitted` is `EPERM`)

F. I forgor 💀 that

**Comment by shrihanDev** [comment]
@tomty89 This part still remains as a confusion to me:

> Also, for some weird reason, a certain binary (aapt2 from revanced/aapt2), downloaded later to $HOME, also threw EACESS without changing the modes in $PREFIX.

**Comment by agnostic-apollo** [comment]
>It might be possible to generally improve it for a bit at the SYMLINKS.txt processing stage

Thanks, will look into it.

`$HOME`  is not under `$PREFIX`. Depends on how you downloaded it and whether given correct perm/owner.

**Comment by agnostic-apollo** [comment]
I have fixed the symlink target not being executable issue locally, will push changes soon.
