### ISSUE TITLE
php dns_get_record not working

### ISSUE THREAD

**Issue by whoisterencelee** [termux/termux-packages#1225]
Many php projects uses the dns_get_record function to test if user is registering a valid email address.

The following will always return false, but should return dns record as an array

```
<?php
$server = 'google.com';
print_r(dns_get_record($server));
```

**Comment by vishalbiswas** [comment]
I get `Warning: dns_get_record(): A temporary server error occurred. in - on line 3`

**Comment by ClosetMonkey** [comment]
PHP needs the dns_search function provided by either libsocket, libresolv, or libbind. The closest I can find in termux-packages is in the dnsutils package which provides bind client functions such as nslookup as well as libbind9. This will require, and still might not work, that the dnsutils package be patched create a symlink from libbind9 to libbind so that PHP's configuration can find it, or the PHP configuration files be patched to look for and link to libbind9 rather than libbind

**Comment by xtkoba** [comment]
Still actual.

Currently when trying to get DNS records `php` relies on `res_init()` and `res_search()` in `libc.so`, which do not work as they try to read non-existent `/etc/resolv.conf`, resulting in `0.0.0.0` being used as the DNS server to query.

**Comment by xtkoba** [comment]
Note that this is nothing related to #1174. `dns_get_record` in PHP does not need the addresses of DNS servers.
