### ISSUE TITLE
How to fix it

### ISSUE THREAD

**Issue by CHRIS111213417** [termux/termux-packages#12544]
### Problem description

It happens all the time when I try to download packages

### What steps will reproduce the bug?

![20221024_174231](https://user-images.githubusercontent.com/81781721/197554609-01ba5e50-05e2-4d77-a622-13d2979b0847.jpg)

### System information

termux-info:

```

```

**Comment by Grimler91** [comment]
Happened due to partial upgrade. 

Download latest bash and readline from https://packages.termux.dev/apt/termux-main/pool/main/b/bash/ and https://packages.termux.dev/apt/termux-main/pool/main/r/readline/, open a [failsafe shell](https://wiki.termux.com/wiki/Recover_a_broken_environment), install bash and readline with `dpkg -i /path/to/debs`, restart termux and upgrade all packages with `pkg upgrade`

**Comment by xtkoba** [comment]
Duplicate of #12216, for reference.

**Comment by CHRIS111213417** [comment]
![20221024_185602](https://user-images.githubusercontent.com/81781721/197571058-b1c85660-42b8-42bf-a8bd-a7c78ebcfc2b.jpg)

**Comment by Tt90645** [comment]
pkg <package>?

**Comment by Tt90645** [comment]
1 The day has passed

**Comment by calle44** [comment]
I have both of this packages installed and I don't know why don't work
