### ISSUE TITLE
[Bug]: recoll's python module does not work out of the box

### ISSUE THREAD

**Issue by Grimler91** [termux/termux-packages#12576]
### Problem description

In termux/termux-packages#12497 recoll's python module was added to the package. It installs to `$PREFIX/lib/python3/dist-packages/recoll/`, but this directory is not part of PYTHONPATH in termux per default, giving an error unless the PYTHONPATH is modified:

```
$ python3
Python 3.10.8 (main, Oct 12 2022, 12:40:52) [Clang 14.0.6 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import recoll
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'recoll'
>>> 
$ PYTHONPATH=$PREFIX/lib/python3/dist-packages/ python3
Python 3.10.8 (main, Oct 12 2022, 12:40:52) [Clang 14.0.6 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import recoll
>>> 
```

Either we should make our python package recognise the lib/python3/dist-packages folder (by setting PYTHONPATH in a profile script?), or we should make recoll install to `$PREFIX/lib/python3.X/site-packages` instead.

Some related discussion was had in the [PR to add termux-gui-pm](https://github.com/termux/termux-packages/pull/12315) by @tareksander.

### What steps will reproduce the bug?

```
$ pkg install recoll
$ python3
>>> import recoll
```

### What is the expected behavior?

recoll should import without errors out of the box.

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.termux.dev/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://mirror.termux.dev/termux-x11 x11 main
# root-repo (sources.list.d/root.list)
deb https://mirror.termux.dev/termux-root root stable
Updatable packages:
flac/stable 1.4.2 aarch64 [upgradable from: 1.4.1]
glib-bin/stable 2.74.1 aarch64 [upgradable from: 2.74.0]
glib/stable 2.74.1 aarch64 [upgradable from: 2.74.0]
graphviz/stable 7.0.0 aarch64 [upgradable from: 6.0.1]
libcairo/stable 1.16.0-10 aarch64 [upgradable from: 1.16.0-9]
libexpat/stable 2.5.0 aarch64 [upgradable from: 2.4.9]
libffi/stable 3.4.4 aarch64 [upgradable from: 3.4.3]
libflac/stable 1.4.2 aarch64 [upgradable from: 1.4.1]
libidn2/stable 2.3.4 aarch64 [upgradable from: 2.3.3]
libxrender/stable 0.9.11 aarch64 [upgradable from: 0.9.10-14]
ragel/stable 7.0.4 aarch64 [upgradable from: 6.10-4]
rsync/stable 3.2.7 aarch64 [upgradable from: 3.2.6-1]
swig/stable 4.1.0 aarch64 [upgradable from: 4.0.2-2]
webkit2gtk/x11 2.38.1 aarch64 [upgradable from: 2.38.0-1]
termux-tools version:
1.31.0
Android version:
11
Kernel build information:
Linux localhost 4.4.111-ge6e6b41f98d8 #1 SMP PREEMPT Sat Aug 21 13:35:28 CEST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G955F
```

**Comment by Grimler91** [comment]
Ping @JCGoran, @landfillbaby maybe you have some suggestions on how to handle this

**Comment by JCGoran** [comment]
I think there is a slightly bigger issue here, which I've only realized afterwards (sorry about that, haven't made packages for termux before): namely, if you look at the manifest via `apt-file list recoll`, you'll see:

```plaintext
recoll: /data/data/com.termux/files/usr/lib/python3/dist-packages/recoll/_recoll.cpython-310-x86_64-linux-gnu.so
```
which, if I'm not mistaken, indicates that the Python lib is actually built for `x86_64`, and not `aarch64`, so the bindings probably don't function properly at the moment. I've naively looked at other packages which have Python bindings, and maybe something like this would work?
https://github.com/termux/termux-packages/blob/e0232d9de91d3001f38e6193d57552c7a6d724c9/packages/unbound/build.sh#L32-L44

**Comment by Grimler91** [comment]
Missed that, the name is wrong indeed, file seems to be correct architecture though:

```
$ file /data/data/com.termux/files/usr/lib/python3/dist-packages/recoll/_recoll.cpython-310-x86_64-linux-gnu.so
/data/data/com.termux/files/usr/lib/python3/dist-packages/recoll/_recoll.cpython-310-x86_64-linux-gnu.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
```

using `termux_setup_python_crossenv` as above would probably fix both the path and the file name issue

**Comment by xtkoba** [comment]
Please make sure to always use `termux_setup_python_crossenv` when installing a Python module, even if it does not contain any C extensions.

**Comment by xtkoba** [comment]
The following is an explanation of commit 2c40a8f2742df2cc83372e4668947dbbf3142996.

In this specific case it turns out that the culprit is in `Makefile.in`:

https://github.com/termux/termux-packages/blob/2c40a8f2742df2cc83372e4668947dbbf3142996/packages/recoll/Makefile.in.patch#L7-L8

Also a workaround is needed for android/ndk#201:

https://github.com/termux/termux-packages/blob/2c40a8f2742df2cc83372e4668947dbbf3142996/packages/recoll/python-recoll-setup.py.in.diff#L7-L12

(Commonly-used `LDFLAGS+=" -lpython${_PYTHON_VERSION}"` is insufficient.)
 
And finally it needs to disable Python 2:

https://github.com/termux/termux-packages/blob/2c40a8f2742df2cc83372e4668947dbbf3142996/packages/recoll/Makefile.in.patch#L16-L17

https://github.com/termux/termux-packages/blob/2c40a8f2742df2cc83372e4668947dbbf3142996/packages/recoll/Makefile.in.patch#L23-L24

**Comment by JCGoran** [comment]
With the current revision (`1.33.1-2`), the module can't seem to be found again:

```plaintext
$ python -c 'import recoll'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'recoll'
```

From what I can tell, the following issues remain:

1. the files are installed in `$PREFIX/lib`, which is not in the Python interpreter's path
2. the files `conftree.py`, `__init__.py`, `qresultstore.py`, `rclconfig.py`, `rclextract.py`, `recoll.py` should be included in the distribution
3. the lib file should be called `_recoll[SOMETHING].so` (since the `.py` files above use `from ._recoll import [OBJECT]`)

Note that even if I do all the above manually (fix path, copy `.py` files there, rename library), there still seem to be issues:

```plaintext
$ PYTHONPATH=$PREFIX/lib/ python -c 'from recoll import recoll'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/recoll/recoll.py", line 22, in <module>
    from ._recoll import *
ImportError: dynamic module does not define module export function (PyInit__recoll)
```

**Comment by JCGoran** [comment]
Could this be reopened? The Python module still doesn't work OOTB.

**Comment by xtkoba** [comment]
Not reproducible for me. The command

```bash
python -c "from recoll import recoll"
```

exits normally.

**Comment by xtkoba** [comment]
Would you please share the `strace` output of the command?

IMO that should have a new issue, instead of reusing once closed one.

**Comment by xtkoba** [comment]
@JCGoran I believe that is another issue. Please open a new one. Thanks.
