### ISSUE TITLE
Please Add PHP mysqli Extension

### ISSUE THREAD

**Issue by Sak94664** [termux/termux-packages#1266]
please add it ,because now MariaDB is available, it's much better to add it!Thanks a lot!
(Sorry for my poor English).   😁😁

**Comment by TheDiamondYT1** [comment]
#1025

**Comment by gagan0123** [comment]
MySQLi is different than MySQL extension that has recently been added. To install WordPress, we'll need MySQLi extension for PHP

**Comment by vishalbiswas** [comment]
@gagan0123 php-mysql includes both pdo_mysql and mysqli extensions. So, this can really be closed.

**Comment by Sak94664** [comment]
@vishalbiswas
I installed php-mysql package,but I didn't see mysqli extension in phpinfo.(configured with php.ini)
Does it need advanced configuration?

**Comment by vishalbiswas** [comment]
@Sak94664
did you add `extension=mysqli.so` in your php.ini?

**Comment by Sak94664** [comment]
@vishalbiswas 
Here is my php.ini:
extension_dir="/data/data/com.termux/files/usr/lib/php"
extension=mysqli.so
extension=pdo_mysql.so
I uses php-cgi -b 127.0.0.1:9000 -c /path/to/ini

**Comment by Sak94664** [comment]
@vishalbiswas 
Sorry,forgot to add it.
It works,thanks!

**Comment by kinhsloob1** [comment]
@vishalbiswas
Sorry i know this issue is closed.
I added the extension to the file and i got this error from apache. 

[Thu Nov 23 11:48:23.353834 2017] [mpm_worker:notice] [pid 15020:tid 548453629616] AH00295: caught SIGTERM, shutting down
PHP Warning:  PHP Startup: Unable to load dynamic library '/data/data/com.termux/files/usr/lib/php/mysqli.so' - dlopen failed: cannot locate symbol &quot;OnUpdateBool&quot; referenced by &quot;/data/data/com.termux/files/usr/lib/php/mysqli.so&quot;... in Unknown on line 0
[Thu Nov 23 11:48:24.426489 2017] [mpm_worker:notice] [pid 15754:tid 547543801520] AH00292: Apache/2.4.29 (Unix) PHP/7.1.11 configured -- resuming normal operations

But running directly using the php cli, mysqli was installed and is working well but with an error 

Segmentation fault

**Comment by Sak94664** [comment]
@kinhsloob1
Try nginx+php+mariadb instead.
It works well.(Tested running wordpress)

**Comment by vishalbiswas** [comment]
@kinhsloob1 Thanks for the report.
Indeed, its not working with apache2. I am not getting any errors in log. Everything seems to go fine except the extension is not getting loaded.
How did you get this error?

**Comment by kinhsloob1** [comment]
@vishalbiswas i had to set my error logs to an eternal directory and reduce the error level in the apache comfiguration file. But i will advice ypu go for nginx,php-fpm. It works like magic

**Comment by vishalbiswas** [comment]
@kinhsloob1 yes, I've tried and it works.
But considering that I'm the package maintainer for apache2, I do have to resolve this.

**Comment by kinhsloob1** [comment]
Ok please do...

**Comment by vishalbiswas** [comment]
@kinhsloob1
Please update to php-7.1.12-1 package. php-mysql is built into the php package now, so, you don't need to have an entry for it in your `php.ini`
It should now work with apache as well
