### ISSUE TITLE
Troubles with executing binary files

### ISSUE THREAD

**Issue by v00x** [termux/termux-packages#1276]
Im trying to compile some backports with the "make" command but it says 

```
make: bin/bash: Command not found
```
[screenshot](https://ibb.co/kLeGCF)

**Comment by Grimler91** [comment]
/bin/bash doesn't exist in termux since it is a prefixed environment. You will need to find the line of code that generates that message and change `/bin/bash` to `/data/data/com.termux/files/usr/bin/bash`. 

It could be that there is the shebang of files causing the problem, we have a script in termux that changes the shebang automatically so you can run `termux-fix-shebang files-to-change` and maybe fix the problem.

**Comment by Grimler91** [comment]
There's an entry about it in the termux wiki: https://wiki.termux.com/wiki/Main_Page#Prefixed_System

**Comment by v00x** [comment]
```
alias su='/system/xbin/su --preserve-environment -c LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib exec /data/data/com.termux/files/usr/bin/bash --login'
```
I used this alias from another issue suggestion but i doesn't seem to fix the problem. 

Also i tried 

```
termux-fix-shebang /data/data/com.termux/files/usr/bin/bash
```


and

```
termux-fix-shebang files-to-change
```
And the output is..

```
# make
make: /bin/bash: Command not found                      make: /bin/bash: Command not found
make: /bin/bash: Command not found
make: /bin/bash: Command not found
make: *** [Makefile:30: default] Error 127
# bash make
/data/data/com.termux/files/usr/bin/make: /data/data/com.termux/files/usr/bin/make: cannot execute binary file
```

**Comment by Grimler91** [comment]
@v00x You shouldn't use su here, there's no need for it in termux. The second error is due to su.

"files-to-change" should be replaced by a list of the files who's prefixes you want to change.

I'll quote myself: 
> bin/bash doesn't exist in termux since it is a prefixed environment. You will need to find the line of code that generates that message and change /bin/bash to /data/data/com.termux/files/usr/bin/bash.

Do `grep -nr "/bin/bash" .` in the project folder to find all possible places where the /bin/bash is used.

**Comment by v00x** [comment]
When i run 
```
grep -nr "/bin/bash"
```
 
the command is accepted but it just stays that way without any output.

**Comment by Neo-Oli** [comment]
@v00x Don't forget the period at the end to only search the current folder. 
`grep -nr "/bin/bash" .`

**Comment by v00x** [comment]
Then i tried to exit su and enter the commans as $ but the permission is denied.

Maybe i shouldn't enter that alias..

**Comment by Grimler91** [comment]
@v00x first of all, open a new shell to get rid of the permission denied errors (I think, could also be that the folders were created by root).

From the grep output you see which lines you need to change. 
Running this should fix the /bin/bash problem:
```
termux-fix-shebang ./scripts/*.sh
sed -i ./Makefile "s@SHELL := /bin/bash@SHELL := $PREFIX/bin/bash@g"
```

**Comment by v00x** [comment]
I made a clean install of the termux app and then edit the shell scripts in the project, so now ``make``
is working. Thanks!

_Sent from my Sony Xperia Z1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by abcyabu** [comment]
Bash: ./ngrok: Permission denied

**Comment by abcyabu** [comment]
ash: ./ngrok: Permission denied
help  me

**Comment by abcyabu** [comment]
bash: ./ngrok: Permission denied
Helpppppp
