### ISSUE TITLE
Tmux 

### ISSUE THREAD

**Issue by its-pointless** [termux/termux-packages#128]
Tmux won't load .tmux.conf in home directory automatically have to specify with -f.

**Comment by fornwall** [comment]
Works when I test. Can you paste the output of `ls -la $HOME/.tmux.conf`, as well as the output from `which tmux`?

**Comment by its-pointless** [comment]
I think i worked out what happened since im the cause and solution... timeto close this.

**Comment by cromo** [comment]
Came across this issue while having the same problem without a solution listed. Here's the results of the requested commands:

```
$ ls -la $HOME/.tmux.conf
lrwxrwxrwx    1 u0_a124  u0_a124         19 May  4 21:08 /data/data/com.termux/files/home/.tmux.conf -> .dotfiles/tmux.conf
$ which tmux
/data/data/com.termux/files/usr/bin/tmux
```

I did get it working by replacing the symlink with a copy of the actual file. However, this isn't as nice because I keep my dotfiles in a git repo, and this means I won't be able to track its changes as easily.
