### ISSUE TITLE
otter-browser (QtWebKit-based): Removal

### ISSUE THREAD

**Issue by xtkoba** [termux/termux-packages#12813]
`otter-browser` is a web browser. While it can be configured to use Qt WebEngine as the browser engine, the package in our repo is configured to use QtWebKit. <a href="https://www.openwall.com/lists/oss-security/2021/08/04/1">QtWebKit is based on old WebKit that has known vulnerabilities</a> and is not suitable for generic use.

As a WebKit-based browser we have GNOME Web (`epiphany`) that uses well-maintained WebKitGTK+. As a web browser we also have Firefox now. So IMO there is no reason to keep `otter-browser` in our repo.

I'm going to remove the `otter-browser` package in 45 days if I see no objections.

As for QtWebKit itself, I'm opposed to removing it. In restricted situations I believe it is still usable and useful (e.g. as a dependency of `phantomjs`).

**Comment by rallg** [comment]
I use otter-browser to read local HTML help files, such as for ImageMagick. Better than Epiphany, probably due to the way the pages are coded in HTML and CSS. But I do not use any Termux browser for the Internet, since I have regular Android apps for that.

I would like to retain otter-browser, even if it does not connect out to the Internet, for reading local files within Termux. Is it possible to work-around the package removal? In Arch Linux, I could create a custom package, unknown to the pacman manager.
Can something similar be done in Termux? If so, I will attempt to figure out how to do it myself. But if not, please let me know, so I do not waste time trying to do the impossible.

**Comment by xtkoba** [comment]
Note that already-installed package is not uninstalled from Termux environment when it is removed from bindist mirrors. You can keep the DEB file locally and use it until dependency is broken.

**Comment by rallg** [comment]
Good. Will do it that way.

**Comment by Anonymous1231-dev** [comment]
@xtkoba i agree with this decision. 
Since we have a better alternative
