### ISSUE TITLE
Package request: magic-wormhole

### ISSUE THREAD

**Issue by dgrabla** [termux/termux-packages#1327]
https://github.com/warner/magic-wormhole

makes it possible to get arbitrary-sized files and directories (or short pieces of text) from one computer to another. The two endpoints are identified by using identical "wormhole codes": in general, the sending machine generates and displays the code, which must then be typed into the receiving machine.

**Comment by emanresusername** [comment]
not as smooth as `pkg install magic-wormhole` but i have it working with the following setup

- find the `pkg install` equivalents of [these](https://magic-wormhole.readthedocs.io/en/latest/welcome.html#linux) 
  - memory's a little fuzzy, but i think i just needed `openssl-dev` `libffi-dev` `python2-dev` and [`gcc-7`](https://wiki.termux.com/wiki/Package_Management#its-pointless_.28live_the_dream.29) 🤔 
- [`pip2 install magic-wormhole[tor]`](https://magic-wormhole.readthedocs.io/en/latest/tor.html)
- have tor running (i had [orbot](https://guardianproject.info/apps/orbot/) already, assume you could `pkg install tor` and run that alternatively)
- `wormhole {send,receive} --tor` 
  - have to use `--tor` or it doesn't work
- profit 🤑

**Comment by verboze** [comment]
Dang, this one took forever to get installed... I also used a workaround to install from pip, but I didn't need to use tor and I wanted it built against python 3. I needed to install the following (I'm sure there are some other requirements that were already satisfied, check the [link](https://magic-wormhole.readthedocs.io/en/latest/welcome.html#linux) @emanresusername shared above):
- `cmake` (I couldn't find build-essential, but this will do)
- `openssl-dev` (instead of libssl - won't work with just openssl, missing header files)
- `libffi-dev` (same as open-ssl above)

Then, it's just a simple matter of installing via pip: `pip3.7 install magic-wormhole`. This will take a while, it had to compile and build a bunch of dependencies from scratch!

**Comment by hammerandtongs** [comment]
Current termux - 

* pkg install python cmake openssl libffi

* pip3 install magic-wormhole

* About 5+ minutes of build

**Comment by xeffyr** [comment]
Closing as this is a python package using external modules.
Should be installed through **pip** instead.

**Comment by marek22k** [comment]
Since it has to be compiled itself and this is a rather long process and there are quite a lot of not clear dependencies, is it possible to make an exception and build the package anyway?
