### ISSUE TITLE
[Bug]: Cant use `sudo cd /sdcard/Android/data/` on Android 12.

### ISSUE THREAD

**Issue by zixijian** [termux/termux-packages#13295]
### Problem description

```
sudo cd /sdcard/Android/data/
env: exec cd: No such file or directory
```
But using `tsu` first can do it.

Is there an easy way to allow me to use `cd /sdcard/Android/data/` in sh scripts？

### What steps will reproduce the bug?

`sudo cd /sdcard/Android/data/` if have `root` access.

### What is the expected behavior?

Hinders or increases the difficulty of automated scripts.

BTW：Visual termux-change-repo for some people, it's not as easy as using a command.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=UNKNOWN
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=29127
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.31.1
Android version:
12
Kernel build information:
Linux 11tp 5.10.66-android12-9-00001-g41ff3fa8fff9-ab8171928 #1 SMP PREEMPT Mon Feb 7 06:19:48 UTC 2022 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
22041216C

```

**Comment by agnostic-apollo** [comment]
`cd` is a shell built-in, not a binary, hence it won't be found like that. Moreover, even if `sudo cd /path` worked, once command returned, you would still be back in original dir, since `cd` would have been done in sub process, not current/parent process.

You can use `sudo -s "cd /path; other commands..."` with my variant.

https://github.com/agnostic-apollo/sudo#script
