### ISSUE TITLE
Error on the new version of NPM

### ISSUE THREAD

**Issue by GuriZenit** [termux/termux-packages#13293]
I'm getting this error on the version 9.1.2 of npm:
```
npm ERR! code EACCES
npm ERR! syscall link
npm ERR! path /data/data/com.termux/files/home/.npm/_cacache/tmp/4f642a1f
npm ERR! dest /data/data/com.termux/files/home/.npm/_cacache/content-v2/sha512/be/ab/0cbc90e0f25082fb10a4b6cbae24791280fb9c61657faeea92f50ace86a920874b1dc0377c202e3e1b25d5067bbb2f526e14d1d0e5c7aa146dbbcb0ed718
npm ERR! errno EACCES
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 10413:10413 "/data/data/com.termux/files/home/.npm"

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2022-11-19T20_47_59_413Z-debug-0.log
```
As I don't have root , I can't solve it with what is indicated in the log

This happens with anything I try, like 
```
npm install package
npm install -g npm
```

**Comment by Grimler91** [comment]
It tries to make a hardlink, which is not allowed on android. Same issue as in https://github.com/termux/termux-packages/issues/11293, where `npm install -g package` worked as a work around

**Comment by truboxl** [comment]
I think we should patch this

**Comment by licy183** [comment]
Maybe we should report this issue to https://github.com/npm/cacache? We have patched it using https://github.com/termux/termux-packages/blob/master/packages/nodejs/deps-npm-node_modules-cacache-lib-util-move-file.js.patch, but if user tries to update `npm` or `cacache`, the patch will not work.

**Comment by GuriZenit** [comment]
If this helps in anything, I installed Ubuntu `v20.04/CLI only` from [Andronix](https://andronix.app), then installed nodejs `v19.1.0` and upgraded npm to `9.1.2`, all worked well:
```
root@localhost:~# node -v
v19.1.0
root@localhost:~# npm -v
9.1.2
root@localhost:~# cd project
root@localhost:~/project# npm install

added 33 packages, and audited 34 packages in 21s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
root@localhost:~/project#
```
I'm still in Termux/Android does Ubuntu change anything?

**Comment by thunder-coding** [comment]
@GuriZenit, we are talking about native Termux environment and not proot based distributions (including third party ones).

**Comment by xtkoba** [comment]
We really need a gimmick that forbids users' updating npm, if the patch is not likely to be merged upstream. Could be just a matter of documentation though.

**Comment by thunder-coding** [comment]
Yeah sure @xtkoba, we can add a notice to the npm's global install script when installing npm. Just wait for some time though. My main device is for repair so I can't test the binaries built by CI. Once it comes, will look into it

**Comment by licy183** [comment]
It seems that `npm@9.2.0` has fixed this.

**Comment by GuriZenit** [comment]
> It seems that `npm@9.2.0` has fixed this.

Still have the error, both now and when testing in v9.2.0 release. does it work for you?

**Comment by licy183** [comment]
Emmm... It seems to work on Bluestacks, but not on my real device. I will record it and report upstream.

**Comment by ginger-tek** [comment]
> > It seems that `npm@9.2.0` has fixed this.
> 
> Still have the error, both now and when testing in v9.2.0 release. does it work for you?

Same here :/

**Comment by ytstrange** [comment]
Use `yarn` to install npm packages !

**Comment by thunder-coding** [comment]
Just pushed 6b05a8e7ba0435bec9afccd6e809329a7a62c27d. Will now include an error message when trying to install npm globally. Also using `--force` will allow to install it anyway (provided for people who know what they are doing)

**Comment by ItsAleph** [comment]
So, uh, any other way to upgrade npm?

**Comment by Alex1Sturm** [comment]
Error;-;

ERR! Can't install npm globally as it will very likely break installation of global packages using npm. See https://github.com/termux/termux-packages/issues/13293

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2023-03-12T00_03_10_133Z-debug-0.log

**Comment by marktforsyth** [comment]
> So, uh, any other way to upgrade npm?

@ItsAleph I think I may have found a way!

Ironically, the suggestion by @OurCodeBase works perfectly for this: using `yarn`. Even though I've been getting the same errors as everyone else, this did the trick:

`npm i -g yarn` (if not already installed)
`yarn global add npm`
 
Oh my machine, this runs without errors. After installation, `npm -v` gives the expected result. Does this work for any of you too?

**Comment by joshcangit** [comment]
No, `yarn global add npm` only installed to the home directory.
Even when I specified `--prefix`.

However, installing `npm` to the home directory then `cp -rf node_modules/npm $PREFIX/lib/node_modules` worked.

**Comment by OurCodeBase** [comment]
Hello @joshcangit 
If you are facing issues with yarn then reset everything and install yarn using package manager `pkg install yarn`.
This will install yarn, npm, and nodejs automatically.
And then you can run `yarn` command anywhere.

**Comment by joshcangit** [comment]
> Hello @joshcangit 
> If you are facing issues with yarn then reset everything and install yarn using package manager `pkg install yarn`.
> This will install yarn, npm, and nodejs automatically.
> And then you can run `yarn` command anywhere.

Um actually, the issue is with `npm`.

I updated it by installing under the home directory then copying it over.
I don't think it matters which package manager I used to do this.

**Comment by OurCodeBase** [comment]
Why are you using npm when yarn is much stable than it.

**Comment by joshcangit** [comment]
> Why are you using npm when yarn is much stable than it.

My idea is `npm` for system-wide packages.
But `yarn` or `pnpm` for packages in current working directory.

**Comment by ItsAleph** [comment]
> > So, uh, any other way to upgrade npm?
> 
> @ItsAleph I think I may have found a way!
> 
> Ironically, the suggestion by @OurCodeBase works perfectly for this: using `yarn`. Even though I've been getting the same errors as everyone else, this did the trick:
> 
> `npm i -g yarn` (if not already installed) `yarn global add npm`
> 
> Oh my machine, this runs without errors. After installation, `npm -v` gives the expected result. Does this work for any of you too?

Works for my needs. Thanks!

> Why are you using npm when yarn is much stable than it.

Woah what an opinionated comment. Not sure for you, but from my own experience, for global packages npm works better. Everyone chooses what works for them, don't bomb people with opinions unless asked :p

**Comment by phanirithvij** [comment]
This has been fixed in https://github.com/npm/cacache/pull/195

**Comment by thunder-coding** [comment]
> This has been fixed in [npm/cacache#195](https://github.com/npm/cacache/pull/195), it works now

Thanks for pointing out, this issue will be closed as completed once we have upgrade to a version of nodejs which comes with this fix for npm. LTS should not be much of a problem, but the latest version will take some time to catch up

**Comment by varxez** [comment]
You can try this:
https://github.com/varxez/termux-npm-updater

**Comment by joshcangit** [comment]
> https://github.com/varxez/termux-npm-updater

Not sure if this works.
I've tried copying `npm` from `node_modules` in the home folder.
The error still occured.

**Comment by thunder-coding** [comment]
> You can try this:
https://github.com/varxez/termux-npm-updater

That script ain't going to work, you are just replacing the npm binary and the node_modules directory without actually applying the fix which we have in our packaged version of node

**Comment by varxez** [comment]
> > You can try this:
> > https://github.com/varxez/termux-npm-updater
> 
> That script ain't going to work, you are just replacing the npm binary and the node_modules directory without actually applying the fix which we have in our packaged version of node

Bro, how about if you personally check the functionality of the script?

**Comment by GuriZenit** [comment]
> > > You can try this:
> > > https://github.com/varxez/termux-npm-updater
> > 
> > That script ain't going to work, you are just replacing the npm binary and the node_modules directory without actually applying the fix which we have in our packaged version of node
> 
> Bro, how about if you personally check the functionality of the script?

This script does the same job as
```
npm i -g npm@latest --force
```

**Comment by elenakrittik** [comment]
@varxez npm is not "node package manager" 🤦
https://github.com/npm/cli#is-npm-an-acronym-for-node-package-manager

**Comment by TomJo2000** [comment]
`npm` installs and manages node packages.
So yes while it might not call itself that, Node Package Manager is an absolutely fair description of the project, whether that branding is used officially or not.

**Comment by Leif-W** [comment]
This seems to have gone off topic.  The name has nothing to do with the functionality.  Nor does bickering about a script.

For me, the patched npm was available in a nodejs update in my Termux some time ago.  At some later time, npm was independently updated upstream somewhere, so that the version installed was out of date.  `npm i -g npm` worked flawlessly, and npm updated without any errors.  I verified new version with `npm -v`.

If some people are still having a bug, then let them please continue to explore that here.  To troubleshoot, I think it might be reasonable to uninstall nodejs then verify the old npm is truly gone, then reinstall nodejs and verify it has the patched npm.  Then wait for a new npm to be released upstream, and try to self-update.

Only people still kbserving the initial problem should be posting here.  Otherwise, if others confirm this is now working and nobody reports errors, close this.  Probably any other bug is a new bug and deserves a new issue.

Thanks to all who got this working for us.

**Comment by n-ce** [comment]
![Screenshot_20230723-003114_Termux](https://github.com/termux/termux-packages/assets/69345507/14f3de44-71c6-495a-aa19-be500174ca1d)
same Issue on latest LTS.

**Comment by Leif-W** [comment]
`npm -g i npm` worked for me.  So people will need more details to reproduce.  Like which version of nodejs is installed?  I've got node v20.2.0.  Did you uninstall and reinstall nodejs?  What is the LTS version?  nodejs-lts is v18.16.1?  Did the patch get backported upstream?  Will it ever?  Did you try `nodejs` (current)?  Is upgrading nodejs possible?  IDK what else to try, that's all I did and things worked since the upstream patch landed.

**Comment by Leif-W** [comment]
nodejs-lts has nodejs v18.16.1 and npm v9.5.1.  The fix landed in cacache v17.0.7.  npm v9.5.1 is using cacahe v17.0.4.  cachev17.0.7 doesn't land in npm until npm v9.6.6, which doesn't land in node until node v18.17.0, which is the very next release after node v18.16.1.  Can nodejs-lts simply be bumped up to v18.17.0 to fix npm self-updates?

**Comment by Leif-W** [comment]
Now when I uninstall nodejs-lts and reinstall nodejs which has the upstream-fixed npm v9.6.6, I can't upgrade because the outdated Termux patch which references this issue 13293 is still applied.

So 2 things:

1) For nodejs package, remove the unneeded packages/nodejs/deps-npm-lib-commands-install.js.patch as nodejs npm v9.6.6 includes cacache v17.0.7 which was fixed for this issue upstream in cacache v17.0.4.

2) For nodejs-lts package, can we bump up one release, from 18.16.1 to 18.17.0 to include npm v9.6.6?  If yes, then likewise delete the cruft deps-npm-lib-commands-install.js patch.

As a workaround, use yarn or possibly another package manager (pnpm gave me a problem which I've not yet diagnosed), to install npm globally.  `yarn global add npm`  Then use npm to install itself globally to the same version (`npm -g i npm`), to clobber any cruft left behind by yarn which may cause discrepancies in reported (i.e. npm v9.6.6) vs installed version (i.e. npm v9.8.1).  (I use npm-check-updates which shows the discrepancy.)

**Comment by GuriZenit** [comment]
> Now when I uninstall nodejs-lts and reinstall nodejs which has the upstream-fixed npm v9.6.6, I can't upgrade because the outdated Termux patch which references this issue 13293 is still applied.  (Edit: I may have previously upgraded using yarn but then forgot.  See workaround below.)
> 
> So 2 things:
> 
> 1) For nodejs package, remove the unneeded packages/nodejs/deps-npm-lib-commands-install.js.patch as nodejs npm v9.6.6 includes cacache v17.0.7 which was fixed for this issue upstream in cacache v17.0.4.
> 
> 2) For nodejs-lts package, can we bump up one release, from 18.16.1 to 18.17.0 to include npm v9.6.6?  If yes, then likewise delete the cruft deps-npm-lib-commands-install.js patch.
> 
> As a workaround, use yarn or possibly another package manager (pnpm gave me a problem which I've not yet diagnosed), to install npm globally.  `yarn global add npm`  Then use npm to install itself globally to the same version (`npm -g i npm`), to clobber any cruft left behind by yarn which may cause discrepancies in reported (i.e. npm v9.6.6) vs installed version (i.e. npm v9.8.1).  (I use npm-check-updates which shows the discrepancy.)

It happened to me, I was wondering why it worked at first, but not on reinstallation, but I used `npm i -g npm --force` instead.

**Comment by Leif-W** [comment]
Again, I have been bypassing this ridiculous limitation for over a year with no ill effects.  The upstream bug which initially triggered this problem has long since been fixed, as noted above, though stubborn illiteracy prevails here.  The ostrich fix here, to not chdck for updates and pretdnd they don't exist, and keep applying a patch for a problem that no longer exists, is beyond silly.  If it's broken, prove it's broken with a specific test, not assume it's broken bevause it broke a few years ago.

**Comment by IamdeiAm** [comment]
Please help out am facing this 
On my Termux on my android phone 


error: "/data/data/com.termux/files/usr/lib/node_modules/node-gyp/bin/node-gyp.js" has bad ELF magic: 23212f75
npm error code 1
npm error path /data/data/com.termux/files/usr/lib/node_modules/truffle/node_modules/bufferutil
npm error command failed
npm error command sh -c node-gyp-build

npm error A complete log of this run can be found in: /data/data/com.termux/files/home/.npm/_logs/2024-08-31T16_01_42_647Z-debug-0.log
~ $
~ $

**Comment by shadow1-ux** [comment]
I tried 
npm install package
npm install -g npm
But the same error is popping 😞

**Comment by warp9pnt9** [comment]
> I tried
> npm install package
> npm install -g npm
> But the same error is popping 😞

Try:

1. pkg install yarn
2. yarn global remove npm
3. yarn global add npm

The offending code was javascript, not binary, and was fixed several years ago in the specific patches I referenced above, but for whatever reason, the Termux devs do not understand or didn't bother reading or don't want to believe it.  Instead, they leave the error message or try to thwart user attempts to upgrade npm.  I've been bypassing this nag for years with zero issues.

There's no need for the silliness.  I call on the devs to show proof that there is any bug at all related to this before they start ripping upgrade features out of users' hands.  I don't think there is.  If there is a bug, I have not seen it.  If I am wrong, fine, but prove it.  I've shown evidence of the official nodejs and npm patches where the issue was identified and resolved nearly 3 years ago.  There's no discussion, no evidence, no dielectic, the devs offer opinion and stubborness.

[edit: fix typo]

**Comment by robertkirkman** [comment]
@Leif-W thanks for explaining, 

**I can confirm, consistent with your claim, that removing the patches and recompiling Termux `nodejs`, followed by using the command `npm install -g npm`, restarting the shell, and using `npm install uuid` or `npm outdated -g`, does not result in any errors on my devices**.

~~I'm not very experienced with NodeJS, and I was not here when this issue was first worked on, so I wasn't aware of this problem.~~

~~I have created a PR to try to fix this and requested approval from other Termux maintainers to accept your idea.~~

~~If you have further input, could you review my PR, and if any further adjustments to my PR are necessary in your opinion, could you leave a review in my PR explaining what further changes are necessary?~~

**EDIT**: @Leif-W I have been informed that this is already planned to be fixed in a future update, if you wait some time, then eventually this will get fixed.
