### ISSUE TITLE
Failing to load Weechat's matrix and python plugin

### ISSUE THREAD

**Issue by IRISnoir** [termux/termux-packages#13297]
![Screenshot_2022-11-20-11-59-09-19_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/46418295/202886410-acd08d61-17f9-4b49-af19-7cee0ba11041.jpg)

This is what I have after updating Termux packages after a long long time

**Comment by xtkoba** [comment]
The following is a kind of dev discussion.

We already had similar cases for `gdb` and `profanity` (#12920). This happens because dependency on `python` does not necessarily imply dependency on a specific version of Python (for example when a package only installs pure Python scripts under `$PREFIX/bin/`) and hence we do not rebuild every revdep after a Python major bump. A package calling `termux_setup_python_crossenv` in `build.sh` is highly probable that it needs to rebuild and actually I rebuild it. But not for others. Can (or should) this situation be improved?
