### ISSUE TITLE
[Disscussion]: Split OpenGL libraries from mesa

### ISSUE THREAD

**Issue by licy183** [termux/termux-packages#13887]
I think making a package depend on the current `mesa` package is ambiguous. It doesn't show clearly which libraries they really depend on (libGL, libGLESv1, libGLESv2 or OSMesa). Should we spilt the packages as [`debian`](https://packages.debian.org/source/sid/mesa) or [`archlinux`](https://github.com/archlinux/svntogit-packages/tree/packages/mesa/trunk) do?

If #13809 is merged, we now have two different vendored OpenGL libraries (Mesa's and ANGLE's). Other distributions use [`libglvnd`](https://gitlab.freedesktop.org/glvnd/libglvnd) to handle different vendored OpenGL libraries. Should we use that too?

CC: @Grimler91 @xtkoba

**Comment by xtkoba** [comment]
For end-users, anything will do unless it breaks consistency.

As a package maintainer, I want to simply write as

```bash
TERMUX_PKG_DEPENDS="opengl"
```

for packages that depend on some OpenGL functionality, whether it be Mesa or ANGLE, or plain GL or EGL.

**Comment by xtkoba** [comment]
Also as a reviewer, I prefer some simple way of specifying dependency on OpenGL in `build.sh`. Contributors are not always very much aware of the structure of Termux packages, and can easily write incorrect dependency if it is complicated. For example now and then I see a dependency specification that misses `ncurses-ui-libs`. This is hard to notice in CI because it pulls in superfluous packages.

**Comment by xtkoba** [comment]
Also as a Gentoo (a Linux distribution) user I'm not in favor of providing separate EGL package. Gentoo (Portage) provides a metapackage `virtual/opengl` that pulls in `media-libs/mesa` in which EGL is forcibly enabled. It should be noted that formerly EGL was optional but that the option was removed because <a href="https://gitweb.gentoo.org/repo/gentoo.git/commit/media-libs/mesa?id=4dd59fa7fb6e80db150d9d754cda4fd43e2a594d">"There's not a sensible reason to disable this while OpenGL is enabled."</a> But please note also that Portage is a source-based distribution and this does not necessarily apply to Termux which primarily adopts binary-based distributions.

**Comment by xtkoba** [comment]
(FWIW, `osmesa` is still an option in Gentoo Portage's `media-libs/mesa`.)

**Comment by truboxl** [comment]
angle is never really used as a driver but as a component for apps

**Comment by licy183** [comment]
> angle is never really "distributed" as a driver but as a component for apps

Yes. It is from chromium and no Linux distribution ever uses it as OpenGL drivers.

> it may even be possible to do angle on top of mesa instead angle on top of swiftshader... some food for thoughts...

ANGLE actually translates OpenGL ES operations to vulkan operations, and `swiftshader` could provide a software implementation of vulkan, so I think ANGLE can work on top of swiftshader. Of cource, according the docs of ANGLE, it can also translate OpenGL ES operations to Desktop GL. I will do some local tests later.

The main reason why I want to add ANGLE is that `libEGL.so` is necessary for lots of applications. I don't think mesa could provide `libEGL.so`. According to its docs, `libEGL.so` must use `egl_dri2` driver,  which cannot work on Termux. That would be awesome if someone can make it work properly.

PS: I'm working on compiling chromium there days, and chromium must use `libEGL` as it dependicies then x11 support is  enabled (See https://github.com/chromium/chromium/blob/182ed04052478f60fedcea49d60529c81a589d90/ui/gl/BUILD.gn#L288). I compiled [`a dummy mesa`](https://github.com/termux-user-repository/tur/pull/176/commits/369b1d5d3d0c0069acffa93ac78cdaf4bea03588) for chromium to make the building system happy. Actually, it cannot work properly. Then I did more investigation on how chromium process on rendering and finally found out ANGLE over SwiftShader.
