### ISSUE TITLE
Build from a local git repository

### ISSUE THREAD

**Issue by aadcg** [termux/termux-packages#14317]
I'm following [these instructions ](https://github.com/termux/termux-packages/wiki/Building-packages#tips-and-tricks), but I'm getting the following:

```log
~/repos/termux-packages $ ./scripts/run-docker.sh ./build-package.sh libfixposix
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
termux - building libfixposix for arch aarch64...
]0;libfixposix...Downloading file:///home/aadcg/repos/libfixposix.git
curl: (37) Couldn't open file /home/aadcg/repos/libfixposix.git
Failed to download file:///home/aadcg/repos/libfixposix.git
```

The folder `/home/aadcg/repos/libfixposix.git` exists and it is a git repository. Any ideas? Thanks.

**Comment by Grimler91** [comment]
As in other issue, try `git+file:///home/aadcg/repos/libfixposix.git` instead

**Comment by agnostic-apollo** [comment]
Issue is likely that `/home/aadcg/...` exists in your local host only. The docker script only mounts the current `termux-packages` directory. The instructions are not very clear about building. You need to move your package repo, under the `termux-packages` directory, otherwise it won't be visible. The instructions are not very clear regarding this. Something I do, which may need more perfecting is the following. It creates a git tag for the version being built and automatically deletes it after building and returns to current branch.


- Move package source directory to `termux-packages/termux-api-package.git`. Or copy if you don't want to risk losing original directory if something goes wrong. If directory does not exist inside `termux-packages` directory, it won't
be mounted in docket container and you will get `No such file or directory` errors, so don't even use symlinks to an outside directory.

`cp -r termux-api-package termux-packages/termux-api-package.git`

- Ensure `git init` has been run if `.git` directory does not exist inside package source directory.

- Add following to termux-packages/termux-api/build.sh:

```shell
TERMUX_PKG_SRCURL=file:///home/builder/termux-packages/termux-api-package.git
TERMUX_PKG_SHA256=SKIP_CHECKSUM
```

- Start docker interactive session

```shell
./scripts/run-docker.sh
```

- Source function to build package

```shell
git config --global user.name "agnostic-apollo"
git config --global user.email "agnosticapollo@gmail.com"
build_local_package() {
#scripts/build/get_source/termux_git_clone_src.sh runs `git clone --depth 1 --branch "v$TERMUX_PKG_VERSION" $TERMUX_PKG_SRCURL`
package="$1"
# Branch to create tag from
branch="main" \
tag="$(grep -E '^TERMUX_PKG_VERSION=' "packages/$package/build.sh" | cut -d '=' -f2 | tail -n 1)"; \
source="$(grep -E '^TERMUX_PKG_SRCURL=' "packages/$package/build.sh" | cut -d '=' -f2 | tail -n 1 | sed 's|^file://||')"; \
branch_created=false; \
(cd "$source" && git checkout "$branch" || exit 1; git branch -D "v$tag" 2>/dev/null || :; git checkout -b "v$tag"; git add -A; git commit -m "$tag";) && \
branch_created=true && \
rm -rf "/home/builder/.termux-build/$package/" "/data/data/.built-packages/$package" && \
./build-package.sh -f "$@" "$package"; \
[ "$branch_created" = "true" ] && (cd "$source" || exit 1; git reset --soft HEAD^; git checkout "$branch";) 1>/dev/null
}

```

- Build package with `build_local_package termux-api -I`

**Comment by aadcg** [comment]
@agnostic-apollo I understand the approach you're suggesting. Thanks for the detailed explanation.

@Grimler91's tip on this one does it for me.

**Comment by aadcg** [comment]
@agnostic-apollo I understand the approach you're suggesting. Thanks for the detailed explanation.

@Grimler91's tip on this one does it for me.
