### ISSUE TITLE
Package Request: pass

### ISSUE THREAD

**Issue by brandonchartier** [termux/termux-packages#147]
[Pass](https://www.passwordstore.org/): The Standard Unix Password Manager

I'm unsure of how simple it would be to get the clipboard functionality, but this is a staple in many peoples' toolkits and would be a great alternative to some of the managers in the Play Store.

**Comment by Neo-Oli** [comment]
Pass is a bash script, so there is no need to compile it. I tried installing it and it mostly runs in termux already. 
`pass init KEY` causes the following error which I don't understand yet: `line 85: /dev/fd/62: No such file or directory`
If you run it with zsh instead of bash  `pass init KEY` works (other commands that work with bash break however). 

I made an early attemt to patch termux-clipboard functionality into it and it sort of works, but I had to remove the base64 encoding stuff from the clip() function, because the string encodes slightly differently after going through `termux-clipboard-set` and `termux-clipboard-get`. It works now, but that encoding was probably there for a reason. I also had to remove the `exec -a` line, because that strangly doesn't work resulting in a command-not-found error. This means it would wipe your clipboard of you decrypt 2 passwords within 45 seconds, as it can't kill the previous sleep command. 
[pass.patch](https://gist.github.com/Neo-Oli/eb9a5c5bcfdbb4ca5488)

**Comment by Neo-Oli** [comment]
I managed get the base64 encoding stuff working. I still have a problem with the `exec -a` stuff. 
`(exec -a Hello sleep 120)` should cause bash to create a sleep process with name "Hello" but instead returns an unknown program error.

**Comment by Neo-Oli** [comment]
Here's my other problem: `while read test; do echo $test; done < <(find .)` causes bash to fail with `/dev/fd/62: No such file or directory`. I don't really understand what does. It seems to be a special kind of redirection. I am so far unable to find any information on it or why it fails in termux. I can think of other ways to program these two problems that would probably work, but I don't really want to change dozens of lines of code. 
Any help with that or the other problem would be greatly appreciated.

**Comment by fornwall** [comment]
@Neo-Oli The problem with process substitution (the `<(...)` construct) not working in bash under Termux has just been fixed (ab41f5b49cacf14dc6dbe1c35926100a86d15611) in version `4.3.42-7`of the bash package.

After updating with `apt update && apt upgrade` you should be able to use it (not that you need to start a new bash process after updating, since the one you are running are still using the old version).

**Comment by Neo-Oli** [comment]
@fornwall Awesome. With that, the `exec -a` solution from IRC and an aditional edit to `pass edit` to write to $PREFIX/tmp instead of tmp, I think everything may be working. I updated [my patch](https://gist.github.com/Neo-Oli/eb9a5c5bcfdbb4ca5488).

**Comment by fornwall** [comment]
@Neo-Oli I'm looking to add this, but I'm having problem with applying your patch, I get

    Hunk #3 FAILED at 135.
    Hunk #4 FAILED at 152.
    Hunk #5 FAILED at 176.
    3 out of 5 hunks FAILED -- saving rejects to file src/password-store.sh.rej

I'm trying with pass master (https://git.zx2c4.com/password-store/snapshot/password-store-0b2f803fe61992af02b8820c400984b1f615a299.tar.xz) and also the latest released version version 1.6.5. Am I doing something wrong or is your patch against another version?

**Comment by Neo-Oli** [comment]
@fornwall Sorry, there was some kind of whitespace issue between my patch and the gist. It should be fixed now. 
Also, I originally patched against  version 1.6.5, but there doesn't seem to be any difference between that version and master yet.

**Comment by fornwall** [comment]
@Neo-Oli Great, it applies now! Which dependencies should the package have, something more than bash and coreutils?

**Comment by fornwall** [comment]
... and I guess `gpg`, `pwgen` and `git` as dependencies?

**Comment by Neo-Oli** [comment]
For general usage it also needs `tree`
For the clipboard functionality it needs `termux-api`

But I think `termux-api` and `git` could be optional, because pass works without them if you don't need these functions, but will throw command not found errors if `pass -c password` or `pass git status` is called. I am unsure what the policy for such dependencies is.

**Comment by fornwall** [comment]
The [pass package](https://github.com/termux/termux-packages/tree/master/packages/pass) is now available and can be installed with `apt install pass` (after the package index has been updated with `apt update`) - try it out and let me know if anything is broken!

**Comment by Neo-Oli** [comment]
@fornwall Question, why do you think pass needs coreutils? I've done a bit of testing and it seems to work fine without it.
