### ISSUE TITLE
apt over-write source.list everytime it is updated

### ISSUE THREAD

**Issue by huiyiqun** [termux/termux-packages#148]
I'm using mirror of TUNA, but everytime apt is updated, ˋsource.listˋ is overwritten. It's annoying.

**Comment by 4679** [comment]
yeah

**Comment by fornwall** [comment]
Hi, thanks for reporting the issue! This has now been fixed in the latest version of the apt package (`1.2.4`), which can be installed with `apt update && apt ugprade`.

Note that installing version 1.2.4 will overwrite the etc/sources.list file one last time - but coming updates of apt will no longer overwrite the file (in the unlikely case that the distribution file changes, you will get to resolve the conflict manually).
