### ISSUE TITLE
[Package]: Tiny C Compiler

### ISSUE THREAD

**Issue by HemanthJabalpuri** [termux/termux-packages#14837]
### Why do you want to add this package to Termux?

Tiny package to compile C programs

### Home page URL

https://bellard.org/tcc/

### Source code URL

https://repo.or.cz/w/tinycc.git

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by TomJo2000** [comment]
This project [looks to be abandoned](https://bellard.org/tcc/#:~:text=I%20am%20no%20longer%20working%20on%20TCC).
Although it is still [widely packaged](https://repology.org/project/tcc/versions).

**Comment by xtkoba** [comment]
`tcc` is now in <a href="https://github.com/termux/termux-packages/blob/b4a715288f40445b50d6ea58958ed8f8b49cc74c/disabled-packages/tcc/build.sh">disabled-packages</a>. According to the message in 23e4884159ec4b3e0b2527ad4e8279775d31888f, it has been disabled because the use cases are limited on Android. But I think it's OK to enable it if you think it is useful. PR is welcome.
