### ISSUE TITLE
Cannot open display - Xwayland client

### ISSUE THREAD

**Issue by lmservas** [termux/termux-packages#14883]
Attempted to install Yisus7u7's mate and xfce4 desktop environments and use them with Termux-X11 and am met with the following:

❯ export XDG_RUNTIME_DIR=${TMPDIR} ~
❯ termux-x11 :1 >/dev/null & ~
[1] 4738
❯ res = 0 ~
Activity is started
Got getWaylandFD
{ParcelFileDescriptor: java.io.FileDescriptor@455f91e}
Lorie requested fd
Got getLogFD
{ParcelFileDescriptor: java.io.FileDescriptor@5b665ff}
Got finish request
App sent finishing command
Starting Xwayland
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/Xwayland": cannot locate symbol "ffi_type_uint32" referenced by "/data/data/com.termux/files/usr/lib/libwayland-client.so"...

[1] + 4738 exit 1 termux-x11 :1 > /dev/null
❯ env DISPLAY=:1 mate-session ~

** (mate-session:5196): WARNING **: 00:05:26.480: Cannot open display:
1 ❯ ~

**Comment by xtkoba** [comment]
Please share the output of `termux-info` command if you file a bug report.

The issue for @edgarluck is not guaranteed to be the same as that for @lmservas. I would recommend opening a new issue for that.

**Comment by twaik** [comment]
You are right, edgarluck's issue is related to another problem...

**Comment by xtkoba** [comment]
As for the OP's issue, I don't know the real cause but it could potentially happen with partial upgrading, when the SOVERSION of libffi assumed by `libwayland-client.so` is different from that of installed `libffi.so`.

I would like to close this issue as "obsolete" because it is more than one year old and we cannot reproduce it now. (If it were relatively new I would close it as "invalid".)
