### ISSUE TITLE
cmake: allow to set CMAKE_HOST_SYSTEM_NAME/CMAKE_SYSTEM_NAME back to Linux

### ISSUE THREAD

**Issue by wuqs-net** [termux/termux-packages#15103]
In #4222 the variables `CMAKE_HOST_SYSTEM_NAME`/`CMAKE_SYSTEM_NAME` are changed to `Android`, which makes it very hard to build some source code that are intended to be built on Linux. Can we have an easy way to switch these variables back to `Linux`?

**Comment by xtkoba** [comment]
Yeah we have a bunch of packages in which we have to pretend to be non-Android, because many projects assume "Android" to be used when and only when building Android app. But note that in many cases we cannot completely pretend to be non-Android, because "Android" also implies Bionic libc being used, which is different from glibc or musl assumed by "Linux".

Also I suppose this affects `SONAME` for shared libraries, because Android does not have SOVERSION suffix, whereas Linux does. Tree-wide rebuild would be necessary to achieve this.

IMO this proposal (to revert back to "Linux") should not be made but instead build scripts (cmake files) for individual projects should be patched.

**Comment by xtkoba** [comment]
This discussion also applies to `host_system` variable in Meson build system.

**Comment by wuqs-net** [comment]
Can we have an option to decide when to pretend to be Linux and when not? I'm not sure if this is possible to implement, as I'm not familiar with the low-level stuff.

**Comment by xtkoba** [comment]
Ah, you mean just an option. That should be possible then.

**Comment by wuqs-net** [comment]
Yeah, maybe like an environment variable or a patched executable `cmake-linux`, not sure what would be the best approach.

**Comment by Sheenur** [comment]
Whenever I want to install ssh on my terminal i receive this error message "CANNOT LINK EXECUTABLE "dropbearkey": library "libcrypto.so.3" not found"

**Comment by xtkoba** [comment]
I wrongly assumed that this issue is about <a href="https://github.com/termux/termux-packages/tree/master/scripts/build/configure/termux_step_configure_cmake.sh">`termux_step_configure_cmake`</a>. In fact that is not the case, because #4222 is for `cmake` package, not for build scripts.

That said, I suppose this is still possible, though I'm not much interested now.

**Comment by truboxl** [comment]
I do not believe in changing `CMAKE_HOST_SYSTEM_NAME`/`CMAKE_SYSTEM_NAME` to `Linux` make sense as a lot of projects have different meanings when it comes down to those variables. In most cases, `Android` make senses in Termux environment except there is no `Android` option. So it is a case by case situation.

What's stopping you from `cmake .. -DCMAKE_HOST_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_NAME=Linux && cmake --build .`?

**Comment by xtkoba** [comment]
Ah, yes, I also wonder if specifying these variables as command-line arguments does not work.

**Comment by truboxl** [comment]
Closed by mistake

**Comment by wuqs-net** [comment]
> What's stopping you from `cmake .. -DCMAKE_HOST_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_NAME=Linux && cmake --build .`?

Well, this simply does not work. You can see if you specify these variables here and then do `message(${CMAKE_HOST_SYSTEM_NAME})`.

I'm not saying just change it to Linux. What I meant is _allow_ to change it. Then under a "case by case situation" when we want Linux it would be possible to do so.

**Comment by Grimler91** [comment]
It works fine to set `CMAKE_SYSTEM_NAME` with configure args, but `CMAKE_HOST_SYSTEM_NAME` is set when cmake is compiled.

What program are you trying to compile? How would changing `${CMAKE_HOST_SYSTEM_NAME}` help, how does the program's CMakeLists.txt use `${CMAKE_HOST_SYSTEM_NAME}`?

**Comment by truboxl** [comment]
CMakeFiles.txt
```cmake
message("ANDROID: ${ANDROID}")
message("CMAKE_SYSTEM_NAME: ${CMAKE_SYSTEM_NAME}")
message("CMAKE_HOST_SYSTEM_NAME: ${CMAKE_HOST_SYSTEM_NAME}")
project(Foo)
message("ANDROID: ${ANDROID}")
message("CMAKE_SYSTEM_NAME: ${CMAKE_SYSTEM_NAME}")
message("CMAKE_HOST_SYSTEM_NAME: ${CMAKE_HOST_SYSTEM_NAME}")
```
Default (Termux)
```
ANDROID: 
CMAKE_SYSTEM_NAME: 
CMAKE_HOST_SYSTEM_NAME: Android
-- The C compiler identification is Clang 15.0.7
-- The CXX compiler identification is Clang 15.0.7
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
ANDROID: 1
CMAKE_SYSTEM_NAME: Android
CMAKE_HOST_SYSTEM_NAME: Android
-- Configuring done
-- Generating done
-- Build files have been written to: /data/data/com.termux/files/home/cmake/termux
```
`-DCMAKE_SYSTEM_NAME=Linux -DCMAKE_HOST_SYSTEM_NAME=Linux`
```
ANDROID: 
CMAKE_SYSTEM_NAME: Linux
CMAKE_HOST_SYSTEM_NAME: Android
...
ANDROID: 
CMAKE_SYSTEM_NAME: Linux
CMAKE_HOST_SYSTEM_NAME: Android
```
`-DANDROID=0`
```
ANDROID: 0
CMAKE_SYSTEM_NAME: 
CMAKE_HOST_SYSTEM_NAME: Android
...
ANDROID: 1
CMAKE_SYSTEM_NAME: Android
CMAKE_HOST_SYSTEM_NAME: Android
```
`-DANDROID=0 -DCMAKE_SYSTEM_NAME=Linux`
```
ANDROID: 0
CMAKE_SYSTEM_NAME: Linux
CMAKE_HOST_SYSTEM_NAME: Android
...
ANDROID: 0
CMAKE_SYSTEM_NAME: Linux
CMAKE_HOST_SYSTEM_NAME: Android
```
Ok confirm `CMAKE_HOST_SYSTEM_NAME` is hardcoded. But the rest as you can see can be changed when set properly. If you think this is still something need to provided, you should approach upstream: https://gitlab.kitware.com/cmake/cmake/-/issues/23089

I don't think we patch CMake to change its behaviour except for fixing issues

**Comment by xtkoba** [comment]
`CMAKE_HOST_SYSTEM_NAME` is hardcoded as `Linux` due to the following code:

https://github.com/Kitware/CMake/blob/8b1160b509962f9ef6be43ef495a23f359c910ce/Source/cmSystemTools.cxx#L3680-L3685

```c++
cm::string_view cmSystemTools::GetSystemName()
{
#if defined(_WIN32)
  return "Windows";
#elif defined(__ANDROID__)
  return "Android";
```

Note that this is not relevant to the PR referenced in the description any longer.

IMO, if any project does not build on Android due to `CMAKE_HOST_SYSTEM_NAME`, then the CMake files of that project should be patched. Unfortunately I am not aware of such a case, because our "packaging" principally means cross-building on GNU/Linux.
