### ISSUE TITLE
[Bug]: qt5-qtwebengine: `build.sh` incompatible with recent change for `lib{pthread,rt}`

### ISSUE THREAD

**Issue by xtkoba** [termux/termux-packages#15152]
### Problem description

Build of `qt5-qtwebengine` messes up `$TERMUX_PREFIX/lib/librt.so`:

https://github.com/termux/termux-packages/blob/610e311f9affe25458d319e067f9ea0229e84201/x11-packages/qt5-qtwebengine/build.sh#L42-L45

What is worse is that this file is removed afterwads:

https://github.com/termux/termux-packages/blob/610e311f9affe25458d319e067f9ea0229e84201/x11-packages/qt5-qtwebengine/build.sh#L79-L80

### What steps will reproduce the bug?

Build any package that relies on the existence of `librt.so` after building `qt5-qtwebengine`.

### What is the expected behavior?

`$TERMUX_PREFIX/lib/librt.so` should not be touched in this way.

### System information

Irrelevant.

**Comment by xtkoba** [comment]
ping @licy183 (as the mantainer of this package)

**Comment by licy183** [comment]
I tried to patch the GN files before, but lots of chromium dependencies needs to link against `libandroid-shmem, `libiconv` and `log`. As always, the building system of `qtwebengine` (or `chromium`) always assume that the target libc is GNU's. `libandroid-shmem`, `libiconv` are part of glibc. The linkage of `liblog` is caused by the incomplete patch for `__ANDROID__` macros. What makes it even harder is that IIRC the building system of `qtwebengine` will not follow the environment variable `LDFLAGS`.

I will try to patch the GN files again. But I suppose that overriding and removing `librt.so` will not break the building system for other packages on the CI, because `termux_step_start_build` will create it if it doesn't exist. It will break if you previously build `qt5-qtwebengine` and cancel it and then build other packages locally.

**Comment by xtkoba** [comment]
OK then.

**Comment by xtkoba** [comment]
No. I think this may be still an issue with on-device building.

Please preserve the original `$TERMUX_PREFIX/lib/librt.so` and restore afterwards, if it needs to be modified in the build. This should be trivial and I can handle it on my own, if the named maintainer is not willing to do it.

**Comment by licy183** [comment]
I don't think `qt5-qtwebengine` will be able to build on device. Maybe we should mark it as `not safe to build on device` as many packages do.

**Comment by xtkoba** [comment]
Fair. Then please mark this package as not suitable for on-device building. Thanks.
