### ISSUE TITLE
Regenerate the bootstrap*.zips

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#1534]
Hi
Could you please regenerate the bootstrap*.zips. Termux-exec broke https://github.com/Neo-Oli/chrooted-termux/, so I need to switch to using the login script instead of invoking the shells directly, which I can't do if the resulting termux-fs still contains the old login script. 

By the way. Termux-exec is likely to break all proot environments, because it gets passed along to the proot environment, where it `libtermux-exec.sh` can't be found. I need to unset LD_PRELOAD specifically in the start.sh script. With chrooted-termux I'll call the new login script, which will set LD_PRELOAD only if Termux-Exec is also installed in the proot environment.

**Comment by fornwall** [comment]
Regeneration done!

About `LD_PRELOAD` - perhaps we can modify `proot` to always clear `LD_PRELOAD` (or special case `libtermux-exec.so`)?

In the long run, perhaps we can replace that by moving the `execve()` wrapper to a shared library that everything links to (we can patch clang so that everything that gets built on device also links against that library)?

**Comment by Neo-Oli** [comment]
> About LD_PRELOAD - perhaps we can modify proot to always clear LD_PRELOAD (or special case libtermux-exec.so)?
I'm not sure this is necessary. It's just [one short line](https://github.com/Neo-Oli/termux-ubuntu/blob/master/ubuntu.sh#L34) that needs to be added in the various start scripts. I've done it in my two (chrooted-termux and termux-ubuntu) and I am only aware of one more (https://github.com/nmilosev/termux-fedora by @nmilosev). There might be other uses for LD_PRELOAD, so clearing it might be bad.
