### ISSUE TITLE
[Package]: Ansible 

### ISSUE THREAD

**Issue by landonh3x** [termux/termux-packages#15377]
![Screenshot_20230228-113920](https://user-images.githubusercontent.com/45246041/221918867-631dd825-738b-458d-94ea-333131500477.png)
### Why do you want to add this package to Termux?

It would be a great benefit for automation of networks and servers in a convenient android package :), thank you guys for all the work you and everyone who contributes to Termux! 

The issue that shows when trying to us Ansible within Termux is this:
~ $ ansible -m copy -a "src=~/.ansible/tmp/test dest=~/test2" localhost
[WARNING]: No inventory was parsed, only implicit localhost is available
localhost | FAILED! => {
    "msg": "failed to transfer file to /data/.ansible/tmp/ansible-tmp-1677602072.8249712-21641-60801604337728/AnsiballZ_stat.py: [Errno 2] No such file or directory: b'/data/.ansible/tmp/ansible-tmp-1677602072.8249712-21641-60801604337728/AnsiballZ_stat.py'"
}

### Source code URL

https://github.com/ansible/ansible

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Pip installing works with this package but not thinking it seems to be playing well with the Python 3.11 maybe? Alot of errors seem to be getting spit out for me. I have Yaml installed and everything needed. Maybe it's just me. I just figure maybe if it's customized for Termux it would have better compatibility then the pup install.

**Comment by xtkoba** [comment]
First note that `ansible` is installable through pip without any problems.

To me the command line in the description looks wrong, because tilde (`~`) is quoted in it. This should not be quoted if it is expected to expand to the path to home directory. I don't know how `ansible` handles the literal `~`, but the error message suggests that it is expanded as `/data`. I remember I saw a similar case with Perl before.

If for example there are hard-coded paths like `/tmp` in the installed files, then we have a good reason to package this on our own. But I don't see any evidence yet.

Labeling as wontfix for now, but that does not mean that we do not package it forever. If we are provided with a good reason, then we are happy to package it.

**Comment by landonh3x** [comment]
Thank you for the clarification and update on the situation. I
appreciate it.
