### ISSUE TITLE
Can't save files to /data/.ssh

### ISSUE THREAD

**Issue by RockyTV** [termux/termux-packages#156]
Whenever I try to ssh to a server, or try to generate a ssh keypair, it says it can't write to /data/.ssh/ because permission is denied.

How to proceed? I'm using the latest version available on F-Droid.

**Comment by fornwall** [comment]
Have you installed the `openssh` package with `apt install openssh`?

It seems that you are trying to run a ssh version provided by your ROM, and this ssh version requires root to write to /data/. You can confirm that by running `which ssh` - this should be a `/data/data/com.termux/files/usr/bin/ssh` when using the ssh binary provided by Termux.

After installing the openssh Termux package you need to run `hash -r` to clear the bash executable path cache to pick up the right binary in the current bash session (otherwise the current bash session continues to use the old ROM-supplied ssh binary).

**Comment by RockyTV** [comment]
Doing the steps you mentioned fixed the issue for me, thank you very much!
