### ISSUE TITLE
mutt smtp issue

### ISSUE THREAD

**Issue by bfortz** [termux/termux-packages#1582]
Since I upgraded packages yesterday mutt cannot send emails using the embedded smtp anymore. I get a "No authenticators available" error. I suspect an SSL/TLS error or something with libsasl.
Maybe due to the fact that libsasl is now build with --disable-gss-api?
Debug not being enabled in mutt, it's hard to figure out what is wrong.

**Comment by Grimler91** [comment]
I think you're right that the error is due to libsasl being built with `--disable-gssapi`. 

I tried building with `--with-gssapi` instead but the build failed due to the configure script trying to run a android binary as part of a test. There might be some cross compiling flag to set, alternatively we'll need to patch the configure script a little bit.

**Comment by fornwall** [comment]
Hm, did it work before?

The libsasl package has never been built with `--with-gssapi`. It's true that `--with-gssapi` was added, but that was just to avoid accidental linkage - the distributed libsasl package never used it.

**Comment by Grimler91** [comment]
Right, maybe it has to do with the mutt upgrade, 1.8.3 -> 1.9.0 then.

Something is different from before.

**Comment by Grimler91** [comment]
`git checkout d3594e89a955fa3e3913eca0902aeca267391570 packages/mutt` (mutt 1.8.3) did not solve the problem.

**Comment by fornwall** [comment]
Hm, could it have to do with the latest libsasl package?

It was rebuilt (bumped revision, so updated from `2.1.26` to `2.1.26-1`) to get an updated .deb file (with control.tar.xz instead of control.tar.gz) - it wasn't intended to change how the package have been built, but it may have accidentally?

**Comment by bfortz** [comment]
I have rebuild mutt with debugging enabled, the problem is clearly linked with libsasl: 
[2017-09-26 16:43:31] SASL: No worthy mechs found
[2017-09-26 16:43:31] smtp_auth_sasl: (null) unavailable
[2017-09-26 16:43:31] No authenticators available
I will investigate further...

**Comment by bfortz** [comment]
Well, I don't know why --disable-gssapi was added. Building without it (but also without --with-gssapi) works perfectly and fixes the problem for me.

**Comment by Grimler91** [comment]
Seems like a bug in the configure script for mutt. Great that it works anyways!

**Comment by fornwall** [comment]
I think I've found the problem!

The libsasl package should contain the following libraries in `$PREFIX/lib/sasl2/`:

- libanonymous.so
- libcrammd5.so
- libdigestmd5.so
- libplain.so

The current libsasl package at version `2.1.26-1` did not contain libplain.so, which causes the `No authenticators available`.

A rebuild fixes this, which is why your new build worked @bfortz - it wasn't due to removing `--disable-gssapi` (you probably didn't build kerberos before anyway, so it didn't make a difference) - it was just a rebuild that was necessary.

Version `2.1.26-2` of libsasl which is available fixes this problem - update with `pkg up`, after which it should start working again.

As for why libplain.so? I don't know yet, but 5519960bb1f62548d0f4d03a479e2d4523c7f22a adds a check that causes the build to bail out with an error if it happens again instead of creating an incomplete package.

**Comment by fornwall** [comment]
Nice work @bfortz and @Grimler91  in reporting and working on the issue!

**Comment by bfortz** [comment]
@fornwall thanks for fixing it so quickly, and for all the work. Termux is great! I wish I could contribute more in the future.

**Comment by ZerooCool** [comment]
SASL est apparemment requis pour que mutt s'authentifie à l'aide de smtps.
Installer le paquet suivant résout le problème : sudo apt install libsasl2-modules
Apt a répertorié ce paquet comme "recommandé", ce qui n'est pas un bogue, car vous n'en avez pas besoin pour exécuter mutt.

# SENDING MAIL
set smtp_url = "smtps://sow.eclipse@smtp.gmail.com:465/"
set smtp_pass = "PASSWORD"
set from = "sow.eclipse@gmail.com"
set realname = "Je suis l'utilisateur du VPS"

# RECEIVING MAIL
set imap_user = "sow.eclipse@gmail.com"
set imap_pass = "PASSWORD"
set folder = "imaps://imap.gmail.com:993"
set spoolfile="+INBOX"
set postponed="+[Gmail]/Drafts"
set record="imaps://imap.gmail.com/Sent"
set header_cache=~/.mutt/cache/headers
set certificate_file=~/.mutt/certificates
set message_cachedir=~/.mutt/cache/bodies
set move = no
