### ISSUE TITLE
[Bug]: openvpn not working

### ISSUE THREAD

**Issue by Yisus7u7** [termux/termux-packages#15859]
### Problem description

![Screenshot_20230328-233450_Termux](https://user-images.githubusercontent.com/64093255/228427780-11ef2ed4-3ade-451b-8357-66421f847dc8.png)

### What steps will reproduce the bug?

exec "openvpn" with or without root

### System information

termux-info:

```
Termux Variables:                         TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=5788
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# root-repo (sources.list.d/root.list)
deb https://packages-cf.termux.dev/apt/termux-root/ root stable
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.37.0
Android version:
13
Kernel build information:
Linux localhost 4.4.302-lineage-geccf0e75105a #1 SMP PREEMPT Tue Mar 28 06:59:00 UTC 2023 aarch64 Android
Device manufacturer:
motorola
Device model:
moto g(6) plus
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by xtkoba** [comment]
What is the expected behavior? I cannot triage this issue properly without it.

If the expected behavior is to print the usage message, then this issue is an enhancement request, because we explicitly configure the package so that the usage message is omitted:

https://github.com/termux/termux-packages/blob/52090d10ccce17ba336a585c99735e87a5bce497/root-packages/openvpn/build.sh#L17

If the expected behavior is to launch a daemon, then this issue is invalid or not a bug, because no config file being specified for the command is a syntax error.

**Comment by Yisus7u7** [comment]
Oh, I didn't know, thank you so much!
