### ISSUE TITLE
[Bug]: Building Rust Failed After LIBLLVM Update

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#15858]
### Problem description

PS: @xtkoba  PLEASE DON'T CLOSE THIS IS HAPPENING

/data/data/com.termux/files/usr/bin/llvm-config: 49: Bad substitution
thread 'main' panicked at 'command did not execute successfully: "/data/data/com.termux/files/usr/bin/llvm-config" "--version"
expected success, got: exit status: 2', native.rs:564:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Build completed unsuccessfully in 0:17:54

[log.txt](https://github.com/termux/termux-packages/files/11095792/log.txt)

### What steps will reproduce the bug?

Building rust '1.68.1' package after libllvm update to '16.0.0'

### System information

Termux docker

**Comment by johndebia2022** [comment]
[https://github.com/termux/termux-packages/commit/0727af2da77089f2dddded7e007f5c09a280b55d](url)

**Comment by buttaface** [comment]
I may have written the substitution wrong, will check it.

**Comment by buttaface** [comment]
This error should be fixed by fd7c3fc, keep this open and let us know of any other build issues.

**Comment by johndebia2022** [comment]
Thanks a lot @buttaface . it is fixed now

**Comment by adarshhegde** [comment]
Installation of rust using pkg is also failing due to libllvm version conflict, this is from a fresh install of termux 

Here is the log
`Fetched 543 kB in 4s (126 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 rust : Depends: libllvm (< 16) but 16.0.0-1 is to be installed
E: Unable to correct problems, you have held broken packages.`

**Comment by UBV76** [comment]
You Can remove all the packages and re install them again or you can re-install the termux 
For removing all the Packages you can use this command 
```
apt remove game-repo science-repo && pkg upgrade
```

**Comment by truboxl** [comment]
Rust 1.68.2 is buildable and available from repo
