### ISSUE TITLE
[Mirror] new Termux-Mirror on ftp.fau.de

### ISSUE THREAD

**Issue by rrzefox** [termux/termux-packages#15873]
We have started mirroring Termux on ftp.fau.de, located in Erlangen, Germany.
The mirror is available at https://ftp.fau.de/termux/ so the sources.list-entries probably would be (can't test):
```
deb https://ftp.fau.de/termux/termux-main stable main
deb https://ftp.fau.de/termux/termux-root root stable
deb https://ftp.fau.de/termux/termux-x11 x11 main
```

rsync or http are also available.
We're syncing every 6 hours.
The server is currently connected to the internet through 25 GBit to the German National Research and Education Network (DFN).

One more note: We would have added this mirror earlier, if your Mirroring-Wiki-page contained more relevant info, mostly: how much space will the mirror use, and how much traffic is there to expect for a typical mirror. This doesn't need to be detailed or up-to-date, anecdotal info is enough, e.g.: "A full mirror uses about 25 GB of disc space (as of March 2023). In February 2023, on of our mirrors, foo.bar served about X GB of outgoing traffic. Note that this value can vary a lot, depending on (among other things) how many other mirrors are serving your geographical location."

**Comment by 2096779623** [comment]
Added to [wiki](https://github.com/termux/termux-packages/wiki/Mirrors/9219baf031bcebac629e1a0a3cf5d29f244f2749).

> mostly: how much space will the mirror use.

Sorry for it. our mirror size is around 20GB (now is 18GB?).

> foo.bar served about X GB of outgoing traffic.

Since we use the cloudflare node by default to speed up upload/download packages, it accepts a lot of traffic (according to previous statistics).

You can also see this link to get an overview of the partial support for rsync mirroring (provided that the user uses mirror.termux.dev as the repo): https://mirror.termux.dev/?mirrorstats

**Comment by Anonymous2716** [comment]
@2096779623  is this a typing error :
```
 If you host a one but didn't find it in the list, please open the issue in
                      ^
```

https://github.com/termux/termux-packages/wiki/Mirrors/9219baf031bcebac629e1a0a3cf5d29f244f2749#mirrors

**Comment by 2096779623** [comment]
> @2096779623 is this a typing error :
> https://github.com/termux/termux-packages/wiki/Mirrors/9219baf031bcebac629e1a0a3cf5d29f244f2749#mirrors

Fixed, thanks!
https://github.com/termux/termux-packages/wiki/Mirrors/11684b7ba6b0056639fb108f36bf3aaa55a8ce9a#mirrors
