### ISSUE TITLE
Package request: gnu-netcat

### ISSUE THREAD

**Issue by 4679** [termux/termux-packages#162]
GNU rewrite of netcat.
http://netcat.sourceforge.net/

https://www.archlinux.org/packages/extra/i686/gnu-netcat/

**Comment by fornwall** [comment]
Note that the lightweight version of `nc` is installed by default, but that lacks many features.

Perhaps the netcat from openbsd is better to package than gnu netcat, since gnu netcat seems to be a dead project with no release since 2004?

I've packaged a test build of the openbsd netcat available at:

    http://fornwall.net/netcat_1.105_arm.deb

Could you try that out and see if it works ok for you?

**Comment by 4679** [comment]
It works well,thanks.

**Comment by Hypoon** [comment]
Are you aware of ncat? It's distributed with nmap, and it's what I've been using in Termux for a while now.

**Comment by fornwall** [comment]
@Hypoon Good point! The ncat program is up to date and is maintained (which `gnu-netcat` is not) and portable (which `openbsd-netcat` is not), so perhaps that should be the netcat of choice in Termux?

I'm thinking about splitting ncat into a separate package from nmap, and setting up `netcat` as a symlink to ncat, so that people trying to run netcat are prompted with

    The program 'netcat' is not installed. Install it by executing:
        apt install ncat

and can invoke is as netcat for familiarity.

@Hypoon @4679 What do you think about that?

**Comment by 4679** [comment]
Sounds great.

**Comment by fornwall** [comment]
There is now a `netcat` package available containing the [ncat](https://nmap.org/ncat/) implementation from the nmap project.

It contains the `ncat` binary and man page, as well as having `netcat` setup as a symlink to `ncat` for discoverability. Thanks for the help and feedback!

**Comment by 4679** [comment]
Areat work!

**Comment by Hypoon** [comment]
@fornwall , I don't have any strong opinion regarding splitting ncat into its own package.

On one hand, a separate package is easier to find by someone looking specifically for netcat.

On the other hand, I assume this means ncat will no longer be provided by the nmap package. That's rather unintuitive, in my opinion. When installing an nmap package, I expect to get the full suite: nmap, ncat, nping, and ndiff (and zenmap, if X is in the picture).

I'm hardly an expert on the apt package management system... but I can imagine a way to get the best of both worlds: have separate packages for each tool, plus a separate package for the whole suite that pulls in the tools' packages as dependencies. I don't know if that's the Debian way of doing things, but it seems practical to me.

**Comment by fornwall** [comment]
@Hypoon Good point! I'll make `nmap` depend on `netcat`, so when installing nmap you will get ncat installed as a dependency!
