### ISSUE TITLE
TMPDIR env var missing when ssh'ing into termux

### ISSUE THREAD

**Issue by Grimler91** [termux/termux-packages#1644]
I'm not sure if this is an issue in the [termux-app source](https://github.com/termux/termux-app/blob/master/app/src/main/java/com/termux/app/BackgroundJob.java) or if it is a problem with the ssh(d) program. 

I noticed that when I ssh into my device, TMPDIR is missing. Is this expected behaviour? 
It causes problems when running texlive in an ssh shell as it uses TMPDIR. 

I removed `export TMPDIR=...` from profile.d/texlive.sh in https://github.com/termux/termux-packages/pull/1606 as I didn't think it was needed after https://github.com/termux/termux-app/commit/c26315185f0e26db2521dfac64029f797346a229.

I see that @malbarbo has already noticed this issue in https://github.com/termux/termux-app/issues/306

**Comment by tigran123** [comment]
I always set TMPDIR in `~/.profile` --- in fact I do a few other bits that are absolutely essential, e.g. SHELL variable must be exported (for some reason it is not exported by default).

```
alias cls='tput clear'
alias dis='objdump --disassemble'
alias j='jobs -l'
alias l='ls -l'
alias ll='ls -al'
alias m='free -m'
alias md='mkdir -p'
alias r='fc -s'
alias rd='rmdir'
alias truss='strace'
alias u='uname -a'
alias df='df -h'
alias t='tty-clock -s'
set -o vi
export HISTSIZE=10000000
export HISTFILESIZE=70000000
export PS1="\$ "
export CONFIG_SHELL=$SHELL
export TMPDIR=$HOME/tmp
export SHELL
export MAXIMA_PREFIX=/data/data/com.termux/files/home/.maxima/maxima-5.36.1
export PATH=$PREFIX/local/bin:$PATH:/data/data/com.termux/files/usr/opt/texlive/2017/bin/custom
export PROMPT_COMMAND='echo -ne "\033]0;lg: ${PWD}\007"'
sshd -p 2222
```

**Comment by Grimler91** [comment]
Reading up a bit on this I've learnt that this is as it should be. The ssh shell is different from a normal shell started in termux, see for example https://stackoverflow.com/questions/216202/why-does-an-ssh-remote-command-get-fewer-environment-variables-then-when-run-man. 

Best solution is probably to export it as @tigran123 suggested.

**Comment by rrthomas** [comment]
I just ran into this problem, and I don't think the reasoning above, that "ssh shell is different from a normal shell", is correct. The Stack Overflow page correctly says that "[t]he SSH command execution shell is a non-interactive shell", but I think @Grimler91 misinterpreted this statement, which is talking about commands such as `ssh user@host command`.

As the ssh(1) man page says:

> When the user's identity has been accepted by the server, the server either executes the given command in a non-interactive session or, if no command has been specified, logs into the machine and gives the user a normal shell as an interactive session.

In other words, an ssh session such as `ssh user@host` is a normal interactive session.

The problem, as I understand it, is that the Termux app magically sets some environment variables in its code. This is fine for failsafe use (that's where I found them), but all those variables should also be set in the relevant system startup file (profile or bash.bashrc, according to whether they should apply to interactive sessions or all sessions), so that they work from remote connections, and not just the Termux app.

It seems that most of the special environment variables for Termux are already set in ssh sessions; for example, `ANDROID_ROOT`, `PREFIX` etc.

Furthermore, `TMPDIR` is not just needed for interactive sessions. Many commands use `TMPDIR`, and if it's not set, will default to `/tmp`, and will then fail to work.

So, please reconsider this issue. Yes, there's an easy workaround, but there's no need to inflict that on users :)

**Comment by tigran123** [comment]
@rrthomas Btw, near the bottom of ssh(1) manpage in the section ENVIRONMENT it lists the environment variables normally set by ssh. Amongst them is the PATH which is set to whatever was specified when ssh was compiled. This is also different from "normal interactive shell" and just as "unpleasant" as the situation you describe, because I normally have `~/local/bin` in my PATH and expected it to be present when executing commands remotely, but, unfortunately, I had to specify the full pathname when doing that (because obviously my `~/local/bin` wasn't among ssh's "trusted" values)

**Comment by rrthomas** [comment]
The fact that ssh sets `PATH` is, as you say, annoying for remote commands, but doesn't really affect interactive sessions, because there one's normal startup files are run (per-user `.profile`, `.bashrc` etc. and, directly or indirectly, system `/etc/profile`, `/etc/bash.bashrc` etc.). These should source a complete environment. The problem on Termux is that some environment variables, like `TMPDIR`, seem to be set only in the app.

**Comment by Grimler91** [comment]
Reopening this then.
