### ISSUE TITLE
[packaging]: bug while building packages which are blacklisted in other

### ISSUE THREAD

**Issue by T-Dynamos** [termux/termux-packages#16487]
In issue: #16427 

It says:

>Lets say package A depends on package B and package B can't be build on aarch64.
When building package A with target aarch64 it runs the build even thought package B should never be build with target aarch64.

But in https://github.com/termux-user-repository/tur/pull/383 it is doing opposite. Basically, while building `openimageio`, I got an error related to `blender`, which depends upon `openimageio`.

**Comment by xtkoba** [comment]
This is expected. `buildorder.py` checks consistency of every package in repos. The Packaging CI will be broken if any one of packages has inconsistent dependencies. For example, I noticed the inconsistency in `{,wx}maxima` package (fixed in 455ca039885957c189a8970b97f77823e04a450e) when testing build of completely unrelated package.

**Comment by xtkoba** [comment]
Note that the list of excluded arches in a package does not automatically propagate to its reverse dependencies. For example, revdeps of `sse2neon` have to specify `i686` as an excluded arch:

https://github.com/termux/termux-packages/blob/c43aca3c2d6efc0270da72b2171cdf4fcd9bb1a4/packages/sse2neon/build.sh#L10

**Comment by licy183** [comment]
Closes via 6089f25dadd8c9247d826e60582016499b6058c2.
