### ISSUE TITLE
binutils and binutils-cross are also dependencies for Rust, but currently not installed automatically.

### ISSUE THREAD

**Issue by sylirre** [termux/termux-packages#16588]
### Discussed in https://github.com/termux/termux-packages/discussions/16587

<div type='discussions-op-text'>

<sup>Originally posted by **oilel** May  6, 2023</sup>
Some Rust programs don't compile, because binutils isn't installed yet. Rust requires not only LLVM to be fully compatible for ARM Android, some programs need binutils.</div>

**Comment by xtkoba** [comment]
You can always manually install `binutils` if needed. `rust` should not depend on `binutils` unconditionally.

**Comment by xtkoba** [comment]
There may need some description of the situation around `binutils` in Termux.

* Run-time dependency on `binutils-is-llvm | binutils`: needed when at least one of the following commands are needed: `addr2line`, `ar`, `c++filt`, `dwp`, `ld`, `nm`, `objcopy`, `objdump`, `ranlib`, `readelf`, `size`, `strings`, `strip`. *Not needed* if `llvm`-prefixed version of the commands (provided by `llvm` package) or `ld.lld` (provided by `lld` package) satisfy the needs.

* Run-time dependency on `binutils-bin`: needed when `as` (GNU as) and/or `ld.bfd` (BFD linker) are needed.

* Build dependency on `binutils-cross`: similar to `binutils-bin` but only for cross-building on Docker image.

None of these are essential nor build-essential. Individual packages should depend on them if needed.

**Comment by xtkoba** [comment]
If the build system of a software assumes GNU binutils and disrespects LLVM toolchain, then that is a bug of that software. Rust itself does not require GNU binutils; "hello world" program builds without it. There is no good reason for us to have `rust` depend on `binutils`.

See also #9715.

**Comment by oilel** [comment]
> There is no good reason for us to have `rust` depend on `binutils`.

The Rust crate zeroize_derive used in some projects failed to compile without binutils. And WebAssembly (wasm)-related projects may fail to compile without binutils. WebAssembly is an alternative to JavaScript, and Rust can be compiled to WebAssembly, but may require binutils.

**Comment by robertkirkman** [comment]
I am planning to simplify this situation by applying the following changes:

- Replace instances of dependency on `binutils-is-llvm | binutils` with `llvm`
- Replace instances of dependency on `binutils-bin` with `binutils`

Resulting in the following new summary:

- Run-time dependency on `llvm`: needed when at least one of the following commands is needed: `addr2line`, `ar`, `c++filt`, `dwp`, `nm`, `objcopy`, `objdump`, `ranlib`, `readelf`, `size`, `strings`, `strip`. Not needed if `clang` is already a dependency because `clang` will pull in `llvm`, which will provide them. Will become present in both `build-essential` and `scripts/setup-termux.sh` because `clang` is in those, which pulls in `llvm`.

- Run-time dependency on `lld`: needed when the `ld` command is needed. `ld` will become a consistent symbolic link to `ld.lld`. Also a dependency of `clang`.

- Run-time dependency on `binutils`: needed when `as` (GNU as) and/or `ld.bfd` (BFD linker) are needed.

If someone from this thread has a concern about this or knows of a problem this would cause, please let me know.
