### ISSUE TITLE
newsboat generates "default.profraw"

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#1672]
I've switched from newsbeuter to newsboat. Every time I launch newsboat it generates an empty default.profraw in the current working directory. I ducked it and it seem to be some kind of "LLVM Code Coverage" File. Maybe there are some debug options enabled in our build?

[default.profraw.zip](https://github.com/termux/termux-packages/files/1386622/default.profraw.zip)

**Comment by Neo-Oli** [comment]
A few other open-source projects have this issue popping up in the last few weeks.
https://github.com/krzysztofzablocki/Sourcery/issues/421
https://github.com/Hammerspoon/hammerspoon/issues/1569

Both these seem to be using clang, so maybe it's something introduced in the latest version of clang?

**Comment by Minoru** [comment]
Clang builds generate this file because Newsboat passed `-fprofile-arcs -ftest-coverage` to the linker [even when profiling was disabled](https://github.com/newsboat/newsboat/blob/7901f2bc02556087dc01cde40f819c30881f63dc/Makefile#L25). I've just pushed a commit that fixes this. Don't hesitate to raise issues directly with Newsboat if you run into any ;)

**Comment by Neo-Oli** [comment]
@Minoru Thanks a lot for fixing it. Sorry for not reporting it to Newsboat directly, I thought for sure this would be an issue with our build only.

**Comment by fornwall** [comment]
Nice! I've updated the newsboat package to version `2.10.1-1` which contains this fix.
