### ISSUE TITLE
Auto update failing for dte

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#16791]
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the dte package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating dte [Current version: 1.11.1]
ERROR: Failed to get 'latest-release-tag' (https://gitlab.com/api/v4/projects/craigbarnes%2Fdte/releases).
HTTP code: 403
Response:
{"message":"403 Forbidden"}</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2023-05-30 20:03:01 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/5124788604">5124788604</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by craigbarnes** [comment]
This was probably caused by the fact I disabled the GitLab releases feature for the `dte` repo. Mostly to encourage people to use https://craigbarnes.gitlab.io/dte/releases.html instead, for the reasons outlined [here](https://github.com/craigbarnes/dte/blob/master/docs/packaging.md#stable-release-tarballs).

I suppose that wasn't such a good idea, so I've re-enabled the feature.
