### ISSUE TITLE
Install 64-bit arm packages on capable devices

### ISSUE THREAD

**Issue by fornwall** [termux/termux-packages#168]
Termux currently installs 32-bit packages even on 64-bit capable devices. This works for now, but hopefully we can soon transition to distributing 64-bit packages for capable devices. This issue tracks problems with 64-bit arm packages known so far:

- ~~gcc fails to compile a simple C file with complaints about not finding `crt1.o`, `crti.o` and `crtn.o`~~.
- ~~python2 segfaults at startup~~.

**Comment by Hypoon** [comment]
Nothing to add, but I figure I'll mention that I've been waiting for this since I first started using Termux. Actually, I was rather disappointed when I put a lot of work into cross-compiling something to Arm64, only to find that the Termux library packages are only 32bit when I attempted to test my binary. That project is actually why I bought this device, and why I first looked into Termux. Unfortunately I've been too busy to investigate further.

**Comment by Hypoon** [comment]
Also worth mentioning: there's a discount available for developers to get 25% off the Pixel C (purchased through Google). I wouldn't recommend the Pixel C for the average user, but it's a reasonable choice for Arm64 development. However, I will mention that this is ChromeOS hardware that runs Android software, so bootloader/kernel/custom-rom development might be a nightmare... just do your homework before you buy, if that's your thing.

**Comment by fornwall** [comment]
@Hypoon The 64-bit arm packages are going live with the newly released version 0.31 of the Termux app - try it out and open any new issues if you encounter a problem!

After updating to 0.31 you need to force a fresh install to receive 64-bit packages. This can be done by reinstalling the app (after saving away work done in `$HOME`), or by running `rm -Rf $PREFIX`, exit all the sessions and restart the app.

Also available is https://termux.com/changelog.html for a complete list of changes in the 0.31 release.
