### ISSUE TITLE
cls command like in windows cmd

### ISSUE THREAD

**Issue by biojet1** [termux/termux-packages#1684]
clear the terminal's scroll-back buffer. The clear command just clears the screen.

**Comment by tigran123** [comment]
You can just add this to your ~/.profile:

```
alias cls="tput reset"
```

and then `cls` command will work as you expect, i.e. will clear the scroll-back buffer.

**Comment by biojet1** [comment]
"Tput reset" does not work i still can scroll down to see the previous output

**Comment by tigran123** [comment]
Oh, I forgot that it is Termux we are talking about and not generic xterm on Linux :)

Yes, you are right, in Termux `tput reset` does not clear the scroll buffer.

**Comment by wdscxsj** [comment]
Try this:

```
alias cls='clear'
```

**Comment by voidzero** [comment]
How about the command `reset`?

**Comment by tigran123** [comment]
@voidzero Try it and see for yourself, that `reset` doesn't clear the scroll buffer. That is, it doesn't clear it when executed directly inside one of Termux's built-in terminals on the Android device. But if you login to Termux environment via gnome-terminal running on Linux (and sshd running in Termux) then, of course, it will clear the scroll buffer, but that is not what is being asked here.

**Comment by voidzero** [comment]
@tigran123 yes, I fully understand and agree with your point. I did test it, but for me it did seem to clear the scrollback buffer. I'm using zsh as my shell, btw. I just ran `cat` on axfile a couple of times and after `reset` could not scroll up again. I do agree that such a method is a workaround; another workaround is to wrap your session with tmux because that one has its own scrollback buffer which can be cleared, but a "clear scrollback buffer" feature would be the ideal option.

**Comment by cbrt64** [comment]
Something I recently noticed: since Termux 0.67, `clear` now clears the scroll buffer! `Ctrl-L` and `reset` still do not. As pointed out in https://github.com/termux/termux-app/issues/207#issuecomment-277552713, it might not be desirable for `reset` to clear the whole buffer.

Thanks, @iamahuman, for fixing this!
