### ISSUE TITLE
Fish tab completion broken (due to the 'apropos' program missing)

### ISSUE THREAD

**Issue by Yajo** [termux/termux-packages#169]
See what happens when you press tab in a fish shell:

[![asciicast](https://asciinema.org/a/39606.png)](https://asciinema.org/a/39606)

**Comment by fornwall** [comment]
The `apropos` program is missing from Termux at the moment.

It could be built as part of [the man(doc) package](https://github.com/termux/termux-packages/blob/master/packages/man/build.sh), where it is currently disabled due to the `HAVE_SQLITE3=0`part of the build script.

Build man with sqlite has two drawbacks:

1. It forces everyone who wants to read man pages to pull in libsqlite as a dependency (600 kB), since man will start.
2. The `apropos` program uses the sqlite database built by `makewhatis`, so that would have to be setup to run automatically on package installation&uninstallation as is done on normal linux distributions.

So, the sqlite-using `apropos` program is a bit heavyweight - either we bite the bullet and go that route, of if possible find a simpler apropos implementation that just works with simple file system search (the man pages in Termux are in one location, and for the apropos usage needed we can go for an exact match).

**Comment by Yajo** [comment]
Those 2 drawbacks don't seem so *heavy* IMHO, so unless you have a better implementation, I'd go that route.

**Comment by Rudloff** [comment]
This error is pretty annoying. In the meantime, would it be possible to patch Fish so the error is ignored?

**Comment by fornwall** [comment]
The apropos command is now available in the man package (which fish now depends on)!

Note that for apropos to give any results you have to run makewhatis command.

**Comment by fornwall** [comment]
Update: The latest version of the `man` package now takes care of updating the man db when necessary, so there is no longer any need to run `makewhatis` manually.
