### ISSUE TITLE
[Bug]: libandroid: What is this package for?

### ISSUE THREAD

**Issue by xtkoba** [termux/termux-packages#16902]
### Problem description

Please explain why this package is needed. I'm going to remove this if no explanation is provided.

### What steps will reproduce the bug?

Install `ffmpeg` package which now depends on `libandroid` package.

### What is the expected behavior?

`libandroid` package should not be needed.

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=5693
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
ffmpeg/stable 6.0-3 aarch64 [upgradable from: 6.0-2]
fluidsynth/stable 2.3.3 aarch64 [upgradable from: 2.3.2]
libde265/stable 1.0.12 aarch64 [upgradable from: 1.0.11]
libjxl/stable 0.8.2 aarch64 [upgradable from: 0.8.1]
termux-tools version:
1.38.3
Android version:
12
Kernel build information:
Linux localhost 4.19.191-g234d1747e22a #1 SMP PREEMPT Sat Mar 25 18:12:54 CST 2023 aarch64 Android
Device manufacturer:
motorola
Device model:
moto e32(s)
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by truboxl** [comment]
https://github.com/termux/termux-packages/pull/16680#issuecomment-1555451801

If you have better ideas feel free to break the package

**Comment by xtkoba** [comment]
I'm not familiar with Termux Docker, but is it true that it does not have `/system/lib(64)?/libandroid.so`?

**Comment by xtkoba** [comment]
Note that there are other packages (e.g. `mpv`, `libgnustep-base`) that link against `libandroid.so`. They also won't work on Termux Docker without `libandroid` package, if `ffmpeg` doesn't. We should be consistent in that.

**Comment by truboxl** [comment]
> I'm not familiar with Termux Docker, but is it true that it does not have /system/lib(64)?/libandroid.so?

Yes and I suggest you to use it if you can fix this in better ways

**Comment by xtkoba** [comment]
What do you mean by "it" if it does not exist?

**Comment by truboxl** [comment]
By it I mean https://github.com/termux/termux-docker

**Comment by xtkoba** [comment]
Then my opinion is Termux Docker is broken and it should be fixed so that it includes system `libandroid.so`. `libandroid.so` is assumed to exist on every Android environment.

**Comment by xtkoba** [comment]
And *normal* Termux environment should not require `libandroid` package.

**Comment by xtkoba** [comment]
FYI, system libs that are assumed to exist:

```
libEGL.so
libGLESv1_CM.so
libGLESv2.so
libGLESv3.so
libOpenMAXAL.so
libOpenSLES.so
libandroid.so
libc.so
libcamera2ndk.so
libdl.so
libjnigraphics.so
liblog.so
libm.so
libmediandk.so
libstdc++.so
libvulkan.so
libz.so
```

**Comment by xtkoba** [comment]
IIUC Termux Docker is not an officially supported environment. So IIUC no problem if the dependency of a package is specified so that it may be insufficient for Termux Docker.

I understand `libandroid` package itself is useful for some environment and I won't remove it from our repo. Please manually install `libandroid` package if necessary.

**Comment by xtkoba** [comment]
(Honestly I don't want to check every package if it depends on `libandroid.so`.)

**Comment by robertkirkman** [comment]
> Then my opinion is Termux Docker is broken and it should be fixed so that it includes system `libandroid.so`. `libandroid.so` is assumed to exist on every Android environment.

I am very happy to announce that termux-docker now contains `libandroid-stub`, and that it has all been cleaned up to work better, so termux-docker is now less broken!

Regular Termux provides at least one implementation of all of these, therefore, alternatives to these are not really needed most of the time (as long as the program is compatible with the Termux builds of them):

```
libEGL.so
libGLESv1_CM.so
libGLESv2.so
libGLESv3.so
libc++_shared.so
libvulkan.so
libz.so
```
In addition to the libraries available above from `pkg install vulkan-loader-generic`, etc, termux-docker now contains these, preinstalled:

```
libOpenSLES.so
libandroid.so
libc.so
libdl.so
liblog.so
libm.so
libmediandk.so
```

Some are stubs, for example `libOpenSLES.so` will not actually play audio, but it will respond to software which requires `libOpenSLES.so` with a valid `SL_RESULT_FEATURE_UNSUPPORTED` error code, which should successfully prevent the software from crashing, allowing it to be tested with non-Audio functionality without having to recompile the package.

That leaves these libraries as the only remaining of those mentioned that are not provided by at least one polyfill or stub in termux-docker:

```
libOpenMAXAL.so
libcamera2ndk.so
libjnigraphics.so
```

I have not yet seen any specific real-world software that could almost be used in termux-docker except that it depends on one of those three and crashes if it is unavailable. If someone knows about one, please feel free to open an issue about it, because the reason I have ignored those three remaining libraries is because nobody seems to need them.
