### ISSUE TITLE
[Enhancement]: add support for `TERMUX_SUBPKG_BLACKLISTED_ARCHES`

### ISSUE THREAD

**Issue by licy183** [termux/termux-packages#17338]
Some packages has useless subpackages for some arches. Excluding these packages can save lots of space.

See #17336

**Comment by xtkoba** [comment]
I can work on it.

I propose using another variable name e.g. `TERMUX_SUBPKG_EXCLUDED_ARCHES` because the behavior for subpkg is different from for parent package. For subpkg the build itself is done but just the binary (sub)package is not created. And, you know...

**Comment by xtkoba** [comment]
Dev memo. A bit extra cares are needed to retain consistency with `buildorder.py`. For example, something unexpected could happen when building a package that depends on `mesa` after the proposed change in #17336 is applied. This however cannot be tested before the change to `mesa` is merged and the binary packages are uploaded, because otherwise the rebuild of `mesa` would be taken into place and the problem would not manifest itself. What is fortunate is that that would not affect end users, would not break consistency in bindist.

**Comment by xtkoba** [comment]
Implemented in b8607907aa293c6c350ecafe431536083b8eee74.

Closing as resolved. If you find any problems regarding this, then please open new issues for them. Thanks.
