### ISSUE TITLE
pypy3: segmentation fault

### ISSUE THREAD

**Issue by qiangz63** [termux/termux-packages#17389]
### Problem description

A problem with I update pypy3 to v7.3.12，the issue did not occur before.

### What steps will reproduce the bug?

pkg i pypy3 ndk-multilib-native-stubs
pypy3

### What is the expected behavior?

Run as expected.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=30279
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://packages.termux.dev/apt/termux-root root stable
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-hacking tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.dev/apt/termux-x11 x11 main
Updatable packages:
nodejs-16/tur-packages 16.20.0 aarch64 [upgradable from: 16.19.1-1]
python-cryptography/stable 41.0.1 aarch64 [upgradable from: 38.0.4]
termux-tools version:
1.38.3
Android version:
12
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.x11 versionCode:12
com.termux.styling versionCode:30
```

**Comment by licy183** [comment]
I can't reproduce it on my device...

**Comment by qiangz63** [comment]
I don't know why, I just ensurepip, and it run fine before. Update package cause this bug.

**Comment by qiangz63** [comment]
I remove pip and reinstall, the bug still...

**Comment by licy183** [comment]
I tested on my devices (Meizu Pro 6s, Android 7.1.1; Xiaomi MIX2s, Android 9; Xiaomi MIX4, Android 12; Xiaomi Pad 5 Pro, Android 13), but none of them successfully reproduced this issue.

**Comment by qiangz63** [comment]
I tested after remove `ndk-multilib-native-stubs` package, it runs. But when I reinstall the package, it produce segmentation fault again.
And I use the package to thru pip build numpy several days ago. @licy183

**Comment by licy183** [comment]
OK. Reproducible for me. It's weird that `pypy3` has `$PREFIX/lib/aarch64-linux-android` in its runpath. I'll fix it.

**Comment by licy183** [comment]
Currently, `pypy` uses cross-translation for aarch64, and compile all the sources using `clang --target=aarch64-linux-android`. Since 7544dd10f87330bfc2c8775134a7760cec7c889f, rpath will be automatically set when cross-compiling. IIRC `libc.so` and `libdl.so` from ndk-multilib are just some stubs and cannot execute.

**Comment by finagolfin** [comment]
The problem is that clang isn't recognizing that your passed-in triple is the native one, as my patch pretty much assumes it won't be overridden like this. We could patch clang to recognize this passed-in triple as the native triple.

**Comment by licy183** [comment]
`pypy`'s Makefile is used in a x86_64/i686 termux-docker environment, so `pypy` executable will have `$PREFIX/ARCH_TRIPLE/lib` in its runpath.

**Comment by finagolfin** [comment]
Oh, I thought it was just overriding the triple, I didn't know you're building with a x86_64-native clang. I'll have to investigate more how pypy works.

**Comment by finagolfin** [comment]
> pypy's Makefile is used in a x86_64/i686 termux-docker environment

OK, I did not know any Termux packages are cross-compiled in a Termux proot with the Termux clang. I thought we always used the NDK clang on the CI.

There are a couple different ways to fix this:

1. Since you are cross-compiling anyway from Termux x86_64 running inside a proot on the CI, can't you just cross-compile directly from linux x86_64 to Android using the NDK clang instead? I find it strange that you need to build this package in a Termux x86_64 proot.
2. We could stick in a flag to disable these rpaths being added, which may be generally useful in the Termux clang.
3. This arch-specific rpath is just a convenience for cross-compiling. We could only apply it when it can be used to run the executable right away, ie x86_64 to i686 and AArch64 to arm. This won't stop the i686 package from still having this problem, but almost noone uses that arch anymore.

Let me know if you have tried 1. and what you think we should do.

**Comment by licy183** [comment]
Actually, 1 is not possible. `pypy` releases rpython files rather than C files. RPython files must be tranlated to C files before compiling. The translation must be operated in Termux x86_64 (or i686), because GNU/Linux is much different from Android.

I agree with option 2. I think rpath to `$PREFIX/ARCH_TRIPLE/lib` should be set by Termux clang users optionally if they really need it.

**Comment by finagolfin** [comment]
I will submit a pull adding a clang flag that disables setting the rpaths, which could be generally useful for on-device builds where you don't want any default rpaths and supply your own.
