### ISSUE TITLE
libtool fix

### ISSUE THREAD

**Issue by StefanL** [termux/termux-packages#1740]
Please update libtool to point to the correct sed location.

Currently it points to ../usr/bin/sed but should point to ../usr/bin/applets/sed (line 88 of libtool). Much appreciated.

Kind regards,

Stefan L

**Comment by StefanL** [comment]
This fix also applies to the libtoolize package which has the sed program hard coded (line 49).

**Comment by Grimler91** [comment]
It's better to install the "real" sed package (with `pkg install sed`), the applets/sed binary is a busybox version with less functionality than the full version. 

Making libtoolize look for /usr/bin/applets/sed could have the unwanted side-effect that tests fail due to applets/sed not supporting specific flags/functions.

**Comment by its-pointless** [comment]
probably best to add sed to libtool's dependencies in build.sh?

**Comment by Grimler91** [comment]
@its-pointless good point

**Comment by fornwall** [comment]
Thanks - the updated version 2.4.6-5 of the libtool package now depends on `sed` and `grep`.

@StefanL Running `pkg up` should fix the problem!
