### ISSUE TITLE
[Package]: GNU IceCat

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#17749]
### Why is it worth to add this package?

* how do you plan to use the requested package
  * daily browsing
* why it would be a nice addition to the Termux repository
  * because we do care about libre software
  * without using tor, we can safely browse web

### Home page URL

https://www.gnu.org/software/gnuzilla/

### Source code URL

http://git.savannah.gnu.org/cgit/gnuzilla.git

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by ChiefMikeK** [comment]
This is based on firefox 67 of june-2019
===
IIUC not still being maintained.

**Comment by TomJo2000** [comment]
As I understand it,
GNU IceCat (formerly known as GNU IceWeasel), is a relic of a now resolved trademark quirk
regarding the "Mozilla Firefox" wordmark, stemming from Debian's use of the wordmark in official
materials.

I don't recall the exact details, but in effect it ended with Mozilla's lawyers suggestion to Debian's lawyers to change the name if they want to use it in official "marketing materials" for the Distro.

This issue has since been resolved, and IceCat is to be considered abandoned in favor of mainline Firefox.
At some point GNU picked up the "fork", though I'm very hazy on the details there.

For more details see:
https://en.wikipedia.org/wiki/GNU_IceCat#Origins_of_the_name

**Comment by TomJo2000** [comment]
> * **facts**
>   
>   * commit log of gnu icecat_ https://git.savannah.gnu.org/cgit/gnuzilla.git/log/
>   * firefox release calendar [ see Q3 2023 ]_ https://wiki.mozilla.org/index.php?title=Release_Management/Calendar&redirect=no
>   * compare with tag 102.15.0_ https://git.savannah.gnu.org/cgit/gnuzilla.git/commit/?id=400fbfdbc0c1ac9c68c9f52fd2ab6899bc8e8bd0

Yes commits are being made to IceCat.
But there has not been any official "stable release" of the project since June 2019.
We do not generally package "pre-release" or "*-git" versions of packages.

As for "proof".
The only maintainers publishing [102.x releases of GNU IceCat](https://repology.org/project/icecat/versions) are:
- The AUR.
- Fedora (Rawhide)
- GNU Guix
and
- Parabola GNU/Linux-libre

These are also the only current packagers of IceCat.
Except for outdated versions available from Chocolatey, PCLinuxOS and SlackBuilds.

**Comment by TomJo2000** [comment]
> > We
> 
> we means termux package creators/uploaders?

We as in, the Termux project and its associated package repositories and infrastructure.

Also it looks like I was wrong on the count of "[not packaging `*-git` versions](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#submitting-new-packages-checklist)", we just prefer to package specified versions.
Be that stable releases or the state of a project as of a specific commit.

In general I tend to use "We" when referring to guidelines set out in the packaging policy or Maintainer Wiki, I apologize for any confusion.

**Comment by TomJo2000** [comment]
It's not up to me.
I'm just a (infrequent) contributor to the project, not a maintainer.

**Comment by TomJo2000** [comment]
Considering I now am a maintainer, and I just stumbled across this again.
And considering we now [have official approval](https://github.com/termux/termux-packages/pull/17840#issuecomment-1915736050) to use official Firefox branding for the firefox package.
We can safely close this as obsolete/not planned.
