### ISSUE TITLE
Question: Install busybox on root?

### ISSUE THREAD

**Issue by Mannshoch** [termux/termux-packages#180]
I have a fresh rooted Fairphone2. I miss at moment an installed busybox. Could i somehow install it with termux?

**Comment by fornwall** [comment]
The busybox package is already installed by default in Termux.

It could be that you need to restore the `PATH` and `LD_LIBRARY_PATH` environment variables after becoming root with `su`, if `su` clears these (because if these variables are cleared your shell won't be able to find the binaries installed by Termux).

Passing `-m` to su should also keep the environment.
