### ISSUE TITLE
[Package]: nodejs-lts and neovim

### ISSUE THREAD

**Issue by bobbyrahmanda13** [termux/termux-packages#18011]
### Why is it worth to add this package?

New versions of nodejs and neovim have been released, please update to the latest version, because I use nvim in termux, but because there is a plugin that asks for a higher version of neovim, Thanks

### Source code URL

https://github.com/neovim/neovim/releases, https://github.com/nodejs/node/releases

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by TomJo2000** [comment]
Updating neovim is already [actively being worked on](https://github.com/termux/termux-packages/pull/18003).

Nodejs updates are *[\*complicated\*](https://github.com/termux/termux-packages/tree/master/packages/nodejs)* due to the sheer amount of patches and moving parts.
(And NodeJS 20.2.0 is currently packaged as `nodejs`, which is not the current minor version but is at least 20.x)

**Comment by bobbyrahmanda13** [comment]
I don't use nodejs stable but I use lts, ​​can you update it?

**Comment by TomJo2000** [comment]
Node 20 is the current, _**and designated future LTS**_ release.
Node 18 is the _**current**_ LTS release and will be replaced as such by Node 20 when Node 21 is released.

If you require features from either Node 19 or 20, please use the regular "stable" `nodejs` package.

**Comment by bobbyrahmanda13** [comment]
okay fine, usually I use the latest version of nodejs, I'm waiting for it

**Comment by GottZ** [comment]
> Node 20 is the current, _**and designated future LTS**_ release. Node 18 is the _**current**_ LTS release and will be replaced as such by Node 20 when Node 21 is released.
> 
> If you require features from either Node 19 or 20, please use the regular "stable" `nodejs` package.

https://nodejs.org/en/about/previous-releases

![nodejs release cycle](https://raw.githubusercontent.com/nodejs/Release/main/schedule.svg?sanitize=true)

while technically keeping it like that could work until april 2025, in reality nodejs had quite some bugfixes in the meantime.
I'm just here to let you know that one month after your comment, 20 became lts.

just so you know.. there were quite some CVE's fixed with high ratings since 20.2.0

is there anything stopping it from being built automagically?

**Comment by thunder-coding** [comment]
Fixed by #19282
