### ISSUE TITLE
[Bug]: Termux tsu can not run in Magisk 27001

### ISSUE THREAD

**Issue by NGLSG** [termux/termux-packages#19179]
### Problem description

none

### Steps to reproduce the behavior.

none

### What is the expected behavior?
``` bash
~ $ su
No su program found on this device. Termux
does not supply tools for rooting, see e.g.
http://www.androidcentral.com/root for
information about rooting Android.
~ $ tsu
No superuser binary detected.
Are you rooted?
```

### System information

* Termux application version:0.118
* Android OS version:13
* [Magisk:kitsune(27001)](https://github.com/HuskyDG/magisk-files)

**Comment by mcagabe19no2fa** [comment]
@Grimler91 it's magisk canary

**Comment by Grimler91** [comment]
I'm not really familiar with magisk canary, but if magisk git history is correct then there does not seem to be any [functional changes between 27000 and canary release of 27001](https://github.com/topjohnwu/Magisk/commits/154121f3dd92e67a3d8e3f518684932c0f9783e6).

Original post does not contain any details about what the issue is (tsu hangs? phone reboots? phone explodes?), or on what device issue occurred. 

Please edit the post to properly fill in the bug report template

**Comment by mcagabe19** [comment]
@Grimler91 seems like they use kitsune [(an modded magisk)](https://huskydg.github.io/magisk-files) so we can't really do anything to them since it's unofficial

**Comment by Grimler91** [comment]
@mcagabe19 thanks for the link!

Don't think we want to support unofficial magisk forks (I'm not going to install another magisk variant at least)

**Comment by XEKZHX** [comment]
On August 3, 2025, using the latest magisk is still the case.

**Comment by agnostic-apollo** [comment]
Use `sudo` package, `tsu` is not maintained anymore.

**Comment by D1MOFRY1998** [comment]
Okey Vaviertly
