### ISSUE TITLE
[Bug]: `pkg up` adds "ignore_keyusage = 1" and "unprotected_errors = 1" to "../../files/usr/etc/tls/openssl.cnf "

### ISSUE THREAD

**Issue by ETERNALBLUEbullrun** [termux/termux-packages#19208]
### Problem description
`
[openssl] master update ">+ /* >+ * unprotectedErrors may be set as workaround for broken server responses: >+ * accept missing or invalid protection of regular error messages,
`
Thus TLS is useless,
plus, all packages run without those quirks.

### What steps will reproduce the bug?

~ $ pkg up
~ $ cat ../../files/usr/etc/tls/openssl.cnf | grep quirk
`ignore_keyusage = 1 # potentially needed quirk
unprotected_errors = 1 # potentially needed quirk`

### What is the expected behavior?

~ $ sed -e "s/ignore_keyusage = 1/#ignore_keyusage = 1/g" ../../files/usr/etc/tls/openssl.cnf -i'.s'
~ $ sed -e "s/unprotected_errors = 1/#unprotected_errors = 1/g" ../../files/usr/etc/tls/openssl.cnf -i'.s'

**Comment by Grimler91** [comment]
You mean you have edited openssl.cnf, but then after pkg up those config changes are reverted?

openssl.cnf should be added to CONFFILES, which should prevent pkg from reverting such changes

**Comment by ETERNALBLUEbullrun** [comment]
Steps was just: install Termux and run `pkg up`
Result was that ignore_keyusage and unprotected_errors got addded to openssl.cnf, was all original.
`~ $ sed -e "s/ignore_keyusage = 1/#ignore_keyusage = 1/g" ../../files/usr/etc/tls/openssl.cnf -i'.s'
~ $ sed -e "s/unprotected_errors = 1/#unprotected_errors = 1/g" ../../files/usr/etc/tls/openssl.cnf -i'.s'` commands is to undo the ignore_keyusage and unprotected_errors that got added to openssl.cnf, due to ```
master update ">+ /* >+ * unprotectedErrors may be set as workaround for broken server responses: >+ * accept missing or invalid protection of regular error messages,
```
which shows those should not be on unless packages fail without those on

**Comment by ETERNALBLUEbullrun** [comment]
[diff.txt](https://github.com/termux/termux-packages/files/14234543/diff.txt)
Fix

**Comment by Grimler91** [comment]
> openssl.cnf should be added to CONFFILES, which should prevent pkg from reverting such changes

openssl.cnf is already in conffiles so no need to update that.

---

@ETERNALBLUEbullrun we are simply shipping the default openssl.cnf, which has those quirks enabled. 
I don't know enough about about openssl's internals to know if it is safe to disable those quirks. Please open an issue in openssl's repo and tell them to disable the quirks per default if you think that is the right thing to do.

> which shows those should not be on unless packages fail without those on

I interpret it more like that those quirks can help when connecting to half-broken servers out in the wild. You can edit openssl.cnf on your device and disable the quirks, apt won't touch the file on updates since it is marked as a conffile.

**Comment by ETERNALBLUEbullrun** [comment]
These defaults are just to troubleshoot. From OpenSSL's: manpages ( https://www.openssl.org/docs/man3.0/man1/openssl-cmp.html ) ```
-unprotected_errors

    Accept missing or invalid protection of negative responses from the server. This applies to the following message types and contents:

        error messages

        negative certificate responses (IP/CP/KUP)

        negative revocation responses (RP)

        negative PKIConf messages

    WARNING: This setting leads to unspecified behavior and it is meant exclusively to allow interoperability with server implementations violating RFC 4210
```

**Comment by TomJo2000** [comment]
> Those defaults are just to troubleshoot

Yep, they should ***under no circumstances*** be used as defaults.
They are intentionally insecure and entirely defeat the security purpose of TLS certification.

**Comment by DDvO** [comment]
This bug report is entirely wrong.

It is clearly due to major misconceptions 
* on the structure of OpenSSL config files
* on the role of the OpenSSL CMP client options `ignore_keyusage`and `unprotected_errors`. 

These options have **nothing** to do with TLS 
but are just CMP client quirks for dealing with deficiencies of certain CMP servers and their configuration.

These options are used in the model `openssl.cnf` solely for CMP client demo purposes.
They do not affect at all the OpenSSL use of TLS.
