### ISSUE TITLE
Package request: zipline

### ISSUE THREAD

**Issue by dhandeo** [termux/termux-packages#1936]
[zipline](http://www.zipline.io/) is a Pythonic algorithmic trading library.  Zipline ships several C extensions that require access to the CPython C API. In order to build the C extensions, pip needs access to the CPython header files for your Python installation. Also depends on numpy and LAPACK, out of box compilation is not trivial.

**Comment by Grimler91** [comment]
It worked out of the box for me after installing numpy&lapack from [its-pointless repo](https://wiki.termux.com/wiki/Package_Management#its-pointless_.28live_the_dream.29). It doesn't work on aarch64 though since zipline depends on statsmodels and that can't be installed on aarch64 for some reason (see https://github.com/termux/termux-packages/issues/1111).

Closing as installation from pip works after the prerequisites has been met.

**Comment by Grimler91** [comment]
Should work on all arches now that #1111 has been fixed. Let us know if it doesn't.
