### ISSUE TITLE
[Package]: microemulator 

### ISSUE THREAD

**Issue by Freed-Wu** [termux/termux-packages#19708]
### Why is it worth to add this package?

This is Java 2 Micro Edition (J2ME) CLDC/MIDP Emulator. Allows demonstrate MIDlet based applications in web browser applet, also can be run as standalone java application.

### Home page URL

https://sourceforge.net/projects/microemulator/

### Source code URL

GPL

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

[Archlinux](https://aur.archlinux.org/packages/microemulator)

**Comment by TomJo2000** [comment]
- 1.) It states on the SourceForge page that the project has moved to:
https://code.google.com/archive/p/microemu/source

- 2.) This package appears to be packaged on only GNU Guix, MacPorts and the AUR.
All under different package names.
https://repology.org/projects/?search=microemu

- 3.) This package has seen no development since ***2013***.
https://code.google.com/archive/p/microemu/source/default/commits

That's gonna be a `NACK` from me.
