### ISSUE TITLE
[python] Locale not set correctly

### ISSUE THREAD

**Issue by Rudloff** [termux/termux-packages#1991]
Hello,

I recently had an issue with a Python program not detecting Termux's encoding correctly (https://github.com/tdryer/hangups/issues/373) although the `LANG` variable is set correctly:
```
ANDROID_DATA=/data
ANDROID_ROOT=/system
EXTERNAL_STORAGE=/sdcard
HOME=/data/data/com.termux/files/home
LANG=en_US.UTF-8
LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
LOGNAME=u0_a99
PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
PREFIX=/data/data/com.termux/files/usr
PWD=/data/data/com.termux/files/home
SHELL=/data/data/com.termux/files/usr/bin/fish
SHLVL=1
SSH_CLIENT=127.0.0.1 50688 8022
SSH_CONNECTION=127.0.0.1 50688 127.0.0.1 8022
SSH_TTY=/dev/pts/1
TERM=xterm-256color
TMPDIR=/data/data/com.termux/files/usr/tmp
USER=u0_a99
```

It seems to happen because `locale.setlocale()` does not work as expected.
The following script:
```python
import locale
locale.setlocale(locale.LC_ALL, "")
print(locale.getlocale())
```
returns `(None, None)` but it should return `('en_US', 'UTF-8')`.
(According to [the doc](https://docs.python.org/2/library/locale.html), `locale.setlocale(LC_ALL, '')` should set the locale to the user default.)

**Comment by tomty89** [comment]
```
$ python
Python 3.6.4 (default, Jan  7 2018, 03:52:16)
[GCC 4.2.1 Compatible Android Clang 5.0.300080 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getlocale()
(None, None)
>>> locale.getdefaultlocale()
('en_US', 'UTF-8')
>>> locale.resetlocale()
>>> locale.getlocale()
('en_US', 'UTF-8')
>>>
$
```

@Rudloff @tdryer Seems like `resetlocale()` helps. I think `LC_*` is a glibc thing (and Termux/Android doesn't use that)? So this might be an upstream python thing (for not being platform-independent enough).

**Comment by gnirlos** [comment]
I know this issue is still open, but I thought I would provide another example.

Even when locale thinks it's set correctly, it's not working...

Python script:
====================
import locale
print('before -> ', locale.getlocale())
locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')
print('after ->  ', locale.getlocale())
print(locale.currency(12.42))
====================

====================
[~/gnirlos/] -> python locale_test.py
before ->  ('en_US', 'UTF-8')
after ->  ('en_US', 'UTF-8')
Traceback (most recent call last):
  File "locale_test.py", line 5, in <module>
    print(locale.currency(12.42))
  File "/data/data/com.termux/files/usr/lib/python3.7/locale.py", line 267, in currency
    raise ValueError("Currency formatting is not possible using "
ValueError: Currency formatting is not possible using the 'C' locale.
====================

**Comment by xdegaye** [comment]
Python ``locale.setlocale()`` is a wrapper around the corresponding function in Android libc. The implementation of [setlocale() in android-7.0](https://android.googlesource.com/platform/bionic/+/refs/tags/android-7.0.0_r36/libc/bionic/locale.cpp#139) is buggy and returns ``C`` when ``locale_name`` is the empty string. With the introduction of the ``__is_utf8_locale()``, the bug is fixed in [the master branch of bionic](https://android.googlesource.com/platform/bionic/+/master/libc/bionic/locale.cpp#158). So the Python statement ``locale.setlocale(locale.LC_ALL, "")`` should now behave correctly.

**Comment by xdegaye** [comment]
@tomty89
In python 3.7 ``locale.getlocale()`` returns now correctly ``('en_US', 'UTF-8')``.

**Comment by xdegaye** [comment]
@gnirlos
The [locale.cpp](https://android.googlesource.com/platform/bionic/+/master/libc/bionic/locale.cpp#88) module does not configure most of the local conventions and sets them to ``not_available`` instead.  This can be seen in python by listing the values set to the members of the ``lconv g_locale`` structure by the ``__locale_init()`` function with ``localeconv()``:
```
>>> locale.localeconv()
{'int_curr_symbol': '', 'currency_symbol': '', 'mon_decimal_point': '',
'mon_thousands_sep': '', 'mon_grouping': [], 'positive_sign': '',
'negative_sign': '', 'int_frac_digits': 127, 'frac_digits': 127,
'p_cs_precedes': 127, 'p_sep_by_space': 127, 'n_cs_precedes': 127,
'n_sep_by_space': 127, 'p_sign_posn': 127, 'n_sign_posn': 127,
'decimal_point': '.', 'thousands_sep': '', 'grouping': []}
```

So the python error message ``Currency formatting is not possible using the 'C' locale`` is misleading, it is the settings of the above values that makes the formatting impossible.

**Comment by jidhub** [comment]
Is this bug responsible for the impossibility for xterm and xev to interpret keycodes that are not ascii (agrave, eacute, ...) ?

**Comment by jidhub** [comment]
I just tried, from an xterm running, shown on the phone screen by bVNC and by the pkgs x11vnc and Xvfb, this command: ssh -Y my_linux_server xterm 
This opened a second xterm in which I could type à and é. But in the first xterm, keycodes corresponding to non-ascii characters are just ignored.

**Comment by jidhub** [comment]
I compiled xorg-xev and x11lib with debug symbols, inside https://github.com/termux/termux-packages/blob/master/scripts/run-docker.sh with the following command: https://github.com/termux/termux-packages/blob/master/build-package.sh -d xorg-xev

This showed me that, when pressing non-ascii keys, XkbTranslateKeyCode from `pkg install libx11` returns an empty string, while XkbTranslateKeyCode from my linux returns a multi-byte char.

**Comment by xtkoba** [comment]
@jidhub Please open a new issue for that. I believe that is not much relevant to the issue here.

**Comment by xtkoba** [comment]
As mentioned above, this is a system-level bug of Android 7 which we cannot fix.
