### ISSUE TITLE
[Pulsar]:  Pulsar text editor

### ISSUE THREAD

**Issue by AhmadNaruto** [termux/termux-packages#20094]
### Why is it worth to add this package?

this is good code editor 

### Home page URL

https://pulsar-edit.dev/

### Source code URL

https://github.com/pulsar-edit/pulsar

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [ ] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [ ] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by TomJo2000** [comment]
![image](https://github.com/termux/termux-packages/assets/43716232/d07e4f46-47be-4fe9-841d-073b7ddff754)
Let's correct that checklist real quick.

**Comment by TomJo2000** [comment]
The bigger issue here is that Pulsar requires `electron`, which is turn depends on `chromium`.
Both of which are not currently packaged in the main repositories due to Chromium timing out the standard GitHub actions runners when building it.

I would suggest moving this package request to [the TUR](https://github.com/termux-user-repository/tur) for the time being,
where both Chromium and Electron are already packaged.
Packages can and do move from the TUR to the main repositories, but we do not currently have the infrastructure in the main repositories to package electron applications.
