### ISSUE TITLE
Archlinux

### ISSUE THREAD

**Issue by ayam12** [termux/termux-packages#2012]
![screenshot_20180107-204009](https://user-images.githubusercontent.com/34999160/34650833-2801f33c-f3bf-11e7-985b-67bb939e75e7.png)
proot warning: can't sanitize binding "/sys/": No such file or directory
proot info: vpid 1: terminated with signal 4
proot error: trying to remove a directory outside of '/data/data/com.termux/files/usr/tmp/', please report this error.
How to fix it?

**Comment by Grimler91** [comment]
I believe this belongs over at https://github.com/sdrausty/termux-archlinux or https://github.com/sdrausty/termux-arch or wherever you got the archlinux script from. Please open an issue there instead.

**Comment by sdrausty** [comment]
@ayam12 @fornwall @Grimler91 Thank  you for taking an interest in Termux and Arch Linux!  Here is more information as far as topics and where to write more about this issue. 

Please direct PRoot in Termux issues [https://github.com/termux/proot here](https://github.com/termux/proot).  Comments regarding [`setupTermuxArch.sh`](https://sdrausty.github.io/TermuxArch/setupTermuxArch.sh) should be directed to https://github.com/sdrausty/TermuxArch/issues and:
>  this belongs over at https://github.com/sdrausty/termux-archlinux or https://github.com/sdrausty/termux-arch

As @Grimler91 stated,  
> wherever you got the archlinux script from

[`setupTermuxArch.sh`](https://raw.githubusercontent.com/sdrausty/TermuxArch/master/scripts/files/stable/setupTermuxArch.sh) creates system information when requested. Run `setupTermuxArch.sh --sysinfo` and post this information along with your input and complete output.  If you think a screenshot will help us in resolving, include it in your post.  



Hopefully you are inspired with Arch Linux in Termux PRoot and [Termux](https://termux.com) on device as well as I am.  A new website regarding Arch Linux in Termux PRoot is being built at https://sdrausty.github.io/TermuxPovray/ regarding https://github.com/termux/termux-packages/issues/202 Package request: povray.  

![scifi_demo](https://user-images.githubusercontent.com/27742457/31354926-371c5e52-ad06-11e7-8dc6-543bc417e5ba.jpg)

**Comment by michalbednarski** [comment]
First of all, `proot` is not supposed to be nested, so don't run `termux-chroot` before `startarch`

If still doesn't work then that appears to be bug in proot should be reported at https://github.com/termux/proot/issues, please attach `typescript` file generated by:
```
script
uname -a
PROOT_VERBOSE=9 startarch
```
(`Ctrl-D` or `exit` to end terminal recording, `Script done, file is typescript` is printed by `script` command at end of recording)

**Comment by michalbednarski** [comment]
Unforunately, there's no documentation as far as I know so the answer is grep the [proot source](https://github.com/termux/proot). I've provided some notes that might be useful

# Syscall log entry
Most of lines in log look like this:
```
vpid 1: sysenter end: prctl(0x26, 0x1, 0x0, 0x0, 0x0, 0x0) = 0x26 [0x7fd6f08100, 0]
```

## vpid
`vpid` is virtual pid assigned by proot. `vpid 1` means first process inside proot and other processes get consecutive `vpid` values, so `vpid 4` means fourth process inside proot

## Syscall phase

Message (Phase) | Meaning
------------ | -------------
sysenter start | Proot intercepted start of syscall and has read registers, values come from process making syscall
sysenter end | Proot has tampered (or not) with syscall and is about to write it's arguments and let syscall be handled by kernel
sysexit start | Syscall was handled by kernel and proot intercepted response
sysexit end | Proot has put final syscall result in register and is about to write registers to tracee and continue it's execution

Note that not all of these will be intercepted and some syscalls might have just sysenter stages (and some syscalls might not appear at all)

## "What those hex numbers mean"
These are values from registers, for details see [source for this log line](https://github.com/termux/proot/blob/6c2b210e3887386a34bcafa154997aa03c291f7f/src/tracee/reg.c#L214).

Values in `()` braces are syscall arguments (their meaning is usually described in `man 2 ...`; values of registers beyond syscall argument count are ignored by kernel).

After `=` is syscall result (which, depending on architecture, might be same register as one of parameters; [errno reference](http://www.virtsync.com/c-error-codes-include-errno) might be useful, but note that values need to be negated after conversion from hex)

In `[]` there's value of stack pointer (which is used when proot injects strings or structures as syscall arguments) and ABI identifier (haven't needed it so far in Termux, usually 0, ABIs can have alternate syscall table)

# Side notes
## PROOT_VERBOSE env var
`PROOT_VERBOSE` environment variable is Termux extension, in normal `proot` there's command line argument `-v 9`. (That command line argument still exists and has precedence over env. In Termux proot is often invoked through wrapper scripts so I've added that var to allow enabling verbose mode without script modification). 9 is not real log level but i can't remember which is actually used highest value (It's about five) and 9 works fine.

## "file is typescript"
[`script`](http://man7.org/linux/man-pages/man1/script.1.html) is terminal recorder program capturing output from terminal to file (defaulting to `typescript`), `proot` outputs debug info to `stderr`. "`typescript`" is not keyword you'll have to look for)

## `strace`ing proot
`strace` can be normally used on `proot`, however `strace -f` (follow) cannot. If `strace` of `proot` invoked in script is needed, `proot` call in shell script needs to be prefixed with `exec` keyword (which causes launched process to replace script interpreter instead of being launched in separate process)

**Comment by sdrausty** [comment]
@michalbednarski Thank you for your thorough reply and the advice.

> the answer is grep the [proot source](https://github.com/termux/proot)

I will be using [ack-grep](https://github.com/termux/termux-packages/tree/master/packages/ack-grep) for this task.
