### ISSUE TITLE
[Bug]: `execve()` gives ": unknown program '''" if you run ./a.out once you compile with clang/g++

### ISSUE THREAD

**Issue by SwuduSusuwu** [termux/termux-packages#20242]
### Problem description

```
~/ $ cat << EOF > test.cxx
#include <unistd.h>
#include <stdio.h>
int main(int argc, char *const* _args) {
  char *args[2];
  printf("1");
  args[0] = "/bin/ls";
  args[1] = "-lh";
  execve(args[0], args, NULL);
  args[1] = "";
  execve(args[0], args, NULL);
  execve(args[0], NULL, NULL);
  args[0] = "/bin/echo";
  args[1] = "u";
  execve(args[0], args, NULL);
  printf("2");
return 0;
}
EOF
~/ $ g++ test.cxx && ./a.out
: unknown program '''
Try ' --help' for more information
~/ $ cat << EOF > test.cxx
#include <unistd.h>
#include <stdio.h>
int main(int argc, char *const* _args) {
  char *args[2];
  printf("1");
  args[0] = "/bin/ls";
  args[1] = "-lh";
  execve(args[0], args, NULL);
  args[1] = "";
  execve(args[0], args, NULL);
  args[0] = "/bin/echo";
  args[1] = "u";
  execve(args[0], args, NULL);
  printf("2");
return 0;
}
EOF
~/ $ g++ test.cxx && ./a.out
12
~/ $
```

### What steps will reproduce the bug?

Install latest Termux from Google Store, install latest `clang` from official repos on Termux

### What is the expected behavior?

Should output directory contents as list

### System information

```shell
Android 14
Termux 1.42.1
```

**Comment by SwuduSusuwu** [comment]
Have removed lots to reduce this.
Original sources: [https://github.com/SwuduSusuwu/SubStack/blob/trunk/cxx/VirusAnalysis.cxx](https://github.com/SwuduSusuwu/SubStack/blob/trunk/cxx/VirusAnalysis.cxx)

**Comment by twaik** [comment]
Playstore build is deprecated and should not be used. Use F-droid or github release.

**Comment by SwuduSusuwu** [comment]
Am not allowed to use this phone to install from third-party sources.
But am curious, which of the new versions fixes this?

**Comment by Grimler91** [comment]
Seems pretty obvious that error comes from:

```c
execve(args[0], NULL, NULL);
```

What do you expect execve to do with NULL as argv[]?

**Comment by SwuduSusuwu** [comment]
> Seems pretty obvious that error comes from:
> 
> ```c
> execve(args[0], NULL, NULL);
> ```
> 
> What do you expect execve to do with NULL as argv[]?

Used all possible variations, all failed.
From searches for examples of how to use exec* functions, commands such as `/bin/ls` without args should run for us.
Which variation (with the third party sources) runs for you?
If the third-party versions of Termux can do this,
could argue to allow third-party sources.

**Comment by TomJo2000** [comment]
This isn't a "third party" issue.
(Additionally I'd like to note that the F-Droid and GitHub APK releases are 1st party distribution methods of Termux.)

What you seem to be dealing with is a fundamental lack of experience with the C programming language.
Aside from the version or distribution channel of Termux you are making use of.

**Comment by SwuduSusuwu** [comment]
> This isn't a "third party" issue. (Additionally I'd like to note that the F-Droid and GitHub APK releases are 1st party distribution methods of Termux.)
> 
> What you seem to be dealing with is a fundamental lack of experience with the C programming language. Unrelated to the version or distribution channel of Termux you are making use of.

The top result on Google (for how to use C/C++ to execute Bash): https://stackoverflow.com/a/30149941/24473928
`#include <unistd.h>
int main() {
        char *args[2];
        args[0] = "/bin/ls";
        args[1] = "-lh";
        execve(args[0], args, NULL);
}
`
Passes args to ls,
but failed (as https://github.com/termux/termux-packages/issues/20242 describes,) so used variations (such as without args,) which also failed.
Are you trying to say that a new version of Termux fixes this, and, if so, which version of Termux fixes this?
Or are you saying that all the results for how to do this were from idiots and that none of them should function on any implementation of Bash/Ash?

Lots of businesses do not allow you to use devices with apps that do not from Google app stores: https://natlawreview.com/article/mitigating-rising-risk-corporate-use-third-party-apps
but if new versions of Termux improve functions for businesses,
could convince bosses to allow this.

**Comment by agnostic-apollo** [comment]
What are you even on about, read the comment by grimler above.

You are passing `NULL` as `argv` in `execve(args[0], NULL, NULL);`, when infact you should be passing the path to the executable you need to execute as the first element of the `argv` array (you name it as `args`). That's why you are getting the unknown program error or would possibly get a segmentation fault.

Your second issue is that your `args` array is of size `2`, when infact it needs to be size `3` and its final element needs to be `NULL` so that it's null terminated, so that the kernel knows when to stop reading arguments in the array, it has no way of knowing the initial size you created the array, so it doesn't know how many args there are. You need to declare `char *args[3];` and set final element as `args[2] = NULL;` if passing only `1` arg to the executable. If you are passing additional args, adjust array size and final index accordingly. Fix that and `ls` and `echo` will work.

Read the manpage for `execve()`

>The char *const argv[] argument is an array of pointers to null-terminated strings that represent the argument list available to the new program.  The first argument, by convention, should point to the filename associated with the file being executed.  **The array of pointers must be terminated by a null pointer.**


https://man7.org/linux/man-pages/man3/exec.3.html

Basically, these are not issues with termux (playstore or fdroid/github), but your own code. The only issue related to `exec()` you may get is shebangs or exectuable path correction not working on Android 14 from `/usr/bin/*` to `$TERMUX__PREFIX/bin/*` paths. For that, install the `termux-exec` package in the zip attached in the comment at https://github.com/termux/termux-exec/pull/24#issuecomment-1873059748

>but if new versions of Termux improve functions for businesses,
could convince bosses to allow this.

There have been 10 app version releases since last playstore release, with massive addition in changes and bug and security/vulnerability fixes. We in no way recommend installing termux from playstore or support it.

https://github.com/termux/termux-app#google-play-store-deprecated

**Comment by agnostic-apollo** [comment]
>https://stackoverflow.com/a/30149941/24473928

I just checked and there is already a comment under it for "You need NULL in the last element of args", same as I said. Answers at stackoverflow, etc should not be used without understand what they are doing, there are tonne of wrong and dangerous answers there. Always read official docs and man pages when running things.

**Comment by SwuduSusuwu** [comment]
Cool, bless you
`char *args = {"/bin/ls", "-lh", NULL};` no output
`char *args = {"/bin/ls", "", NULL};` success
`char *args = {"/bin/ls", NULL, NULL};` success
`char *args = {"/bin/echo", "test", NULL};` no output
(for `execve(args[0], args, NULL`)

To install fdroid.apk (or ternux.apk) gives this error (and most businesses do not allow you to use your own device if you change this):
![Screenshot_20240518-071419](https://github.com/termux/termux-packages/assets/168943815/f042ba71-c5e8-4cea-a51e-bc9bd99131a5)
Hope https://github.com/termux/termux-app/issues/2155 resolves this

**Comment by twaik** [comment]
> and most businesses do not allow you to use your own device if you change this

What exactly do you mean?

**Comment by agnostic-apollo** [comment]
https://developer.android.com/work/dpc/security#unknown_sources

**Comment by agnostic-apollo** [comment]
>char *args = {"/bin/ls", "-lh", NULL}; no output (do not want "-lh", but example has this, and curious what the problem is)

Use `char *args[] = {"/bin/ls", "-lh", NULL};`, not `char *args =...`.
