### ISSUE TITLE
[Bug]: Can't Open Display: 0

### ISSUE THREAD

**Issue by Kabax237** [termux/termux-packages#20268]
### Problem description

Ranking on Galaxy S22 after installing mobox on Terminus I get Can't open display: 0

### What steps will reproduce the bug?

Installing Mobox x86 on Terminus on a s22

### What is the expected behavior?

Open up wine

### System information

```shell
Galaxy S22
```

**Comment by twaik** [comment]
This is a termux support space. If your issue is with a third-party project built on top of termux, we probably can't help you with it. Seek help from the author(s) of that project instead.

Third-party projects, with starting points for support where we know them:
Mobox: https://github.com/olegos2/mobox/issues
Andronix: https://github.com/AndronixApp/AndronixOrigin/issues
TUR (termux-user-repository): https://github.com/termux-user-repository/tur/issues

This list isn't complete - if someone tells you a project is a derivative of termux, the same applies. If you need more help contacting the authors of a third-party project, please google it instead of asking for that here.
