### ISSUE TITLE
Package request: libc6:armhf

### ISSUE THREAD

**Issue by ephetic** [termux/termux-packages#2043]
I'm trying to run a 32b Linux binary (closed source demo) and from what I can tell it can't find the 32b runtime on my aarch64 Android.

**Comment by Grimler91** [comment]
This won't work. You can't only run binaries on the architecture they were built for. 
And as you hinted, it probably wouldn't work out of the box even if the arch were correct since termux is a prefixed system, and your binary looks for libs etc in the standard locations.

**Comment by ephetic** [comment]
It's an ARM build and aarch64 is supposedly backwards compatible, but I can't speak to your point about the prefix system.

**Comment by Grimler91** [comment]
Right, I assumed you talked about x86 (i686) since you just said 32bit. 
Is it build for arm linux or arm android? 
If it is built for arm linux then you would need to run it in termux-chroot since termux is prefixed. 

It won't work anyways, see for example https://stackoverflow.com/questions/34648832/can-old-arm32-binary-files-be-run-on-aarch64-kernel. Might be possible if you compile your own kernel.
