### ISSUE TITLE
FATAL ERROR: Could not find /data/data/com.termux/files/usr//data/data/com.termux/files/usr/bin/mariadbd


### ISSUE THREAD

**Issue by Bhavinkhilnanii** [termux/termux-packages#20647]
I was trying to install mariadb then this error poped out

**Comment by tqfx** [comment]
Temporary workaroud

```
mariadb-install-db --user=root
```

Waiting for PR

**Comment by alpha23150833-crypto** [comment]
_**### 

> Pkg install python

**_
__

**Comment by yton980-blip** [comment]
mariadb-install-db --user=root --auth-root-authentication-method=normal

**Comment by yton980-blip** [comment]
#!/data/data/com.termux/files/usr/bin/bash

BIN=/data/data/com.termux/files/usr/bin
HOME=/data/data/com.termux/files/home

# Exit if dex is not in same directory
dex="$( cd -- "$( dirname "${0}" )" \
  > /dev/null 2>&1 || exit 1; pwd -P )/rish_shizuku.dex"
if [[ ! -f "${dex}" ]]; then
  echo "ERROR: Cannot find ${dex} in current directory!"
  exit 1
fi

# Create Shizuku script file
cat > "${BIN}/shizuku" << 'EOF'
#!/data/data/com.termux/files/usr/bin/bash

# Disconnect offline devices
offline=$( adb devices | awk '$2 == "offline" {print $1}' || true )
if [[ -n "${offline-}" ]]; then
  while read -r device; do
    adb disconnect "${device}" > /dev/null 2>&1
  done <<< "${offline}"
  sleep 1
fi

# Make list of open ports
ports=$( nmap -sT -p30000-50000 --open localhost 2> /dev/null \
  | awk -F/ '/open/ {print $1}' || true )

# Go through list of ports
for port in ${ports}; do

  # Try to connect to port, and save result
  adb disconnect "localhost:${port}" > /dev/null 2>&1
  result=$( adb connect "localhost:${port}" || true )

  # Check if connection succeeded
  if [[ "${result-}" =~ "connected" || "${result-}" =~ "already" ]]; then

    # Show message to user
    echo "${result}"

    # Start Shizuku
    adb -s "localhost:${port}" wait-for-device > /dev/null 2>&1 && sleep 1
    if adb -s "localhost:${port}" shell '
      apk=$( pm path moe.shizuku.privileged.api 2> /dev/null \
        | sed "s/\r//;s/^package://" || true )
      abi=$( getprop ro.product.cpu.abi 2> /dev/null \
        | sed "s/\r//;s/-.*//;s/armeabi/arm/" || true )
      [ -n "${apk-}" ] && [ -n "${abi-}" ] \
        && "$( dirname "${apk}" )/lib/${abi}/libshizuku.so" || exit 1'
    then

      # Disable wireless debugging, because it is not needed anymore
      adb -s "localhost:${port}" shell settings put global adb_wifi_enabled 0
      exit 0

    else
      echo "ERROR: Failed to start Shizuku. Is app installed and up-to-date?"
      exit 1
    fi
  fi
done

echo "ERROR: No working port found! Is wireless debugging enabled?"
exit 1
EOF

# Create Rish script file
cat > "${BIN}/rish" << EOF
#!/data/data/com.termux/files/usr/bin/bash

[ -z "\$RISH_APPLICATION_ID" ] && export RISH_APPLICATION_ID="com.termux"

/system/bin/app_process -Djava.class.path="${HOME}/rish_shizuku.dex" \
  /system/bin --nice-name=rish rikka.shizuku.shell.ShizukuShellLoader "\${@}"
EOF

# Give execution permission to script files
chmod +x "${BIN}/shizuku" "${BIN}/rish"

# Copy dex to home directory
if [[ "${dex}" != "${HOME}/rish_shizuku.dex" ]]; then
  rm -f "${HOME}/rish_shizuku.dex"
  cp "${dex}" "${HOME}/rish_shizuku.dex"
fi

# Remove dex write permission, because app_process cannot load writable dex
chmod -w "${HOME}/rish_shizuku.dex"
exit 0

**Comment by yton980-blip** [comment]
# Show message to user
echo "${result}"

# Start Shizuku
adb -s "localhost:${port}" wait-for-device > /dev/null 2>&1 && sleep 1
if adb -s "localhost:${port}" shell '
  apk=$( pm path moe.shizuku.privileged.api 2> /dev/null \
    | sed "s/\r//;s/^package://" || true )
  abi=$( getprop ro.product.cpu.abi 2> /dev/null \
    | sed "s/\r//;s/-.*//;s/armeabi/arm/" || true )
  [ -n "${apk-}" ] && [ -n "${abi-}" ] \
    && "$( dirname "${apk}" )/lib/${abi}/libshizuku.so" || exit 1'
then

  # Disable wireless debugging, because it is not needed anymore
  adb -s "localhost:${port}" shell settings put global adb_wifi_enabled 0
  exit 0

else
  echo "ERROR: Failed to start Shizuku. Is app installed and up-to-date?"
  exit 1
fi
