### ISSUE TITLE
Linuxbrew in Termux? [Package Request] [Help Wanted]

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#2071]
Hi there,
I heard  [Linuxbrew](http://linuxbrew.sh)  is available for 32-bit ARM.
is it possible to install [Linuxbrew](http://linuxbrew.sh) in Termux?
I tried their primary installation method, but it shows error.
After installing brew using their alternative installation method, I tried to open brew but it shows  **CANNOT LINK EXECUTABLE: library "libandroid-support.so" not found** 
Can anyone help me about it?
Also adding a brew package in the repository would be great.

![screenshot_20180128-032256](https://user-images.githubusercontent.com/21147895/35476487-b55c2894-03da-11e8-9603-ac16be01f4f9.png)

Thanks.

**Comment by Grimler91** [comment]
"Alternative installation method" means that you compiled it on device?

You can fix this type of error by `export LDFLAGS=" -landroid-support"` and the recompile the package.

**Comment by emanresusername** [comment]
i think the alternative install is the [`sudo`less one to the $HOME directory](http://linuxbrew.sh/#features)
i'm interested in this one too was casually updating a [zsh plugin](https://github.com/zpm-zsh/linuxbrew/blob/master/linuxbrew.plugin.zsh) but it looks like the [install script](https://github.com/Linuxbrew/install/blob/master/install) has been updated much more recently, note to self to review that
if other quirks/environment variables/etc come up (and/or you want to add to my sample size of ~1 using that plugin 😅 ) lmk

**Comment by emanresusername** [comment]
@grayalias did you figure out how to make it work? don't [denvercoder9](https://xkcd.com/979/) me!!
![https://xkcd.com/979/](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)

**Comment by emanresusername** [comment]
DEAR PEOPLE FROM THE FUTURE: [here's what i've figured out so far ...](https://github.com/emanresusername/linuxbrew-zsh-plugin/blob/termux/linuxbrew.plugin.zsh#L47-L62)

i think the issue is something with the `$(brew --prefix)/lib/ld.so` not being there 

[symlinking `/bin/false` to it](https://github.com/Linuxbrew/homebrew-core/issues/3880#issuecomment-324961662) prevented an earlier error, but then things break later with the following

```ruby
CANNOT LINK EXECUTABLE /usr/bin/gcc-7: library libandroid-support.so not found
CANNOT LINK EXECUTABLE /usr/bin/clang: library libLLVM-5.0.so not found
Error: hello cannot be built with any available compilers.
Install Clang or brew install gcc
```

i found some things about how on android it's `/system/bin/linker{,64}` instead of `ld.so` but symlinking those instead also didn't work :cry:

**Comment by grayalias** [comment]
@emanresusername unfortunately no. 🙁

**Comment by sjackman** [comment]
Hi, all. I maintain Linuxbrew. I don't have an Android system on which to test, but I can chime in with a few observations. These are all completely untested. Let me know if anyone tries this out and gets it working! See also https://github.com/Linuxbrew/brew/wiki/Chromebook-Install-Instructions. I don't have a Chromebook and haven't tested these instructions myself. Feel free to edit the Wiki.

# Symlink the dynamic linker
See https://github.com/termux/termux-packages#android-dynamic-linker
and https://github.com/Linuxbrew/brew/blob/ed30aa3789a127f03b8fffe07ee1391550797ec4/Library/Homebrew/cmd/install.rb#L322
```sh
ln -s /system/bin/linker64 $HOME/.linuxbrew/lib/ld.so || ln -s /system/bin/linker $HOME/.linuxbrew/lib/ld.so
```

# Use DT_RUNPATH rather than DT_RPATH
Apparently the dynamic linker does not support DT_RPATH.
See https://github.com/termux/termux-packages#android-dynamic-linker
and https://android.googlesource.com/platform/bionic/+/nougat-mr1-release/linker/linker.cpp#3910
Note the conspicuous absence of DT_RPATH. Someone who cared enough could add support to the Android dynamic linker for DT_RPATH.
For Linuxbrew, see https://github.com/Linuxbrew/brew/issues/598
and https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/shims/linux/super/cc#L258
Add the option `ld --enable-new-dtags` to use `DT_RUNPATH` rather than the default `DT_RPATH`.
Alternatively you can use `patchelf --shrink-rpath` which has the side effect of changing `DT_RPATH` to `DT_RUNPATH`.

**Comment by bukzor** [comment]
@sjackman In my testing (if I remember correctly) Homebrew already creates the necessary linker symlink.
The actual cause of the reported problem is that the brew shell script blanks LD_LIBRARY_PATH which all termux binaries use to find libandroid.so.

Converting termux from leaning on LD_LIBRARY_PATH to using RUNPATH will fix this. The fix is pretty simple. When compiling termux binaries, they need to add the options `-Wl,--enable-new-dtags -Wl,-rpath=\\\$ORIGIN/../lib`.  The `$ORIGIN` there signifies the final location of the binary, and the value of `rpath=` should resolve to the location of libandroid.so.

Another nice side-effect is that the resulting userspace is relocatable, which will play quite nicely with termux-chroot.

**Comment by sjackman** [comment]
Ah, got it. Yes, big thumbs up for using `RPATH` (or `RUNPATH`) rather than `LD_LIBRARY_PATH`. An existing installation of `termux` could be hacked up using `patchelf` to test it.

**Comment by emanresusername** [comment]
is this more of an install script thing/brew thing? or a termux thing? 
i'm pretty far out of my depth in either pool 😅 ... but ftr, [this](https://github.com/emanresusername/brew/commit/48c763cad5d60397020d96c7280f33ce5483cbdd#commitcomment-27562883) did not work :(

**Comment by bukzor** [comment]
@sjackman To be very clear, RPATH is never going to work, since the Android linker doesn't support it. I'm sure this was originally tried, then the current LD_LIBRARY_PATH system was chosen when it didn't work. RUNPATH should work correctly however.

**Comment by sjackman** [comment]
Note that the Android dynamic linker is open source, and someone who were sufficiently motivated could add support for `DT_RPATH` to Android. See https://android.googlesource.com/platform/bionic/+/nougat-mr1-release/linker/linker.cpp#3910
Adding hacktastic support for DT_RPATH that had the same behaviour as `DT_RUNPATH` should be pretty easy. Possibly as easy as…
```diff
-      case DT_RUNPATH:
+      case DT_RUNPATH: case DT_RPATH:
```
though emulating the GNU dynamic linker behaviour would probably be better.

**Comment by fornwall** [comment]
Note that RUNPATH requires android 7.0 or later, while Termux currently supports Android 5.0 or later. I'm thinking of droppping 5.0 support in the near future, while 6.0 will be supported longer, so we cannot do the LD_LIBRARY_PATH-> RUNPATH transition just yet.

**Comment by sjackman** [comment]
You could use `RUNPATH` if available on Android 7+ and fall back to `LD_LIBRARY_PATH` for Android <7.

**Comment by bukzor** [comment]
Fixed (?) here: https://github.com/termux/termux-packages/pull/2255

**Comment by sdrausty** [comment]
> droppping 5.0 support in the near future

Why are you thinking about this?  What is the motivation?

**Comment by bukzor** [comment]
We have RUNPATH by default in binutils now (#2255). How do I rebuild clang under this change?

**Comment by bukzor** [comment]
@fornwall A brief description to help me jumpstart would be very useful.

**Comment by tomty89** [comment]
Did you think Termux packages are built with toolchain in Termux? Coz they are not but built with toolchain in the NDK.

**Comment by bukzor** [comment]
No, I didn't assume such a thing.

**Comment by tomty89** [comment]
What do you mean by "How do I rebuild clang under this change?" then?

**Comment by bukzor** [comment]
Ah, okay, yes, I did think this would change how clang would be compiled.
I'll open another, separate ticket for compiling clang with --enable-new-dtags.

**Comment by sdrausty** [comment]
Git bloat:
```
Press RETURN to continue or any other key to abort
==> Downloading and installing Linuxbrew...

remote: Counting objects: 107017, done.
remote: Compressing objects: 100% (208/208), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Failed during: git fetch origin master:refs/remotes/origin/master --tags --force
```
Trying again in [TermuxArch](https://sdrausty.github.io/TermuxArch/).  Thank you for bringing this project to my attention @grayalias.  I 💘 love the way it refuses to run as root user.  
![screenshot_2018-03-21-18-46-41](https://user-images.githubusercontent.com/27742457/37741547-2f4958f8-2d38-11e8-9450-cf3df364fd9b.png)
How about you?

**Comment by bukzor** [comment]
@sdrausty I have a small number of linuxbrew packages compiling successfully using this method: https://github.com/Linuxbrew/brew/wiki/Android

**Comment by ExtremeNerd** [comment]
I am pretty beginner compared to everyone here... However, what about extending the android linker, then prepending the $PATH variable so that the extended linker is invoked? Just an idea, though....

**Comment by ExtremeNerd** [comment]
Also, what about Entware? I don't think of it as a Linuxbrew alternative but it might help avoid building some packages....

**Comment by xeffyr** [comment]
> Also, what about Entware?
it might help avoid building some packages....

Yes, it can help to avoid building of some packages, but only those that don't use config files or external data as **paths are hardcoded**.

**Comment by baguio** [comment]
> @sdrausty I have a small number of linuxbrew packages compiling successfully using this method: https://github.com/Linuxbrew/brew/wiki/Android

Should we still be using this method after the [Homebrew 2.0 release and its merge with Linuxbrew](https://brew.sh/2019/02/02/homebrew-2.0.0/), @bukzor ?

**Comment by sjackman** [comment]
Perhaps relevant, Homebrew on Linux (aka Linuxbrew) now supports AArch 64 (aka 64-bit ARM or armv8) as well as 32-bit ARM (armv6).

**Comment by tukusejssirs** [comment]
I’d like to say that I tried to run `sudo cmd` (`sudo`comes from [here](https://gitlab.com/st42/termux-sudo)), however, I get  this error:

```bash
CANNOT LINK EXECUTABLE "cmd": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib64/libunwind.so"...
```

I believe that it is connected with this issue.

Btw, I’d like to run Android apps directly from Termux, this is how I noticed this error.

**Comment by tukusejssirs** [comment]
I’d like to say that I tried to run `sudo cmd` (`sudo`comes from [here](https://gitlab.com/st42/termux-sudo)), however, I get  this error:

```bash
CANNOT LINK EXECUTABLE "cmd": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib64/libunwind.so"...
```

I believe that it is connected with this issue.

Btw, I’d like to run Android apps directly from Termux, this is how I noticed this error.

**Comment by quackduck** [comment]
I too get an error when using the primary install method but it's about Ruby even when I have the newest Ruby installed:
```
Homebrew requires Ruby 2.6 which was not found on your system.
Homebrew portable Ruby requires Glibc version 2.13 or newer,
and your Glibc version is too old.
See https://docs.brew.sh/Homebrew-on-Linux#requirements
Install Ruby 2.6 and add its location to your PATH.
```
even using the other method:
```
$ eval $(~/.linuxbrew/bin/brew shellenv)
/data/data/com.termux/files/home/.linuxbrew/Homebrew/Library/Homebrew/brew.sh: line 6: uname: command not found
/data/data/com.termux/files/home/.linuxbrew/Homebrew/Library/Homebrew/brew.sh: line 7: uname: command not found
/data/data/com.termux/files/home/.linuxbrew/Homebrew/Library/Homebrew/cmd/shellenv.sh: line 9: /bin/ps: No such file or directory
```

**Comment by tomty89** [comment]
Latest Ruby in Termux is of version 2.7 though.
uname and ps are in coreutils and procps respectively, still the scripts need to run them from the right place (/data/data/com.termux/files/usr/bin), hence they might need modifications

**Comment by quackduck** [comment]
So the files that need to be edited are
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/shellenv.sh
(
```sh
...
  case "$(/bin/ps -p $PPID -o comm=)" in
...
```
)
and
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/brew.sh
(
```sh
...
HOMEBREW_PROCESSOR="$(uname -m)"
HOMEBREW_SYSTEM="$(uname -s)"
...
```
).

I'd like to point out that `uname` is in `$PATH` suggesting that the Homebrew install script might be doing more than I would expect.

**Comment by twaik** [comment]
The reason of closing this is the same as a reason for closing guix-related issue #3240. Building package-manager does not let us bring it's packages. Porting package should be done individually, we already do this for other packages.
