### ISSUE TITLE
tmpfile() and mkstemp(): solutions?

### ISSUE THREAD

**Issue by vaites** [termux/termux-packages#208]
Hi

I had problems with tmpfile() and mkstemp() functions because none is working well with Android SDK (returns a non-writable file in /data/local/tmp). In [this thread](http://stackoverflow.com/questions/7595324/creating-temporary-files-in-android-with-ndk) on StackOverflow an user tells he has the same problem...

Is there any alternative function that we can switch to? Or can be added working versions of this functions to libandroid-support package in a similar way to iconv?.

Thanks!

**Comment by fornwall** [comment]
I created [a patch for stdio.h](https://github.com/termux/termux-packages/blob/master/ndk_patches/stdio.h.patch) to define a `tmpfile()` function inline. Look it over and try it out, perhaps something similar can be done for `mkstemp()`.

You will need to remove the standalone toolchains, normally `$HOME/lib/android-standalone-toolchain-*`, so that they get recreated with the new patch for the headers.

**Comment by vaites** [comment]
I tested tmpfile() function and works ok. If you can add mkstemp() function too would be great (my C skills are limited).

**Comment by ViliusSutkus** [comment]
Hey,

I had this same problem too. My app was using a native library that calls tmpfile and it fails ...

Packaged the fix as an AAR library https://github.com/ViliusSutkus/tmpfile , which can be imported through gradle.

Not sure how you people package your termux packages. Do they end up as an APK or AAR? or Just a plain .so? My fix uses ContentProvider to obtain cache directory on Application's startup. That puts a requirement on having an Application to actually execute the ContentProvider.

**Comment by xtkoba** [comment]
As `mkstemp()` accepts a full path template, it does not need to be re-implemented.

Now that the patch for `tmpfile()` is already merged, I think this can be closed.
