### ISSUE TITLE
Today's upgrade of TeX Live is broken.

### ISSUE THREAD

**Issue by tigran123** [termux/termux-packages#2084]
Almost every time when I do "pkg upgrade", if texlive is mentioned in the list, I am 99% sure that after the upgrade nothing will work. This is (probably) because my TeX Live installation is proper (i.e. full 5-6GB or whatever, storage space is cheap and shouldn't be counted), but the one in Termux is minimalistic, i.e. missing all the key packages.

Here is the error from the log:

```
This is XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017/Termux) (preloaded format=xelatex 2017.10.15)  1 FEB 2018 14:46
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**urantia-study-edition
(./urantia-study-edition.tex
LaTeX2e <2017-04-15>
Babel <3.10> and hyphenation patterns for 5 language(s) loaded.

(/data/data/com.termux/files/usr/share/texlive/texmf-dist/tex/latex/base/book.c
ls
Document Class: book 2014/09/29 v1.4h Standard LaTeX document class

(/data/data/com.termux/files/usr/share/texlive/texmf-dist/tex/latex/base/bk10.c
lo
File: bk10.clo 2014/09/29 v1.4h Standard LaTeX file (size option)

! Font TU/lmr/m/n/10=[lmroman10-regular]:mapping=tex-text; at 10.0pt not loadab
le: Metric (TFM) file or installed font not found.
<to be read again>
                   relax
l.54 \normalsize

```

Oh, looks like the entire "opt/texlive/2017/texmf-dist" tree is gone somewhere, look:

```
$ locate -c texlive
118144
$ locate -e texlive
/data/data/com.termux/files/usr/var/lib/dpkg/info/texlive-bin.list
/data/data/com.termux/files/usr/var/lib/dpkg/info/texlive-bin.md5sums
/data/data/com.termux/files/usr/var/lib/dpkg/info/texlive-bin.preinst
/data/data/com.termux/files/usr/var/lib/dpkg/info/texlive.list
/data/data/com.termux/files/usr/var/lib/dpkg/info/texlive.md5sums
/data/data/com.termux/files/usr/var/lib/dpkg/info/texlive.postinst
/data/data/com.termux/files/usr/var/lib/dpkg/info/texlive.preinst
/data/data/com.termux/files/usr/var/lib/dpkg/info/texlive.prerm
```

Interestingly, the "-e" option of locate did come in handy --- I knew it would someday, when I suggested to the author of locate(1) to add it some 15 years ago or so :)

Oh and a note to the maintainer of TeX Live in Termux: please don't consider my criticism as harsh and annoying --- I actually sincerely ADMIRE your work and think that nobody in the whole world could have done it better. To have TeX Live on a mobile is a revolutionary idea and of a very very fundamental kind. I think you are just a tiny bit short of perfection --- and you would certainly attain it if you make the _full_ installation of TeX Live to be properly handled, i.e. to be the default (and ignore the interests of those people who vainly try to squeeze such serious piece of software into a mobile with less than 32GB of internal storage --- it is simply impossible).

**Comment by Grimler91** [comment]
Yeah, I should perhaps have put out a warning. 

The latest update moves the files from $PREFIX/opt to $PREFIX/share (and binaries to $PREFIX/bin) and I didn't see any good (bug free/easy to maintain) way of keeping user-installed files. Future updates shouldn't break things like this update, the files are where they belong (similar to where they are in other distributions). The binaries are now also recognized by command-not-found.

I'm still working on getting texlive-full up and running so that you could potentially use this instead of doing a `tlmgr install scheme-full`, no need for tlmgr then and no risk of files being accidently removed. What remains before texlive-full is real is:
- Some build-package.sh changes to allow subpackages and packages to rely on/conflict with each other in more ways
- Verifying that packages are installable on arm (dpkg fails for too large .deb files) (and my arm device has only 8 gb internal storage so I need to free up space on it to test, which is cumbersome)
- Testing, testing and testing

Subscribe to https://github.com/termux/termux-packages/issues/1456 for updates.
I'm hoping to have the full version operational at the latest when texlive 2018 is released.

**Comment by tigran123** [comment]
Thank you, brother, I knew it is all in your good and capable hands. I might take a closer look when/if I have some time. For now I've subscribed to the issue you suggested. Thank you again! :)

**Comment by fornwall** [comment]
I'm closing this then in favour of tracking progress in #1456.
