### ISSUE TITLE
[Bug]: CANNOT LINK EXECUTABLE "apt": library "liblz4.so.1" not found: needed by /data/data/com.termux/files/usr/lib/libapt-pkg.so in namespace (default)

### ISSUE THREAD

**Issue by Eythan-ship-it** [termux/termux-packages#20944]
### Problem description

Sometimes when I try to upgrade the package or install git/python2/pip It says that

### What steps will reproduce the bug?

Pkg install git
Pkg install python2 

### What is the expected behavior?

Idk

### System information

```shell
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PACKAGE_VARIANT=apt-android-7
TERMUX_APP_PID=30695
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_VERSION=0.119.1
TERMUX__USER_ID=0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://mirror.mwt.me/termux/main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.43.1
Android version:
14
Kernel build information:
Linux localhost 4.19.191-28701252-abA137FXXU5EXE3 #1 SMP PREEMPT Wed May 29 10:41:40 +07 2024 armv8l Android
Device manufacturer:
samsung
Device model:
SM-A137F
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by Biswa96** [comment]
`liblz4.so.1` file is not provided by any package. `libapt-pkg.so` depends on `liblz4.so`.

$ readelf -d $PREFIX/lib/libapt-pkg.so | grep lz4
  0x0000000000000001 (NEEDED)       Shared library: [liblz4.so]

**Comment by v-tibi** [comment]
So what to do if pkg no longer works? It is just that? Termux is screwed?

**Comment by Biswa96** [comment]
> So what to do if pkg no longer works? It is just that? Termux is screwed?

First, prove that it does not work.

**Comment by v-tibi** [comment]
It says 'cannot link executable "apt": library "liblz4.so.1" not found' and pkg update gets aborted. I guess it means just that.

**Comment by Biswa96** [comment]
Where did you install termux from?

**Comment by v-tibi** [comment]
It is from F-droid.

**Comment by v-tibi** [comment]
Well there are a ton of crap installed and configured just how I like them, and it took a good amount of time to get there so I just don't feel like it right now 😆

**Comment by Biswa96** [comment]
Could you try installing the apt package with `dpkg --install <deb-file-path>` command from this link https://packages-cf.termux.dev/apt/termux-main/pool/main/a/apt/ ? Match the `uname -m` output with the apt deb file. I am not sure if dpkg is working in your system now.

**Comment by v-tibi** [comment]
That worked, I could do the apt update and upgrade without any issue. Thanks @Biswa96, you saved me from some headache for sure! 👍

**Comment by Eythan-ship-it** [comment]
> Where did you install termux from?

F-droid

**Comment by Eythan-ship-it** [comment]
F-droid

**Comment by vvkisil** [comment]
Another solution to this issue: soft link the installed library to the required file name:
`ln -v -s /data/data/com.termux/files/usr/lib/liblz4.so /data/data/com.termux/files/usr/lib/liblz4.so.1`

**Comment by p-f-w** [comment]
> So what to do if pkg no longer works? It is just that? Termux is screwed?

your problem is little bit older as my own, but may be another one has the same

please look at "/data/data/termux.com/files/usr/lib"

on termux prompt you can "cd ../usr/lib"

and "ls liblz4.*"

there should be shown a file "liblz4.so"

if so then create a symbolic link called "liblz4.so.1" to "liblz4.so"

"ln -s liblz4.so liblz4.so.1"

works for me in an older termux installation, but does not know what the reason is for the problem

i answered because i'm was looking for a solution of the same problem and found only two sources with the same problem without solution

but in an installed debian (anlinux) under termux i was found the file "liblz4.so.1" and there this is only a symbolic link to "liblz4.so"

no need of android root rights as a reddit comment means
(on termux file system the user has all rights)
