### ISSUE TITLE
[Bug]: hard links 

### ISSUE THREAD

**Issue by selfote44** [termux/termux-packages#21167]
### Problem description

Hello. I tried to create a hard link with "ln" command, but the error "ln: failed to create hard link 'hola' => 'hola.c': Permission denied" occurs. 

### What steps will reproduce the bug?

ln hola.c hola

### What is the expected behavior?

The hard link "hola" would be created. 

### System information

```shell
Termux Variables:
TERMUX_EXEC__PROC_SELF_EXE=/data/data/com.termux/files/usr/bin/termux-info
TERMUX_VERSION=googleplay.2024.07.07
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.net stable main
Updatable packages:
command-not-found/stable 2.4.0-38 aarch64 [upgradable from: 2.4.0-37]
nano/stable 8.1 aarch64 [upgradable from: 8.0]
pinentry/stable 1.3.1 aarch64 [upgradable from: 1.3.0-1]
unrar/stable 7.0.9 aarch64 [upgradable from: 7.0.8]
termux-tools version:
3.0.7
Android version:
12
Kernel build information:
Linux localhost 4.14.186-perf-gcb8ba6f75777 #1 SMP PREEMPT Mon Jan 9 12:43:36 CST 2023 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
M1908C3JGG
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by twaik** [comment]
Unfortunately Android restricts creating hardlinks, no matter if it is private (termux's filesystem) or shared (sdcard or internal memory shared storage).
All termux packages are patched to avoid using hardlinks.
Termux can not override or bypass this restriction because it is a regular android application running in application sandbox.
