### ISSUE TITLE
arm 32bit executables on aarch64

### ISSUE THREAD

**Issue by ahmdshbz** [termux/termux-packages#2126]
Hello,
I would like to run an application on my phone, but I am unable to run either the linuxarm or linuxx8 6 versions of the application. Pkg install libc6-i386 does not work. FYI, 'uname -m' returns 'aarch64'

**Comment by Grimler91** [comment]
So I guess you have downloaded pre compiled binaries of the package (for linux arm and linux x86). That won't work, packages need to be compiled for termux for reasons described here: https://wiki.termux.com/wiki/Differences_from_Linux. 

You could get around some of the problems by installing termux-ubuntu/termux-fedora/termux-arch but you would also need to find a binary compiled for aarch64. Arm or x86 binaries won't work since they are compiled for different processors.
