### ISSUE TITLE
Package zlib instead of relying on the zlib system library

### ISSUE THREAD

**Issue by tomty89** [termux/termux-packages#2136]
Can someone tell me:
1. Why we don't have zlib built as a package in Termux but make use of the `libz.so` in `/system`?
2. How does other programs built for/in Termux even know where to look for the `libz.so`?

**Comment by tomty89** [comment]
Seems like if the necessary libraries aren't found in `-L$path` (and `$path` is `LD_LIBRARY_PATH` in the case), the linker link program to the ones found in `/system`.

Still, why don't we have zlib built?

**Comment by its-pointless** [comment]
several reasons we don't ship a version of libz.so
1. due to compatibility reasons. particularly during things that use audio. As it is we disable a small bit of ffmpeg so we maintain compitibility with nougat due to liblzma incompatibility.  using libz is far more common. 
2. size reasons its not really neccesary to add libz.so if its in the ndk.

**Comment by tomty89** [comment]
I don't think 2 is valid. I doubt that `libz.so` is the only library that exists in ndk / universally in Android, and I am quite sure it wouldn't be the biggest among them either. Or are there other libraries that we make use of the ones in `/system` that I wasn't aware of? (I mean, apart from libc or so that I assume to be special case)

As for compatibility, doesn't it help improve it since libz in /system can be of different versions in different Android builds? While if we ship one the Termux programs can always stick to the same one (not even necessarily needs to be the latest).

As for linking issue, I have no idea. It does seem to me that stuff can be a bit mad on that. I just wonder if it's really the case for libz though (like how is it relevant to the liblzma/mpv/ffmpeg issue? Linking problems mostly occur with compression libraries?)

**Comment by its-pointless** [comment]
"libz in /system can be of different versions in different Android builds"
no. if its in the ndk they keep stable generally.  libz is an officially supported api.

**Comment by tomty89** [comment]
All I wonder is what so special about zlib in this case.
```
$ dpkg -L ndk-sysroot | grep '\.pc'
/data/data/com.termux/files/usr/lib/pkgconfig/zlib.pc
$
```

**Comment by fornwall** [comment]
@tomty89 I guess the question is what we gain by packaging zlib ourselves instead of using the system library?

As said, it's a stable API exposed by Android to apps so it is portable. One thing we would gain is a newer zlib version than 1.2.8, is that what you are after here?

I'm not opposed to the idea of packaging zlib ourselves, I just want to understand the desired benefits.

**Comment by tomty89** [comment]
@fornwall Well it was more of curiosity. Just wondered *what made you not* building it from the first place.

I am fine with it though I guess. I suppose it would be kind of a tremendous work to change now so I am not really going after that.

**Comment by kaeptmblaubaer1000** [comment]
The benefits could e.g. be that CMake detects it.

**Comment by tomty89** [comment]
Maybe we should have a zlib.so symlink shipped in ndk-sysroot like we do for libpthread and librt

**Comment by tomty89** [comment]
Reopening as we are moving forward to a new binary repo set and adopting DT_RUNPATH. @fornwall @xeffyr

**Comment by xeffyr** [comment]
Closing since zlib is actually in progress for Android 7 and for Android 5 PR is available.
