### ISSUE TITLE
apt vs pkg

### ISSUE THREAD

**Issue by lukeeey** [termux/termux-packages#2151]
I personally don't think it is a good idea to promote `pkg` over the standard `apt`. I know that pkg is a wrapper for apt to help make it easier to use, but new users who have never used the Linux terminal before might see pkg as being the norm and they won't even know about apt, so if they move on to *actual* Linux, they are gonna have a problem.

**Comment by Systemad** [comment]
You can use apt instead of pkg if you want. As far as I'm aware, it does the same thing.

**Comment by tomty89** [comment]
Well it's not like people who "plan on moving from Termux to *actual* Linux" cannot stick to apt alone. Also apt is not like a universal standard anyway, there are yum/dnf in the redhat world and the lovely pacman from Arch, only to name a few other package managers.

**Comment by tomty89** [comment]
Also `pkg` is a real short shell script that covers only a subset of switches in apt, you *can't* even stick to it if you want to be manipulative enough to your Termux installation.

**Comment by GitToTheHub** [comment]
I was wondering, what's the difference about "pkg" and "apt" and was coming to this post (I'm new to Linux). I don't understand why pkg is the standard in Termux because it's only a wrapper for apt?

I was confused when i tried to uninstall a package with following:

$ pkg uninstall vim-python
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  diffutils gdbm libcrypt libffi libsqlite libutil
  ncurses-ui-libs python vim-runtime
Use 'apt autoremove' to remove them.
..

It says "use 'apt autoremove'" to remove unused packages and i was trying like something:
$ pkg uninstall vim-python apt autoremove
And
$ pkg uninstall vim-python autoremove
And
$ pkg autoremove
Nothing helped until i tried simply 'apt autoremove' and it worked.

Maybe it would be really better to use apt as default :)

**Comment by xeffyr** [comment]
> what's the difference about "pkg" and "apt"

pkg is a wrapper around apt.
We added it because people frequently forget to run "apt update" before installing packages.

**Comment by GitToTheHub** [comment]
Ok and "apt update" updates "apt" itself i presume?

**Comment by xeffyr** [comment]
> update (apt-get(8))
           update is used to download package information from all configured sources. Other
           commands operate on this data to e.g. perform package upgrades or search in and
           display details about all packages available for installation.

**Comment by GitToTheHub** [comment]
Ah ok, so "apt update" does not upgrade any software, it's only to gather informations about the packages and there dependencies. Thank you :)

**Comment by Ro-del-sys** [comment]
In my first time i tried to type the cmatrix command i know it's the most simple command but it took to me so much time bcz i used pkg he didn't give nothing as outcome but when i use apt-get he worked
