### ISSUE TITLE
alpine: why isn't pipe working?

### ISSUE THREAD

**Issue by Quasic** [termux/termux-packages#2164]
`````
ALPINE 2.21   PIPE MESSAGE                                   Line 2 of 2 ALL

Can't exec /data/data/com.termux/files/usr/bin/applets/cat
Reason: No such file or directory
`````

**Comment by Quasic** [comment]
I haven't used alpine in a while. I will try with the latest version, sometime, to see if this is still an issue.

**Comment by xtkoba** [comment]
I suppose the situation has been pretty much changed since the deprecation of `busybox` (https://github.com/termux/termux-packages/commit/17d5dfc0a607176c8cdbe9a59f0091f8ea89dfb0), by which `$PREFIX/bin/applets` had been populated before.

Now the `cat` command is provided by the `coreutils` package, which `alpine` should depend on.
