### ISSUE TITLE
Use of pkg program

### ISSUE THREAD

**Issue by Wetitpig** [termux/termux-packages#2177]
The `pkg` program is just a wrapper for `apt` only, in similar ease to use. Why do we need this program, but not directly invoking `apt`? Thanks!

**Comment by Neo-Oli** [comment]
Because in Debian* `apt update` is run as a cron job. But unless explicitly started by the user Termux doesn't call `apt update` at all. All `pkg` commands run `apt update` before installing anything. Before we had this we had daily issues and people in IRC stating that such and such package wasn't found, because they never ran `apt update`. That is all. As a more experienced user there is nothing to loose from not using `pkg` at all and calling `apt install` yourself (judging yourself when to run `apt update`).

**Comment by Wetitpig** [comment]
sorry saw that someone just asked this question a few days ago. if that is the case shall we use symlinking rather than a short script?

**Comment by Wetitpig** [comment]
Ok thanks
