### ISSUE TITLE
[Bug]: can i add the path to the Buildozer executable to the system path

### ISSUE THREAD

**Issue by Kivypls** [termux/termux-packages#21814]
### Problem description

can i add the path to the Buildozer executable to the system path using the cmd command  
setx PATH %PATH%
 , is it really possible to do this? Is it written that it is dangerous or is it wrong? Somewhere he writes safely, and somewhere he doesn't

### What steps will reproduce the bug?

![Снимок экрана 2024-10-14 190744 translated](https://github.com/user-attachments/assets/0ea1acc4-00a4-443a-a967-e8e3b9dc2e8b)
Is it because of this error that I do it (buildozer is installed) or do I not need to do it?

### System information

```shell
VS Studio / Python
```

**Comment by twaik** [comment]
1. Termux does not not package powershell.  You should contact developer of the package/script you used to install this.
2. Termux does not package visual studio. In the case if you use vscode from tur-repo you should open issue in [tur](https://github.com/termux-user-repository/tur/issues). Otherwise it is 3rd-party program we offer zero support for.
3. In the case if you use proot-distro we offer zero support for it, it is completely under your responsibility.
