### ISSUE TITLE
[Bug]: Update hilbish shell

### ISSUE THREAD

**Issue by xronin01** [termux/termux-packages#22001]
### Problem description

The hilbish package is outdated, please update to v2.3.2
https://github.com/Rosettea/Hilbish/releases

### What steps will reproduce the bug?

.

### System information

```shell
.
```

**Comment by twaik** [comment]
Thank you for your notification. However, there is no need to inform us when a new version of a program is released. We are aware of new versions as soon as they become available. Unfortunately, due to limited personnel, we are unable to immediately update all available packages. We prioritize updates based on several factors, but we appreciate your understanding and patience.

Additionally, we are currently unable to compile the project due to an issue with the build system. Until this problem is resolved, we will not be able to update the package.
https://github.com/arnodel/golua/issues/105

**Comment by twaik** [comment]
You can download and install artifacts from https://github.com/termux/termux-packages/actions/runs/11580324966. Please, report if it works fine.

**Comment by xronin01** [comment]
It works, thank you 👍

**Comment by xronin01** [comment]
now resolved 
https://github.com/arnodel/golua/pull/106
