### ISSUE TITLE
Combining characters not display properly in tmux

### ISSUE THREAD

**Issue by agguser** [termux/termux-packages#224]
In bash/vim, outside tmux, typing `echo ดีที่สุด` (which consists of characters: e c h o ด ี ท ี ่ ส ุ ด) works properly.
But when inside tmux, it becomes `echo ดี ที ่ สุ ด` (notice the spaces added)!
How can this be solved?

**Comment by fornwall** [comment]
Thanks! This should be fixed in the new `2.2-1` version of the tmux package - update to it with

    apt update && apt upgrade

After updating, be sure to exit all tmux sessions so that tmux restarts before trying again (running `tmux attach` should say `no current session`).

Re-open the issue if the problem remains after updating!

**Comment by agguser** [comment]
It works! Thanks a lot!
