### ISSUE TITLE
package request: Lazyread

### ISSUE THREAD

**Issue by buribu** [termux/termux-packages#2245]
Lazyread auto-scrolls files or command output to the screen.

It features different scroll modes, configurable scroll speed and colors, the ability to pause, the ability to search, and more. It can render text, HTML, PDF, gzip, tar, zip, ar, bzip2, MS-Word, nroff (man pages), binary executables, directories, .deb, .so, .rpm, piped output from other programs, and more.

http://lazyread.sourceforge.net/

![unabomberlazyreadlesspipepdf](https://user-images.githubusercontent.com/782908/37374512-39faa854-26fa-11e8-9d38-818dadb62107.jpeg)

**Comment by sdrausty** [comment]
@buribu doesn't `pip install lazyreader` work for you?
```
$ pip install lazyreader
Collecting lazyreader
  Downloading lazyreader-1.0.1.tar.gz
Installing collected packages: lazyreader
  Running setup.py install for lazyreader ... done
Successfully installed lazyreader-1.0.1
```

**Comment by buribu** [comment]
@sdrausty It works, but they are similar names for different projects. My request is about giving more support to common file formats. The image I posted is the lesspipe that accompanies the lazyread showing the text content of a pdf. Thing that the python module lazyreader can not do.

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install lazyread
```

**Comment by TomJo2000** [comment]
- Slated to be removed in #25113
This package has not seen any development since 2003 and falls short of the [current packaging criteria](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).
`less`/`lesspipe` should provide an adequate (maintained) replacement.

If this package is still being actively used by some users it can instead to moved to the [TUR](https://github.com/termux-user-repository/tur).
