### ISSUE TITLE
"droppping 5.0 support in the near future" ?

### ISSUE THREAD

**Issue by bukzor** [termux/termux-packages#2256]
Branched from https://github.com/termux/termux-packages/issues/2071.

>  @fornwall commented on Feb 14 
> Note that RUNPATH requires android 7.0 or later, while  Termux currently supports Android 5.0 or later. I'm thinking of  droppping 5.0 support in the near future, while 6.0 will be supported  longer, so we cannot do the LD_LIBRARY_PATH-> RUNPATH transition just  yet.

> @sdrausty commented 13 hours ago 
>  Why are you thinking about this?  What is the motivation?

**Comment by fornwall** [comment]
Thanks! In general, the reason for dropping old platform support is:

- Diminishing returns (fewer and fewer users are running old platform versions as devices are upgraded or replaced).
- More and more people are using newer platform versions.
- It makes more sense to focus on newer platform and allow using features from those.
- It's easier to develop for if one does not have to test on and design around limitations in old platform versions.

**Comment by bukzor** [comment]
What are some of the limitations of Lollipop that currently constrain the design?

**Comment by sdrausty** [comment]
>  RUNPATH requires android 7.0 or later, 

@fornwall can Termux use similar methods to [TermuxArch](https://sdrausty.github.io/TermuxArch/) in as far as detecting its' environment and adjust its' components accordingly for install?  

Another words, a modular Termux that detects Android 7+ and either uses RUNPATH or not.  Good luck in sorting this out, and keep up the great work!  

The enormous market share of Android 5 reflects my opinion about dropping Android 5 support.  There are about a dozen Android 5 devices at my disposal.  How about you?   Excluding such a great market of users with their devices does not appear to be a good future course for Termux. Do you agree? 

Some of these older Android 5 devices are headed for a very interesting project.  It has to do with rendering animations from scenes writen in computer code.  Termux tested very well in the cold month of January 2018.  It took days to produce the more complex 2D renderings at [TermuxPovray](https://sdrausty.github.io/TermuxPovray/) at 4K and 8K resolutions. Older devices are preferred for projects that take days and weeks to complete, since such a device should be monotasked for best results.

![Created in TermuxArch](https://sdrausty.github.io/TermuxPovray/docs/files/tulips/tulips512.png)

Also, a potential user might not want to install any apps on their newest device.  Such a user might be tempted to play with Termux on an older model device.  **The potential new user base on older model devices is tremendous!  Is it sound judgement to exclude such an overwhelming amount of potential Termux users who might want to tinker with Termux on older devices?**  All this issue wants for resolution is programming expertise.  Do you agree?

**Comment by sdrausty** [comment]
I do have an Android KitKat device awaiting Termux:
```
$ gplaycli --search Termux
Title                          Creator           Size      Downloads              Last Update  AppID                             Version  Rating
Termux                         Fredrik Fornwall  217.83KB  1,000,000+ downloads   25 Jan 2018  com.termux                        60       4.72
Termux:API                     Fredrik Fornwall  69.94KB   50,000+ downloads      4 Feb 2018   com.termux.api                    16       4.73
Hacker's Keyboard              Klaus Weidner     1.20MB    1,000,000+ downloads   10 Dec 2016  org.pocketworkstation.pckeyboard  1039003  4.44
Terminal Emulator for Android  Jack Palevich     551.44KB  10,000,000+ downloads  15 Apr 2015  jackpal.androidterm               71       4.40
Terminal IDE                   Spartacus Rex     47.56MB   1,000,000+ downloads   3 Mar 2013   com.spartacusrex.spartacuside     102      4.35
```
It does run Terminal Emulator for Android well.  Maybe a stripped down modular version of a conforming to Android version Termux for Android 4 will also become real.  This Android versioning topic is repeated in numerous issues.  A modular Termux that conformes to its' environment should be able to accommodate Android versions galore, as many as desired.  It this idea doable in a fairly simple way?

**Comment by its-pointless** [comment]
There is a way around some of the constraints. The ndk static libs have been updated. So missing math stuff can be added from the libm.a static lib.
Im guessing some of the libc stuff can be added from libc.a.

**Comment by Hax4us** [comment]
I have also 5.0 ... Don't drop support please And there are many KitKats also , waiting for termux :) 
And I know its time for 7.0 , but trust me there are many users including me with 5.0 :)

**Comment by sdrausty** [comment]
Inclusiveness dictated through computer programming expertise; It appears 'the community' demands this time and again; Can this be accomplished via Termux?

**Comment by tomty89** [comment]
I think the appropriate time to drop lollipop support in Termux might the time Google drops theirs. That said, only if it is affordable to wait until then.
