### ISSUE TITLE
can't compile berkeley-db with cxx support

### ISSUE THREAD

**Issue by bukzor** [termux/termux-packages#2273]
This should reproduce the issue:

```
pkg install make clang proot
wget http://download.oracle.com/berkeley-db/db-6.2.32.tar.gz
tar xvf db-6.2.32.tar.gz
cd db-6.2.32/build_unix
termux-chroot ../dist/configure --enable-cxx
termux-chroot make -j30
```

Once the build has run to error, you can reproduce quickly by running the command directly:
```
bash-4.4$ g++ -c -I. -I../src -D_GNU_SOURCE -D_REENTRANT -O3 ../lang/cxx/cxx_channel.cpp  -fPIC -DPIC -o .libs/cxx_channel.o
In file included from ../lang/cxx/cxx_channel.cpp:13:
In file included from ./db_cxx.h:55:
In file included from /data/data/com.termux/files/usr/bin/../include/c++/v1/iostream:38:
In file included from /data/data/com.termux/files/usr/bin/../include/c++/v1/ios:216:
In file included from /data/data/com.termux/files/usr/bin/../include/c++/v1/__locale:15:
In file included from /data/data/com.termux/files/usr/bin/../include/c++/v1/string:470:
In file included from /data/data/com.termux/files/usr/bin/../include/c++/v1/string_view:169:
In file included from /data/data/com.termux/files/usr/bin/../include/c++/v1/__string:56:
In file included from /data/data/com.termux/files/usr/bin/../include/c++/v1/algorithm:643:
In file included from /data/data/com.termux/files/usr/bin/../include/c++/v1/memory:658:
/data/data/com.termux/files/usr/bin/../include/c++/v1/atomic:1184:13: error: expected unqualified-id
atomic_init(volatile atomic<_Tp>* __o, _Tp __d) _NOEXCEPT
            ^
```

I've tried changing the standards version (e.g. `-std=c++98`) and tried changing the stdlib (`--stdlib=libstdc++`). The standards version has no effect and the libstdc++ seems to be missing entirely.

The compile seems to be sad about `/usr/include/c++/v1/atomic` which is from the `ndk-stl` package.

**Comment by Grimler91** [comment]
libstdc++ is in `/system/lib`. 
I wouldn't try compiling it in chroot, 

That being said you're probably better off cross compiling it from ubuntu or the provided docker image. Just adding --enable-cxx should hopefully not cause issues.

I'll close this as it, arguably, is off topic for this github repo. The google+ group, gitter or the mailing list might be more appropriate. 
Helping with every build error just because they happen in termux is out of our scope and ability.

**Comment by bukzor** [comment]
Thanks @Grimler91. That's totally reasonable, and I'll follow up on your suggestions.

**Comment by tomty89** [comment]
@bukzor I can successfully compile it by using the libstdc++ headers from the NDK.

With the PR above:
```
$ export CPLUS_INCLUDE_PATH=$PREFIX/include/c++/4.9/
```

It didn't require me to link against libstdc++, but with `-stdlib=libstdc++` it builds as well.

```
$ ../dist/configure CXXFLAGS='-stdlib=libstdc++' --prefix=$PREFIX/local --enable-cxx
```

With that the libdb_cxx libraries were linked against libstdc++.so according to `ldd`, otherwise it shows linkage to `libc++_shared.so`.

Didn't test whether any of the builds actually works though.

**Comment by bukzor** [comment]
@tomty89 That's after your fix in #2276 yes? You were able to reproduce the problem without it?

**Comment by tomty89** [comment]
Yes, apparently Berkeley DB does not support llvm libc++ headers. (Not sure if there's a switch or something like that to make it do so though.)

**Comment by bukzor** [comment]
There's a discussion on the oracle forums from many months ago. The maintainer is aware of the problem and the solution, but unmotivated to improve it.

Thanks for the hand! @tomty89 What's the best way for me to ask for help with this *type* of issue? Or, do you monitor anything other than termux-packages issues?

**Comment by tomty89** [comment]
Well I guess before you make any attempt to make it work, you'll have to make sure your attempt actually targets the problem.

You actually managed to identify that it's some header problem and the headers are shipped in `ndk-stl`, so instead of having a rush to try to switch to an alternative, you should think about whether you are switching the right thing, and whether there's actually such alternative available in the current system for you to switch. In this case, obviously the way is to take a look at the build script of `ndk-stl` here and browse its source, the Android NDK, for a bit (with `find`, for example). Questions (if any) for these parts should be fine here.

And the rest are just generic building knowledge (like the `CFLAGS` / `CPLUS_INCLUDE_PATH` stuff).

**Comment by fornwall** [comment]
Note that clang and libc++ is the only supported alternative on Android - gnustl (libstdc++) is going to be removed from NDK r18.

@bukzor This thread: https://community.oracle.com/thread/3952592 links to a patch to make berkeley-db C++ support work with libc++. Does that one work for you?

**Comment by bukzor** [comment]
Good catch. I'll try that. Do you know why this doesn't happen on my Ubuntu? Or: Do you have any clues as to how would I generate a reproduction outside of Android?
