### ISSUE TITLE
How to build ffmpeg

### ISSUE THREAD

**Issue by Karendaa** [termux/termux-packages#2398]
I'm just a newbie to this.Is it possible to build ffmpeg on device rather than on desktop?

**Comment by Karendaa** [comment]
Curious maybe?I have pc with windows installed and the ffmpeg full featured,I mainly just use termux's ffmpeg to extract audio,cut video,concatenate video,and maybe encode short video,and leave the heavy one to my pc,and yeah there are specific format .mlv that termux's ffmpeg give me error.And I know one can build on pc but on device that's new to me so yeah i like to try/learn.

**Comment by Grimler91** [comment]
Alright. Building on device isn't that different from building on a pc with gnu/linux installed, so you can follow the ffmpeg linux compilation steps: https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu. Some package names might be a bit different but otherwise it's pretty straight forward.

**Comment by Karendaa** [comment]
Ah okay,really thx for the answer,will close issue

**Comment by 78Alpha** [comment]
I know this is marked as closed, but I myself have tried to build ffmpeg from a terminal on android, the process halts because, when the keyboard is called, it "reduces" the terminal's resolution, so on one of the configuration steps it stops as it needs the terminal to be a certain size, meaning you can't proceed. Trying to use an xserver (xsdl) to pass that one step isn't very easy, needs a virtual keyboard and the commands preset...

My personal use is that my phone is faster at encoding than my pc (2 core laptop vs 8 core phone, and all cores can be enabled at once with slight risk), trying to encode to h.265.

**Comment by dickyharper** [comment]
@Grimler91 
Hello
Can I download a specific version of ffmpeg?  If yes, how?
