### ISSUE TITLE
wireshark install error in termux

### ISSUE THREAD

**Issue by NavLock** [termux/termux-packages#2581]
E: Failed to fetch https://termux.xeffyr.ml/dists/extra/x11/binary-aarch64/xtrans_1.3.5-1_aarch64.deb  Writing more data than expected (35860 > 35648)
   Hashes of expected file:
    - SHA512:c4e70d12417938ecdb7a93198e671ef6368628984031f77a71a0e800c5602b5ae02238ac0e88d5f829cab2310aa82facc25d4ef3da0660f388562fe203239c9c
    - SHA256:40b24b535b621e4b77e563a92b09889003410882106acca3e00322d4221b0917
    - SHA1:8684cf7008ac1e67f463a033be0cb2bb98e617c2 [weak]
    - MD5Sum:a66b743f5e35e479e544a8cdbc581cbc [weak]
    - Filesize:35648 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by remo7777** [comment]
try `apt-get update --fix-missing` then `apt update` then install your wireshark pkg

**Comment by xeffyr** [comment]
@NavLock Try again `apt update`. This error may appear only when package lists are rebuilt (e.g. when new packages to added to termux-extra-packages or automatic script updates mirror of https://termux.net).
![screenshot_20180626-094930_termux](https://user-images.githubusercontent.com/25881154/41894085-81b26c26-7926-11e8-937f-f2155146416e.jpg)

And since this is my repository, open issues here: https://github.com/xeffyr/termux-extra-packages/issues
