### ISSUE TITLE
[Bug] Wrong return value of command-not-found

### ISSUE THREAD

**Issue by tippl** [termux/termux-packages#2655]
This is a weird one. The package in git has correct return value (127), but on phone it only returns 0 for me.
![screenshot_20180715-101336](https://user-images.githubusercontent.com/2827500/42731984-88211e6c-8818-11e8-938d-e0775ae9978e.png)

as opposed to this on my pc
![screenshot_20180715_101548](https://user-images.githubusercontent.com/2827500/42731954-222fda76-8818-11e8-923f-434fe526e5f7.png)

This breaks some scripts, since when there is a condition using a not installed package it returns 0 and passes.

**Comment by tomty89** [comment]
https://github.com/termux/termux-packages/blob/master/packages/zsh/etc-zshrc#L3

**Comment by tippl** [comment]
Right, that makes a lot more sense. I was only looking at the package itself.

**Comment by fornwall** [comment]
The commit 8927f8fbc66ae5ac57ee875aea556265cfc0e8ce which introduced the `return 0` here referenced http://zsh.sourceforge.net/Doc/Release/Command-Execution.html:

> The function should return status zero if it successfully handled the command, or non-zero status if it failed. In the latter case the standard handling is applied: ‘command not found’ is printed to standard error and the shell exits with status 127.

If not returning 0, we get double error output - both from command-not-found and from zsh, as noted in https://github.com/termux/termux-packages/pull/566:

```
The program 'sl' is not installed. Install it by executing:
 apt install sl
zsh: command not found: sl
```

Here the first two lines are from our command-not-found program and the last is from zsh due to `command_not_found_handler()` not returning 0.

Perhaps we could change command_not_found_handler() to exit with an error exit value directly, with `exit 127` if command-not-found fails?

**Comment by tomty89** [comment]
@fornwall Apparently that has changed at some point:

> If no external command is found but a function command_not_found_handler exists the shell executes this function with all command line arguments. The return status of the function becomes the status of the command. If the function wishes to mimic the behaviour of the shell when the command is not found, it should print the message ‘command not found: cmd’ to standard error and return status 127.

```
% ps
PID   USER     TIME  COMMAND
 7936 u0_a312   0:00 -zsh
 7965 u0_a312   0:00 ps
% cat ../usr/etc/zshrc
command_not_found_handler() {
        /data/data/com.termux/files/usr/libexec/termux/command-not-found $1
}

PS1='%# '
% sl
The program 'sl' is not installed. Install it by executing:
 pkg install sl
%
```

**Comment by fornwall** [comment]
@tomty89 Ah, that makes sense. I guess we can remove the ` || exit $?` part?

**Comment by fornwall** [comment]
@tomty89 I've updated it in 6d0bb9fc31c9b1a2966ebb21429fb63f30fed03c now, thanks!
