### ISSUE TITLE
wget refuse to download 100 GB file

### ISSUE THREAD

**Issue by divinity76** [termux/termux-packages#2692]
Running the following command:

wget http://rfiles.ratma.net/100gb.sparse.zip -O /dev/null

Is supposed to download the 100GB file in the url, but instead spew the error: 
Connecting to rfiles.ratma.net (62.210.139.73:80)
wget: content-length 107374182400 is garbage

(Btw, sorry if this is already a known issue, I'm on a phone with a small screen, and it was very unpleasant to search through the bug tracker on this screen)

**Comment by divinity76** [comment]
To anyone looking for a quick workaround: curl is not affected.

**Comment by Grimler91** [comment]
All the busybox programs are slimmed down to save space and often lack different features. It seems busybox' wget can't handle large files for some reason, but it's not really worth investigating since it works in the full wget package. 

Might be related to our particular busybox configuration, or just a shortcoming of busybox' wget on some of our arches.
