### ISSUE TITLE
Cannot use mysql commands

### ISSUE THREAD

**Issue by MathieuPIN** [termux/termux-packages#2822]
Hi !
I installed mariadb with Termux but when I try to use a "mysql" command I got this error : 
mysql: Can't read dir of '/data/data/com.termux/files/usr/etc/my.cnf.d' (Errcode: 2 "No such file or directory")
Fatal error in defaults handling. Program aborted

Can you help me to fix it pls ?

**Comment by xeffyr** [comment]
> I got this error :
mysql: Can't read dir of '/data/data/com.termux/files/usr/etc/my.cnf.d' (Errcode: 2 "No such file or directory")

Is it difficult to create missing directory ?

Actually, since `etc/my.cnf.d` does not exist, your DB is not initialized. Execute these commands for initializing the DB (after creating needed dir, of course):
```
mysql_install_db
mysql_secure_installation
```
