### ISSUE TITLE
[Package request] add bat

### ISSUE THREAD

**Issue by luisdavim** [termux/termux-packages#2842]
They even provide arm debian packages:
https://github.com/sharkdp/bat/releases

**Comment by ExtremeNerd** [comment]
Ask them to provide statically linked binaries instead. Those should work everywhere.

**Comment by T4P4N** [comment]
now, It's availble via apt
```
apt install bat
```

**Comment by projectextremum** [comment]
```
$ bat practice/c/writetoapipe.c
less: unrecognized option `--RAW-CONTROL-CHARS'                         
```

Then it shows busybox help screen for `less` binary.

It appears like `less` package is a dependency to `bat`.

After running `pkg install less`, it appears to work properly.

**Comment by sharkdp** [comment]
Yes, `less` should *probably* be listed as a dependency.

It is not strictly required as `bat` allows to turn off paging (`--paging=never`) or to use another pager (`export BAT_PAGER="..."`). But `less` will be used by default, if it is available.

Unfortunately, `bat` can not detect whether `less` is the original version or the busybox replacement. Otherwise, we could default to "no pager" if the busybox replacement would be detected.
