### ISSUE TITLE
Build Android Studio Project With Termux

### ISSUE THREAD

**Issue by mojtabamarashee** [termux/termux-packages#2864]
Is it possible to build existing android studio project using termux and make apk file?

**Comment by xeffyr** [comment]
> studio project
> using termux and make apk file

@mojtabamarashee Not possible. We don't have properly working JDK and `possible` never will have (unless something changes in OpenJDK's source).

Yesterday, I completely dropped experimental OpenJDK build from support (in https://github.com/xeffyr/termux-extra-packages) as GCC was removed from NDK after update to r18. It seems that OpenJDK can't be built using NDK's clang, even if can - it is not working properly anyway. See https://wiki.termux.com/wiki/Development_Environments#OpenJDK.

**Comment by mojtabamarashee** [comment]
thanks

**Comment by its-pointless** [comment]
I can still build it. I just use gcc-8 instead.

**Comment by xeffyr** [comment]
@its-pointless Yes, with GCC it builds but with clang no.

**Comment by Bakaika** [comment]
Got Android Studio to work in an Ubuntu proot. (XServer XSDL)
![screenshot_20181005-152325_xserver xsdl](https://user-images.githubusercontent.com/41478984/46521632-c6369580-c8b2-11e8-9efd-f441f44e099d.jpg)

It is slow though (no hardware acceleration). And on non-x86_64 devices doesn't function correctly, due to the Android SDK being x86_64 only.
You can use QEMU infront of everything however. You have to manual build QEMU otherwise you''ll get warnings about requested features.

**Comment by xeffyr** [comment]
> You have to manual build QEMU otherwise you''ll get warnings about requested features.

@Bakaika What's wrong with QEMU ?

**Comment by Bakaika** [comment]
![screenshot_20181005-194921_termux](https://user-images.githubusercontent.com/41478984/46533613-d3b24680-c8d7-11e8-9e90-2a7e332ad024.jpg)
QEMU user from Ubuntu's repos.

**Comment by xeffyr** [comment]
> QEMU user from Ubuntu's repos.

Oh, I was think that there is something with [qemu from x11-packages](https://github.com/termux/x11-packages/tree/master/packages/qemu-system-x86_64).

**Comment by Bakaika** [comment]
lol
