### ISSUE TITLE
keep getting ”integer overflow” with many termux apps

### ISSUE THREAD

**Issue by fornwall** [termux/termux-packages#287]
_From @smemsh on May 24, 2016 16:41_

cannot figure out what is generating this error, is it specific to termux, is a warning or error.  however execution appears to halt:
```
$ mosh myserver
internal error: integer overflow 2147483647 * 4 prevented
mosh: Can't count colors: 22

$ su -l; id -un
internal error: integer overflow 2147483647 * 4 prevented
u0_a39

$ uname -a
Linux localhost 3.4.42-g7f4d949-00002-gb042f2b #1 SMP PREEMPT Tue Jan 6 10:06:17 CST 2015 armv7l Android
```

same issue appears to prevent `pip install pycrypto` from successfully running `configure`:
```
[...snip]
creating build/lib.linux-armv7l-3.5/Crypto/Signature
    copying lib/Crypto/Signature/__init__.py -> build/lib.linux-armv7l-3.5/Crypto/Signature
    copying lib/Crypto/Signature/PKCS1_v1_5.py -> build/lib.linux-armv7l-3.5/Crypto/Signature
    copying lib/Crypto/Signature/PKCS1_PSS.py -> build/lib.linux-armv7l-3.5/Crypto/Signature
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    running build_ext
    running build_configure
    internal error: integer overflow 2147483647 * 4 prevented
    internal error: integer overflow 2147483647 * 4 prevented
    error: [Errno 2] No such file or directory: 'src/config.h'
```
I have a Moto G 2014 (”titan” board model) with a stock ROM.  I traced the processes doing the write(2) of the integer overflow error and it's indeed the actual processes themselves (such as `mosh` above after the shell script wrapper has `execve()`'d `mosh` itself), so it's almost like it's coming from libc or something.  I cannot find these error substrings anywhere in Google searches so I am very puzzled where this is coming from, but unfortunately it makes termux rather unusable.

_Copied from original issue: termux/termux-app#97_

**Comment by fornwall** [comment]
_From @smemsh on May 24, 2016 16:42_

P.S. I will be happy to know if anyone else can successfully complete `pip install pycrypto`.

**Comment by fornwall** [comment]
Interesting! Haven't seen that one before, will look around. Let me know if you (or anyone else) finds out anything more here!

**Comment by smemsh** [comment]
I figured this out; the problem was on my end, kind of bizarre set of circumstances:

After looking in more detail at the `mosh` traces, I discovered that the `write(2)` syscall generating this error message was actually coming out of `/system/bin/sh`, not `mosh-client` as I originally had thought.  `mosh` itself is a perl script which calls (in perl) `exec mosh-client <args> ...` which does `execve("/system/bin/sh", ["sh", "-c", "mosh-client -c"] ... [environment])` and this was the process the error string was coming out of, i.e. the Android system shell.  My guess is that the other programs (`su` and `configure` via `pip` above) with this error were either using `system(3)`, invoking the shell manually, or something else which ends up calling `/system/bin/sh`.

Now, where I found the error string, after searching all `termux` files, user installed and system files, was actually in `/system/xbin/sugote-mksh`:
```
$ strings -a /system/xbin/sugote-mksh | grep 'integer.overflow.*prevented'
integer overflow %zu %c %zu prevented
```
This must be part of the magic of how SuperSU/Superuser work on Android, by intercepting calls to make shells... I remember reading something about it having to run before the Android system zygote spawned to get the right SELinux context, and calling into it from shells after that... don't know how that works to be honest, but basically, this is happening because my system is rooted.

Now, why was it getting that error? Turns out (after bisecting shell init) I had `$HISTSIZE` set in my shell init to `$(($((2**31)) - 1))` which I did because I wanted it to be effectively unlimited.  This was never a problem for me on glibc systems (even low memory ones), but Android+Bionic+SuperSU versions of `sh`/`libc` must do something differently... their `malloc()` might preallocate or pre-zero pages or something, I don't know without digging into more code.  It might also be that the Android system shell really allocates the memory, whereas bash/dash only grow it as it's written to.

I don't have to figure that out because I found out that just setting `$HISTSIZE` empty is the right way to make it unlimited in `bash` (which is what I care about), not by setting it huge.  Which then makes the error go away! Then my `configure` proceeds in the `pip install pycrypto`, and the build finishes.

I can also successfully `su` and run `mosh` as well now.  So this is not a `termux` issue at all.

Highly doubt anyone else will see this (even those on rooted phones) because it's probably very rare for people to be setting `$HISTSIZE` to some huge number.  But at least it's searchable now in case someone does :-)

**Comment by smemsh** [comment]
P.S.: the problem with moving the issues between repos is (1) no attribution in issue metadata (just a string in the comments) and (2) I don't own it, so I cannot close it.  So they don't show up in my list of open issues for example. (Github should really provide a way to reparent an issue...)

**Comment by smemsh** [comment]
hm, I see you don't use the perl wrapper in `termux`, I was referencing my own local copy on the laptop and didn't know about the custom binary you were using.

Well anyways, I did trace it on my phone, so everything else I said was valid except how `/system/bin/sh` got invoked (obviously, not via perl, but instead by your `mosh` wrapper replacement).

**Comment by fornwall** [comment]
Thanks for the interesting write-up!

Generally we want to avoid calling `/system/bin/sh` from Termux, since that system binary varies between devices (it's not a stable target) and may not work due to `LD_LIBRARY_PATH` being set (a shared library in Termux may clash with one that `/system/bin/sh` links to).

I've now updated both `mosh` and `openssh` to instead call the Termux-supplied `$PREFIX/bin/sh` (which is just `dash`, the same shell as on Debian&Ubuntu).

**Comment by smemsh** [comment]
incidentally I did also have to set `$CONFIG_SHELL` to the `termux` one for the build to succeed because otherwise it kept stopping on missing `/bin/sh` which I think may be needed often with autoconf run inside `termux`.

**Comment by smemsh** [comment]
btw, it might be that using `/system/bin/sh` is required to escalate privs on rooted phone because that's how SuperSU et al hook in (maybe).  So switching out the shell might break some usage scenarios (like running a root sshd) and maybe make it impossible for `sudo` to ever work.  not sure about this, just something to consider.

on my Android 5 only libc is linked dynamically into `/system/bin/sh`

**Comment by fornwall** [comment]
Sure - `/system/bin/sh` will still be there for those who need it (`sudo`, etc), but for code used in most normal Termux packages it's better to call the `$PREFIX/bin/sh`.
