### ISSUE TITLE
Net::SSLeay incomplete BN_GENCB error

### ISSUE THREAD

**Issue by b3nsh4** [termux/termux-packages#2941]
Dependencies installed
> Make
> Clang
> libclang 
> " -dev
> Openssl
> "-tool
> "$-dev
> ccrypt
> perl

Current error
```
cpan install Net::SSLeay::Handle
Loading internal logger. Log::Log4perl recommended for better logging
Reading '/data/data/com.termux/files/home/.cpan/Metadata'
  Database was generated on Sun, 07 Oct 2018 08:54:24 GMT
Running install for module 'Net::SSLeay::Handle'
Checksum for /data/data/com.termux/files/home/.cpan/sources/authors/id/M/MI/MIKEM/Net-SSLeay-1.85.tar.gz ok
'YAML' not installed, will not store persistent state
Configuring M/MI/MIKEM/Net-SSLeay-1.85.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Warning: Guessing NAME [Net-SSLeay] from current directory name.
*** Found OpenSSL-1.1.1 installed in .
*** That's newer than what this module was tested with
    You should consider checking if there is a newer release of this module
    available. Everything will probably work OK, though.
*** Be sure to use the same compiler and options to compile your OpenSSL, perl,
    and Net::SSLeay. Mixing and matching compilers is not supported.
Do you want to run external tests?
These tests *will* *fail* if you do not have network connectivity. [n] n
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Net::SSLeay
Writing MYMETA.yml and MYMETA.json
  MIKEM/Net-SSLeay-1.85.tar.gz
  /data/data/com.termux/files/usr/bin/perl Makefile.PL -- OK
Running make for M/MI/MIKEM/Net-SSLeay-1.85.tar.gz
cp lib/Net/SSLeay.pm blib/lib/Net/SSLeay.pm
AutoSplitting blib/lib/Net/SSLeay.pm (blib/lib/auto/Net/SSLeay)
blib/lib/Net/SSLeay.pm: some names are not unique when truncated to 8 characters:
 directory blib/lib/auto/Net/SSLeay:
  do_https3.al, do_https2.al, do_https4.al, do_https.al truncate to do_https
  do_httpx3.al, do_httpx2.al, do_httpx4.al truncate to do_httpx
  get_https.al, get_https3.al, get_https4.al, get_http.al, get_http3.al, get_http4.al, get_httpx.al, get_httpx3.al, get_httpx4.al truncate to get_http
  head_https.al, head_https3.al, head_https4.al, head_http.al, head_http3.al, head_http4.al, head_httpx.al, head_httpx3.al, head_httpx4.al truncate to head_htt
  post_https.al, post_https3.al, post_https4.al, post_http.al, post_http3.al, post_http4.al, post_httpx.al, post_httpx3.al, post_httpx4.al truncate to post_htt
  put_https.al, put_https3.al, put_https4.al, put_http.al, put_http3.al, put_http4.al, put_httpx.al, put_httpx3.al, put_httpx4.al truncate to put_http
  ssl_read_all.al, ssl_read_until.al, ssl_read_CRLF.al truncate to ssl_read
  ssl_write_all.al, ssl_write_CRLF.al truncate to ssl_writ
  tcp_read_all.al, tcp_read_until.al, tcp_read_CRLF.al truncate to tcp_read
  tcp_write_all.al, tcp_write_CRLF.al truncate to tcp_writ
cp lib/Net/SSLeay.pod blib/lib/Net/SSLeay.pod
cp lib/Net/SSLeay/Handle.pm blib/lib/Net/SSLeay/Handle.pm
Running Mkbootstrap for SSLeay ()
chmod 644 "SSLeay.bs"
"/data/data/com.termux/files/usr/bin/perl" "-Iinc" -MExtUtils::Command::MM -e 'cp_nonempty' -- SSLeay.bs blib/arch/auto/Net/SSLeay/SSLeay.bs 644
"/data/data/com.termux/files/usr/bin/perl" "-Iinc" "/data/data/com.termux/files/usr/lib/perl5/5.28.0/ExtUtils/xsubpp"  -typemap '/data/data/com.termux/files/usr/lib/perl5/5.28.0/ExtUtils/typemap' -typemap '/data/data/com.termux/files/home/.cpan/build/Net-SSLeay-1.85-5/typemap'  SSLeay.xs > SSLeay.xsc
mv SSLeay.xsc SSLeay.c
arm-linux-androideabi-clang -c   -I/data/data/com.termux/files/usr/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64    -DVERSION=\"1.85\" -DXS_VERSION=\"1.85\" -fPIC -Wno-unused-function "-I/data/data/com.termux/files/usr/lib/perl5/5.28.0/arm-android/CORE"   SSLeay.c
  MIKEM/Net-SSLeay-1.85.tar.gz
  /data/data/com.termux/files/usr/bin/make -- NOT OK

```

![](https://i.imgur.com/5eAS74b.png)

**Comment by fornwall** [comment]
> *** That's newer than what this module was tested with
>     You should consider checking if there is a newer release of this module
>     available. Everything will probably work OK, though.

It seems to be an issue with openssl 1.1 compatibility - is Net::SSLeay supposed to be compatible with openssl 1.1?

**Comment by bensh4** [comment]
@fornwall I tested the latest version of openssl and openssl without 'no-engine' config by @xeffyr as well. Not working in both. Seems this issue is within latest version of Net:SSLeay

**Comment by Grimler91** [comment]
Net::SSLeay doesn't support openssl 1.1.1 yet it seems, here is the upstream issue: https://rt.cpan.org/Public/Bug/Display.html?id=125218. 
There is a patch attached to that issue that might work

**Comment by naveedpash** [comment]
The patches didn't help me.
I did look at the SSLeay.xs file where's the error points:
`5398 #ifdef __ANDROID__
5399
5400 RSA *
5401 RSA_generate_key(bits,ee,perl_cb=&PL_sv_undef,perl_data=&PL_sv_undef)
5402         int bits
5403         unsigned long ee
5404         SV* perl_cb
5405         SV* perl_data
5406     PREINIT:
5407         simple_cb_data_t* cb_data = NULL;
5408     CODE:
5409        /* Android does not have RSA_generate_key. This equivalent is contributed by
5410        /* but is not portable to old OpenSSLs where RSA_generate_key_ex is not avai
5411        int rc;
5412        RSA * ret;
5413        BIGNUM *e;
5414        e = BN_new();
5415        BN_set_word(e, ee);
5416        cb_data = simple_cb_data_new(perl_cb, perl_data);
**5417        BN_GENCB new_cb;**
5418        BN_GENCB_set_old(&new_cb, ssleay_RSA_generate_key_cb_invoke, cb_data);
5419
5420        ret = RSA_new();
5421        rc = RSA_generate_key_ex(ret, bits, e, &new_cb);
5422
5423        if (rc == -1 || ret == NULL)
5424            croak("Couldn't generate RSA key");
5425        simple_cb_data_free(cb_data);
5426        BN_free(e);
5427        e = NULL;
5428        RETVAL = ret;
5429     OUTPUT:
5430         RETVAL
5431
5432 #else`

Basically the problem is that `new_cb` is being initialized on the stack but its size is unknown at initialisation; its size will be whatever `perl_cb` coughs up based on the options passed to that.  So the compiler freaks out. To initialise on the heap, we need to declare a pointer to a BN_GENCB struct instead. Therefore simply add an asterisk like so:

`5417        BN_GENCB *new_cb;`

And voila, it compiles (albeit with 24 warnings)! Openssl has changed the way `BN_GENCB` is implemented; an explicit callback `BN_GENCB_new()` is required after declaring it to allocate heap space. The author was probably aware of this because s/he used `BN_new()` and `BN_free()` so I suspect the missing asterisk was a typo.

Although I'm not sure if `BN_GEN_free(new_cb)` should be called. I don't think so because `simple_cb_data_free(cb_data)` is called so that should free the memory taken by `new_cb` too, right? (I work with Rust and now I think in #lifetimes)

**Comment by b3nsh4** [comment]
@naveedpash https://m.youtube.com/watch?v=wvt0cmueHkQ
