### ISSUE TITLE
Apt List Error 

### ISSUE THREAD

**Issue by Klavyeli** [termux/termux-packages#3046]
![screenshot_20181111-105334](https://user-images.githubusercontent.com/38491552/48310476-da9c3b00-e5a0-11e8-9380-c7313d37b62a.png)
I wonder what the problem of this error is
A5 2016 Android 7.0 Nougat

**Comment by xeffyr** [comment]
Have you run apt as root ?

**Comment by Klavyeli** [comment]
Yes still error
![screenshot_20181111-121356](https://user-images.githubusercontent.com/38491552/48311100-6dda6e00-e5ab-11e8-806a-9e53157397ec.jpg)

**Comment by Grimler91** [comment]
You get that error because you used apt as root. You shouldn't use apt as root.

You need to chown the files mentioned there to the normal user, or just run `rm -rf $PREFIX` and restart termux. This will remove all installed programs but leave $HOME intact.

See also https://github.com/termux/termux-packages/issues/2278, https://github.com/termux/termux-app/issues/542

**Comment by Klavyeli** [comment]
![screenshot_20181111-133303](https://user-images.githubusercontent.com/38491552/48311805-5f458400-e5b6-11e8-81b1-96e229a5895c.jpg) 
No command is running

**Comment by Grimler91** [comment]
@Klavyeli You haven't said what you have done and my crystal ball is kinda foggy today so I have no idea how you ended up with the `mkshrc: getprop: not found` error.
This issue describes the same error, and a solution: https://github.com/termux/termux-app/issues/849

**Comment by xeffyr** [comment]
Solution:

1. `rm -rf $PREFIX`
2. Exit from application by closing ALL sessions. Or do **force-stop** from Android's settings.
3. Open Termux again.
