### ISSUE TITLE
Package request: mtr

### ISSUE THREAD

**Issue by Rudloff** [termux/termux-packages#305]
Hello,

It would be pretty useful to have [MTR](http://www.bitwizard.nl/mtr/) in Termux.

**Comment by Sekanato** [comment]
Me too. I'm not sure though, that it would work with no root, as traceruote doesn't(traceroute: socket: Operation not permitted).

**Comment by Neo-Oli** [comment]
@Sekanato but `tracepath` works. And that does essentially the same as traceroute

**Comment by Sekanato** [comment]
@Neo-Oli Forgot about that one. That's great, but still it isn't mtr.

**Comment by fornwall** [comment]
I started a package definition for `mtr` at https://github.com/termux/termux-packages/tree/master/disabled-packages/mtr. The current status is that it does not build due to using features from `search.h` (hash table manipulation functions there), which does not work with bionic.

The cleanest solution would be to implement `hcreate()` and add it to `mtr` to be used for the Android build.

**Comment by Rudloff** [comment]
It seems older versions of mtr (e.g. 0.80) don't use hsearch.
Would it be ok to package an old version?

**Comment by karolba** [comment]
Hey @fornwall, mtr is still in `disabed-packages/`, and required root to function correctly. I feel like this should not be closed yet.

**Comment by fornwall** [comment]
@karolba Sorry, it got closed by merging the PR.

Note that I just created a new repo, https://github.com/termux/termux-root-packages, to contain root-only packages for Termux (with mtr as the first package, so I've removed it from this repo). In a short while there will be an apt repo setup containing root-only packages, so that those interested in installing them can do so.

**Comment by xeffyr** [comment]
mtr is already available as root package: https://github.com/termux/termux-root-packages/tree/master/packages/mtr
