### ISSUE TITLE
Package request: deborphan

### ISSUE THREAD

**Issue by Rudloff** [termux/termux-packages#306]
Hello,

Would it be possible to port deborphan to Termux?

Regards,

**Comment by Rudloff** [comment]
I tried a basic port here: https://github.com/Rudloff/termux-packages/commit/e2b170148161cce1166443a5902096ed21c41e91
But it crashes:
```
u0_a118@localhost ~> deborphan -f /data/data/com.termux/files/usr/var/lib/dpkg/status
bionic/libc/upstream-netbsd/lib/libc/regex/regfree.c:110: regfree: assertion "preg->re_magic == MAGIC1" failed
'deborphan -f /data/data/com.ter…' has stopped
fish: Job 1, 'deborphan -f /data/data/com.ter…' terminated by signal SIGABRT (Abort)
```

**Comment by fornwall** [comment]
@Rudloff I tracked down the crash due to deborphan calling `regfree` on `regexp_t` variables never initialized with `regcomp` (in src/pkginfo.c one can see that some regexpes are compiled only under certain conditions, while they are unconditionally freed). This seems to work with glibc but bionic asserts on this and crashes. I've added a patched disabled package definition at https://github.com/termux/termux-packages/tree/master/disabled-packages/deborphan, which also patches some paths.

However, even with this I can't get deborphan to output any warning, possibly because of the simplified structure of the control fields used in Termux deb packages. I tried the `-a` flag but no luck.
