### ISSUE TITLE
Debootstrap not finding debian keyring?

### ISSUE THREAD

**Issue by projectextremum** [termux/termux-packages#3105]
```
$ debootstrap --arch=armhf stable . http://deb.debian.org/debian/
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/debian-archive-keyring.gpg
I: Retrieving InRelease
I: Retrieving Release
```

I downloaded debian keyring from official repo, unpacked & passed it through `--keyring` option that worked. But isn't it anyway better to add the keyring or provide some way to download it?

Also, it appears to download `armel` packages when no architecture is specified even on `armhf` boxes, I might be wrong though.

**Comment by xeffyr** [comment]
Seems *debootstrap* looks for keyring on standard path which is not exist in Termux.

**Comment by mahesh-hegde** [comment]
Hey both these command options work. since debootstrap a shell script, think it should be possible to fix it in a better way. (Aw, snap. There is lot of perl stuff too).

As a side issue/note, perl dependency for debootstrap is quite large. On debian all it requires is a `perl-base` package which is pretty minimal.

**Comment by xeffyr** [comment]
Fixed in https://github.com/termux/termux-packages/pull/3234.
