### ISSUE TITLE
openssl - can't find certificates

### ISSUE THREAD

**Issue by erlanger** [termux/termux-packages#3109]
I am working on porting SWI-Prolog to termux. SWI-Prolog's author has done quite a bit of work to get things working as shown here: SWI-Prolog/swipl-devel#358.

We're almost there. There seems to be a bug with the openssl configuration:

When I try to to make an `https` download in termux using SWI-Prolog (the development version which I am working on) I get the following error from strace:

```
openat(AT_FDCWD, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY|O_LARGEFILE) = -1 EN
OENT (No such file or directory)
```
Obviously there is no `/etc/ssl` in Android, is this a bug in the openssl package?

There is no error on the prolog side, since everything works fine in other platforms, and all the other ssl tests on termux pass. It is only failing to validate the github certificate because it doesn't find `ca-certificates.crt`.

**Comment by xeffyr** [comment]
> Obviously there is no /etc/ssl

Termux is not a Linux distribution. At least not traditional.
Take a look on https://wiki.termux.com/wiki/Differences_from_Linux

***

Packages are patched and compiled in special way so everything is located under `$PREFIX`.

Snippet from [openssl/build.sh](https://github.com/termux/termux-packages/blob/master/packages/openssl/build.sh):
```
...
	./Configure $TERMUX_OPENSSL_PLATFORM \
		--prefix=$TERMUX_PREFIX \
		--openssldir=$TERMUX_PREFIX/etc/tls \
		shared \
		no-ssl \
		no-comp \
		no-dso \
		no-hw \
		no-srp \
		no-tests
...
```

Files and directories accessed by OpenSSL libraries:
```
$ strings libssl.so | grep -P '^/\w+/'
$ strings libcrypto.so | grep -P '^/\w+/'
/data/data/com.termux/files/usr/etc/tls/ct_log_list.cnf
/data/data/com.termux/files/usr/lib/engines-1.1
/dev/urandom
/dev/random
/dev/srandom
/dev/tty
/data/data/com.termux/files/usr/etc/tls/private
/data/data/com.termux/files/usr/etc/tls
/data/data/com.termux/files/usr/etc/tls/certs
/data/data/com.termux/files/usr/etc/tls/cert.pem
```

***

> is this a bug in the openssl package?

If that was a bug, then apt was completely unusable as sources.list configured to use https.

***

> It is only failing to validate the github certificate because it doesn't find ca-certificates.crt.

You should use `/data/data/com.termux/files/usr/etc/tls/cert.pem` instead of `ca-certificates.crt`.

**Comment by erlanger** [comment]
Thanks, I'll patch the sources, appreciate the quick response.

**Comment by erlanger** [comment]
Okay, everything working now. Thanks!
