### ISSUE TITLE
Android 5.1.1 some packages doesn't work

### ISSUE THREAD

**Issue by ntbatch** [termux/termux-packages#3211]
Android 5.1.1

msmtp 1.8.1 work OK
After update to msmtp 1.8.2:
'CANNOT LINK EXECUTABLE: cannot locate symbol "__register_atfork" referenced by "msmtp"'

nslookup(package dnsutils):
'CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "dns_categories" referenced by "libns.so"'

**Comment by Delta-Sigma** [comment]
I am experiencing the same issue. I'm trying to use the 'dig' command. And I get:

CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "dns_categories" referenced by "libns.so"

**Comment by holishing** [comment]
when I execute `nslookup`, I experienced related issue:
```
$ nslookup
CANNOT LINK EXECUTABLE: could not load library "libirs.so" needed by "nslookup"; caused by cannot locate symbol "isc_assertion_failed" referenced by "libirs.so"...
```

**Comment by talentlessguy** [comment]
I updated apt and it worked fine. Termux should use a newer apt version by default not to update manually every time after install.

**Comment by noloader** [comment]
Sorry about the late comment. This issue is a top hit when searching on the problem... 

Also see [Android linker changes for NDK developers | __register_atfork](https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#available-in-api-level-23) in the NDK docs.
