### ISSUE TITLE
libandroid-support error: CANNOT LINK EXECUTABLE ...  cannot locate symbol "nl_langinfo" referenced by ...

### ISSUE THREAD

**Issue by steffenl82** [termux/termux-packages#3283]
Today while doing an "apt update" and "apt ugrade" I got an upgrade for libandroid-support.

Now my termux installation is completely inaccessible.

When I try to start termux I get the following message and the program immediately terminates:

"CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/bash": cannot locate symbol "nl_langinfo" referenced by "/data/data/com.termux/files/usr/lib/libreadline.so.7.0"..."

Any help would be highly appreciated! Thank you.

**Comment by steffenl82** [comment]
it is an arm device

**Comment by Grimler91** [comment]
(Oh yeah, you apparently wrote that in the title.. :) )

You can downgrade libandroid-support temporarily until is fixed by:
 * opening a failsafe session: https://wiki.termux.com/wiki/Recover_a_broken_environment#Launching_a_Failsafe_Session
 * download libandroid-support 22: `curl -LO https://grimler.se/dists/testing/misc/binary-arm/libandroid-support_22-1_arm.deb`
 * setting up environment: `export PATH=$PREFIX/bin:$PATH; export LD_LIBRARY_PATH=$PREFIX/lib`
 * install old version: `dpkg -i ./libandroid-support_22-1_arm.deb`
 * restart the app

And then avoid `apt upgrade` for a while (or use `apt-mark hold libandroid-support`)

**Comment by aero** [comment]
@Grimler91
```
sh: curl: not found
```
in failsafe session.

**Comment by Grimler91** [comment]
@aero ah, sorry, so you need to export PATH before downloading, I'll update the steps

**Comment by sw2000** [comment]
Hi, I was getting this error while in failsafe mode that prevented me following the instructions above. CANNOT LINK EXECUTABLE DEPENDENCIES: "libcurl.so" is 32-bit instead of 64-bit

I reinstalled Termux and held back libandroid-support, ran pkg update as usual, and it appears to be working again now, thanks.

**Comment by Grimler91** [comment]
@sw2000 probably means that your arch wasn't arm (I'll add a note about that in the instructions)

**Comment by steffenl82** [comment]
@Grimler91  Thank you for the instructions. However, I only able to go to the point of installing the previous version, when I get the following error:

tar: chown 1000:1000 '.': Operation not permitted
tar: chown 1000:1000 './control': Operation not permitted
dpkg-deb: error: tar subprocess returned error exit status 1
dpkg: error processing archive ./libandroid-support_22-1_arm.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 ./libandroid-support_22-1_arm.deb

**Comment by Grimler91** [comment]
@steffenl82 Hmm, which folder did you download the .deb to? Try it from termux home (/data/data/com.termux/files/home) if you were in some other folder.

If that wasn't the issue then it might be something problem with busybox tar, need to look into that

**Comment by steffenl82** [comment]
The file is in the home folder (/data/data/com.termux/files/home)

**Comment by steffenl82** [comment]
I was finally able to recover my installation manually by extracting libandroid-support.so from libandroid-support_22-1_arm.deb and putting it into /data/data/com.termux/files/usr/lib/

**Comment by Grimler91** [comment]
@steffenl82 glad you solved it!

**Comment by landfillbaby** [comment]
this seems to be fixed along with #3285

**Comment by diooktput** [comment]
Unfortunately, it's still broken for me although Termux was reinstalled on my phone. I want to connect my laptop, but `mosh` is still broken with same bug.

> $ mosh username@ip
> CANNOT LINK EXECUTABLE "mosh-client": cannot locate symbol "nl_langinfo" referenced by "/data/data/com.termux/files/usr/bin/mosh-client"...
> Aborted
> $ pkg up
> Hit:1 https://termux.net stable InRelease
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> All packages are up to date.
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Calculating upgrade... Done
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> $ termux-info
> Updatable packages:
> All packages up to date
> System information:
> Linux localhost 3.18.31-perf-g7240fae #1 SMP PREEMPT Wed Dec 12 16:53:54 CST 2018 aarch64 Android
> Termux-packages arch:
> aarch64
> Android version:
> 7.1.1
> Device manufacturer:
> OPPO
> Device model:
> CPH1801
> $

**Comment by cilantro13** [comment]
https://termux.net stable InRelease iya still same
