### ISSUE TITLE
Package request: libtorrent-rasterbar

### ISSUE THREAD

**Issue by newmania** [termux/termux-packages#3327]
**Package description**
libtorrent is a feature complete C++ bittorrent implementation focusing on efficiency and scalability. It runs on embedded devices as well as desktops. This is the missing piece needed to run deluged on Termux.

**Link to home page and sources**
1. Home page: https://www.libtorrent.org/
2. Source code: https://github.com/arvidn/libtorrent

**Additional information**
Have you compiled or tried to compile the package on device?
* I'm having trouble getting the build environment container running on my MacBook and have not been able to try building this.

**Comment by tomty89** [comment]
"on device" means on Termux btw.

**Comment by KingRanger984** [comment]
Any progress?

**Comment by FreddieOliveira** [comment]
Yes. This lib has libboost as dependence, so first step is to install it. Then run the usual cmake, make, make install:

```text
$ pkg install boost
$ git clone https://github.com/arvidn/libtorrent.git
$ mkdir libtorrent/build
$ cd libtorrent/build
$ cmake -DCMAKE_INSTALL_PREFIX=/data/data/com.termux/files/usr ..
$ make -j8
$ make install
```

Bear in mind that `cmake` doesn't generate a uninstall target in the Makefile by default, so to eventually uninstall it you should use the generated `install_manifest.txt` by running `xargs rm < install_manifest.txt` instead of `make uninstall`

**Comment by johnmarshall515** [comment]
@FreddieOliveira 

> $ pkg install boost
> $ git clone https://github.com/arvidn/libtorrent.git
> $ mkdir libtorrent/build
> $ cd libtorrent/build
> $ **cmake -DCMAKE_INSTALL_PREFIX=/data/data/com.termux/files/usr ..**
> $ make -j8
> $ make install

Thank you for your instructions. I am having a problem at this step and don't know how to proceed:

$ cmake -DCMAKE_INSTALL_PREFIX=/data/data/com.termux/files/usr ..
-- The C compiler identification is Clang 11.0.0
-- The CXX compiler identification is Clang 11.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc - skippe                                                                                                                                                             d
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/c++ - ski                                                                                                                                                             pped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB - Success
-- Performing Test HAVE_CXX_ATOMICS64_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS64_WITHOUT_LIB - Success
-- Found OpenSSL: /data/data/com.termux/files/usr/lib/libcrypto.so (found versio                                                                                                                                                             n "1.1.1i")
-- Found Boost: /data/data/com.termux/files/usr/lib/cmake/Boost-1.74.0/BoostConf                                                                                                                                                             ig.cmake (found version "1.74.0")
-- The following features have been enabled:

 * BUILD_SHARED_LIBS, build libtorrent as a shared library
 * dht, enable support for Mainline DHT
 * deprecated-functions, enable deprecated functions for backwards compatibility
 * encryption, Enables encryption in libtorrent
 * exceptions, build with exception support
 * extensions, Enables protocol extensions
 * i2p, build with I2P support
 * logging, build with logging
 * mutable-torrents, Enables mutable torrent support
 * streaming, Enables support for piece deadline

-- The following RECOMMENDED packages have been found:

 * OpenSSL, Full-strength general purpose cryptography library, <https://www.ope                                                                                                                                                             nssl.org/>
   Provides HTTPS support to libtorrent

-- The following REQUIRED packages have been found:

 * Threads
 * boost_headers (required version == 1.74.0)
 * Boost

-- The following features have been disabled:

 * static_runtime, build libtorrent with static runtime
 * build_tests, build tests
 * build_examples, build examples
 * build_tools, build tools
 * python-bindings, build python bindings
 * python-egg-info, generate python egg info
 * python-install-system-dir, Install python bindings to the system installation                                                                                                                                                              directory rather than the CMake installation prefix
 * gnutls, build using GnuTLS instead of OpenSSL

-- Configuring done
CMake Error at CMakeLists.txt:536 (add_library):
  Cannot find source file:

    deps/try_signal/try_signal

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .ispc


CMake Error at CMakeLists.txt:536 (add_library):
  No SOURCES given to target: torrent-rasterbar


CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by FreddieOliveira** [comment]
It seems the build instructions changed since April (or I gave wrong instructions). Now, you should `git clone --recurse-submodules https://github.com/arvidn/libtorrent.git` in order to also download some dependencies. The other instructions remain the same:

```
pkg install boost
git clone --recurse-submodules https://github.com/arvidn/libtorrent.git
mkdir libtorrent/build
cd libtorrent/build
cmake -DCMAKE_INSTALL_PREFIX=/data/data/com.termux/files/usr ..
make -j8
make install
```

and `xargs rm < install_manifest.txt` to uninstall it.

**Comment by johnmarshall515** [comment]
Thank you that part works now. For some reason when I run **make -j8** my device freezes and keeps crashing somewhere around 15%-20% so I am unable to compile :(

**Comment by FreddieOliveira** [comment]
This happens because of high RAM usage. Try lowering the number of cores used: `make -j4`

If it still crashes run with one single thread: `make`

It will take longer, but probably succeeded.

**Comment by johnmarshall515** [comment]
Ok I got it to compile and now I believe my last obstacle to getting deluged running is building the python module for libtorrent. 

I started following this: http://www.libtorrent.org/python_binding.html which requires installing boot-build with these instructions: http://www.libtorrent.org/building.html#step-2-setup-bbv2

So I downloaded boost source package to run bootstrap.sh but get this error: `./bootstrap.sh: 1: ./tools/build/src/engine/build.sh: not found`

I'm guessing this needs to be built through termux's boost package rather than boost's github package, but it is beyond my knowledge on how to actually do that.

**Comment by piyushgarg** [comment]
I am able to compile the libtorrent-rasterbar and successfully running qBittorrent-nox on top of it, no isssues so far.

## build libtorrent
git clone --recurse-submodules https://github.com/arvidn/libtorrent.git
cd libtorrent
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=off -Dstatic_runtime=on -DCMAKE_INSTALL_PREFIX="${PREFIX}" ..
make && make install



## build qbittorrent-nox
pkg in qt5-qttools qt5-qtsvg
git clone https://github.com/qbittorrent/qBittorrent.git
cd qBittorrent/
git checkout tags/release-4.3.7

mkdir build
cd build
cmake -D VERBOSE_CONFIGURE=ON -D STACKTRACE=OFF -DGUI=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=off -Dstatic_runtime=on -DCMAKE_INSTALL_PREFIX="${PREFIX}" ..
cd ..
cmake --build build

This libtorrent-rasterbar can be added easily to termux.

**Comment by xtkoba** [comment]
Seems like almost ready for packaging?
