### ISSUE TITLE
ifaddrs.h

### ISSUE THREAD

**Issue by Rudloff** [termux/termux-packages#338]
Hello,

Some programs require the ifaddrs.h header file to build but it does not seem to exist on Android.
There is an Android version available here: https://github.com/morristech/android-ifaddrs

It works if you include it into the source you're trying to build (see https://github.com/termux/termux-packages/pull/329 for example) but this is not a very clean solution.
Would it be possible to include this file in Termux so we can build programs that require it?

Regards,

**Comment by fornwall** [comment]
We can patch the NDK headers to add ifaddrs.h (this is already done for `elf.h` and `sysexits.h`, which are added).

In this case the code is split into a C file - do you think you could inline the code into the header file, so that it can be used directly without having to compile an additional C file?

**Comment by Rudloff** [comment]
This seems like a good idea but unfortunately I don't know enough about C to do it myself.

**Comment by fornwall** [comment]
The `ifaddrs.h` file provided by @qnnnnez has now been added - thanks a lot.

It's available both when building Termux packages, and it's also available when building on the device after running an `apt update && apt upgrade`.
