### ISSUE TITLE
Eternal Terminal

### ISSUE THREAD

**Issue by flying-sheep** [termux/termux-packages#3385]
**Package description**
Eternal Terminal is a SSH wrapper for unstable (e.g. mobile) connections similar to mosh. It comes as client command and server daemon. Just like mosh it uses SSH for the initial connection. Unlike mosh it relies on an “Eternal TCP” layer instead of a virtual terminal screen, which makes it work exactly like SSH, only stable to reconnects and roaming. Unlike mosh it supports mouse scrolling, tmux control mode (-CC) and leaves its output on the terminal emulator after exiting.

**Link to home page and sources**
1. Home page: https://mistertea.github.io/EternalTerminal/
2. Source code: https://github.com/MisterTea/EternalTerminal

**Additional information**
I haven’t tried to build it yet, but since it uses cmake, that should be a breeze.

**Comment by RebelLion420** [comment]
I have tried building this on device and I'm still searching for compatibility edits 3 hours in. So it's probably stuck to cross-compile only

**Comment by whiterst** [comment]
request too
i tried to install it,but failed

**Comment by sayak-brm** [comment]
Still waiting

**Comment by chunlinyao** [comment]
It can compiled on termux, but got SIGSEGV when execute.

**Comment by RossComputerGuy** [comment]
Use `strace`, it can help figure out why its not working.

**Comment by kellytrinh** [comment]
Still not working?  Would be great to get `et` rolling on termux so can use it to/from my phone on the go.

**Comment by buttaface** [comment]
I have some packages built at the above pull, but it's not working, maybe because I don't use gflags? Try it out by going to the above Termux pull, click on `Checks`, then `Artifacts` on the right, then `termux-packages` to download the built Termux packages. Unpack them and then install the right one for your architecture with `dpkg -i eternal-terminal_6.0.13_aarch64.deb`. Any suggestions or patches are welcome.
