### ISSUE TITLE
MPD: crashes frequently 

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#3441]
**Problem description**
MPD will crash with the following error message ever since the latest NDK update:

`Invalid address 0xa3e02480 passed to free: invalid page index`

**Steps to reproduce**
`mpd --no-daemon --stdout`
It will usually happen within a few seconds.

**Expected behavior**
It shouldn't crash

**Additional information**
```
Updatable packages:
All packages up to date
System information:
Linux localhost 3.4.0-perf-g284400aea4b #1 SMP PREEMPT Mon Feb 25 13:31:32 UTC 2019 armv7l Android
Termux-packages arch:
arm
Android version:
8.1.0
Device manufacturer:
Fairphone
Device model:
FP2
```

This looks very similar to #3435. Is this perhaps related?

**Comment by xeffyr** [comment]
> Invalid address 0xa3e02480 passed to free: invalid page index

Perhaps same as `aria2c` ?

**Comment by Neo-Oli** [comment]
@xeffyr It does look very similar.

**Comment by Neo-Oli** [comment]
Unfortunately I can't seem able to produce a stack trace with gdb due to the weird way MPD is started.

**Comment by its-pointless** [comment]
libz linked before other libs causes issues when using exceptions on arm. same issue as gmic on arm. i should find some time to patch this and a few other similar issues as well at some point.

**Comment by its-pointless** [comment]
not working on mpd even though even with libz link moved.. bugger

**Comment by its-pointless** [comment]
oh got it working 
mpd needs to be compiled with -lz last 
libflac needs to be compiled with "-fexceptions" added to  cflags

**Comment by its-pointless** [comment]
also @Neo-Oli  
gdb ~/../usr/libexec/mpd
then in gdb
set environment LD_LIBRARY_PATH=/system/lib:/system/vendor/lib:/data/data/com.termux/files/usr/lib

**Comment by tomty89** [comment]
@its-pointless I think we should starting building our own zlib even before merging `android-7` into master / ditching `LD_LIBRARY_PATH`, if it also works, instead of having random "reordering" patches all over the place.

We just need (actually it could be merely reassurance) to rename the libz.so symlink to e.g. libtermuz.so and sed zlib.pc accordingly (and make sure the SONAME is `libz.so.1`).

Will open a PR later to day.

**Comment by its-pointless** [comment]
> @its-pointless I think we should starting building our own zlib even before merging `android-7` into `master` / ditching `LD_LIBRARY_PATH`, if it also works, instead of having random "reordering" patches all over the place.
> 
> We just need (actually it could be merely reassurance) to rename the libz.so symlink to e.g. libtermuz.so and sed zlib.pc accordingly (and make sure the SONAME is `libz.so.1`).
> 
> Will open a PR later today.

It non't solve all problems regarding this.

**Comment by unimog401** [comment]
I'm experiencing a mpd crash that may be related to this. It started happening after updating from mpd:arm 0.21.4 to 0.21.5. I can't set bind_to_address to "any", if I do mpd segfaults when i restart it. mpd seems to work fine if I don't enable external IP address. localhost works fine.

**Comment by gerroon** [comment]
I experience segfaults, this was not used to be the case :(

**Comment by xeffyr** [comment]
Should be fixed by:

* https://github.com/termux/termux-packages/commit/7e60494c163ebbecedc21624749c53af7bf5a741
* https://github.com/termux/termux-packages/commit/b7a8798698f74e8cc6f4d5359c5835c2ecb33236
* https://github.com/termux/termux-packages/commit/75f0967f9345127bf551280bd2b8c9da2987527d
* https://github.com/termux/termux-packages/commit/cd12ae19be4b1f0bdf9ad95c068827c0cfe7bd02
