### ISSUE TITLE
How can I add clang package by default in termux

### ISSUE THREAD

**Issue by sgpatil** [termux/termux-packages#3511]
Hi,
I want to install termux on more than 1 devices (of my students). After installation, I need to install clang each time. Is there any way, I modify the code to auto install clang package and setup storage on start-up.

**Comment by Grimler91** [comment]
Hi, this is an interesting question. 

The best way to obtain what you want would be to create a custom [bootstrap](https://termux.net/bootstrap/) that is installed when termux starts for the first time. 
Problem is that it isn't possible to choose to download a custom bootstrap, only way would be to recompile termux-app and change the default [bootstrap url](https://github.com/termux/termux-app/blob/f2757fdb76cd6d14ba732716e51a1b11fc6e93e0/app/src/main/java/com/termux/app/TermuxInstaller.java#L188). 
But, doing this would mean that your students wouldn't get termux-app updates from Fdroid/google play, since the app isn't installed from Fdroid or google play.

The most reasonable way to get what you want is to tell the students to install the app and then run a script you've written through something like 
```
curl -O script.sh https://myurl.com/script.sh; bash script.sh
```
where script.sh installs clang and setups storage.

So, to conclude, there is currently not a good way to obtain what you want without having to run at least a one-line command on each device.

**Comment by xeffyr** [comment]
> But, doing this would mean that your students wouldn't get termux-app updates from Fdroid/google play, since the app isn't installed from Fdroid or google play.

Custom Termux app means that students not only wouldn't receive any application updates but also that all plugins should be rebuilt. Outdated plugins may cause problems, e.g. package `termux-api` should be always in sync with Termux:API application, otherwise it may not work properly.

So best way is to use script - it easily can be stored on Github and does not require building bootstrap archives and/or custom Termux application.
