### ISSUE TITLE
[Question] How to pkg install PHP v 7.2 instead of the current 7.3

### ISSUE THREAD

**Issue by HarisHashim** [termux/termux-packages#3513]
Hello & good day!

The issue is thty I have older installation in different Android device that use PHP v 7.2 which come with iconv extension by default. My script runs without issue.

In new device my script throw an error saying iconv function not found. PHP version is the latest and php -m shows that iconv is not included by default. This just sucks elephant egg.

So how to install older version of PHP using pkg install?

This can also be solved by re enabling iconv in the new PHP version. But who knows what else is broken in that package. (And, obviously I dont know how to do this, tried but for the love of god, I have no idea where to get iconv.so).

TIA
Haris

**Comment by xeffyr** [comment]
> how to install older version of PHP using pkg install

You can't. We do not keep older package versions.

**Comment by HarisHashim** [comment]
Can I have some starter tip how to build ld version of PHP from source for termux?

Or maybe it will be easier to add iconv extension to current PHP?

**Comment by HarisHashim** [comment]
@xeffyr  any pointer?

I have also created #3541 that will also help in solving this question.

TIA

**Comment by OGKingD** [comment]
@HarisHashim 
I had a similar problem while trying to install composer...
The phar extension is missing , try installing it or recompile PHP without -- disable -phar ....
What I did which you can do....

************************
*since you cannot downgrade your PHP version in termux download server for PHP on play store . Faster find use the Package name com.esminis.server.php
 //The app has the option to download any version of PHP...
// The app also has the option to enable and disable any module .... .
*Run the app server for PHP.
* Download your preferred version of PHP. //for me the PHP version was 7.2=> 7.3.3 yours would be the version that worked for u .
* Go into /data/data/com.esminis.server.php/files.    And copy and paste the file "php " to your termux directory /data/data/com.termux/files/usr/bin
* Check to see if the module is enabled PHP -m
*Give it a go...

**Comment by its-pointless** [comment]
#3560 attempt at fix for missing iconv
