### ISSUE TITLE
Packages fetched over HTTP

### ISSUE THREAD

**Issue by zzak** [termux/termux-packages#362]
I noticed today when using `apt install <something>` that the packages were downloaded using plain-text.

```
404  Not Found [IP: Y.Y.Y.Y]
E: Failed to fetch http://termux.net/dists/stable/main/binary-aarch64/python2_2.7.12_aarch64.deb
```

This could lead to a possible MitM attack, resulting in a user installing harmful packages on their machine.

I'm not sure if this is a limitation of Android platform, or perhaps the packaging system, or even if this is the right place to report!

Hope that helps, and thanks for the software! :beers:

**Comment by its-pointless** [comment]
No the first time you use apt it is already cryptically signed. If it was tampered with apt would complain and not install.

**Comment by zzak** [comment]
@its-pointless Oh, I wasn't sure!

Anyways, closing this ticket, thanks for the feedback <3

**Comment by Zhu-Zhi-Hao** [comment]
Hi，if you want use HTTPS for security of deb packages，and it is also I want to do，just ：

`apt install apt-transport-https`

And change url:  http to https in source.list like this:
`https://mirrors.tuna.tsinghua.edu.cn/termux`

Note :  There's a termux package mirrors in Tsinghua universe of China , allow to use HTTPS service。because of GFW you know...

**Comment by fornwall** [comment]
It's also possible to use `https://termux.net` (after installing the `apt-transport-https` package) if you do not want to use a mirror!
