### ISSUE TITLE
[Package request] adb
(Android Debug Bridge)

### ISSUE THREAD

**Issue by Hunter9888x** [termux/termux-packages#3660]
adb (Android Debug Bridge)

adb is great for
Android tv or fire tv

to enable accessibility services
or
enable launcherhijack & tvsettingsonfire

**Comment by metaspook** [comment]
@xeffyr
Please add this package it's very necessary..

**Comment by metaspook** [comment]
@xeffyr
Please add this package it's very essential..

**Comment by kcubeterm** [comment]
Something like this app, https://play.google.com/store/apps/details?id=eu.sisik.hackendebug

It's works as expected,

**Comment by mrjk** [comment]
```
why there is no ADB or fastboot packages available ?
```

@xeffyr answer's: Because of unsuitable build system. ADB/fastboot are meant to be built as part of Android OS source tree.

You are always welcome to write makefile for them and submit a pull request to termux-packages ;)

**Comment by DRSDavidSoft** [comment]
I have been using @rendiix's pre-compiled `adb` binaries to great success. There's also an alternative from @MasterDevX.

Links to both:
- https://github.com/rendiix/termux-adb-fastboot
- https://github.com/MasterDevX/Termux-ADB

Hopefully, Termux will provide an `adb` package when possible.

**Comment by pono1991** [comment]
cara menjalankan secripnya gimana?

Pada tanggal Jum, 3 Jul 2020 22.29, David Refoua <notifications@github.com>
menulis:

**Comment by teou1** [comment]
The above mentioned binaries are older versions and do not support wireless adb and pin pairing. Hopefully rendiix or osmosis will recompile the new version 1.0.41. The termux developers are obviously not interested (this request is open more than 18 months...).

**Comment by teou1** [comment]
Thanks to osm0sis and surge 1223 we now have a solution to that problem.
So, download adb.bin somewhere on your phone from here https://github.com/Magisk-Modules-Repo/adb-ndk/tree/master/bin 
Then use fx file explorer - connect to - left menu, termux, to authorize fx to see part of termux filesystem and transfer adb.bin there. Do not try to do it from termux itself: you'll be greeted with an error later on, because of the enforced no execution policy on Android 11 (good for virus protection, bad for power users, see here https://github.com/termux/termux-app/issues/1072 ).
As next step you run termux and 
chmod +x adb.bin 
just to be sure.
Now you can 
./adb.bin
 and read the help how to pair and then connect. Remember there are different ports for pairing and connecting.

**Comment by xeffyr** [comment]
Now is available as part of `android-tools`.
