### ISSUE TITLE
Please dont kill me for reporting this but.... 

### ISSUE THREAD

**Issue by dipayand** [termux/termux-packages#3679]
"pkg list-asshole" command lists all the available package.

**Comment by Grimler91** [comment]
Well, this is intended behaviour, sort of. Pkg looks at only the first letters of the arguments, to make it possible to run `pkg up` instead of `pkg upgrade`, `pkg in` instead of `pkg install`, and similar. See the source code: https://github.com/termux/termux-packages/blob/c11e72522673e0f43659ed9a6cbafbe8f97ba224/packages/termux-tools/pkg#L37
