### ISSUE TITLE
document the distro build and upgrade process

### ISSUE THREAD

**Issue by bubnikv** [termux/termux-packages#3782]
**Problem description**

Please document the following:

What is the process to build the distro packages from this repository? Who is responsible for this process? Is it an automated process? Does it run daily? Or on request of whom? 

What is the process to update the packages? I am worried that the packages will freeze at the initial commit. Is there a reasonable process to upgrade the packages to newer sources? I see that the process to adapt to the non-FHS structure is pretty manual, so there is again a risk that because of that manual process the packages will freeze at their initial versions.

**Comment by Grimler91** [comment]
What do you mean with "freeze at the initial commit"?

If you open a PR to termux-packages with updated sources then we can merge this and the updated package can be built and uploaded (manually or automatically) to the repo(s).

Packages are rebuilt when a new commit is pushed. It is automated for the android >= 7 repo through cirrus CI/gitlab CI (have a look at https://wiki.termux.com/wiki/Bintray_package_hosting) and done manually by Fornwall for the [android 5&6 repo](https://termux.net).

**Comment by xeffyr** [comment]
> What is the process to build the distro packages from this repository?
Is it an automated process?

Once commits were pushed to the branches `master` or `android-5`, the [CI system](https://cirrus-ci.com/termux/termux-packages) starts to build modified packages. When finished, they are uploaded to https://bintray.com/termux/termux-packages-24.

This is done *automatically* only for branch `master` with few exceptions.

Packages on branch `android-5` are built and uploaded *manually* by [Fornwall](https://github.com/fornwall).

> Who is responsible for this process?
Or on request of whom?

Maintainers, who can write commits to the repository:

- @Grimler91
- @fornwall
- @xeffyr

> Does it run daily?

On each push or PR merge.

> What is the process to update the packages?

In most cases just bump `TERMUX_PKG_VERSION` and `TERMUX_PKG_SHA256` in related build scripts. Sometimes it may be needed to fix patches.

Then, in case of package updated on branch `master`, it will be built & uploaded to repository automatically. Depending on package, this takes from ~20 seconds to more than 1 hour.

Updating packages for branch `android-5` will take longer time.

Also, the packages in https://github.com/termux/termux-packages are always updated before than packages in additional repositories (such as unstable or x11 packages).

> I am worried that the packages will freeze at the initial commit.

Have you seen the commit history ? If so, you will find that packages are updated quite frequently. For example, `vim` was updated today: https://github.com/termux/termux-packages/commit/ee38d7835da63a0d359e019a225b0073795b71ff.

> I see that the process to adapt to the non-FHS structure is pretty manual, so there is again a risk that because of that manual process the packages will freeze at their initial versions.

Yes, there is a risk. But not because of non-FHS structure (FHS paths are fixed easily).

There is example of such "freezed" package - [x11-packages/mesa](https://github.com/termux/x11-packages/blob/master/packages/mesa/build.sh). It was freezed on v17.3.9 because newer versions cannot be built with Android NDK, at least without heavy patching.

But as far I know, mesa was the only freezed package.

**Comment by xeffyr** [comment]
And https://wiki.termux.com/wiki/Bintray_package_hosting should be updated - we no longer use Gitlab CI for termux-packages, though other repositories may.

I will also document the process at https://github.com/termux/termux-packages/tree/master/docs in near time. These docs are quite outdated.

**Comment by bubnikv** [comment]
Thank you guys for all the information. I really appreciate your hard work on the project.
I was not able to find the referenced wiki page
https://wiki.termux.com/wiki/Bintray_package_hosting
I did not find the link any where on the wiki front page or elsewhere, but maybe I was not looking carefully. Anyway, as you guys wrote a lot of information into this issue, how about to copy it into the wiki :-)

I was asking because I am the lead on 
https://github.com/prusa3d/PrusaSlicer
and I would love to see our application to run on Termux.

Thanks again for your time.
