### ISSUE TITLE
gcc not working? -lc and -ldl not found

### ISSUE THREAD

**Issue by Arsonary** [termux/termux-packages#379]
I recently installed Termux onto my laptop running Remix OS and I seem to be getting an error every time I try to run even a simple program to print hello world.
Can anyone please help? I really need this to work for classes.

`$ cat a.c
#include<stdio.h>

int main(void){
        printf("Hello World");
        return 0;
}
$ gcc a.c
/data/data/com.termux/files/usr/bin/ld: skipping incompatible /lib/../lib64/libc.so when searching for -lc
/data/data/com.termux/files/usr/bin/ld: skipping incompatible /system/lib64/libc.so when searching for -lc
/data/data/com.termux/files/usr/bin/ld: cannot find -lc
/data/data/com.termux/files/usr/bin/ld: skipping incompatible /lib/../lib64/libdl.so when searching for -ldl
/data/data/com.termux/files/usr/bin/ld: skipping incompatible /system/lib64/libdl.so when searching for -ldl
/data/data/com.termux/files/usr/bin/ld: cannot find -ldl
collect2: error: ld returned 1 exit status`

**Comment by fornwall** [comment]
Probably the x86_64 port of gcc needing patches.

Could you try using clang instead and see if that works better?  For Android clang seems to be the future as Google only supports clang for Android - I will probably setup `gcc` as a an alias for `clang` by default in Termux soon.

**Comment by fornwall** [comment]
The problem is probably that you have a `x86-64` in Remix OS, but you have a `aarch64` installation of Termux packages. This (besides being slower due do the translation layer) doesn't work for some cases such as using a C compiler.

The reason for that is that Remix OS supports running `aarch64` binaries through a translation layer, so Termux versions prior to `v0.39` mistakes a Remix OS `x86-64` installation as a `aarch64`.

What you need to do:

1. Update to Termux `v0.39` (or a later version when one comes), which will correctly identify a `x86-64` Remix OS installation. Either do the update manually or wait for an update of Termux in Remix OS.

2. If you have an `aarch64` installation from earlier, you then need to remove the installation to force a fresh install (Termux will not do this automatically, but keep in using the `aarch64` installation if one exists). Do this by running `rm -Rf $PREFIX` and restart the app.

You can verify which CPU arch your Termux installation is by running

    dpkg --print-architecture

This should ideally output `x86_64` for your laptop.
