### ISSUE TITLE
texlive problem: can't find file `dehypht-x-2019-04-04.tex'.

### ISSUE THREAD

**Issue by smaslovski** [termux/termux-packages#3830]
**Problem description**

After installing texlive-latexrecommended with all the dependencies I tried to compile a simple latex file (see below). It fails with the following errors due to a failure of mktexfmt when producing the latex format file:

$ latex test.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Termux) (preloaded format=latex)
 restricted \write18 enabled.

kpathsea: Running mktexfmt latex.fmt
mktexfmt: mktexfmt is using the following fmtutil.cnf files (in precedence order):
mktexfmt:   /data/data/com.termux/files/usr/share/texlive/texmf-dist/web2c/fmtutil.cnf
mktexfmt: mktexfmt is using the following fmtutil.cnf file for writing changes:
mktexfmt:   /data/data/com.termux/files/home/.texlive2019/texmf-config/web2c/fmtutil.cnf
mktexfmt [INFO]: writing formats under /data/data/com.termux/files/home/.texlive2019/texmf-var/web2c
mktexfmt [INFO]: --- remaking latex with pdftex
mktexfmt: running `pdftex -ini   -jobname=latex -progname=latex -translate-file=cp227.tcx *latex.ini'
.........
.........
.........
===========================================
Local configuration file hyphen.cfg used
===========================================

(/data/data/com.termux/files/usr/share/texlive/texmf-dist/tex/generic/babel/hyp
hen.cfg
(/data/data/com.termux/files/usr/share/texlive/texmf-dist/tex/generic/babel/swi
tch.def)
(/data/data/com.termux/files/usr/share/texlive/texmf-dist/tex/generic/hyphen/hy
phen.tex)
(/data/data/com.termux/files/usr/share/texlive/texmf-dist/tex/generic/hyphen/du
myhyph.tex)
(/data/data/com.termux/files/usr/share/texlive/texmf-dist/tex/generic/hyphen/ze
rohyph.tex)
! I can't find file `dehypht-x-2019-04-04.tex'.
<to be read again>
                   \relax
l.172   \repeat

(Press Enter to retry, or Control-D to exit)
Please type another input file name:
! Emergency stop.
<to be read again>
                   \relax
l.172   \repeat

No pages of output.
Transcript written on latex.log.
mktexfmt [ERROR]: running `pdftex -ini   -jobname=latex -progname=latex -translate-file=cp227.tcx *latex.ini >&2 </dev/null' return status 1
mktexfmt [ERROR]: return error due to options --strict
mktexfmt [INFO]: Disabled formats: 7
mktexfmt [INFO]: Not selected formats: 43
mktexfmt [INFO]: Failed to build: 1 (pdftex/latex)
mktexfmt [INFO]: Total formats: 51
mktexfmt [INFO]: exiting with status 1
I can't find the format file `latex.fmt'!

**Steps to reproduce**

1. On a fresh install of Termux install texlive-latexrecommended
 2. Try compiling the following latex file (or any other):

\documentclass{article}

\title{Check latex}

\author{First Last}

\begin{document}

\maketitle

Here I try to type a few sentences in \LaTeX.

$$ x^2+y^2 = z^2$$

The end.

\end{document}

**Expected behavior**

Latex format file produced OK; latex source compiled OK.

**System information**

$ termux-info
Updatable packages:
libx11/x11 1.6.7-5 aarch64 [upgradable from: 1.6.7-4]
libxcb/x11 1.13.1-2 aarch64 [upgradable from: 1.13.1-1]
libxt/x11 1.1.5-7 aarch64 [upgradable from: 1.1.5-6]
xorg-xauth/x11 1.0.10-8 aarch64 [upgradable from: 1.0.10-7]
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-24 x11/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/termux-root-packages-24 root/stable
https://its-pointless.github.io/files/24 termux/extras
https://its-pointless.github.io/files/24 termux/extras
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 3.18.71-15759240 #1 SMP PREEMPT Thu Apr 4 14:01:51 KST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.0.0
Device manufacturer:
samsung
Device model:
SM-T820

**Comment by Grimler91** [comment]
`dehypht-x-2019-04-04.tex` is part of texlive's dehyph-exptl package, which is part of the langgerman collection, so you need to install texlive-langgerman through apt. 

The more sensible action would be to install `texlive-full` though, so that you get all collections. If you don't want to do this (first low disk space for example), then it is better to install texlive-tlmgr and install the packages you need through tlmgr.

**Comment by smaslovski** [comment]
Should not texlive-latexrecommended have enough dependences to other packages to work out of the box? Which metapackage besides texlive-full does this?

**Comment by Grimler91** [comment]
I've packaged each texlive-collection as they are provided upstream. The collections aren't really supposed to work standalone, they are rather a convenient way to group packages by category. So, to be sure to have a working tex system we either need to install texlive-full in termux, or use tlmgr to install needed packages individually. 

To get fully working systems we would need to provide texlive's scheme-minimal, scheme-full, .. meta packages, but that would mean that we would have ~5 HUGE packages instead of the ~20 with reasonable sizes that we have now.

Another option would be to package each individual texlive package, but that would mean creating and maintaining thousands of packages.

So, either install texlive-full through apt, or install for example scheme-medium through tlmgr to be sure to have a working system

**Comment by Grimler91** [comment]
The package you get through `apt install texlive` currently corresponds to scheme-minimal. We could add a few more texlive packages to it so that the pdflatex format generation works, but we have to draw the line somewhere

**Comment by Grimler91** [comment]
I'll re-open this and look at adding more packages to the base texlive package when I have time

**Comment by smaslovski** [comment]
> Debian's texlive-base or archlinux's texlive-core can be used as reference.

Exactly.

**Comment by davidpiano** [comment]
I have recently encountered this exact problem. After it happened, I saw this discussion, so I installed texlive-full to correct it - BUT that didn't make the problem go away. Is there a setting I need to change, formats I need to remake, or anything I can do as a stopgap to get my files to be processed?
