### ISSUE TITLE
Can I run fdisk?

### ISSUE THREAD

**Issue by Trendle** [termux/termux-packages#3862]
I have a bash script on my phone that requires fdisk. Is there an fdisk binary that works with Termux?

**Comment by Grimler91** [comment]
Requires it for what? 
fdisk is a partitioning program and you cannot partition your device/sdcard/usb without root, at least not on recent android versions.

**Comment by Trendle** [comment]
Does it matter why it requires it? My question is whether or not I can run fdisk with Termux. I have root access on my phone.

**Comment by Grimler91** [comment]
If you just need it to list partitions then there are other ways.
We don't have fdisk in any of the repos.

**Comment by Trendle** [comment]
So the reason I can't run fdisk is that Termux requires a binary that is specifically built for it? Or you're just saying it isn't in the repos?

**Comment by xeffyr** [comment]
> fdisk is that Termux requires a binary that is specifically built for it?

Yes, Termux can run binaries compiled only for Android. Even statically-linked binaries from Linux may be problematic.

> Or you're just saying it isn't in the repos?

Yes, `fdisk` is not available. That is the reason why you can't run it.
But since you wrote above that you have root access, there is a chance that `fdisk` is available with system busybox (only if it was installed at rooting stage).

**Comment by PERCE-NEIGE** [comment]
Hello. What are the other ways to replace Fdisk?

**Comment by xeffyr** [comment]
@PERCE-NEIGE `parted` or `gptfdisk` from root-repo.
