### ISSUE TITLE
Pkg update & pkg install error

### ISSUE THREAD

**Issue by wyssdbd** [termux/termux-packages#3886]
Reading package lists... Done
W: GPG error: https://dl.bintray.com/grimler/game-packages-21 games Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5AAAC9E0A46BE53C
E: The repository 'https://dl.bintray.com/grimler/game-packages-21 games Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://dl.bintray.com/grimler/science-packages-21 science Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5AAAC9E0A46BE53C
E: The repository 'https://dl.bintray.com/grimler/science-packages-21 science Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by xeffyr** [comment]
Use `apt install termux-keyring` for temporary workaround (installs even with these warnings/errors).

**Comment by xeffyr** [comment]
Bootstrap packages fixed, so on **re-installation** of Termux app this error will no longer appear.

If you did `apt install termux-keyring`, you also should be okay and no further steps required.

**Comment by gemini4545** [comment]
I've tried the 

> Bootstrap packages fixed, so on **re-installation** of Termux app this error will no longer appear.
> 
> If you did `apt install termux-keyring`, you also should be okay and no further steps required.

I've tried the  apt install termux-keyring, but there's error as below:
apt update
Hit:1 http://mirrors.tuna.tsinghua.edu.cn/termux stable InRelease
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-21 science InRelease
Get:4 https://its-pointless.github.io/files termux InRelease [9176 B]
Get:5 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Hit:5 https://dl.bintray.com/grimler/game-packages-24 games Release
Err:4 https://its-pointless.github.io/files termux InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 906F5AFA9A32C72D
Err:6 https://dl.bintray.com/grimler/game-packages-24 games Release.gpg
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5AAAC9E0A46BE53C
Get:7 https://dl.bintray.com/grimler/science-packages-21 science Release [5348 B]
Get:8 https://dl.bintray.com/grimler/science-packages-21 science Release.gpg [475 B]
Err:8 https://dl.bintray.com/grimler/science-packages-21 science Release.gpg
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5AAAC9E0A46BE53C
Reading package lists... Done
W: GPG error: https://its-pointless.github.io/files termux InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 906F5AFA9A32C72D
E: The repository 'https://its-pointless.github.io/files termux InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.bintray.com/grimler/game-packages-24 games Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5AAAC9E0A46BE53C
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.bintray.com/grimler/science-packages-21 science Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5AAAC9E0A46BE53C

How can I do?

**Comment by Grimler91** [comment]
@gemini4545 you don't have its-pointless' key. Get it by following instructions in readme here: https://github.com/its-pointless/gcc_termux

You also seem to be subscribed to both android-7 repositories (game-packages-24) and android-5 repositories (http://mirrors.tuna.tsinghua.edu.cn/termux, science-packages-21, https://its-pointless.github.io/files). This is weird, you should either use only android-5 or only android-7 repositories.

Also, you're not connecting to http://mirrors.tuna.tsinghua.edu.cn/termux over https even though the mirror supports https, I would change the url to use https.

**Comment by gemini4545** [comment]
@Grimler91 Thank you so much, I seem begin to understand the reasons behind, but since I'm fresh new for termux or even for linux actally, so it's a little hard for me to follow the README, and not sure how to opperate using only one repositories, and use https. 
Could the command code be provided seperating from the comment?
Really appreciate!

**Comment by priyalpaladiya** [comment]
I am facing this error


apt update
Hit:1 https://termux.net stable InRelease
Err:1 https://termux.net stable InRelease
  Unknown error executing apt-key
Ign:2 https://dl.bintray.com/grimler/game-packages-21 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-21 science InRelease
Err:4 https://dl.bintray.com/grimler/game-packages-21 games Release
  403  Forbidden
Err:5 https://dl.bintray.com/grimler/science-packages-21 science Release
  403  Forbidden
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://termux.net stable InRelease: Unknown error executing apt-key
E: The repository 'https://dl.bintray.com/grimler/game-packages-21 games Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://dl.bintray.com/grimler/science-packages-21 science Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by agnostic-apollo** [comment]
@priyalpaladiya check #6726

**Comment by agnostic-apollo** [comment]
@priyalpaladiya Check https://github.com/termux/termux-app/issues/2115#issuecomment-855544280 instead.
