### ISSUE TITLE
Midnight Commander: Cannot link executable

### ISSUE THREAD

**Issue by RombalC** [termux/termux-packages#3921]
$ mc
CANNOT LINK EXECUTABLE "mc": cannot locate symbol "__aeabi_d2ulz" referenced by "/data/data/com.termux/files/usr/bin/mc"...
Aborted

$mcedit
CANNOT LINK EXECUTABLE "mcedit": cannot locate symbol "__aeabi_d2ulz" referenced by "/data/data/com.termux/files/usr/bin/mc"...
Aborted

**Comment by xeffyr** [comment]
You didn't posted any of:

1. `termux-info`

2. `apt show mc`

*On all my devices `mc` and `mcedit` working without linking errors.*

**Comment by RombalC** [comment]
$ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.9.77+ #1 SMP PREEMPT Mon Apr 15 22:14:00 WIB 2019 armv7l Android
Termux-packages arch:
arm
Android version:
8.1.0
Device manufacturer:
Xiaomi
Device model:
Redmi 6A

$ apt show mc
Package: mc
Version: 4.8.22-3
Maintainer: Fredrik Fornwall @fornwall
Installed-Size: 2552 kB
Depends: libandroid-support, libiconv, ncurses, glib, openssl, libssh2, zlib
Homepage: https://www.midnight-commander.org/
Download-Size: 538 kB
APT-Manual-Installed: yes
APT-Sources: https://dl.bintray.com/termux/termux-packages-24 stable/main arm Packages
Description: Midnight Commander - a powerful file manager

**Comment by xeffyr** [comment]
Should be fixed in `4.8.22-4`.

**Comment by gridmeister** [comment]
Fixed in 4.8.22-4 but in mc_4.8.23 again

CANNOT LINK EXECUTABLE "mc": cannot locate symbol "__aeabi_d2ulz" referenced by "/data/data/com.termux/files/usr/bin/mc"...
Aborted

mc_4.8.23_arm.deb

$ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.14.29 #23 SMP PREEMPT Tue Nov 27 22:37:50 CST 2018 armv8l Android
Termux-packages arch:
arm
Android version:
7.1.2
Device manufacturer:
Amlogic
Device model:
X96mini

**Comment by xeffyr** [comment]
> but in mc_4.8.23 again

https://github.com/termux/termux-packages/issues/4027
