### ISSUE TITLE
Package Request: notmuch

### ISSUE THREAD

**Issue by BrainDamage** [termux/termux-packages#394]
https://notmuchmail.org/ is a fast mail indexer, which optionally integrates with emacs, mutt, vim, etc

**Comment by Neo-Oli** [comment]
I'd also like to see notmuch on termux, since my entire mailsystem now runs exclusively on termux.

**Comment by tristan-k** [comment]
@Neo-Oli Can you elaborate how you do email with termux? I'm curious.

**Comment by Neo-Oli** [comment]
@tristan-k. I like nothing more than to talk about my email setup. Be ready for a long essay. It has many components and is the result of months of configuration tweaking. I'd suggest you start small; connect mutt to gmail to try it out. 

But here's my entire email system: 

# Reading Emails

I use mutt as my email reader. When I started with termux I was still using gmail. After discovering mutt in the repository I set that up with mutt. There are various tutorials for that and they all work without a problem in Termux.

## Dealing with html emails

mutt is a console reader. It can only display text files. But as a fairly standard config you have w3m that converts html-only emails to plain text. 

## Viewing attachments

In the ~/.mailcap file you can set programs to use to open various files according to mime type. You can use `xdg-open` to open most files, which will open them in whatever android app "feels" capable of opening them. 


# Receiving Emails
Mutt connects to the imap server of gmail and shows remote mails. This is fairly slow. This way mutt is more of a handicap compared to the web interface of gmail. A few months ago I decided to switch away from gmail to another email service with my own domain. I was still connecting via imap and it was still slow. But imap functionality is a bit of an afterthought anyway. It's real strength is dealing with maildir or mbox mail storage formats. I decided on maildir.
I am using getmail (in the apt repository) to receive messages. I am running busybox's cron which periodically runs this command, which downloads all emails to `~/mail` (and deletes it on the server). To emulate gmails filters I wrote [my own script](https://gist.github.com/Neo-Oli/c56bb216a83e5a9ac7f6e453050b8fbc) that I hook into the postprocessor of getmail.

I also run a cron job for this [script that I wrote](https://gist.github.com/Neo-Oli/50b3ef5f3895953f61f0864afb329b41). It checks the `~/mail/new` for new messages and creates a `termux-notification` for each and removes it again when the email was read or mutt was opened. 
[screenshot](https://cloud.githubusercontent.com/assets/7983745/24743733/9c5f115e-1aaf-11e7-807a-1e837a1f4dd1.png). 

# Sending Emails

Mutt is perfectly able to send emails. You can put an smtp server into the config and everything will just work. The problem for me was that it means that I need internet to send an email. I want to just press send and it sends the email whenever I have internet. For example, I want to write a bunch of emails on an airplane that get sent automatically after I landed. 
For this I set mutt to not send any emails (I actually had to define a script that does nothing in the mutt config as an external sendmail programm), but copy of the "sent" mail to my .outbox mailbox. Then I have [this script](https://gist.github.com/Neo-Oli/99dcc837fe9c62eca5bc1814edd3a228), which I run as a cronjob as well, that sends all mails in my `~/mail/.outbox` folder with busybox's sendmail. If the sending fails because I have no internet connection, it will just try to send at the next cronjob interval again. After it is sent it will move it to the `~/mail/.sent` mailbox.

# Backing up emails
I have a folder. It lives in `/storage/54E2-F956/Android/data/com.termux/files/drive` (so termux has full access to it) on my 128 GB SD Card. **All** my files are in there. Emails, Photos, Videos, Music, Projects and Emails. A cronjob runs a script that `rsync`s this folder very night to a computer at my home. From there I back it to another computer once a week. I also use [bup](https://bup.github.io/) on the (nightly) computer to create snapshots that I can restore files from. All this has nothing really to do with my email setup. But I wrote earlier that my mail folder is `~/mail`. The reason is that the external SD card has the `exfat` file system. Maildir (which, as opposed to mbox, saves every email as an individual file) has a filename format that includes a `:`. Semicolons aren't allowed on `exfat` file system. But I still wanted the emails to be in that `drive` folder for nightly backups. I could have zipped them, but then each night a huge file would have to be `rsync`ed to my backups. [This](https://gist.github.com/Neo-Oli/817dcbb87e76deb5630ae808452d19a0) is the part in my backup script that deals with this. It creates a symlink of every email in `/data/data/com.termux/files/usr/tmp/mailbackuptemp`, but replacing all occurences of `:` with `%%%%%`. Then it `rsync`s this to my SD card with the `-L` switch, which converts symlinks to real files. I also have [this script](https://gist.github.com/Neo-Oli/15a3a1f8d31035c454231dc6998cfe43), which restores the original files in `~/mail` (replacing '%%%%%' with ':' again)


# Conclusion

What this all means is that all my email lives in my Termux. I have no way of viewing my emails outside of Termux. It allows me a great deal of flexibility.  I can configure it all exactly to my liking. It has grown over months to an absolute moloch of different gears in my system. You don't have to start out that way. Mutt is fairly easy to configure using external email providers and imap. But searching things gets really fast when you have a local email storage.  And it would get even faster if `notmuch `was available on Termux

Let me know if you have any questions or want me to elaborate on a specific part.

**Comment by vishalbiswas** [comment]
@Neo-Oli If you typed all that on Termux, I'ld like to know what keyboard do you use?

**Comment by Neo-Oli** [comment]
@vishalbiswas I didn't. But I almost always use termux through SSH from a Laptop or Desktop so wouldn't be a problem. I even do all my development on Termux (Python and webdev). As for actual keyboard suggestions, I use SwiftKey as a keyboard (because of the only acceptable multilingual support I've seen). I also have a [Logitech K480](https://www.logitech.com/en-us/product/multi-device-keyboard-k480) Bluetooth keyboard that works fairly well but it doesn't have great keys.

**Comment by fornwall** [comment]
There is now a `notmuch` package available - install it with `packages install notmuch`.

It's completely untested, let me know if there are any problems!
