### ISSUE TITLE
Can't use dart-sdk anywhere else

### ISSUE THREAD

**Issue by AugustToko** [termux/termux-packages#3944]
**Problem description**
I installed dartsdk using **pkg install dart** in the terminal. When I move dartsdk to the **/data/local/tmp** directory and go to the sdk folder bin directory, execute **./pub** and return it to me **/system/bin/sh: ./pub: Permission denied.**
But I executed **./dart --version** and it was normal to return it to my version of dartvm.
I got the same error even with **chmod +x ./pub**, or changed the file owner.

_Except for **dart**, other commands cannot be used._

**Steps to reproduce**
1. use **pkg install dart**
2. move dart-sdk dir to **/data/local/tmp**
3. Use the adb shell tool to go to **/data/local/tmp/dart-sdk/bin**
4. Execute the command **./pub**
5. see error

**Additional information**
I use the id in the terminal to get uid (use **id**), then use **su uid(just got uid)** in the adb shell , and then execute **./pub** it runs normally (prompt me can't find bash, I know this is an environment variable)

**Comment by Grimler91** [comment]
Moving files to other locations is not possible. They are compiled for `/data/data/com.termux/files/usr` as prefix and excepts libraries, config files and other stuff to be in that prefix.
When you try to execute pub from adb it tries to access `/data/data/com.termux/files/usr/` but since you aren't "logged in" as the termux user you don't have access to that files. 

Why do you want to execute it from an adb shell? `ssh`ing into termux ([over USB possibly](https://glow.li/technology/2016/9/20/access-termux-via-usb/)) feels like a better option

**Comment by AugustToko** [comment]
> Moving files to other locations is not possible. They are compiled for `/data/data/com.termux/files/usr` as prefix and excepts libraries, config files and other stuff to be in that prefix.
> When you try to execute pub from adb it tries to access `/data/data/com.termux/files/usr/` but since you aren't "logged in" as the termux user you don't have access to that files.
> 
> Why do you want to execute it from an adb shell? `ssh`ing into termux ([over USB possibly](https://glow.li/technology/2016/9/20/access-termux-via-usb/)) feels like a better option

Thank you very much for your prompt reply, I tried to use dart-sdk in my own application (via `Runtime.getRuntime().exec()`). It seems that I should compile dart-sdk myself.
