### ISSUE TITLE
Android 5.1 (aarch64) dnsutils don't work

### ISSUE THREAD

**Issue by Vasya-Kl** [termux/termux-packages#4003]
Termux 0.72 (w. su)
dnsutils 9.14.2

$
$ dig
$ nslookup
$ which dig
/data/data/com.termux/files/usr/bin/dig
$ ls -la /data/data/com.termux/files/usr/bin/dig
-rwx------ 1 u0_a40 u0_a40 135256 May 23 17:24 /data/data/com.termux/files/usr/bin/dig
$ 

Help please.

**Comment by Avevad** [comment]
Have some problems with the package too:
```
$ dig
CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "dns_categories" referenced by "libns.so"...
$ nslookup
CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "dns_categories" referenced by "libns.so"...
```

**Comment by its-pointless** [comment]
whats occurring looks to be a linking issue with android 5 where symbols aren't global. the symbol "dns_catagories" is in libdns.so and its  undefined libns.so but libns.so does not link against libdns.so so when libns.so loads it can't find the symbol "dns_catagories". But in android 6 the bug is fixed and so libns.so does find the symbol. 

if i find time i will fix it.

**Comment by its-pointless** [comment]
LD_PRELOAD=$PREFIX/lib/libdns.so:$PREFIX/lib/libisccfg.so:$PREFIX/lib/libisc.so dig works ...

**Comment by its-pointless** [comment]
a solution ... #4007

**Comment by Vasya-Kl** [comment]
> LD_PRELOAD=$PREFIX/lib/libdns.so:$PREFIX/lib/libisccfg.so:$PREFIX/lib/libisc.so dig works ...

Work for me.

Thx.

**Comment by Grimler91** [comment]
Closing as duplicate of https://github.com/termux/termux-packages/issues/3440
