### ISSUE TITLE
Rust cargo failed to create package

### ISSUE THREAD

**Issue by aquaductape** [termux/termux-packages#4081]
Trying to create a cargo package with command `cargo new hello`. I made sure to set the `$USER` by doing this command `USER=xyz`. But i still get an error.
```
Failed to create package `hello` at `/data/data/com.termux/files/home/hello`

Caused by:
  could not determine the current user, please set $USER
```
I use Galaxy s10e

**Comment by RossComputerGuy** [comment]
set USER to the output of whoami.On Jul 21, 2019 12:19 PM, Caleb Taylor <notifications@github.com> wrote:Trying to create a cargo package with command cargo new hello. I made sure to set the $USER by doing this command USER=xyz. I get an error.
Failed to create package `hello` at `/data/data/com.termux/files/home/hello`

Caused by:
  could not determine the current user, please set $USER

I use Galaxy s10e

**Comment by aquaductape** [comment]
Didn't work. My `whoami` output is `u0_a273`. I set $USER to it `USER=u0_a273`. Same error message.

**Comment by aquaductape** [comment]
Ok i got it to work. I wrote the set $USER command wrong. Correct one is `export USER=xyz`, doesn't have to be the value from `whoami`.
