### ISSUE TITLE
PyStan

### ISSUE THREAD

**Issue by StephenDeSalvo** [termux/termux-packages#4085]
Time series analysis.  This package gives direct access to the full functionality of STAN.  

Running pip install pystan caused Terminux to crash while it was running the setup.py file.

**Comment by RossComputerGuy** [comment]
I noticed while trying pip install pystan, my phone seemed to have slowed, heated up, and other apps reopened when i went back to them. When reopenening termux, the entire app restarted.Tested on Samsung Galaxy S8.On Jul 21, 2019 4:55 PM, Stephen DeSalvo <notifications@github.com> wrote:Time series analysis.  This package gives direct access to the full functionality of STAN.
Running pip install pystan caused Terminux to crash while it was running the setup.py file.

**Comment by Grimler91** [comment]
Termux is killed sometimes for me and sometimes not when trying to install it. This happens on my galaxy s8+ (6 GB ram).

Doesn't seem like python3 is supported so you probably want to use `pip2 install pystan` instead of `pip install pystan`.

Running git cloning pystan, checking out v2.19.0.0 and then running `python2 setup.py --verbose install &> system.log` shows that it fails with:
```
[...]
aarch64-linux-android-clang: pystan/stan/src/stan/lang/grammars/functions_grammar_inst.cpp
aarch64-linux-android-clang: pystan/stan/src/stan/lang/grammars/block_var_decls_grammar_inst.cpp
7 warnings generated.
aarch64-linux-android-clang: pystan/stan/src/stan/lang/grammars/term_grammar_inst.cpp
clang-8: error: unable to execute command: Hangup
clang-8: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 8.0.0 (tags/RELEASE_800/final)
Target: aarch64-unknown-linux-android
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/bin
clang-8: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang-8: error: unable to execute command: Hangup
clang-8: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 8.0.0 (tags/RELEASE_800/final)
Target: aarch64-unknown-linux-android
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/bin
clang-8: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
[...]
```

**Comment by xeffyr** [comment]
Clang issue exactly same as in https://github.com/termux/termux-packages/issues/3005. Some CPP code can trigger clang to use large amount of RAM, up to 1-2 GB.

And since amount of spawned clang instances is usually same as device cores, RAM usage can be much higher (for 8 core device it can be >12 GB).

**Comment by xeffyr** [comment]
We don't package python modules, mostly due to issues with native extensions cross-compilation. But perhaps it is time to try https://pypi.org/project/distutilscross/ ?

**Comment by RossComputerGuy** [comment]
Maybe, if we do that then we could also get some other packages that require python modules to work.
