### ISSUE TITLE
Can't remove vi

### ISSUE THREAD

**Issue by Exaeta** [termux/termux-packages#409]
The package 'vi' is always installed and can't be removed. Unfortunately it seems to have been set as my default editor...

**Comment by Neo-Oli** [comment]
Vi can not be removed. But you can just overwrite the $EDITOR variable in your .barh_profile or your .zshrc

`export EDITOR=nvim`

**Comment by fornwall** [comment]
The `vi` program is bart of the `busybox` package and can be considered a fallback editor that can save you if you screw up the system (since busybox is not linked against any Termux-provided shared library).

As @Neo-Oli says you can still set the `EDITOR` environment variable to configure your default editor.
