### ISSUE TITLE
Package 'python-dev' has no installation candidate

### ISSUE THREAD

**Issue by Pavan-kalyan-thota** [termux/termux-packages#4151]
**Problem description**
I am trying to install python-dev package
![IMG_20190807_193339](https://user-images.githubusercontent.com/45842100/62629166-4baf2a00-b94a-11e9-83f9-a0e90568223b.jpg)
I am new to termux. So requesting for help.

**Comment by xeffyr** [comment]
`python-dev` is replaced by `python`.
https://wiki.termux.com/wiki/No_more_-dev_packages

**Comment by Pavan-kalyan-thota** [comment]
Does that mean I can use python I stead of python-dev

**Comment by xeffyr** [comment]
Yes.

**Comment by stalkerned** [comment]
please return python-dev. many libraries do not work without python-dev. pyinstaller does not work for me, asks python-dev

**Comment by xeffyr** [comment]
@stalkerned No. Now package "python" contains both `python` and `python-dev`. Same goes for all dev packages. They will not be returned because **they are merged into one package**.

> OSError: Python library not found: libpython3.7m.so.1.0, libpython3.7m.so, libpython3.7.so.1.0, libpython3.7mu.so.1.0
This would mean your Python installation doesn't come with proper library files.
This usually happens by missing development package, or unsuitable build parameters of Python installation.

These libraries were never part of dev package.

**Comment by xeffyr** [comment]
Development packages are Debian-specific thing, but Termux isn't Debian and doesn't follow its way.
