### ISSUE TITLE
I get an error when trying to install packages

### ISSUE THREAD

**Issue by AadiRajUthup** [termux/termux-packages#4201]
$pkg install git                            
 Hit:1 https://termux.net stable InRelease
Get:3 https://hax4us.github.io/termux-tools extras InRelease [5670 B]
Ign:4 https://hax4us.github.io/termux-tools termux InRelease
Ign:5 https://termux-x11.ml x11 InRelease
Err:6 https://hax4us.github.io/termux-tools termux Release
  404
Err:7 https://termux-x11.ml x11 Release
  404
Ign:8 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:9 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Ign:10 https://dl.bintray.com/xeffyr/unstable-packages-24 unstable InRelease
Err:2 https://Auxilus.github.io termux InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A02DAB86B7A6E4BE
Ign:11 https://dl.bintray.com/xeffyr/x11-packages-21 x11 InRelease
Get:12 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Hit:12 https://dl.bintray.com/grimler/game-packages-24 games Release
Ign:3 https://hax4us.github.io/termux-tools extras InRelease
Get:14 https://dl.bintray.com/grimler/science-packages-24 science Release [5348 B]
Hit:14 https://dl.bintray.com/grimler/science-packages-24 science Release
Get:16 https://dl.bintray.com/xeffyr/unstable-packages-24 unstable Release [6065 B]
Hit:16 https://dl.bintray.com/xeffyr/unstable-packages-24 unstable Release
Get:18 https://dl.bintray.com/xeffyr/x11-packages-21 x11 Release [6055 B]
Hit:18 https://dl.bintray.com/xeffyr/x11-packages-21 x11 Release
Reading package lists... Done
E: The repository 'https://hax4us.github.io/termux-tools termux Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://termux-x11.ml x11 Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://Auxilus.github.io termux InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A02DAB86B7A6E4BE
E: The repository 'https://Auxilus.github.io termux InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://hax4us.github.io/termux-tools extras InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5A13A121F25D06F7
W: Target Packages (main/binary-aarch64/Packages) is configured multiple times in /data/data/com.termux/files/usr/etc/apt/sources.list:3 and /data/data/com.termux/files/usr/etc/apt/sources.list.d/hax4us.list:1
W: Target Packages (main/binary-all/Packages) is configured multiple times in /data/data/com.termux/files/usr/etc/apt/sources.list:3 and /data/data/com.termux/files/usr/etc/apt/sources.list.d/hax4us.list:1
W: Target Packages (main/binary-aarch64/Packages) is configured multiple times in /data/data/com.termux/files/usr/etc/apt/sources.list:3 and /data/data/com.termux/files/usr/etc/apt/sources.list.d/hax4us.list:1
W: Target Packages (main/binary-all/Packages) is configured multiple times in /data/data/com.termux/files/usr/etc/apt/sources.list:3 and /data/data/com.termux/files/usr/etc/apt/sources.list.d/hax4us.list:1
 /data/data/com.termux/files/usr/etc/apt

**Comment by xeffyr** [comment]
> E: The repository 'https://hax4us.github.io/termux-tools termux Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://termux-x11.ml x11 Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://Auxilus.github.io termux InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A02DAB86B7A6E4BE
E: The repository 'https://Auxilus.github.io termux InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://hax4us.github.io/termux-tools extras InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5A13A121F25D06F7

Do not use repositories that are no longer exist or not maintained.

**Comment by AadiRajUthup** [comment]
Please help

**Comment by xeffyr** [comment]
Remove any of urls that are not working.

Specifically https://termux-x11.ml/ is no longer APT repository.

**Comment by xeffyr** [comment]
If you are following third-party tutorials, you take care about all errors they are producing.
