### ISSUE TITLE
How can i move all termux files from my internal storage to sd card my termux has sd card permission?

### ISSUE THREAD

**Issue by InsaNe1430** [termux/termux-packages#4309]
**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by InsaNe1430** [comment]
I want o to move my termux files to sdcard my internal storage is not sooo much pleade help

**Comment by xeffyr** [comment]
Moving to external SD card is not supported.

**Comment by xeffyr** [comment]
Answer in FAQ btw: https://wiki.termux.com/wiki/FAQ

**Comment by isrgish** [comment]
This can be done but it's not for the faint of heart.
Here is a general idea.
1. Format an sd card (or a 2nd partition) as ext4.
2. Mount it manually.
3. Copy over the usr folder to a folder on the sd card.
4. Delete the usr folder from your device.
5. Make a symlink where the usr folder was, which is in `/data/data/com.termux/files` name it `usr`.
6. Viola you've got it done.

The main challange is that once you delete the `usr` folder from your device, you don't have accsess to your full termux installation.                                                What I did was as follows:
1. When you start termux without a full installation, termux insta;ls a minimial version of packages. Since we already have a file named `usr` it installs it as `usr-staging`.
2. I used failsafe mode to rename `usr` which is the link to our termux installation on the sd card. I renamed it to `usr-temp`. Then I renamed `usr-staging` to `usr`. Now I have a working minimal installation.
3. I installed the tsu package locally (downloaded in advance).
4. Now I was able to manually mount the sd card.
5. Now I renamed `usr` to `usr-staging` and `usr-temp` to `usr` for this you need to use again a failsafe session ans use mv from `/system/bin`.

You can setup a script to run everytime you reboot. I also use Total Commander to run an su command to mount it.

**Comment by dbcoopersbenjamins** [comment]
> Moving to external SD card is not supported and won't be.

Unless you change it in the developer options to force apps to external.... Idk, js

**Comment by xeffyr** [comment]
> Unless you change it in the developer options to force apps to external

This doesn't work because Termux hardcodes everywhere in packages internal storage installation path:
```
/data/data/com.termux/...
```
Moving it breaks everything.

**Comment by dbcoopersbenjamins** [comment]
Hey after looking back, I realized how it seems I came across as
condescending. I really wasn't, I was just throwing an idea out there to
try and help. So I apologize if I seemed offensive.
