### ISSUE TITLE
OpenVPN doesn't hide my IP

### ISSUE THREAD

**Issue by IRISnoir** [termux/termux-packages#4392]
Hello, I am trying to use OpenVPN to hide myself. But when I initiate it like I am supposed to, the success message appears but the effect does not as when I look up my own IP, the results show me my own IP and not a protected one.

**Comment by xeffyr** [comment]
Please, read the answer here: https://github.com/termux/termux-root-packages/issues/123#issuecomment-525723854.

I provided OpenVPN package as-is due to multiple requests. It doesn't work on Android out-of-box because of incorrect routes from Android's view point. You should configure them manually, according to your device's needs. We can't do that.
