### ISSUE TITLE
bs1770gain is maintained by someone with hate group affiliations

### ISSUE THREAD

**Issue by jkatzmewing** [termux/termux-packages#4455]
So normally I wouldn't post this kind of thing, but this is pretty extreme; the maintainer dedicates bs1770gain to his "European heritage", and his personal site is full of barely veiled neo-Nazi rhetoric.

Note that both the following links are NSFW; the second is basically a hate site, and in the first Belkner shows an inability to keep propaganda out of the changelog.

http://bs1770gain.sourceforge.net/
http://home.snafu.de/pbelkner/

I would suggest removing this package from the repo. Again, normally I wouldn't suggest this kind of intervention, but Belkner is very open with his racism; IMO hosting software that links back to his hate sites is giving him a platform to spread hate.

**Comment by Grimler91** [comment]
Thanks for starting this discussion.
@Neo-Oli removed himself as TERMUX_PKG_MAINTAINER for the same reason: https://github.com/termux/termux-packages/pull/2736

I wonder if other distros are having similar discussions? 
I'll add it to the agenda for Sunday's [development meeting](https://wiki.termux.com/wiki/Dev:Development_Session_42).

If someone feels strongly that the package should be kept then please comment here. 
To be very clear, note that "freedom of speech" or "don't censor" are not valid reasons for keeping the package since: 

- We are not obligated to spread the author's package, or messages

- We are not stopping the author from sharing his world view

**Comment by jkatzmewing** [comment]
Aye, thanks @Grimler91.

I just noticed that the software is also in Debian and Ubuntu repos; I'm guessing it predates Belkner's swing into open bigotry.

**Comment by Neo-Oli** [comment]
So, I've followed this closely since I first noticed last year and found the following discussions and their result.

### Debian
Debian  maintainers [concluded](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=913352) that the racist statements go against the Free Software Guidelines (DFSG) and the [Diversity Statement](https://www.debian.org/intro/diversity) and have for now [patched out](https://sources.debian.org/patches/bs1770gain/0.5.2-2/2000-non-controversial-usage.patch/) the offending message the software prints on startup. They have raised concerns about linking to the project webpage and the code still being in the source code where other developers have to look at it. 

### Arch Linux
Arch Linux has also [patched out](https://git.archlinux.org/svntogit/community.git/tree/trunk/remove-inappropriate-text.patch?h=packages/bs1770gain) the offending statements.

### CentOS
On CentOS bs1770gain was packaged by a left radio station. They were one of the first that removed all support from the package and issued a statement [in place of the package repository](https://github.com/radiorabe/centos-rpm-bs1770gain). 

### Beets
Beets is music library management tool. It is one of the main reasons to use bs1770gain (and also the reason why I initially packaged bs1770gain). After [a discussion ](https://github.com/beetbox/beets/issues/3127) it removed all mention of bs1770gain from the documentation. It is still an undocumented feature, but I think the latest version of bs1770gain doesn't work anymore with it. The version Termux packages still works. 
It will possibly be removed altogether in the future.


I haven't really found any examples where something similar happened with other software. But I had a lot of discussions about this with a few different people. Most people seem to conclude that forking such software would be the best course of action in such cases. I did indeed find one fork of bs1770gain called [iwwbs1770](https://github.com/tildejoy/iwwbs1770) by @tildejoy that does precisely that. Though if this turns out to be a well maintained fork remains to be seen

**Comment by RossComputerGuy** [comment]
If the software is not critically or fully required by any packages we have then I believe we should remove the package to not associate ourselves with whats happening. It's better to disassociate than to remove the racial bits.

**Comment by landfillbaby** [comment]
GStreamer and FFmpeg both have standards compliant loudness scanners, so it's not like this package fills a niche or anything.

**Comment by xeffyr** [comment]
Package is now removed and no longer installable (except for installations using `termux.net`, but that will be fixed soon I guess).

**Comment by Neo-Oli** [comment]
For everyone who used bs1770gain with together with beets. As of version 1.5.0 of beets (which hasn't yet been released) it will support ffmpeg as a backend for replaygain. I tested this in termux and it works well.
 All you need to to is build beets from master (`pip install git+https://github.com/beetbox/beets.git`) or a version > 1.5.0 (when it gets released), install ffmpeg (`pkg install ffmpeg`) change the `backend` property of the replaygain plugin to `backend: ffmpeg`

**Comment by johnslippers** [comment]
This is absolute BS. I am not going to research what every developer stands for before using his code. If it works, it works. This cancel culture is getting retarted. If you want to struggle because somebody offended your grown-ass (something we all go through), don't make life harder for everybody else. People need to get a backbone and stop involving everybody in their fights. Stop being a Karen!

**Comment by Grimler91** [comment]
@johnslippers feel free to compile and use it then.

Developers are free to have whatever opinion they want. In this case the developer chose to incorporate statements into the software, i.e. use it to distribute their opinions, which we chose to not facilitate.
