### ISSUE TITLE
No rustc in 1.38.0-1

### ISSUE THREAD

**Issue by roalyr** [termux/termux-packages#4457]
Updated rust with 'apt upgrade', rustc binary doesn't seem to be in the .deb
![Screenshot_20191025_105323](https://user-images.githubusercontent.com/46825200/67553454-dca9cc00-f715-11e9-8d05-9d83efc2403b.jpg)

**Comment by roalyr** [comment]
Updated to 1.38.0-2 still no rustc.

**Comment by its-pointless** [comment]
I will fix build in a second. This didn't show up in testing on  my machine due to differences in scripts and build env. Sorry about that.

**Comment by roalyr** [comment]
All works now.

**Comment by glella** [comment]
Just updated to 1.38.0-1 and rustc does not seem to be there, despite it seems you fixed this exact same thing a few days ago

**Comment by xeffyr** [comment]
> Just updated to 1.38.0-1

Rust `1.38.0-1` is already there, unless you are on Android 5.

**Comment by karanrathod907** [comment]
hi wanna help to install python3

**Comment by roalyr** [comment]
1.38.0-2 didn't work either, it was 1.38.0-3 that worked properly. Currently 1.38.0-3 is the most recent version according to `apt-cache policy rust`.

**Comment by glella** [comment]
oops, thanks for the clarification. Now will try using 1.38.0-3. Newbie question then: on Termux if I do "pkg upgrade" or "pkg install" I only see ver 1.38.0-1 (with no rustc). How to I get the 1.38.0-3 version? Need to switch to some other "nightly" build?

**Comment by xeffyr** [comment]
Just wait until @fornwall compile it.
Right now it is not available for legacy Termux environments.

**Comment by glella** [comment]
Understood. Will wait. Thank you

**Comment by glella** [comment]
@xeffyr re-reading your comment above, could you clarify:
- what do you mean "for legacy Termux environments"
- "It requires some fixes". Previous version worked perfectly fine. Minor tweaks or something broke?
If I can help in any way please let me know

**Comment by xeffyr** [comment]
> what do you mean "for legacy Termux environments"

There are 2 types of Termux environment:

1. Legacy, for devices running Android 5 and 6 but may run on higher Android versions with certain restrictions. Located at `termux.net`. Packages built manually by @fornwall, so delays are expected. Supporting will be finished after 01.01.2020.

2. Another environment is for Android 7+ to obtain various benefits of newer libc and do not care about `LD_LIBRARY_PATH` and things missing on Android 5. Packages for Android 7+ will fail on older devices. Located at https://bintray.com/termux/termux-packages-24. Package builds are automatic because [Bintray](https://bintray.com) offers API for handling generated \*.deb files.

> "It requires some fixes"

"Fixes" are https://github.com/termux/termux-packages/commit/4e993d60b5de3cad1afea7abc2b1dff8f229c540.

**Comment by glella** [comment]
Thank you. Now I understand what is going on. If I follow along this guide I should be able to link to the new master branch Android 7+, correct ?
[https://wiki.termux.com/wiki/Bintray_package_hosting](url)

**Comment by xeffyr** [comment]
No, this is old instruction.
Use `termux-upgrade-repo` and follow instructions it will print. Note that it will wipe $PREFIX so if you keep here some custom stuff, you will need to move it to $HOME temporarily.

**Comment by glella** [comment]
Excellent. Thank you. Worked perfectly and now I can use rust again !!
