### ISSUE TITLE
A issue about running the `am` command

### ISSUE THREAD

**Issue by ljd1996** [termux/termux-packages#4498]
When I run the `am` command in the [termux-app](https://github.com/termux/termux-app), I can get a normal result.
But when I use my own apt repository and a specified application id such as `com.test` to generate the bootstrap.zip through the [generate-bootstraps.sh](https://github.com/termux/termux-packaging/blob/master/scripts/generate-bootstraps.sh) in termux-packaging. The `am` command doesn`t work, the error message is as follows,
```shell
cmd: Failure calling service activity: Failed transation (2147483646)
```
 when I log in as the root user, the `am` command can be executed normally. Why is this?

**Comment by xeffyr** [comment]
This happens because everything is bound to Termux prefix and in some places it is *hardcoded*.

See 
https://github.com/termux/TermuxAm/blob/7a6a9d1f3cedca53de773501b565f189c770e6c1/am-libexec-packaged
and 
https://github.com/termux/TermuxAm/blob/7a6a9d1f3cedca53de773501b565f189c770e6c1/app/src/main/java/com/example/termuxam/IActivityManager.java#L32
