### ISSUE TITLE
Git clone username and password 

### ISSUE THREAD

**Issue by Raja5221** [termux/termux-packages#4500]
![Screenshot_2019-11-06-13-28-54-882_com termux](https://user-images.githubusercontent.com/57415178/68279536-a23b1a00-0099-11ea-8a58-9a2619943264.png)
![Screenshot_2019-11-06-13-29-13-840_com termux](https://user-images.githubusercontent.com/57415178/68279550-a830fb00-0099-11ea-8a08-a7e9118872bc.png)

**Comment by Raja5221** [comment]
Any one have solution

**Comment by aristarh2704** [comment]
Add "t" symbol at the end of command)

**Comment by 69MN69** [comment]
> Any one have solution

Try with your gmail. Dont try with your username

**Comment by IkayJnr** [comment]
Not working

**Comment by kcubeterm** [comment]
@IkayJnr make sure link is correct and that repo is public if you not own that,

**Comment by kith-hyzenburg** [comment]
Wheres the solution for this please

**Comment by xeffyr** [comment]
@kith-hyzenburg Here is a solution:
1. Ensure your URL has no typos.
2. Ensure that repository you are cloning exists or not private.

**Comment by Princewill4** [comment]
Still having same issues

**Comment by ChiefMikeK** [comment]
maybe try `pkg install gh` vice `$ git` ?

**Comment by xeffyr** [comment]
Already stated, that if `git` asks for password but it not works, then follow these troubleshooting steps:

1. Ensure your URL has no typos. This means: no truncated urls, like ending in `.gi` instead of `.git` (you may omit the ".git" though), no other typos like `gitub.com` instead of `github.com`. Check what you typing, shell won't correct your mistakes!

2. Ensure that repository you are cloning exists or not private. Git, at least in GitHub scope, does not distinguish private repositories from deleted or non-existent ones. If repository does not exist, you will be prompted for password anyway. If you got the repo link from social media, do not expect that it will be correct forever. Sometimes repositories are removed from public, typically due to unexpected attention from community or just being moved to another account.

If you really sure that repository is **private** and belongs to **your account**, try using a [personal access token](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token) instead of password. Remember that you can't clone private repositories to which you don't have access.

As already suggested, you may have better luck with `gh` - GitHub command line client.
