### ISSUE TITLE
Postgresql 11.5 

### ISSUE THREAD

**Issue by Paradox2019** [termux/termux-packages#4533]
Hello guys.

I am an developer from a small company and we have some trouble with the postgresql-package.

We have 2 mobile devices with android 7, termux installed and the package postgresql.
On the first device, there is Postgresql package version 10.5 installed. On the second one, there is the PostgreSQL package version 11.5 installed.

For information: Both devices have the same specs. 

We have a database which have to be installed on both devices. on device one we have no trouble with restoring the database from .SQL file. 
On the second device, it stucks on the same query every time. So that it is impossible for us, to restore the database to the second device. 

we use the command
psql -d databasename < backup.sql

the log files from postgresql didn´t show anything. Same for the debug level logging.

First, we thought that maybe the device is broken, so we decided to test a third device. Same problem with postgressql 11.5 :(

Is there any way to get the problem solved, maybe with the old 10.5 package of postgresql ? Can you provide the old package t install via pkg ?

Termux-info
Linux localhost 3.4.0 #1 SMP PREEMPT Wed Dec 13 20:16:59 IST 2017 armv71 Android
Termux-packages arch:
arm
Android Version:
5.1.1
Device manufacturer: 
Zebra Technologies
Device model:
TC75

I hope you can help us. :) Regards

**Comment by Grimler91** [comment]
You mention android 7 but the termux-info says android 5.1, which version(s) do you have?
Also, please don't truncate the output of `termux-info`, you have removed the part about subscribed repos so we now have no idea which postgresql 10.5 you need (the one from the android 5 bramch or the one from android 7 (master) branch). 

The proper thing to do is to update all packages on both devices so that you have updated packages (11.5) on both devices.

**Comment by Paradox2019** [comment]
Hey, sorry for bad answer. 
Sorry for my mistake. On both devices is android 5.1 installed. Not Android 7. 
I have subscribed the normal package repo. 

> The proper thing to do is to update all packages on both devices so that you have updated packages (11.5) on both devices.

Why should I upgrade from a working to a non-working version from postgres? 
As i said, the problem is: On the Device with the older Postgres-Version (10.5) installed, my database can be used without any problems. On the device with the newer (11.5) i cannot restore my database backup because it hangs without any error in logs.

**Comment by Grimler91** [comment]
So how did you create the backup? I guess you have read the [docs on how to move databases between postgresql versions](https://www.postgresql.org/docs/9.0/migration.html)?

**Comment by Paradox2019** [comment]
With pg_dump and with psql. Both. 
The Database is running on a normal server which is running postgresql 11.5. So i don´t understand why a backup shoud not run on postgresql 11.5 on the devices. :( On Postgresql 10.5 on the mobile devices it work properly.

**Comment by xeffyr** [comment]
Downgraded versions will not be added to to repository.

Android 5 postgresql 10.5 packages:

[postgresql_10.5_aarch64.deb.gz](https://github.com/termux/termux-packages/files/3846925/postgresql_10.5_aarch64.deb.gz)
[postgresql_10.5_arm.deb.gz](https://github.com/termux/termux-packages/files/3846926/postgresql_10.5_arm.deb.gz)
[postgresql_10.5_i686.deb.gz](https://github.com/termux/termux-packages/files/3846927/postgresql_10.5_i686.deb.gz)
[postgresql_10.5_x86_64.deb.gz](https://github.com/termux/termux-packages/files/3846928/postgresql_10.5_x86_64.deb.gz)

Android 7:
[postgresql_10.5_aarch64.deb.gz](https://github.com/termux/termux-packages/files/3847015/postgresql_10.5_aarch64.deb.gz)
[postgresql_10.5_arm.deb.gz](https://github.com/termux/termux-packages/files/3847016/postgresql_10.5_arm.deb.gz)
[postgresql_10.5_i686.deb.gz](https://github.com/termux/termux-packages/files/3847017/postgresql_10.5_i686.deb.gz)
[postgresql_10.5_x86_64.deb.gz](https://github.com/termux/termux-packages/files/3847018/postgresql_10.5_x86_64.deb.gz)

***

How-to:

1. Download package with right architecture (e.g. ARM devices should use \*_arm.deb package) and right Android version (Android 5 & 6 devices should use packages for Android 5).
2. Uncompress package with `gunzip /path/to/file` (had to gzip them due to Github's file type restrictions).
3. Install file with `dpkg -i /path/to/file`.

**Comment by Grimler91** [comment]
You probably need to upgrade all packages before being able to use the debs above, as they have been built against the latest versions of the dependencies

**Comment by Paradox2019** [comment]
> 
> 
> Downgraded versions will not be added to to repository.
> 
> Android 5 postgresql 10.5 packages:
> 
> [postgresql_10.5_aarch64.deb.gz](https://github.com/termux/termux-packages/files/3846925/postgresql_10.5_aarch64.deb.gz)
> [postgresql_10.5_arm.deb.gz](https://github.com/termux/termux-packages/files/3846926/postgresql_10.5_arm.deb.gz)
> [postgresql_10.5_i686.deb.gz](https://github.com/termux/termux-packages/files/3846927/postgresql_10.5_i686.deb.gz)
> [postgresql_10.5_x86_64.deb.gz](https://github.com/termux/termux-packages/files/3846928/postgresql_10.5_x86_64.deb.gz)
> 
> Android 7:
> [postgresql_10.5_aarch64.deb.gz](https://github.com/termux/termux-packages/files/3847015/postgresql_10.5_aarch64.deb.gz)
> [postgresql_10.5_arm.deb.gz](https://github.com/termux/termux-packages/files/3847016/postgresql_10.5_arm.deb.gz)
> [postgresql_10.5_i686.deb.gz](https://github.com/termux/termux-packages/files/3847017/postgresql_10.5_i686.deb.gz)
> [postgresql_10.5_x86_64.deb.gz](https://github.com/termux/termux-packages/files/3847018/postgresql_10.5_x86_64.deb.gz)
> 
> How-to:
> 
>     1. Download package with right architecture (e.g. ARM devices should use *_arm.deb package) and right Android version (Android 5 & 6 devices should use packages for Android 5).
> 
>     2. Uncompress package with `gunzip /path/to/file` (had to gzip them due to Github's file type restrictions).
> 
>     3. Install file with `dpkg -i /path/to/file`.

Installed the 10.5 Package for Android 5 to the second device (removed the 11.5 package) and see... The Database can be restored... Don´t know how this causes. :/ 

Thanks man !

**Comment by postsql** [comment]
it looks like changing dynamic_shared_memory_type could fix it also for newer versions, see #4812

**Comment by openlie** [comment]
> Hello guys.
> 
> I am an developer from a small company and we have some trouble with the postgresql-package.
> 
> We have 2 mobile devices with android 7, termux installed and the package postgresql.
> On the first device, there is Postgresql package version 10.5 installed. On the second one, there is the PostgreSQL package version 11.5 installed.
> 
> For information: Both devices have the same specs.
> 
> We have a database which have to be installed on both devices. on device one we have no trouble with restoring the database from .SQL file.
> On the second device, it stucks on the same query every time. So that it is impossible for us, to restore the database to the second device.
> 
> we use the command
> psql -d databasename < backup.sql
> 
> the log files from postgresql didn´t show anything. Same for the debug level logging.
> 
> First, we thought that maybe the device is broken, so we decided to test a third device. Same problem with postgressql 11.5 :(
> 
> Is there any way to get the problem solved, maybe with the old 10.5 package of postgresql ? Can you provide the old package t install via pkg ?
> 
> Termux-info
> Linux localhost 3.4.0 #1 SMP PREEMPT Wed Dec 13 20:16:59 IST 2017 armv71 Android
> Termux-packages arch:
> arm
> Android Version:
> 5.1.1
> Device manufacturer:
> Zebra Technologies
> Device model:
> TC75
> 
> I hope you can help us. :) Regards
