### ISSUE TITLE
How to open Android apps with Tor?

### ISSUE THREAD

**Issue by RasoolSaeedNejad** [termux/termux-packages#4543]
Hello.
I know there are two ways to open Android apps inside Termux:
For Exmaple:
1) `$ am start --user 0 -n com.android.chrome/com.google.android.apps.chrome.Main`
2) `$ termux-open-url https://youtube.com`

**Now**, what can I do to get the apps through **Tor**?

Thank You...

**Comment by xeffyr** [comment]
1. Use proxydroid to setup system proxy: https://play.google.com/store/apps/details?id=org.proxydroid
    Host: 127.0.0.1
    Port: 9050
    But ensure that you have tor daemon running and configuring socks5 protocol in app.
    I use https://adguard.com though.

2. Transparent proxy via /system/bin/iptables. Idea how to configure it you can got from https://trac.torproject.org/projects/tor/wiki/doc/TransparentProxy (instruction will require few changes in order to be used on Android).
