### ISSUE TITLE
continously delete a file if it exists while pid of app exists

### ISSUE THREAD

**Issue by lasansingh** [termux/termux-packages#4607]
I have an app, I want to continuously delete the specific file if it exists and run this script till my app closes?
i mean how can i do this in termux ?
i know for getting pid of system running apps i need to use root. I rooted my device.
```su -c pidof com.termux```
so run the script till pid of termux application exists

**Comment by xeffyr** [comment]
Variants for *preventing file creation*:

1. Replace file with directory:
```
rm -f /path/to/file
mkdir -p /path/to/file
```

2. Delete file and make parent directory read-only:
```
rm -f /parent/dir/file
chmod 500 /parent/dir
```

3. Truncate file and make it read only:
```
cat /dev/null > /path/to/file
chmod 400 /path/to/file
```

4. Truncate file and make it immutable (e2fsprogs package and root are needed):
```
cat /dev/null > /path/to/file
chattr +i /path/to/file
```

5. Just symlink file to /dev/null:
```
rm -f /path/to/file
ln -s /dev/null /path/to/file
```

***

Using loops like
```
while true; do
    rm -f /path/to/file
done
```
is the worst possible variant. Why:

* CPU usage will be up to 100 %.
* Race condition. There is significant probability that your program will be able to open file before it will be deleted. On Linux/Android files are just unlinked instead of being "deleted" and program having opened file descriptor will be able to write/read from deleted file.

**Comment by lasansingh** [comment]
@xeffyr suppose I symlink it to /dev/null then what will happen when the app tries to write to it?
is the symlink replaced with file or it will be redirected to /dev/null for truncation?
one more thing, some files reside in android internal storage then how is it possible to make symlinks in internal storage?

**Comment by xeffyr** [comment]
Symlink works like a file. In case if it points to /dev/null, everything that was written is discarded:
```
[xeffyr]:/tmp/test:$ echo foo > bar.txt
[xeffyr]:/tmp/test:$ cat bar.txt 
foo
[xeffyr]:/tmp/test:$ rm -f bar.txt 
[xeffyr]:/tmp/test:$ ln -s /dev/null bar.txt
[xeffyr]:/tmp/test:$ echo foo > bar.txt
[xeffyr]:/tmp/test:$ cat bar.txt
```
Program will not know whether written data is really written to that file (unless it doesn't verify file contents).

For shared storage you may use trick with directory named as file:
```
[xeffyr]:/tmp/test:$ echo foo > bar.txt
[xeffyr]:/tmp/test:$ cat bar.txt 
foo
[xeffyr]:/tmp/test:$ rm -f bar.txt 
[xeffyr]:/tmp/test:$ mkdir bar.txt
[xeffyr]:/tmp/test:$ echo foo > bar.txt
bash: bar.txt: Is a directory
```

Or (if you have root), you can create empty file on internal storage and make it immutable (everything available on /storage/emulated/0 is stored in /data/media):
```
pkg install e2fsprogs
tsu
cd /data/media/0/       # directory in /data/media may be device-specific
cat /dev/null > ./path/to/file
chattr +i ./path/to/file
```
