### ISSUE TITLE
node-sass fails to run, possibly from libuv

### ISSUE THREAD

**Issue by clshortfuse** [termux/termux-packages#462]
`npm install -g node-sass` compiles node-sass but when you actually try to run it, the following appears

`Error: dlopen failed: cannot locate symbol "uv_async_send" referenced by "/data/data/com.termux/files/usr/lib/node_modules/node-sass/vendor/android-arm64-48/binding.node"...`

I tried compiling libuv on my own in termux and using it, but then `node` completely breaks.

**Comment by clshortfuse** [comment]
It appears it's not just node-sass. serialport package gives the same error, except:

cannot locate symbol "uv_pull_init"

**Comment by clshortfuse** [comment]
Well, I got it to work by compiling it 6.6.0 manually.

`python configure --openssl-no-asm --dest-os=android --without-snapshot --dest-cpu=arm64 --without-inspector`

My only issue is having to termux-fix-shebang every npm package.

**Comment by fornwall** [comment]
@clshortfuse So, with a node compiled on the device you don't have the problem? Interesting!

**Comment by fornwall** [comment]
I've created an issue at https://github.com/android-ndk/ndk/issues/201 which may relate to this problem.

Building node.js on the device does perhaps fix the problem as a side effect of not using shared libraries (libuv is linked statically into the node binary)?

**Comment by fornwall** [comment]
What happens is:

- The node executable links against the libuv shared library.
- A lot of node packages with native code uses symbols from libuv.
- At runtime the `dlopen()` of shared libraries in node modules (such as `binding.node` above) fails due to libuv symbols not being resolved. This is caused by the Android linker, which does not use symbols in linked shared libraries to resolve symbols when other libraries are `dlopen()`:ed. As  mentioned in the above linked NDK issue this is unlikely to change due to backwards compatibility.

There are different solutions available:

1. Try to upstream a change to node (in `common.gypi` - I think) that every module is linked against libuv on Android (as every module).
2. Try to upstream changes to every node module using libuv symbols, in order to make them link explicitly against libuv on at least Android.
3. Build node.js against libuv statically. This means that the symbols are part of the executable and the `dlopen()` works.

I'm leaning against option (3) as the most practical (and perhaps elegant) solution.

**Comment by clshortfuse** [comment]
Yeah, I'll think packaging the libuv library makes most sense because it doesn't assume any guarantees in terms of how the operating system links symbols.

**Comment by fornwall** [comment]
@clshortfuse Thanks! This has now been fixed in the `6.6.0-1` update of the nodejs package, to which one can update with

    apt update && apt upgrade
