### ISSUE TITLE
Why is Termux Emacs loading so many packages?

### ISSUE THREAD

**Issue by makoto-yamashita** [termux/termux-packages#4739]
Termux Emacs is very slow due to the load of many packages.
When 
`emacs --daemon -Q`
is executed, 100 packages are loaded.
In particular, loading all the languages are very slow. 
(chinese, cyrillic, indian, sinhara, english, ethiopic, european, czech, slovak, romanian, greek , hebrew, japanese, korean, lao, tai-viet, thai, tibetan, vietnamese, georgian, khmer, burmese, cham)

How can we skip these files?

**Comment by Grimler91** [comment]
The reason you are seeing these packages being loaded is because our emacs is not dumped. You can play around with disabling packages by editing `$PREFIX/share/emacs/26.3/lisp/loadup.el`.

Note that it is possible to dump emacs with the new portable dumper, but I haven't figured out how to cross-compile a dumped emacs (see https://github.com/termux/termux-packages/pull/4622). 
It is possible to compile emacs on device though and get a fast-starting, dumped, emacs.

See also https://github.com/termux/termux-packages/issues/2856
