### ISSUE TITLE
Suggestion: please make help pages local.

### ISSUE THREAD

**Issue by tigran123** [termux/termux-packages#476]
The help pages (especially keyboard shortcuts) should not require internet connection. It would be very convenient if they were accessible locally without access to internet.

**Comment by xeffyr** [comment]
Since `termux-tools v0.95` man page `termux` is provided. Run `pkg upgrade` to ensure that latest version of `termux-tools` is installed.

Offline help will be supplied only as standard man page. Embedding help pages in HTML format inside the application will not happen. [Termux Wiki](https://wiki.termux.com/wiki/Main_Page) remains to be the main source of up-to-date information about Termux.
