### ISSUE TITLE
ziglang

### ISSUE THREAD

**Issue by yubrajbhoi** [termux/termux-packages#4760]
**Package description**
Zig is a general-purpose programming language designed for robustness, optimality, and maintainability.

**Link to home page and sources**
https://github.com/ziglang/zig

**Additional information**
It compiles fine using the embedded lld but in the linking step it gets struck on a atomic error.

**Comment by buttaface** [comment]
Zig apparently only has [Tier 2 support](https://ziglang.org/download/0.5.0/release-notes.html#Tier-2-Support) [for Android](https://ziglang.org/download/0.5.0/release-notes.html#Android-Support), so it's not ready yet. It seems to be moving fast though, you may want to try building it in Termux and help fill in whatever pieces it is missing.

**Comment by yubrajbhoi** [comment]
@buttaface an obvious patch is to add `"atomic"` to `target_link_libraries`. After that it gets stuck on LLVM errors.

**Comment by DolphinChips** [comment]
i've tried building zig yesterday on device, but it fails on linking. here's what i did so far:
* applied this little patch to zig repo:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 467918557..fb80a93d1 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -448,6 +448,8 @@ set_target_properties(zig0 PROPERTIES
     LINK_FLAGS ${EXE_LDFLAGS}
 )
 target_link_libraries(zig0 zigcompiler)
+target_link_libraries(zig0 atomic)
+target_link_libraries(zig0 android-spawn)
 
 if(MSVC)
     set(LIBSTAGE2 "${CMAKE_BINARY_DIR}/zigstage2.lib")
```
* after running `cmake ..`, manually changed in CMakeCache.txt line
```
ZIG_PREFER_CLANG_CPP_DYLIB:BOOL=off
```
to
```
ZIG_PREFER_CLANG_CPP_DYLIB:BOOL=on
```
after doing all of above, build fails with
```
[ 97%] Linking CXX executable zig0
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: zig_cpp/libzig_cpp.a(zig_clang_cc1_main.cpp.o): in function `long std::__ndk1::__libcpp_atomic_refcount_increment<long>(long&)':
/data/data/com.termux/files/usr/include/c++/v1/memory:3350: undefined reference to `__atomic_fetch_add_4'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: zig_cpp/libzig_cpp.a(zig_clang_cc1_main.cpp.o): in function `long std::__ndk1::__libcpp_atomic_refcount_decrement<long>(long&)':
/data/data/com.termux/files/usr/include/c++/v1/memory:3361: undefined reference to `__atomic_fetch_add_4'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: zig_cpp/libzig_cpp.a(zig_clang_driver.cpp.o): in function `int std::__ndk1::__cxx_atomic_fetch_sub<int>(std::__ndk1::__cxx_atomic_base_impl<int>*, int, std::__ndk1::memory_order)':
/data/data/com.termux/files/usr/include/c++/v1/atomic:1036: undefined reference to `__atomic_fetch_sub_4'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: zig_cpp/libzig_cpp.a(zig_clang_driver.cpp.o): in function `int std::__ndk1::__cxx_atomic_fetch_add<int>(std::__ndk1::__cxx_atomic_base_impl<int>*, int, std::__ndk1::memory_order)':
/data/data/com.termux/files/usr/include/c++/v1/atomic:1014: undefined reference to `__atomic_fetch_add_4'
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/zig0.dir/build.make:135: zig0] Error 1
make[1]: *** [CMakeFiles/Makefile2:225: CMakeFiles/zig0.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```
which should have been solved by
```
+target_link_libraries(zig0 atomic)
```
but it still happens nonetheless :(

**Comment by buttaface** [comment]
Probably has to do with the order those libraries are passed to the linker, see if you can get atomic passed _after_ libc++, as it looks like it's getting passed before now.

**Comment by DolphinChips** [comment]
@buttaface i've manually edited `build/CMakeFiles/zig0.dir/link.txt` to pass `-latomic` after `-lclang-cpp` and it worked! however, now build fails when it tries to run zig0, i've tried setting breakpoint at `main` and `_start` but seems like it never got hit for some reason (or i'm just bad at lldb)

**Comment by buttaface** [comment]
I'd check what `zig0` is linked against and its rpath, `readelf -d path/to/zig0 | grep -E "NEEDED|RUNPATH"`. That might give you a clue, as I doubt those four tweaks are all you need to build the zig compiler on Android.

**Comment by DolphinChips** [comment]
i forgot to send the error that `zig0` gives me
```
: CommandLine Error: Option 'mc-relax-all' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```
which seems to come from one of the llvm libs

regarding the command that you sent,
```
0x00000001 (NEEDED)                     Shared library: [libandroid-spawn.so]
 0x00000001 (NEEDED)                     Shared library: [libclang-cpp.so]
 0x00000001 (NEEDED)                     Shared library: [libLLVM-10.so]
 0x00000001 (NEEDED)                     Shared library: [libc.so]
 0x00000001 (NEEDED)                     Shared library: [libc++_shared.so]
 0x00000001 (NEEDED)                     Shared library: [libdl.so]
 0x00000001 (NEEDED)                     Shared library: [libm.so]
 0x0000001d (RUNPATH)                    Library runpath: [/data/data/com.termux/files/usr/lib]
```

**Comment by buttaface** [comment]
>LLVM ERROR: inconsistency in registered CommandLine options

Oh, I've seen that before, apple/swift#29454, looks like a common LLVM problem. You'll need to check the zig compiler and its library dependencies to see where [that flag](https://github.com/llvm/llvm-project/blob/release/10.x/llvm/include/llvm/MC/MCTargetOptionsCommandFlags.inc#L21) is getting set twice. This command shows me all the libraries where that flag's been linked in my local build of LLVM for Swift trunk, you will have problems if you try to link against two of those libraries:
```
> readelf -sW build/Ninja-Release/llvm-android-aarch64/lib/* | grep -E "File:|RelaxAll" | grep RelaxAll -B1
File: build/Ninja-Release/llvm-android-aarch64/lib/libLTO.so
   640: 0000000001f2eb00   208 OBJECT  LOCAL  DEFAULT   21 _ZL8RelaxAll
File: build/Ninja-Release/llvm-android-aarch64/lib/libLTO.so.10git
   640: 0000000001f2eb00   208 OBJECT  LOCAL  DEFAULT   21 _ZL8RelaxAll
File: build/Ninja-Release/llvm-android-aarch64/lib/libclang-cpp.so
  1554: 00000000034cb470   208 OBJECT  LOCAL  DEFAULT   20 _ZL8RelaxAll
File: build/Ninja-Release/llvm-android-aarch64/lib/libclang-cpp.so.10git
  1554: 00000000034cb470   208 OBJECT  LOCAL  DEFAULT   20 _ZL8RelaxAll
File: build/Ninja-Release/llvm-android-aarch64/lib/libclangHandleLLVM.a(handle_llvm.cpp.o)
   489: 0000000000000090   208 OBJECT  LOCAL  DEFAULT 1149 _ZL8RelaxAll
File: build/Ninja-Release/llvm-android-aarch64/lib/liblldCommon.a(TargetOptionsCommandFlags.cpp.o)
   473: 0000000000000090   208 OBJECT  LOCAL  DEFAULT 1125 _ZL8RelaxAll
```
Since you're linking zig against the Termux LLVM, you may require a fix in this repo, but more likely you're pulling in an unnecessary dependency somewhere when building zig.

**Comment by DolphinChips** [comment]
@buttaface i tried a few things but weren't successful with them :(

i've ran your command in `/data/data/com.termux/files/usr/lib` and it resulted only in liblldCommon.a being outputed, `grep -r RelaxAll` gave the same result. The only places where this lib is mentioned are in link.txt of zig0 and zig targets, removing them results in linker error.

I did `grep -r` in zig source code and found https://github.com/ziglang/zig/blob/master/src/zig_clang_cc1as_main.cpp#L479, which is a part of libzig_cpp.a, unfortunately just removing that line didn't help :(

Running `grep -r RelaxAll` in build directory results in 4 object files matching (zig_llvm.cpp.o, zig_clang.cpp.o, zig_clang_cc1_main.cpp.o, zig_clang_cc1as_main.cpp.o), but only one of them mention RelaxAll or *Streamer functions (which, if i understand correctly, are the way to set that option) in sources, so not sure how that got in other files, but it might be that this is the reason for zig0 failing to launch.

**Comment by buttaface** [comment]
I believe the issue is that a static global variable like that can only be initialized once, either in the executable or in any shared libraries it invokes. I could be wrong about this and the reasoning that follows, so you may want to check it for yourself with some test code.

Now that you found that it is only in one LLVM static library- I also see it in `libclangHandleLLVM.a` from the `libllvm-static` Termux package, but maybe you don't use that for zig- the question is, in how many zig executables or shared libraries did that variable get included?

What you tried, not linking that static library or removing that line of source, wasn't going to work (in the former case, at least not without supplying the functions that _were_ needed). I think you'll have to check the zig executable and all its shared library dependencies, and their dependencies and so on, to see which of them has that variable.

I think the problem is that one of them will try to initialize that variable before `main` is run- which is why setting a breakpoint there didn't work, it's too late by then- and then when a second one does, runtime error.

However, the symbol won't be found in a stripped executable or shared libraries, as I don't see it in the Termux clang or its shared library dependencies but they also use it. I got lucky with that Swift test binary before and was able to find the problem just from the CMake config.

You may have to do more work to find and fix this, ie building the zig executable and its shared library dependencies unstripped and then looking for the symbol. I've already told you which unstripped LLVM shared libraries had it in my local build, so if you can find any two of those as zig dependencies or the unstripped zig executable itself has that symbol, that narrows down the problem. Then, I think you have to figure out which of those is unnecessary and can be excised, say by modifying some headers to leave it out.

I could be way off in this reasoning, but I believe this is the problem.

**Comment by evs-chris** [comment]
I also managed to get the build to the point that it's running zig0, but best I can tell it's linked against libc, which naturally doesn't exist for bionic things. It looks like zig supports building with musl, but I don't have the requisite braincells to arrange it within termux. Luckily, the 0.8 nightlies for linux aarch64 seem to be built against musl, and as such, appear to work fine just fine in termux.

**Comment by buttaface** [comment]
You could add bionic to the list of libc's supported by Zig if wanted: shouldn't be too bad if it already supports any BSD libc, as Bionic is based on the BSD libc.

**Comment by buribu** [comment]
Note that there are binaries for many platforms on the official website. I remember running zig 0.9.0 in termux just unzipping and putting the executable directory in the environment variable. https://ziglang.org/download/
