### ISSUE TITLE
texlive: error when installing some packages

### ISSUE THREAD

**Issue by kurokirasama** [termux/termux-packages#4825]
I recently changed my device, so I did a clear installation of termux. After installing texlive, I installed the following packages:

```
tlmgr update --self
tlmgr update --all

tlmgr install collection-fontsrecommended multirow doublestroke xargs bigfoot
lipsum xcolor etoolbox xkeyval microtype listings mathtools

```
after it finished, I got this error:

`Cannot open /data/data/com.termux/files/texmf-dist/web2c/updmap.cfg for writing: No such file or directory at /data/data/com.termux/files/usr/share/texlive/tlpkg/TeXLive/TLUtils.pm line 3147.
`

**Additional information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.4.153-perf+ #1 SMP PREEMPT Sun Nov 10 07:06:57 WIB 2019 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 7

```

Regards,

**Comment by Grimler91** [comment]
I think one of the updated packages have edited the texmf.cnf settings causing tlmgr/texlive to look for files in /data/data/com.termux/files/texmf-dist` instead of `/data/data/com.termux/files/usr/share/texlive/texmf-dist`. I can have a look later today and see what you need to change to make it working again. 

I'll fix this at the latest when texlive 2020 is released, but will see if it is possible to have a quick-fix as part of the tlmgr wrapper until then.

**Comment by Grimler91** [comment]
To get texlive working again after `tlmgr update --all` you need to re-apply [this patch](https://github.com/termux/termux-packages/blob/master/packages/texlive/texmf.cnf.patch) to `$PREFIX/share/texlive/texmf-dist/web2c/texmf.cnf` and probably regenerate `$PREFIX/share/texlive/texmf-dist/ls-R`.

This can be done with: 
```sh
( 
cd $PREFIX/share/texlive
curl -LO https://raw.githubusercontent.com/termux/termux-packages/master/packages/texlive/texmf.cnf.patch
patch -Np1 -i texmf.cnf.patch
mktexlsr
)
```

**Comment by angelog0** [comment]
@Grimler91 wrote:

> To get texlive working again after `tlmgr update --all` you need to re-apply this patch

Does this mean that we have to apply the patch after each `tlmgr update --all`?

**Comment by angelog0** [comment]
@Grimler91, the patch you propose does not work here, in the sense tha building documents fails with:

```
LaTeX Warning: You have requested release `2020/02/02' of LaTeX,
               but only release `2018-12-01' is available.
```

this ,after a `scheme-full`, an `update --all` etc.

But why do you  not release an update for the package which is broken and insist in waiting for TL 2020 which will happen for April... This causes only confusion a time wasting for the user.

**Comment by Grimler91** [comment]
> Does this mean that we have to apply the patch after each tlmgr update --all?

Only if `$PREFIX/share/texlive/texmf-dist/web2c/texmf.cnf` is updated, so only if kpathsea has received an update.

> the patch you propose does not work here, in the sense tha building documents fails with:
> 
> ```
> LaTeX Warning: You have requested release `2020/02/02' of LaTeX,
>                but only release `2018-12-01' is available.
> ```
> 
> this ,after a scheme-full, an update --all etc.

That's a warning, not an error, so should not cause a failure. 

When I do tlmgr install `scheme-full`, `tlmgr update --all`, and then apply the above patch I get a texlive that works fine for my test document so please share the steps for reproducing the error you're getting.

> But why do you not release an update for the package which is broken and insist in waiting for TL 2020 which will happen for April... This causes only confusion a time wasting for the user.

Because we only have a limited amount of allowed network traffic on `bintray.com/termux` and if I bump texlive then `apt upgrade` will download ~1 GB of archives for every termux user with texlive installed. We hit the limit a few months ago: https://github.com/termux/termux-packages/issues/4358

**Comment by angelog0** [comment]
@Grimler91 wrote:
> When I do tlmgr install scheme-full, tlmgr update --all, and then apply the above patch I get a texlive that works fine for my test document so please share the steps for reproducing the error you're getting.

```
- Reset Termux (clean cache, delete data), i.e. reinstall Termux
- Install texlive-tlmgr
- tlmgr install scheme-full (fmtutil fails in some cases)
- tlmgr update --all

- cd $PREFIX/share/texlive
- curl -LO \ https://raw.githubusercontent.com/termux/termuxpackages/master/packages/texlive/texmf.cnf.patch
- patch -Np1 -i texmf.cnf.patch
- mktexlsr

- latexmk -pdf foo.tex
- 
```

Same failure. 

Maybe you have to try from scratch... Anyway I wasted enough time and will return to test Yermux when you will add `biber`
