### ISSUE TITLE
Tmate SSH keys not found

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#484]
We talked about this on #termux 
In order for tmate to work you need to execute 'source source-ssh-agent', which only works in bash. Tmate shouldn't require ssh-agent and should pick up the keys from the default location.

**Comment by brunobell** [comment]
So seems this has not been fixed yet, since I ran into a hard time after installed and configured lots of stuff and when I relogin then comes the termux 'Do not execute directly source me instead' bug.
My phone is not rooted yet, is there any way for me to hack into termux like a livecd mode and get things all right? Thx

**Comment by brunobell** [comment]
ok, I flashed recovery of my android and got root privilige then adb into termux dir to comment the lines that hecks if accidentaly executed instead of sourced, and biubiubiu, I got in.
weird though, I didn't install tmate. maybe another package executed it

**Comment by xeffyr** [comment]
Looks like it works now.
Just need to `ssh-keygen -t rsa -f ~/.ssh/id_rsa` and everything is okay. Also keys should be on both sides.
