### ISSUE TITLE
TeXLive issues

### ISSUE THREAD

**Issue by angelog0** [termux/termux-packages#4867]
The following occurs on a new tablet (RAM 4 GiB, STORAGE 128 GiB) with Android 8.0.0.

I installed TeXLive in this way:

```
$ pkg install termux-tlmgr
$ tlmgr install scheme-full
```
with the last command there was about 2 errors for some `.pl` file not found. Anyway I tested the installation building some documents,

`$ lmkpdf scritto && lmkclean && rm -rf *.bbl *.brf *.xml`

(where `lmkpdf` is an alias, `latexmk -pdf`; and `lmkclean` is another alias, `latexmk -c`). And all this worked.

Then I did

```
$ tlmgr option autobackup 0

$ tlmgr update --list
$ tlmgr update --self
$ tlmgr update --all 
```

There were about 59 packages to be upgraded (WHY if I have just installed TeXLive that way?). In this upgrade there were many _errors_ like these

```
[...]
/data/data/com.termux/files/usr/bin/tlmgr.ln: (make_container __BACKUP_luaotfload.r47444.tar) texmf-dist/tex/luatex/luaotfload/luaotfload-letterspace.lua does not exist
[...]
TLPDB: These files would have been removed due to removal of
TLPDB: tetex, but are part of another package:
 texmf-dist/texconfig/README - texlive-scripts-extra
[...]
[59/59, 05:12/05:12] update: scheme-infraonly [1k] (41515 -> 53569) ... done
running mktexlsr ...
done running mktexlsr.
running mtxrun --generate ...
done running mtxrun --generate.
Cannot open /data/data/com.termux/files/texmf-dist/web2c/updmap.cfg for writing: No such file or directory at /data/data/com.termux/files/usr/share/texlive/tlpkg/TeXLive/TLUtils.pm line 3162.
```

After this, rebuilding the documents fails:

```
[...]
kpathsea: Running mktexfmt pdflatex.fmt
Can't locate mktexlsr.pl in @INC (@INC contains: /data/data/com.termux/files/tlpkg /data/data/com.termux/files/texmf-dist/scripts/texlive /data/data/com.termux/files/usr/lib/perl5/site_perl/5.30.1/aarch64-android /data/data/com.termux/files/usr/lib/perl5/site_perl/5.30.1 /data/data/com.termux/files/usr/lib/perl5/5.30.1/aarch64-android /data/data/com.termux/files/usr/lib/perl5/5.30.1 .) at /data/data/com.termux/files/usr/bin/mktexfmt line 23.
BEGIN failed--compilation aborted at /data/data/com.termux/files/usr/bin/mktexfmt line 25.
I can't find the format file `pdflatex.fmt'!
Latexmk: fls file doesn't appear to have been made.
Latexmk: Errors, so I did not complete making targets
[...]
```

They are about 10 years I use TeXLive (and contribuited to port it to Cygwin, 2007-2008) and install it on macOS, GNU/Linux and Windows+WSL. Usually I have a local repo of `tlnet` and install TeXLive with `install-tl` script, maintaining the installation updating `tlnet` (`rsync`) and with the above steps using `tlmgr`. 

Can I do somting similar on Termux? I found on the WEB people refers to a `termux-install-tl` script but I do not find it in any package, it seems...

Thanks.

**Comment by Grimler91** [comment]
> There were about 59 packages to be upgraded (WHY if I have just installed TeXLive that way?).

texlive and texlive-tlmgr contains a minimal set of packages, those packages are taken from texlive 2019, released in April. Apparently 59 packages have received updates since April. 

I think one of the updated packages have edited the texmf.cnf settings causing tlmgr/texlive to look for files in /data/data/com.termux/files/texmf-dist` instead of `/data/data/com.termux/files/usr/share/texlive/texmf-dist`. I can have a look later today and see what you need to change to make it working again. 

> Can I do somting similar on Termux? I found on the WEB people refers to a termux-install-tl script but I do not find it in any package, it seems...

The termux-install-tl was part of the initial texlive installation for termux. It has since then been removed. It isn't possible (at least not easily) to use the install-tl script provided upstream as termux/android is very different from a normal GNU/Linux distribution. 

Closing this in favour of https://github.com/termux/termux-packages/issues/4825 since that issue was opened earlier.
