### ISSUE TITLE
termux-usb usage

### ISSUE THREAD

**Issue by Nic2012** [termux/termux-packages#4902]
I was successful in compiling and installing libgphoto library and its cli gphoto2 (https://github.com/gphoto) in termux on a non-rooted Android 7 device.
A typical one liner cmd would be `gphoto2 -q -set-config iso=1000`, but its mostly called with different arguments.

According to https://wiki.termux.com/wiki/Termux-usb definition we have to specific usb port by `termux-usb -r -e <command> /dev/bus/usb/001/xyz`. When I understand the magic behind this, a file descriptor will be transferred by callback to the command.

But how we can call the custom command with different additional arguments?

BTW in the meantime I was able to connect gphoto2 with a Nikon camera via ptp/ip port remotely and call some action (take a picture, get ISO settings etc.) without any problems. But only few camera devices around the globe support ptp/ip.

**Comment by Grimler91** [comment]
Hi,

The termux-usb syntax could be improved a bit, it passes the fd as the last argument so in your case you want something like:
```
termux-usb -r -e "gphoto2 -q -set-config iso=1000 -usb-fd" /dev/bus/usb/001/xyz
```
Where gphoto2 needs to be patched to accept a new command line argument `-usb-fd`.

I have uploaded an example patch for another software here: https://github.com/Grimler91/ttwatch/commit/1ad9f96f596efed5c5e1fc76fdabeaeba0cfab1b. It basically boils down to that [libusb_wrap_sys_device](https://github.com/Grimler91/ttwatch/commit/1ad9f96f596efed5c5e1fc76fdabeaeba0cfab1b#diff-f81774eed944e070346af3a0c7305d7bR339) needs to be used instead of [libusb_open](https://github.com/Grimler91/ttwatch/commit/1ad9f96f596efed5c5e1fc76fdabeaeba0cfab1b#diff-f81774eed944e070346af3a0c7305d7bR360)
