### ISSUE TITLE
Termux 0.92 don't show keyboard in start.

### ISSUE THREAD

**Issue by claudiohagra** [termux/termux-packages#4925]
All the times when start Termux it don't show the alphanumeric keyboard, but only show numeric keyboard. How fix it?

**Comment by xeffyr** [comment]
Samsung device ?

It is a keyboard bug, i.e. it can't properly switch to generic input type. Instead it uses the last one.

As workaround I'm suggesting to open & close the alternate text input view (https://wiki.termux.com/wiki/Touch_Keyboard#Text_Input_View), it will reset the keyboard state. You can even continue to use it for text input.

Otherwise use a different keyboard application.
