### ISSUE TITLE
Unittesting binaries developed via the golang package

### ISSUE THREAD

**Issue by trivigy** [termux/termux-packages#4966]
Not entirely sure if this is the appropriate place for the question. If you are a know of a better place to ask feel free to close on redirect to where this should be asked.

I am working on a component that needs to run both of a termux/arm64 and x86 machines. Most of the development is done on an x86 host. But I seem to have complex race condition issues when trying to compile and run on termux/arm64 while not seeing the same issues on x86.

It is quiet cumbersome doing debugging in a termux terminal. Would rather have an automated way to run tests from x86 and just target termux/arm64.

Q: Do you know of any way to do unit testing of termux/arm64 targeted binaries on an x86 host? Docker containers maybe? Not sure.

**Comment by Grimler91** [comment]
For testing arm64 binaries on x86, have a look at https://wiki.qemu.org/Main_Page. Testing termux specific binaries is a bit different since you then want to have them compiled against android's libc. Might be possible with qemu from [@xeffyr's termux docker image](https://github.com/xeffyr/termux-docker) (I haven't tried this)

**Comment by xeffyr** [comment]
Possible in https://github.com/termux/termux-docker with package qemu-user-aarch64. But that will require arm64 binaries to be statically linked.
