### ISSUE TITLE
[htop] Only 6 cores shown. (minor issue)

### ISSUE THREAD

**Issue by kevinlekiller** [termux/termux-packages#505]
Qualcomm MSM8937 Snapdragon 430, shows 6 cores in htop, should show 8.

`cat /proc/cpuinfo` : https://gist.github.com/kevinlekiller/344ec0295004c45d573eb8420068b7a3#file-cpuinfo-txt

Screenshot of htop : https://i.imgur.com/ZMEziFm.png

**Comment by tigran123** [comment]
Are you sure that  you run `cat /proc/cpuinfo` and `htop` simultaneously? If yes, then indeed there is a bug. You see on my 8-core system it only shows 2 or 3 or 4 cpus. Occasionally 5 or 6. And _only_ if I run it very very early after boot it shows all 8. This is because the cpus are shutdown at runtime and booted up again as necessary (I mean in hardware sense, not in software --- so the /proc/cpuinfo does reflect it --- e.g. right now my /proc/cpuinfo says I have 3 cpus and htop agrees with it). If you run dmesg (as root) you will see messages about "CPU SHUTDOWN" or something like that.

**Comment by kevinlekiller** [comment]
Unfortunately I don't have root access on this device, so I can't get dmesg output.

The issue may be the phone turns off some cores for power saving, although other programs on the android store detect these cores and show them turning on / off as usage increases/decreases.

Will close since I can't provide enough information for this issue to be fixed, will reopen in the future if I get root access to the device and can provide more information.

Thanks.
