### ISSUE TITLE
Start syncthing on boot

### ISSUE THREAD

**Issue by n0ego** [termux/termux-packages#5122]
Hi

I've installed syncthing package within termux: $pkg install syncthing

I was wondering what is the best way to start syncthing as a service? Does anybody have any idea how much running syncthing as a service affects battery life?

Many thanks.

**Comment by Grimler91** [comment]
> I was wondering what is the best way to start syncthing as a service?

Install the termux:boot if you want to be able to start it on device boot (rather than when termux starts). You can then create a script which is automatically run when device boots.

If you want to control it like a service you can create a [termux-services](https://wiki.termux.com/wiki/Termux-services) script. You would then create an executable script at `$PREFIX/var/service/syncthing/run` with the content (not tested but something like this):

```sh
#!/data/data/com.termux/files/usr/bin/sh

syncthing -logflags 0 2>&1
```

To make the service start on device boot install the termux:boot app and add a boot script with the content

```sh
#!/data/data/com.termux/files/usr/bin/sh
source /data/data/com.termux/files/usr/etc/profile.d/start-services.sh
```

> Does anybody have any idea how much running syncthing as a service affects battery life?

Probably device specific, and depends on if you are on wifi or not.

**Comment by n0ego** [comment]
That's brilliant. I've opted to install termux-service with suggested script and set it to be executable.

Thank you.
