### ISSUE TITLE
Daemon

### ISSUE THREAD

**Issue by Swalih-t** [termux/termux-packages#5230]
How to run daemon in termux without error

**Comment by ChiefMikeK** [comment]
✌️ Sort of a vague question?  

- Needs more info!

- At least a screenshot showing command line and resulting error message 🔢

**Comment by ustcpetergu** [comment]
If you mean how to run a bash script that stays background after terminal exit, I'm using something like this: `setsid bash /sdcard/my.sh > /dev/null 2>&1 < /dev/null`

By the way, this problem seems to be more related to bash/Linux instead of termux-specific -- solutions for Linux will work for termux too ;-)
