### ISSUE TITLE
Android 10, "Permission denied" in a SD card

### ISSUE THREAD

**Issue by KangKazumi** [termux/termux-packages#5320]
Android 10 upgrade turned out to be such a bad idea because I lost the writing permission in my external SD card.

Is there a way to fix it?

**Comment by kcubeterm** [comment]
Can you provide device vendor as well, because many custom rom devices , termux can access even write also, like in Redmi(miui)

**Comment by RalfWerner** [comment]
> I lost the writing permission in my external SD card.
```
a=Android/data/com.termux/files; b=/storage/????-*; ln -s /sdcard/$a a; ln -s $b/$a b; ls -la a/ b/; cp b/* a
```
creates two symlinks that allow writing and lists the content! At least one of the two paths is the _sdcard_ but be careful - the paths are also disposed of with the _termux deinstallation_.
But, the _google-file-App_ on Android 10 can edit termux data (`cp/mv` - always with a new timestamp).

**Comment by KangKazumi** [comment]
![Screenshot_20200521_012625](https://user-images.githubusercontent.com/63225844/82477672-672c9100-9a95-11ea-9a41-33583547e65d.png)

**Comment by RalfWerner** [comment]
try `$a` from my example above behind `/2` or instead

**Comment by xeffyr** [comment]
Full rw access to external storage was never supported.

Why ? Answer in \-\-\> https://wiki.termux.com/wiki/Internal_and_external_storage

**Comment by KangKazumi** [comment]
@RalfWerner was right.
I've got it working now!
![Screenshot_20200521_093747](https://user-images.githubusercontent.com/63225844/82515824-d4b0df80-9ade-11ea-8739-61671fd29dc4.png)

Thanks a million!

**Comment by RalfWerner** [comment]
> Full rw access to external storage was **never** supported.

@xeffyr This contradicts my experience with my Android 8/9 devices from different _arch_, on which all data allow r+w access and only restrictions due to _fat-differences_ have to be considered.
With Q10/R11 that _**changes**_. Therefore I would not label the question as _**invalid**_. My _real_ devices cannot be upgraded to Q10 and my 30Gb sdcard works _simply_ like a USB stick, so I test with emulations.

I reread [wiki](https://wiki.termux.com/wiki/Internal_and_external_storage) and miss the changes that result in Q10 and R11 and _targetSdkVersion 29/R_ (`*29.apk`)
comes [Aug 20](https://gitter.im/termux/dev?at=5e65346f85f81e18a8f29a05) in less than 3 monthes. Here are some suggestions:

- First, unlimited access from _google-file_ to all termux data (including `nl/` and packages `u/`). "App-private storage" does not apply to _google_, especially since the properties can be changed without `termux-setup-storage` (`tss`) in _phone-setup_.

- Symlinks (like ~/storage) are only allowed _"one way"_ and _"x-file-access" **not** _(fat differences)_.
Scripts can, however, be executed as the _"input"_ of the interpreter (e.g. _bash_).

- /sdcard exists on most devices and is a symlink with an unclear destination - often the real sdcard if it exists or internal storage. When _formatting_ the sdcard, the folders (Android to Pictures) are created (different spellings) to which `tss` creates uniform symlinks. However, these folders are then multiple on one device and only the path `/storage/*/*` in _termux_ is unique.

- `tss` is not possible on R11 because the basic function `am` no longer works (@fornwall [confirmed](https://gitter.im/termux/dev?at=5e7de98ed7d8504dee6d8167)). I prefer debug to wiki-docu!

At `*29.apk`, three different owner/group assignments have been set up on the sdcard on three different emulators. For _termux_ all imaginable rw combinations and groups are included. _google_ is allowed to do everything again and the `$a` path (@KangKazumi above) always belongs to _termux_ - but unfortunately it is also disposed of with the app. Thanks to _google_ (problem & solution) there is data recovery:)

**Comment by xeffyr** [comment]
> This contradicts my experience with my Android 8/9 devices from different arch, on which all data allow r+w access and only restrictions due to fat-differences have to be considered.

I don't understand what you mean. If you would like to share way how to bypass ownership restriction in **root folder of external sdcard**, everyone would like here to see it.

For now I can't confirm your experience. This is what on Android 8.0:

![Screenshot_20200521-132858_Termux](https://user-images.githubusercontent.com/25881154/82550433-2f8e1980-9b67-11ea-8bea-40fba0ca04f2.jpg)

And this is what on Android 10:

![scr](https://user-images.githubusercontent.com/25881154/82551397-cc04eb80-9b68-11ea-8cde-caa15312e8e8.png)

Pretty much difference ? Not really.

And that restriction was applied in Android 4.4 perhaps, on my tablet with Android 3.0 external sd still has RW access. Google does not allow full (full means RW access to all folders) write access without usage of Storage Access Framework, which for now is used by nearly all file managers.

> I reread wiki and miss the changes that result in Q10 and R11 and targetSdkVersion 29/R (*29.apk)
comes Aug 20 in less than 3 monthes. Here are some suggestions:

This issue about Termux versions currently available to users. It is SDK 28-only.

Wiki will be updated once that app will be released.

**Comment by RalfWerner** [comment]
> I hope you noticed that only root has RW access to sdcard root, rest is read-only.

**No!** my sdcard (or devices) obviously behaves differently than yours (selection `ll=ls -la`):
```
[~]$ ll /sdcard/ # symlink to */self/primary on gigaset
drwxrwx--- 16 root everybody      4096 Apr 30 17:21 .
drwx--x--x  4 root everybody      3488 Sep  5  2019 ..
drwxrwx---  5 root everybody      3488 Nov 28 13:44 Android
drwxrwx---  2 root everybody      3488 Mar 25 13:41 Download

[~]$ ll sd/ # symlink to sdcard on huawei (same, when I exchange in gigaset)
drwxrwx--- 27 root everybody     32768 May 19 11:29  .
drwxrwx---  5 root everybody     32768 Nov 25 16:07  Android
drwxrwx---  2 root everybody     32768 Feb 12 09:56  Download
-rwxrwx---  1 root everybody 393297643 Mar 31 17:11  tu.tgz # backup termux
-rwxrwx---  1 root everybody 848887325 Feb 26 15:06  uu.tgz # backup ubuntu

[~]$ ll /storage/0FF8-0D15/ # Q10 emulation
drwxr-x---  3 root everybody 2048 May 21 11:22 Android
drwxr-xr-x  2 root everybody 2048 May 21 11:23 Download
drwxr-xr-x  2 root everybody 2048 May 21  2020 LOST.DIR
[~]$ ll /storage (before reformat sdcard - no $a)
drwxr-xr-x  5 root root       100 May 21 11:22 .
drwxr-xr-x 13 root everybody 2048 May 21 11:23 0FF8-0D15
drwx--x--x  3 root everybody 4096 May 21 11:22 emulated
drwxr-x--x  2 root root        60 May 21 11:22 self
[~]$ ll /storage/0FF8-0D15/
drwxr-x---  3 root everybody 2048 May 21 11:22 Android
[~]$ ll /storage (after reformat sdcard and "setup-storage")
drwxr-xr-x 13 root everybody 16384 May 21 12:14 5D0B-13E5
[~]$ ll /storage/5D0B-13E5/Android/data/com.termux/files/
```
I cannot test my two R11 emulators at the moment because of the `am` problem. When `*28.apk` was on it, there were owner/group names nobody and sdcardrw or something.
Studio can create a `*card.img` with _mksdcard_ (done with 2 Gb), which (theoretically) can be used in several emulators - I just _**don't find it**_ or the sdcards when creating (5Gb) the emulators!
`$a` is only created with `tss` and I would have expected _**two cards.**_ Do you have _**experience with it?**_
> Wiki will be updated once that app will be released

Nice thank you! The question about _"sdcard packages"_ is often asked and should be mentioned.

**Comment by xeffyr** [comment]
> No! my sdcard (or devices) obviously behaves differently than yours

I don't see anything different. Make sure we are talking about EXTERNAL sdcard. Not about the shared storage or whatever is linked to `/sdcard`. Do not mix the storage types and move from the actual topic.

### Shared storage
```
[~]$ ll /sdcard/ # symlink to */self/primary on gigaset
drwxrwx--- 16 root everybody      4096 Apr 30 17:21 .
drwx--x--x  4 root everybody      3488 Sep  5  2019 ..
drwxrwx---  5 root everybody      3488 Nov 28 13:44 Android
drwxrwx---  2 root everybody      3488 Mar 25 13:41 Download

[~]$ ll sd/ # symlink to sdcard on huawei (same, when I exchange in gigaset)
drwxrwx--- 27 root everybody     32768 May 19 11:29  .
drwxrwx---  5 root everybody     32768 Nov 25 16:07  Android
drwxrwx---  2 root everybody     32768 Feb 12 09:56  Download
-rwxrwx---  1 root everybody 393297643 Mar 31 17:11  tu.tgz # backup termux
-rwxrwx---  1 root everybody 848887325 Feb 26 15:06  uu.tgz # backup ubuntu
```
\- here is exactly what I have in `/sdcard`. That's expected behaviour on all Android devices supported by Termux. **Full read-write access is available here and no one says Termux can't write to it.**

### External storage

```
[~]$ ll /storage/0FF8-0D15/ # Q10 emulation
drwxr-x---  3 root everybody 2048 May 21 11:22 Android
drwxr-xr-x  2 root everybody 2048 May 21 11:23 Download
drwxr-xr-x  2 root everybody 2048 May 21  2020 LOST.DIR
[~]$ ll /storage (before reformat sdcard - no $a)
drwxr-xr-x  5 root root       100 May 21 11:22 .
drwxr-xr-x 13 root everybody 2048 May 21 11:23 0FF8-0D15
drwx--x--x  3 root everybody 4096 May 21 11:22 emulated
drwxr-x--x  2 root root        60 May 21 11:22 self
[~]$ ll /storage/0FF8-0D15/
drwxr-x---  3 root everybody 2048 May 21 11:22 Android
[~]$ ll /storage (after reformat sdcard and "setup-storage")
drwxr-xr-x 13 root everybody 16384 May 21 12:14 5D0B-13E5
[~]$ ll /storage/5D0B-13E5/Android/data/com.termux/files/
drwxr-x--- 2 u0_a150 everybody 32768 May 21 12:14 .
drwxr-x--- 3 u0_a150 everybody 32768 May 21 12:14 ..
```
\- same as in screenshots from my previous post.

**Comment by RalfWerner** [comment]
`# symlink to sdcard on huawei (same, when I exchange in gigaset)` **above is _indeed_** the small card that I _took out_ of my Huawei with a pin during the manufacturer check - SSM - do you remember? and _insert in_ my gigaset used (sdcard symlink was different in this periode) - _**no internal/shared memory!**_

With the emulators you are right my question is here: _**where is the second sdcard?**_

**Comment by RalfWerner** [comment]
> I don't see anything different. Make sure we are talking about EXTERNAL sdcard
```
[~]$ df sd/; ll sd sd/
Filesystem              1K-blocks    Used Available Use% Mounted on
/mnt/media_rw/3566-3331  62334976 1308160  61026816   3% /storage/3566-3331
lrwxrwxrwx 1 u0_a116 u0_a116       22 May 23 15:11 sd -> /storage/3566-3331

sd/:
drwxrwx--- 6 root everybody    131072 May 23 15:38 .
drwxr-xr-x 5 root root            120 May 23 15:06 ..
drwxrwx--- 3 root everybody    131072 May 23 14:25 Android
-rwxrwx--- 1 root everybody    443502 Oct 22  2019 feh.tgz
-rwxrwx--- 1 root everybody    833075 Nov 12  2019 i.tgz
drwxrwx--- 7 root everybody    131072 May 23 10:12 ip
drwxrwx--- 3 root everybody    131072 May 23 15:38 recovery_log
-rwxrwx--- 1 root everybody 378749040 May 23 14:37 tu.tgz # termux backup (armv7l)
-rwxrwx--- 1 root everybody 379064709 May 23 14:28 uu.tgz # ubuntu backup
```
@xeffyr Gigaset only allows _only EXTERNAL **sdcard!**_ I bought a new (64Gb) today and had it inserted by the dealer. In addition, done the latest system updates (google security update Feb 2020). Control: see `above`, after _unrestricted_ moving from _intern_ to _sdcard._ You wrote:
> I don't understand what you mean. If you would like to share way how to bypass ownership restriction in root folder of external sdcard, everyone would like here to see it.

I can find _**no restriction** in root_ on _**all**_ my Android 8+9 devices - and use it since two years!
Do we still talk past each other or would you like to invite: _**"everyone would like here to see it"**_

**Comment by xeffyr** [comment]
> Gigaset allows only EXTERNAL sdcard!

If external sdcard used as shared storage, restrictions do not apply. Just like for adopted storage.

> I can find no restriction in root on all my Android 8+9 devices - and use it since two years!

Manufacturer can implement changes for improving user experience on its own. That includes behaviour not defined by official SDK, like full access to external sdcard. AOSP (which is only the true Android OS) does not do that.

If you observe a behaviour not defined by SDK, you cannot claim that "you find no restriction". External storage restriction exists on most devices starting from Android 4.4, where URI-based paths were enforced. If you don't have AOSP device, use emulator from SDK package.

Huawei devices definitely shouldn't be used to examine Android OS features, there lots of other non-standard changes (e.g. in power management). Not just the sdcard "improvement".

I have provided enough information in my [post](https://github.com/termux/termux-packages/issues/5320#issuecomment-632015979). If write access to external storage was not restricted, Termux wouldn't had provided the `termux-setup-storage` script.

**Comment by xeffyr** [comment]
Issue is locked as went into offtopic.
