### ISSUE TITLE
Some CLI packages seems depend on GUI library 

### ISSUE THREAD

**Issue by rekaerst** [termux/termux-packages#5357]
Recently I found that some pure CLI programs depend on GUI libs such as libx11,libcairo,librsvg and gtk.
E.g. if I wanna install links or translate-shell I need to install 62.4MB of programs and they're mostly graphic libs.

**Comment by Grimler91** [comment]
For translate-shell you are probably seeing mpv's dependencies, since it is a recommended dependency. You could install it with `apt install --no-install-recommends translate-shell` to omit them.

Links is built with the `--enable-graphics` configure option, and for that libx11 and the others are needed. This was requested in https://github.com/termux/termux-packages/issues/4973.
