### ISSUE TITLE
dlopen failed: cannot locate symbol

### ISSUE THREAD

**Issue by fahadali32** [termux/termux-packages#5459]
**dlopen failed: cannot locate symbol 
apt install opencv I just put this cmd for installing opencv

But it shows me dlopen error

![Screenshot_2020-06-29-11-59-21-692_com termux](https://user-images.githubusercontent.com/38833848/85980063-7c390000-ba03-11ea-918b-240e46efe445.jpg)
 **
I am using xioami phone 
Arc : armv7l
Please help me ....i am trying this about 7 days...

**Comment by Grimler91** [comment]
opencv comes from [its-poinless repo](https://wiki.termux.com/wiki/Package_Management#By_its-pointless_.28live_the_dream.29:) so either open an issue in https://github.com/its-pointless/gcc_termux, or just wait since its-pointless was already pinged in https://github.com/termux/termux-packages/issues/1992, or re-compile it yourself with the instructions in https://github.com/termux/termux-packages/issues/1992#issuecomment-507943741

The error happens because one of the dependencies was updated, and opencv then needs to be re-compiled

**Comment by fahadali32** [comment]
What should I do?

**Comment by Grimler91** [comment]
@fahadali32 That's up to you, I gave you three options
