### ISSUE TITLE
Can i kill localhost process ?

### ISSUE THREAD

**Issue by zababurinsv** [termux/termux-packages#5548]
In termux i run on port 8083 node.

In ubuntu i use in package.json this script:

but in termux it is not working.

`"kill": "kill $(lsof -t -i:8083)"`
I get this eror

```
sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! radio@1.0.0 kill: `kill $(lsof -t -i:8083)`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the radio@1.0.0 kill script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.```

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2020-07-15T12_44_45_322Z-debug.log
```

And two variant

`"kill": "fuser -k 8083/tcp && echo 'Terminated' || echo 'Nothing thing was running on the PORT'"`

```
radio@1.0.0 kill2 /data/data/com.termux/files/home/server-radio
> fuser -k 8083/tcp && echo 'Terminated' || echo 'Nothing was running on the PORT'
Cannot open protocol file "/proc/net/tcp": Permission denied
Nothing was running on the PORT
```

**Comment by xeffyr** [comment]
You can kill processes launched within Termux but only if you know their pid or name.

On new Android versions you can't read /proc/net/tcp due to SELinux, so utilities using it will not work without root. Consider using alternate ways of getting pid of processes, e.g. through pidfiles or through matching process name. `start-stop-daemon` can deal with that.
