### ISSUE TITLE
Package request: borgbackup

### ISSUE THREAD

**Issue by hmohamad** [termux/termux-packages#557]
Would be awesome to have this great backup utility on termux.
https://github.com/borgbackup/borg
I already tried compiling it myself, but since gcc isn't available, the Cython deps wouldn't build.

**Comment by Neo-Oli** [comment]
Based on the work of @ravenschade in https://github.com/borgbackup/borg/issues/1155 I tried packaging borgbackup and its dependencies. https://github.com/Neo-Oli/termux-packages/tree/borg/packages/borgbackup 
I am currently stuck at:
```
aarch64-linux-android-clang -L/data/data/com.termux/files/usr/lib -lpython3.6m -Os -I/data/data/com.termux/files/usr/include -I/data/data/com.termux/files/usr/include/python3.6m build/temp.linux-x86_64-3.6/borg/compress.o -L/data/data/com.termux/files/usr/lib -L/data/data/com.termux/files/usr/lib -llz4 -o build/lib.linux-x86_64-3.6/borg/compress.cpython-36m-x86_64-linux-gnu.so
/home/builder/.termux-build/_lib/15.2-aarch64-21-v11/bin/../sysroot/usr/lib/crtbegin_dynamic.o:crtbegin.c:function do_arm64_start: error: undefined reference to 'main'
/home/builder/.termux-build/_lib/15.2-aarch64-21-v11/bin/../sysroot/usr/lib/crtbegin_dynamic.o:crtbegin.c:function do_arm64_start: error: undefined reference to 'main'
clang50: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'aarch64-linux-android-clang' failed with exit status 1
```
To get there I had to install cython on the build machine. I also had to a weird thing to $LDSHARED to get it to use `aarch64-linux-android-clang` instead of `x86_64_linux_gcc` for building the C extensions. I am not sure is actually how it is supposed to go. 

Anybody got any ideas?

**Comment by bpereto** [comment]
jup, compile with LDSHARED="$CC -shared"

**Comment by bpereto** [comment]
@Neo-Oli 
Based on your branch I updated the sources (borg 1.1.8, libacl) and got a working build here :tada: 
https://github.com/bpereto/termux-packages/tree/borg

**Comment by bpereto** [comment]
Ups, to early :)
compiles cpython-37m-x86_64-linux-gnu.so :S

**Comment by xeffyr** [comment]
Closing because package was added in https://github.com/termux/termux-packages/commit/fc6b158f89a3e8cf0f21cd38598e6e171acda69d.
