### ISSUE TITLE
Package request : libharfbuzz.so.0

### ISSUE THREAD

**Issue by N1NG4** [termux/termux-packages#5570]
I am using Android 9. All Packages are Updated and Upgraded. When i tried to run my Python Script that is having a Library( [HarfPy](https://github.com/ldo/harfpy) ). When i run it it shows that"... library "libharfbuzz.so.0" not found". I am installed all the HarfBuzz Packages Available and tried all the help available at Internet... But Nothing works.. when i tried to search libharfbuzz.so.0 pkg there is no package available... So i think thereshould  libharfbuzz.so.0 package should be Available. Here is a link to RPM package [LibHarfBuzz.so.0](https://pkgs.org/download/libharfbuzz.so.0) that we can't install in Termux. I thinks this can Help You..

**Comment by Grimler91** [comment]
It looks for the library specified on [harfbuzz.py#L45](https://github.com/ldo/harfpy/blob/def20f7a46e429ba9fbe266a96e1732397565b5a/harfbuzz.py#L45). You will need to patch it to look for libharfbuzz.so, or create a symlink libharfbuzz.so.0->libharfbuzz.so, but I have not tested it so not sure if it will work with our version of harfbuzz.

Since the error you get is easily fixed by patching the python code or creating a symlink, I do not see a reason for changing our harfbuzz package

**Comment by N1NG4** [comment]
@Grimler91 Thanks for Your support ❤️, Bro can you tell me in a small brief with code to be changed. I am a newbie in Termux so i didn't understand what you saying. So please help me to solver the issue. Here is the error i am getting.
`Traceback (most recent call last):
  File "create_image.py", line 3, in <module>
    import harfbuzz as hb
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/harfbuzz.py", line 45, in <module>
    hb = ct.cdll.LoadLibrary("libharfbuzz.so.0")
  File "/data/data/com.termux/files/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/data/data/com.termux/files/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen failed: library "libharfbuzz.so.0" not found`
Hope you reply fast and Help me :)

**Comment by xeffyr** [comment]
```
pkg install harfbuzz
ln -s $PREFIX/lib/libharfbuzz.so $PREFIX/lib/libharfbuzz.so.0
```

**Comment by N1NG4** [comment]
@xeffyr Very Very thanks for your help, It is Working now..
