### ISSUE TITLE
rcs: FORTIFY: %n not allowed on Android

### ISSUE THREAD

**Issue by LeadRDRK** [termux/termux-packages#5595]
**Problem description**

Running any commands in rcs (like ci, co, log) will result in FORTIFY: %n not allowed on Android. 
I believe this is the same as #4381

**Steps to reproduce**

Run any rcs command. 

**Expected behavior**

It should work normally. 

**Additional information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.4.177-MinhKer_Q-V14.3_Pro-A305F-20200405 #47 SMP PREEMPT Sun Apr 5 14:25:40 +07 2020 aarch64 Android
Device manufacturer:
unknown
Device model:
Phh-Treble vanilla
```

**Comment by xeffyr** [comment]
I have pushed a fix for https://github.com/termux/termux-packages/commit/cca47345e660d08c400b93163bb79c1c840ddb9d, fixed package will be available soon.

Today finally switched to Android 10, so I guess will be able to catch most of these bugs. Error `FORTIFY: %n not allowed on Android.` happens due to same reason and affects packages using `vasnprintf.c` from gnulib.
