### ISSUE TITLE
Termux is hanging

### ISSUE THREAD

**Issue by tomato0121** [termux/termux-packages#5630]
While creating a wordlist or brute force it stops by it self.Im using elpscrk and instagramCracker
My device info:
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://dl.bintray.com/termux/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# root-repo (sources.list.d/root.list)
deb https://dl.bintray.com/grimler/termux-root-packages-24 root stable
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.4.153-perf+ #1 SMP PREEMPT Fri Nov 8 00:25:05 WIB 2019 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 5 Pro

**Comment by kcubeterm** [comment]
I think it's because of your phone hardware, your phone could hang on 2 minutes of infinite loop .lol

**Comment by buttaface** [comment]
These are not termux programs, so it's not our problem.

Most likely those programs are using up all your CPU and it's Android itself killing the app. You could try acquiring wakelock from the Termux slide in the notifications dropdown- that might help- but if Android is killing the whole app because of something you're doing, there's nothing we can do.
