### ISSUE TITLE
Why so much permissions required to install termux-widget from F-Droid ?

### ISSUE THREAD

**Issue by Siltaar** [termux/termux-packages#582]
It requires capability to send SMS, full access to network… Looks like devs did check every permissions available by default, while nearly nothing is usefull for this app (maybe just : access to local storage…).

Would it be possible to narrow down required permissions to install termux-widget ?

**Comment by fornwall** [comment]
The widget app does not request any additional permission.

Do you have the Termux:API add-on installed? That app does require a lot of permissions in order to work, and as all Termux add-ons run as the same user (since they all access the same Linux environment) it may seem that Termux:Widget requires those if you have Termux:API installed.
