### ISSUE TITLE
watch(1)

### ISSUE THREAD

**Issue by imnisp** [termux/termux-packages#5983]
I am on 7.x

- [X] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

**Package description**

WATCH is a command-line tool, part of the Linux procps and procps-ng packages, that runs the specified command repeatedly and displays the results on standard output so you can watch it change over time.

**Link to home page and sources**
1. Home page:
https://gitlab.com/procps-ng/procps
2. Source code:
git@gitlab.com:procps-ng/procps.git

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.

I *have* installed the termux 'procps' package but 'watch' is not included.

My understanding is that in Nougat, htop and associated tools like 'watch' can see processes in the current shell via 'procfs', a "pseudo" file system dynamically generated by the kernel to provide information about the status of entries in its process table. So I am unclear why 'watch' would not be present in the termux procps package. If anyone knows answers regarding 'watch(1)' in termux, I would appreciate dialog.

**Comment by xeffyr** [comment]
> So I am unclear why 'watch' would not be present in the termux procps package.

I'm unclear why your Termux installation doesn't have it...

Verify that your installation is correct and packages are up-to-date. As of 2020.10.30, the latest `procps` version is `3.3.16-2`. If you have something else - upgrade packages, otherwise re-install Termux.

I don't see any issue on our side.

![Screenshot_20201030-211904_Termux](https://user-images.githubusercontent.com/25881154/97748133-a6a3e280-1af5-11eb-94a9-7395760aec86.png)
