### ISSUE TITLE
Pkg update BADSIG 5A897D96E57CF20C

### ISSUE THREAD

**Issue by maeluiseryn** [termux/termux-packages#5986]
**Problem description**

The command pkg update fails with error:

W: GPG error: https://grimler.se/termux-packages-24 stable Release: The following signatures were invalid: BADSIG 5A897D96E57CF20C Termux Releases (Termux automatic builds) <contact@termux.com>
E: The repository 'https://grimler.se/termux-packages-24 stable Release' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

**Steps to reproduce**

Executing command pkg update

**Expected behavior**

Should update package list 

**Additional information**

**Comment by maeluiseryn** [comment]
Reinstalling termux solved the issue

**Comment by Grimler91** [comment]
Thanks for reporting, reinstalling termux seem to have selected another mirror for you, which did not have this problem. Reinstalling termux should not technically be necessary in this case since the problem is with the mirror rather than with termux on your device. 

Anyways, I fixed the problem by manually updating the files on the mirror after your report, thanks.
