### ISSUE TITLE
Package request: mingw-w64

### ISSUE THREAD

**Issue by rc-chuah** [termux/termux-packages#6027]
**Package description**
Mingw-w64 is an advancement of the original mingw.org project, created to support the GCC compiler on Windows systems. It has forked it in 2007 in order to provide support for 64 bits and new APIs. It has since then gained widespread use and distribution.

**Link to home page and sources**
1. Home page: http://mingw-w64.org/doku.php
2. Source code: https://github.com/mirror/mingw-w64

**Additional information**
* http://mingw-w64.org/doku.php/download
* http://mingw-w64.org/doku.php/documentation

**Comment by xeffyr** [comment]
Wontfix.

**Comment by xtkoba** [comment]
MinGW-w64 does not necessarily require GCC running on Android. We can borrow recipes from <a href="https://github.com/mstorsjo/llvm-mingw">LLVM MinGW</a> and build MinGW-w64 toolchain to work with Clang/LLVM.

**Comment by leapofazzam123** [comment]
why would anyone even want to build windows apps on fucking android

**Comment by leapofazzam123** [comment]
maybe this should be in tur

**Comment by rajveerexe** [comment]
> why would anyone even want to build windows apps on fucking android

So Called Encrypters need that

**Comment by SwuduSusuwu** [comment]
> why would anyone even want to build windows apps on fucking android

- Because not everyone can afford to use a traditional computer with _Microsoft Windows_ (_Win32_), but everyone should produce cross-platform code.
- _MinGW_ allows you to ensure that your code is cross-platform (if your code compiles on _Linux_ + _Win32_, it is more cross-platform than most code).
  - You can also use [_Hangover_](https://github.com/termux/termux-packages/issues/23987) to ensure that unit tests pass on _Win32_.

**Comment by Biswa96** [comment]
@SwuduSusuwu Please stop posting in closed older threads. There is already a llvm-mingw-w64 package https://github.com/termux/termux-packages/tree/master/packages/llvm-mingw-w64
