### ISSUE TITLE
mopidy

### ISSUE THREAD

**Issue by DarkPhoenix2005** [termux/termux-packages#6046]
Mopidy is an extensible music server written in Python.

Mopidy plays music from local disk, Spotify, SoundCloud, Google Play Music, and more. You edit the playlist from any phone, tablet, or computer using a variety of MPD and web clients

Link to repo:https://github.com/mopidy/mopidy

**Comment by Grimler91** [comment]
We generally do not package python modules that can be installed through pip (see https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests). 

Do you get an error when installing mopidy through pip? Or when running mopidy after it has been installed from that source?

**Comment by DarkPhoenix2005** [comment]
Yes, I tried to install it with pip but when I try to start it it gives me a module error called  ```ca``` and that is not available in pypi.

**Comment by Grimler91** [comment]
I am getting an error due to gst-python not being installed, and we do not have that one as a package (requested before in https://github.com/termux/termux-packages/issues/1932). I'll re-open that one in case someone wants to look into it, but cross-compiling python stuff is not really supported (by python), so might take a while.
