### ISSUE TITLE
elfutils-ext and libelf provide the same file

### ISSUE THREAD

**Issue by ph4n70m-nuk3r** [termux/termux-packages#6104]
**Problem description**
Packages `elfutils-ext` and `libelf` clash on header file.
![Screenshot_20201130-095426~2](https://user-images.githubusercontent.com/74739269/100595497-e0355c80-32f2-11eb-8d3e-b967c6ec7b67.png)

**Steps to reproduce**
- Install:
  - Package: `libelf`, Version: `0.179`
- Install:
  - Package: `elfutils-ext`, Version: `0.176`
- Try to upgrade:
  - Package: `libelf`, Version: `0.182`

**Expected behavior**
Package able to be upgraded.

**Additional information**
```
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list                            deb https://main.termux-mirror.ml/ stable main                                      # science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)    deb https://dl.bintray.com/grimler/game-packages-24 games stable                    Updatable packages:
libelf/stable 0.182 arm [upgradable from: 0.179]
Android version:
7.0
Kernel build information:
Linux localhost 3.18.35+ #1 SMP PREEMPT Tue Mar 26 11:34:42 CST 2019 armv7l Android
```

**Comment by Grimler91** [comment]
You seem to have an installation with old android < 7 packages as well as android >= 7 packages, since elfutils-ext is not a package in any android >= 7 repositories. This will lead to various problems. I would recommend you to uninstall termux and then re-install the app, you can backup files in your home directory before following instructions on the wiki: https://wiki.termux.com/wiki/Backing_up_Termux

Closing since elfutils-ext is not a package that is available for android >= 7.
