### ISSUE TITLE
Termux is awesome

### ISSUE THREAD

**Issue by dzproduction24** [termux/termux-packages#616]
Hello I am some dude who fucking loves Termux, its awesome so awesome that I really really wish to be able to have the termux packages as a standalone binary (lik busybox) which occasionaly installs to /system/xbin, I tryed some stuff like moving all the bins manually to system xbin but then I recognised that the bins are linked to hardcoded lib files. Isnt there anyway we could possibly embed this *.so files in the binaries itself ? btw. busybox is a biatch cuz most of the tools are stripped down and few bins like wget wont work for some odd reason

**Comment by fornwall** [comment]
Thanks!

> Isnt there anyway we could possibly embed this *.so files in the binaries itself?

It's unfortunately out of scope for the current Termux project to have statically linked binaries. Note however that you can put a script like e.g. this in `/system/xbin/bash`:

```sh
#!/system/bin/sh

PREFIX=/data/data/com.termux/files/usr
LD_LIBRARY_PATH=$PREFIX/lib $PREFIX/bin/bash $@
```

This sets up the shared libraries so that you can call `/system/xbin/bash` from other apps.

> busybox is a biatch cuz most of the tools are stripped down and few bins like wget wont work for some odd reason

The busybox tools are stripped down as you say, and e.g. wget does not support https or a lot of options. But most of the fully-featured tools are available in Termux, run e.g. `apt install wget` to install the normal fully-featured wget, and `apt install coreutils` to install the fully-featured versions of tools such as `ls`.
