### ISSUE TITLE
golang: linker problem on build

### ISSUE THREAD

**Issue by tonvieira** [termux/termux-packages#6183]
On build a GoLang simple project Iˋm getting this error:

runtime/cgo
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: $WORK/b057/_x006.o:/data/data/com.termux/files/usr/lib/go/src/runtime/cgo/gcc_linux_arm64.c:15: multiple definition of `x_cgo_inittls'; $WORK/b057/_x003.o:/data/data/com.termux/files/usr/lib/go/src/runtime/cgo/gcc_android.c:80: first defined here
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)

On a simple Hello World it builds, but when I import the package net/http stops to build.

command used:
go build

also happens on:
go test

**Comment by landfillbaby** [comment]
might be related to #6174¿

**Comment by xeffyr** [comment]
@landfillbaby Very unlikely. https://github.com/termux/termux-packages/pull/6174 is a draft and is not merged.

However `clang` was recently updated to 11.

**Comment by RossComputerGuy** [comment]
Maybe look at how `x_cgo_inittls` is defined/used in `/data/data/com.termux/files/usr/lib/go/src/runtime/cgo/gcc_linux_arm64.c` and `/data/data/com.termux/files/usr/lib/go/src/runtime/cgo/gcc_android.c`

**Comment by xeffyr** [comment]
Fixed by https://github.com/termux/termux-packages/commit/20f7ae73afb8a5110bafe6281d980b268125e590 + https://github.com/termux/termux-packages/commit/533e7987294e1c2f8b59574aa5ece0e1cf081c57.

P.S. You can even workaround it manually, until updated `golang` package will be available for installation. Just edit `/data/data/com.termux/files/usr/lib/go/src/runtime/cgo/gcc_linux_arm64.c` by adding `extern` to definition of `x_cgo_inittls`.

**Comment by emuvs** [comment]
Thanks!
