### ISSUE TITLE
Bug report: locate

### ISSUE THREAD

**Issue by BigBrotherIsWatchingYa** [termux/termux-packages#619]
I installed mlocate, and when I try to use it:

$ locate script
locate: can not stat () `/data/data/com.termux/files/usr/var/mlocate/mlocate.db': No such file or directory

**Comment by fornwall** [comment]
You need to run `updatedb` to generate or updated the locate database. There is currently no automated setup of this in the Termux package.

**Comment by BigBrotherIsWatchingYa** [comment]
Ooooh okay, sorry and thank you ^^.

**Comment by wdscxsj** [comment]
I installed `mlocate` and called `updatedb`, but even this fails to print anything:

```
$ locate locate
```

`mlocate.db` has been properly created because `locate` can be found under the `/data/data/com.termux/files/usr/bin` area in the db's content.

It seems that my `locate` doesn't use `mlocate.db` at all. Deleting `mlocate.db` WON'T cause an error like "locate: can not stat () '/data/data/com.termux/files/usr/var/mlocate/mlocate.db': No such file or directory". On the other hand, `locate -h` works fine.

Actually I've reinstalled `mlocate` several times without success. Any suggestion is welcome. Thanks!

**Comment by remo7777** [comment]
:cold_sweat: not working mlocate

**Comment by remo7777** [comment]
:cold_sweat: not working mlocate

**Comment by fornwall** [comment]
See https://github.com/termux/termux-packages/issues/1454 - version `0.26-2` of the mlocate package fixed running on Android 7.0 or later versions.

**Comment by zroorz** [comment]
> See #1454 - version `0.26-2` of the mlocate package fixed running on Android 7.0 or later versions.

How to find other paths except APP data path?

**Comment by mySaYo** [comment]
> > 请参阅#1454 -`0.26-2`在 Android 7.0 或更高版本上修复的 mlocate 包版本。
> 
> 如何找到除termux数据路径之外的其他路径？

updatedb -U /sdcard/
 The sdcard is added with this command, but the other directories are gone. . .
