### ISSUE TITLE
nvim: bug within android 11 fdsan

### ISSUE THREAD

**Issue by fireclouu** [termux/termux-packages#6251]
**Problem description**

some plugins for neovim not working because android's fdsan emitted error
**Steps to reproduce**

install neovim, plug ALE and you'll see it isnt working due to restriction to file that needed to be analyzed
**Expected behavior**

it should lint and fix errors on neovim since it is a plugin that supports that
**Additional information**

```
try to look for :ALEInfo and check logs , fdsan restricts reading/writing some file
```

**Comment by Grimler91** [comment]
Probably related, though in your case it does not seem to crash in the same way:

https://github.com/termux/termux-packages/issues/5980
https://github.com/termux/termux-packages/issues/5790
https://github.com/termux/science-packages/issues/50

**Comment by Grimler91** [comment]
The issue probably has to be fixed in the plugin source code https://github.com/dense-analysis/ale, but it would probably help them if we can pinpoint where it happens.

**Comment by sudipta-nandan** [comment]
even :PluginInstall command in vim is throwing fdsan error.

**Comment by sudipta-nandan** [comment]
![Screenshot_20210326_020517_com.android.chrome.jpg](https://user-images.githubusercontent.com/25419259/112540299-04ec9d00-8dd8-11eb-9c37-da20674a084a.jpg)

will this document be of any help?

**Comment by sudipta-nandan** [comment]
I just want to add something in this issue...
I first noted this same issue while running :PluginInstall command in vim in my Android 11 device. A few days ago.

Today i saw the logcat from termux and to my surprise i saw each time the error got invoked the logs ar dumping under 'zsh'. It was always accompanied by a zsh process.

So I changed the shell from zsh to bash.
Voila! No Errors.

In my opinion the problem most of the people are facing are due to handling of some files by 'zsh shell'. I would ask then to change their shell to 'bash' and try to reproduce the same and see whether the error is gone.

And I think the error is in the code of zsh shell.
Hope this helps.

**Comment by xeffyr** [comment]
zsh issue is here: https://github.com/termux/termux-packages/issues/6376

**Comment by fireclouu** [comment]
ah yes `zsh` is to blame, closing this now.
