### ISSUE TITLE
[Question] Build llvm and clang for termux from source

### ISSUE THREAD

**Issue by namniav** [termux/termux-packages#6257]
Hi, thanks a lot for your amazing work on Termux! 
I am trying to compile llvm(with its sub-projects and tools, e.g. clang, clangd, lldb, etc.) from [source](https://github.com/llvm/llvm-project) in Termux. I managed to compile them successfully except that they are built to targeting `aarch64-unknown-linux-gnu`(while the clang installed by `pkg` is built to targeting `aarch64-unknown-linux-android24`) and when I use the compiled clang to compile a `helloword.c`, it tried to and failed to link with some non-existing `crt*.o`s for entry point of the program.
I could fix this by manually running `ld helloworld.o` with correct linking flags(copied from  `clang -v` with the installed clang). But I am still wondering the more correct way to build llvm for termux. Is there any tips about how the llvm package is built?

**Comment by Grimler91** [comment]
You can see all the patches we apply here: https://github.com/termux/termux-packages/tree/master/packages/libllvm, and some details about how it is cross-compiled here: https://github.com/termux/termux-packages/blob/master/packages/libllvm/build.sh

Since it is cross-compiled and not compiled in termux you may have to adjust some things though.
