### ISSUE TITLE
Add pdo_mysql to php package

### ISSUE THREAD

**Issue by emilio1625** [termux/termux-packages#630]
PHP package exists in repository but has no mysql support
I understand that it is complex to create a mariadb package, but is there any reason not to include pdo_mysql driver?

**Comment by Wetitpig** [comment]
Can you provide the script? Thanks

**Comment by Neo-Oli** [comment]
@emilio1625 The reason you can't include the pdo_mysql driver is because it can't be built without mariadb. It is a requirement for both building and running pdo_mysql, even if you use a remote database. That said, as soon as mariadb also works on arm (it only works on aarch64 at the moment) the pdo_mysql driver can be included. There is already a pull request for it here: https://github.com/termux/termux-packages/pull/1025. As far as I know, we're waiting for the release of the next version of the Android NDK, which shouldn't be too long.

If you are running aarch64 and don't want to wait, you can build php with pdo_mysql yourself with the linked pull request. I've been testing it with both a remote and local mariadb server and it works great.

**Comment by robertvalik** [comment]
I believe the MariaDB package is working - #216 . It would be great to have pdo_mysql!

**Comment by sicaboy** [comment]
any update on this?

**Comment by gagan0123** [comment]
Even I'm waiting for this for so long.

Thanks to the Termux team we now have mariadb, but without MySQL extension for PHP, its of no use.

**Comment by fornwall** [comment]
Thanks to @vishalbiswas there is now a `php-mysql` package - install with `pkg install php-mysql`!

**Comment by alo0oz** [comment]
No php-mysql package is available in the repo.

**Comment by Quasic** [comment]
@alo0oz, see #1912
