### ISSUE TITLE
mu package does not include mu4e

### ISSUE THREAD

**Issue by citizenkevin** [termux/termux-packages#6394]
It's not clear to me if this is a bug or a package request. 

> pkg install mu  

appears to not include mu4e, the popular email client for emacs users, as expected (forr mu, most distros seem to include mu4e with it), which leads to the following error within emacs when attempting to run mu4e:

> Cannot open load file: No such file or directory, mu4e. 

For Ubuntu/Debian, it *seems* mu4e may be included in the 'maildir-utils' package (https://github.com/djcb/mu). However, if a "mu" package exists in the termux pkg manager, makes me wonderr why mu4e isn't a part of it.

So I'm a bit confused. Can someone clarify what's going on here? What's the path to getting mu4e installed in termux?

**Comment by m4lvin** [comment]
I think this happens because `emacs` is not listed as a dependency in the `build.sh`:

https://github.com/termux/termux-packages/blob/10e3f4d4ffe86d2c37af39d1a341539325473bf9/packages/mu/build.sh#L8

Hence emacs is not available while building mu. And mu checks for that at build-time, see [here](https://github.com/djcb/mu/blob/42f2e73025d9000e958d31687bb17edf3ef787c1/configure.ac#L88). And here is an example of the termux build log, copying from https://github.com/termux/termux-packages/runs/3517683624#step:3:2053. I think the `command not found` comes from no `emacs` being available.
```
/home/builder/.termux-build/mu/src/configure: line 15001: no: command not found
configure: WARNING: emacs is too old to build mu4e (need emacs >= 25.3)
```
Then later the same build log shows this:
```
mu configuration is complete.
------------------------------------------------
mu version                           : 1.6.6

Xapian version                       : 1.4.18
GLib version                         : 2.66.1
GMime version                        : 3.2.7
Build 'mug' toy-ui (gtk+/webkit)     : no

Have direntry->d_ino                 : yes
Have direntry->d_type                : yes
------------------------------------------------
```
When I compile mu on another system this block also contains a line about building mu4e:
```
mu configuration is complete.
------------------------------------------------
mu version                           : 1.6.6

Xapian version                       : 1.4.18
GLib version                         : 2.66.8
GMime version                        : 3.2.7
Build mu4e                           : yes
Emacs version                        : GNU Emacs 27.1
Build 'mug' toy-ui (gtk+/webkit)     : no

Have direntry->d_ino                 : yes
Have direntry->d_type                : yes
------------------------------------------------
```

The easy solution might thus be to add `emacs` to `TERMUX_PKG_DEPENDS` :thinking: 

However, also in Debian `mu4e` [does not depend on](https://packages.debian.org/bullseye/mu4e) `emacs`. And technically I guess emacs is only a build-time dependency, so I am wondering if there is a way to specify those for ermux packages?

**Comment by Grimler91** [comment]
> The easy solution might thus be to add `emacs` to `TERMUX_PKG_DEPENDS` :thinking:
> 
> However, also in Debian `mu4e` [does not depend on](https://packages.debian.org/bullseye/mu4e) `emacs`. And technically I guess emacs is only a build-time dependency, so I am wondering if there is a way to specify those for ermux packages?

Termux has TERMUX_PKG_BUILD_DEPENDS for build-time dependencies. 

Could be that emacs for the host needs to be installed in the docker image we are cross-compiling with as well, in which case emacs-nox needs to be added to [setup-ubuntu.sh](https://github.com/termux/termux-packages/blob/master/scripts/setup-ubuntu.sh)

**Comment by m4lvin** [comment]
> Termux has TERMUX_PKG_BUILD_DEPENDS for build-time dependencies.

Thanks!!


After adding `TERMUX_PKG_BUILD_DEPENDS="emacs"` I could see that emacs is built, but still get no mu4e:

```
mu configuration is complete.
------------------------------------------------
mu version                           : 1.6.6

Xapian version                       : 1.4.18
GLib version                         : 2.66.1
GMime version                        : 3.2.7
Build 'mug' toy-ui (gtk+/webkit)     : no

Have direntry->d_ino                 : yes
Have direntry->d_type                : yes
------------------------------------------------
```

Hence I did `sudo apt update && sudo apt install emacs` within the docker container as well as "rm -rf /data/data/.built-packages/mu output/mu_1.6.6_arm.deb`.
A new run of "./build-package.sh -a arm mu" then gave me the following:

```
mu configuration is complete.
------------------------------------------------
mu version                           : 1.6.6

Xapian version                       : 1.4.18
GLib version                         : 2.66.1
GMime version                        : 3.2.7
Build mu4e                           : yes
Emacs version                        : GNU Emacs 26.3
Build 'mug' toy-ui (gtk+/webkit)     : no

Have direntry->d_ino                 : yes
Have direntry->d_type                : yes
------------------------------------------------
```

And indeed, when I copy the resulting `output/mu_1.6.6_arm.deb` to my phone and install it in termux with `sudo apt install ./mu_1.6.6_arm.deb` then I get a working mu4e in emacs! 🎉

However, I did not test anything besides opening the mu4e homescreen and I am worried that mu4e is now built for the older emacs 26.3 in ubuntu (in the docker container), and not the version 27.2 that is in termux itself :-/

I do not yet understand what the effect of `TERMUX_PKG_BUILD_DEPENDS` actually is. Shouldn't binaries from those packages be available when building the package? Is the compiling actually happening in the docker container or "one level deeper" in an arm-qemu-chroot or such which simulates termux as closely as possible? is one of these what is called a "host build" in the wiki? 🤔 Sorry for all the newcomer questions!

**Comment by m4lvin** [comment]
I have now tried the following:

```
termux_step_pre_configure() { 
  export EMACS=$TERMUX_PREFIX/bin/emacs
}
```

However, this gives
```
/home/builder/.termux-build/mu/src/configure: line 15001: /data/data/com.termux/files/usr/bin/emacs: cannot execute binary file: Exec format error
```
which is somewhat expected, because this emacs binary is compiled for arm and cannot run on the build host. Is there a way to execute an a foreign architecture binary during the build process? :thinking: 

Alternatively, I tried `TERMUX_PKG_HOSTBUILD=true` but then I get this:
```
configure: error: Package requirements (gmime-3.0) were not met:

No package 'gmime-3.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GMIME_CFLAGS
and GMIME_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

Also after looking at the build scripts for other packages using gmime it was not clear to me how to fix this :thinking:

**Comment by Grimler91** [comment]
> Shouldn't binaries from those packages be available when building the package

TERMUX_PKG_BUILD_DEPENDS makes the libraries, binaries and other files for arm/aarch64/i686/x86_64 available, but they cannot be run since they are for another architecture

Should be no need for a hostbuild of mu4e (probably), using

```
termux_step_pre_configure() { 
  export EMACS=/usr/bin/emacs
}
```
Hopefully works. It could be a problem that host emacs is 26.3, as you mentioned, but if it seemed to work then maybe it is fine (to get newer emacs we need to update the docker image that we are building in)

**Comment by m4lvin** [comment]
Thanks!

> to get newer emacs we need to update the docker image that we are building in

Currently there is no emacs at all, the one above I installed manually in my running docker container.

Would it be okay to submit a PR which adds the dependency in `build.sh` and also updates the list of packages in https://github.com/termux/termux-packages/blob/master/scripts/setup-ubuntu.sh?

**Comment by Grimler91** [comment]
@m4lvin yes, please open a PR!
It shouldn't be necessary to add emacs to TERMUX_PKG_BUILD_DEPENDS, adding it to setup-ubuntu.sh should be enough
