### ISSUE TITLE
Cannot ssh-keygen

### ISSUE THREAD

**Issue by huiyiqun** [termux/termux-packages#64]
```
$ which ssh-keygen
/data/data/com.termux/files/usr/bin/ssh-keygen
$ ssh-keygen
CANNOT LINK EXECUTABLE: cannot locate symbol "OpenSSL_add_all_algorithms" referenced by "ssh-keygen"...
page record for 0xb6eef00c was not found (block_size=64)
```

**Comment by fornwall** [comment]
Could it be bash caching the path to the system ssh-keygen executable? Unfortunately `which` does not show that, since it does not know about the bash path cache.

So, run `hash -r` and try again (or create a new session)! If it still fails for you after doing that, and making   sure that you have the latest package versions (run `apt update && apt upgrade`): Which device do you have, and which Android version do you run?

**Comment by huiyiqun** [comment]
It works, thanks.

**Comment by reduardo7** [comment]
I have same problem. I can't fix with it.

**Comment by fornwall** [comment]
@reduardo7 See my response in #203.

**Comment by arvind-gr** [comment]
@fornwall Solution worked on me too. Issue previously observed on Android Pie rooted with Magisk 18.1
