### ISSUE TITLE
Need a way to downgrade libicu to version 67

### ISSUE THREAD

**Issue by anang42429** [termux/termux-packages#6415]
So, I'm building a small application using python and mongodb as the database, and after the last update, mongodb can't run.

I've stored about 20mb of data generated over the last 9 months into Mongodb.

Is there a way to downgrade libicu to version 67?

![Screenshot_20210216-123458.png](https://user-images.githubusercontent.com/39028530/108108744-9b37ef80-70c3-11eb-8a13-3733323279f0.png)

**Comment by landfillbaby** [comment]
instead of downgrading libicu, ask @its-pointless to rebuild mongodb

**Comment by anang42429** [comment]
> instead of downgrading libicu, ask @its-pointless to rebuild mongodb

Can you show me how to rebuild Mongodb? I have opened the issue on the @its-pointless repo, and there is no answer.

**Comment by xeffyr** [comment]
Sorry, downgrading isn't supported. Termux implements rolling-release updates variant, we do not keep older package versions as will introduce issues with binary repository size as well as will make tracking old deb files pending for removal more difficult. Library updates, like libicu, may introduce ABI changes which will require rebuilding all dependent packages and thus not backwards compatible. While downgrade will fix `mongodb`, it will break all other packages.

As in https://wiki.termux.com/wiki/Getting_started#Tips:
*Do backups, always! Without backups, you will be probably unable to roll back if something go wrong. Please note that software developers should pay attention to backing up debfiles of used compilers, interpreters or dependencies because Termux does not provide older package versions and it is a rolling-release.*

> Can you show me how to rebuild Mongodb?

Neither patches nor build script is available for `mongodb`.
