### ISSUE TITLE
dlopen failed: library "/data/data/com.termux/files/usr/libexec/apache2/li bphp7.so" not found

### ISSUE THREAD

**Issue by dzxjava** [termux/termux-packages#6493]
I set php-apache,then I execute apachectl start, There was an error here.

`dlopen faile d: library "/data/data/com.termux/files/usr/libexec/apache2/li bphp7.so" not found`

I used Google to find the cause, but the problem is still not resolved.So I am here to ask you for help. Can friends give me some suggestions?

**Comment by amm834** [comment]
When php is version 8.0, libphp7.so file is removed from libexec because termux did not support old version.
You can use `php8` .

You can setup php module like this,
[Https Conf File](https://github.com/amm834/developement_env_setup/blob/main/httpd.conf) 

If you want to setup yourself, you can do like that

```conf
LoadModule php_module libexec/apache2/libphp.so
<FilesMatch \.php$> 
   SetHandler application/x-httpd-php
</FilesMatch>
<IfModule dir_module>
    DirectoryIndex index.php
</IfModule>
```
At the end of `httpd.conf`.
You will need to install
```
pkg install php php-apache apache mariadb -y
```

Do you want to setup from scratch?
Read this 
[Termux LAMP stack setup from scratch](https://github.com/amm834/Developement-Setup)

**Comment by dzxjava** [comment]
> When php is version 8.0, libphp7.so file is removed from libexec because termux did not support old version.
> You can use `php8` .
> 
> You can setup php module like this,
> [Https Conf File](https://github.com/amm834/developement_env_setup/blob/main/httpd.conf)
> 
> If you want to setup yourself, you can do like that
> 
> ```
> LoadModule php_module libexec/apache2/libphp.so
> <FilesMatch \.php$> 
>    SetHandler application/x-httpd-php
> </FilesMatch>
> <IfModule dir_module>
>     DirectoryIndex index.php
> </IfModule>
> ```
> 
> At the end of `httpd.conf`.
> You will need to install
> 
> ```
> pkg install php php-apache apache mariadb -y
> ```
> 
> Do you want to setup from scratch?
> Read this
> [Termux LAMP stack setup from scratch](https://github.com/amm834/Developement-Setup)

I set it up according to your suggestion, and it can work normally.
Thank you very much. Your answer solved my problem.
