### ISSUE TITLE
How can I ensure a package gets into the repo?

### ISSUE THREAD

**Issue by soaringowl2145** [termux/termux-packages#653]
I have seen packages on here that have went months without being added to the repo.  Is there something that can do to help speed up the process?

Thanks.

**Comment by fornwall** [comment]
I've fallen behind on pull requests unfortunately, but will go through them the coming weeks.

With that said, if there is a package you want specifically you can comment on it's issue, perhaps stating your use case or arguing why it's important.

About helping out the project, there are some things one could do:

- Help resolving issues in existing packages, so that we have a better quality in the packages already added, and free up resources for looking at new ones.
- Help with keeping already added packages up to date.
- Help out with resolving issues and spreading information at the Google+ community (https://termux.com/community).
- Offer to maintain an 'extras' repository where packages could be added more freely (a larger undertaking, but it would be great if anyone tried it).

**Comment by soaringowl2145** [comment]
Well I know there are many downloaders in the repo, but none of them can ACCELERATE a download.  Axel can actually cut download time by a huge amount, like to 20 percent of what it would normally take if issued a command such as:

axel -n 100 urltofile

**Comment by fornwall** [comment]
Aha! The downside with axel is that it seems to be a dead project (last release in 2009).

However, have you tried [aria2](https://aria2.github.io/) (`apt install aria2`, then execute `aria2c`)? Look at the `-x` flag for downloading a file from one host using multiple connections.

**Comment by soaringowl2145** [comment]
It just updated a few days ago.  The other one was a fork.  The one I am referencing is here:

https://github.com/eribertomota/axel
