### ISSUE TITLE
`texlive-bin` package executables unreachable

### ISSUE THREAD

**Issue by askar882** [termux/termux-packages#6588]
**Problem description**

After installing `texlive-bin` package, I'm still unable to run the executables created by the package. That is, if I run `pdftex` command I get a `command not found` error.
I noticed that the package created a folder named `texlive` under `/data/data/com.termux/files/usr/bin/` and the executables like `pdftex` is in that folder. But the `texlive` folder is not in the `$PATH` variable, making it impossible to run those executables directly from the command line.
I'm wondering if this is a bug or the `texlive` folder is meant to be manually added to the `$PATH`.

**Steps to reproduce**

Run `apt install texlive-bin` to install the package and then run `pdftex`.

**Additional information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.9.186-perf+ #2 SMP PREEMPT Wed Aug 5 22:10:22 CST 2020 armv8l Android
Device manufacturer:
Google
Device model:
Pixel 3
```

**Comment by Grimler91** [comment]
Currently, the directory is added to PATH through a profile script which is created by the [texlive](https://github.com/termux/science-packages/blob/6485c133c539ec20663cf5807a3d1e5db3c8e917/packages/texlive/build.sh#L52) package or the [texlive-installer](https://github.com/termux/unstable-packages/blob/6864b5fff3b420e8f3bd50c42ebd1e04ec7c539f/packages/texlive-installer/build.sh#L46) package. 

If you installed texlive-bin then it should install [`texlive` as well](https://github.com/termux/termux-packages/blob/34916a6f65207e41ced26f3bedb16fc371a0dc12/packages/texlive-bin/build.sh#L16) unless you chose to not install the recommended packages? 

If you have installed texlive as well then you need to source $PREFIX/etc/profile.d/texlive.sh or restart the shell to update PATH (the info message at the end of the installation [mentions this](https://github.com/termux/science-packages/blob/6485c133c539ec20663cf5807a3d1e5db3c8e917/packages/texlive/build.sh#L72)).

Setting up the profile script would make more sense in `texlive-bin`. I deliberately put it in `texlive` and `texlive-installer` so that `texlive` would not be an empty package though, as empty packages are removed by apt (might be possible to tweak our build-package process to avoid this).

**Comment by askar882** [comment]
I didn't have `science-repo` or `unstable-repo` installed. So when I install `texlive-bin`, neither `texlive` nor `texlive-installer` is installed automatically. After installing `science-repo` and reinstalling `texlive-bin`, `pdftex` is finally running.
Thank you very much.
