### ISSUE TITLE
I have not been able to install Python 3 yet, it gives an error, my Android phone is 8, please help me

### ISSUE THREAD

**Issue by sweetman135** [termux/termux-packages#6598]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by xeffyr** [comment]
* Use `pkg install python`.
* Use `termux-change-repo` if issues are with repository.
* Use Termux app from F-Droid because `pkg` in the build from Google Play contains outdated mirror list.
* Ensure you don't have networking issues.
* Ensure you don't have storage issues.
* Ensure your Termux environment is not broken.
* I can continue this list further because you have not provided issue description...

Fill the issue template properly next time.

**Comment by sweetman135** [comment]
Xeffyr:
Thank you for your guidance
