### ISSUE TITLE
Waiting for cache lock: Could not get lock /data/data/com.termux/files/usr/var/lib/dpkg/lock-frontend. It is helWaiting for cache lock: Could not get lock /data/data/com.termux/files/usr/var/lib/dpkg/lock-frontend. It is held by process 29039 (dpkg)

### ISSUE THREAD

**Issue by manya7777777** [termux/termux-packages#6603]
![Screenshot_20210407-144014](https://user-images.githubusercontent.com/63000958/113841328-363d7380-97af-11eb-9a51-86533b0bba71.png)

**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by agnostic-apollo** [comment]
Just close all termux sessions and restart app and try again. There might be some other `dpkg` command running in a different session, you can confirm it with `pgrep -fa dpkg` and then kill it with `kill <pid>`.

Otherwise, run `rm -f $PREFIX/var/lib/dpkg/lock-frontend` to delete the lock file and try again.

**Comment by manya7777777** [comment]
It won't work.

**Comment by agnostic-apollo** [comment]
There might be some other lock files that are left that need to be deleted. Did you get a different error?

**Comment by xeffyr** [comment]
> There might be some other lock files that are left that need to be deleted.

No need, if they are not acquired by already running process.

@manya7777777 You have multiple instances of apt/dpkg running, perhaps on other sessions. I will assume you have executed `pkg upgrade` on multiple sessions but can't get further due to configuration replacement dialog. Open session where package manager is still running and do what is prompted to finish the upgrade. Otherwise force-close Termux. Never run multiple instances of package manager, this is not supported.

**Comment by agnostic-apollo** [comment]
> @agnostic-apollo No need, if they are not acquired by already running process.

Yeah, actually that makes sense since it gave the pid. I guess I'm stuck in the past.

**Comment by Kuppanvairamalai** [comment]
Options marked [*] produce a lot of output - pipe it through 'less' or 'more' !
