### ISSUE TITLE
Package request: U-Boot

### ISSUE THREAD

**Issue by LeapofAzzam-backup** [termux/termux-packages#6638]
## Requesting new package

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [X] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description

U-Boot is an open-source, primary boot loader used in embedded devices to package the instructions to boot the device's operating system kernel. It is available for a number of computer architectures, including 68k, ARM, Blackfin, MicroBlaze, MIPS, Nios, SuperH, PPC, RISC-V and x86

**Link to home page and sources**

1. Home page: https://www.denx.de/wiki/U-Boot/
2. Source code: https://github.com/u-boot/u-boot

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into. (I got a lot of linker error. I tested it with Qemu AArch64 configuration.)
* If it did work then please share build steps and any patches that you had to apply.

**Comment by RossComputerGuy** [comment]
> boot loader

I don't see why we should have u-boot installed. Termux runs on top of Android and doesn't have access to the partitions like a typical Linux distro. This means Termux is sort of a "sandboxed" Linux environment. If you need U-Boot then you'll have a rooted device and a proot distro would definitely have u-boot in its repositories. The only way U-Boot would be of some use would be to have a rooted device and since not every Android device can be rooted, this won't be added to the main repository. Plus I don't think we even have GRUB or syslinux in the package repositories because of the reasons I have already stated.

**Comment by WMCB-Tech** [comment]
Downloaded u-boot packages in *Debian* and it seems it might be used for QEMU, but not sure on how usable it is

**Comment by Grimler91** [comment]
U-boot, and the Linux kernel, are device specific. A generic package would not be usable. 

Barely any phones/tablets are supported either so to use u-boot you first need to port it to your device. (I.e creating device tree files, setting up a board init file and finding the base memory address where u-boot is loaded)

**Comment by LeapofAzzam-backup** [comment]
I know, i want to use it for QEMU

**Comment by LeapofAzzam-backup** [comment]
> Downloaded u-boot packages in _Debian_ and looked at the contents, it seems it might be used for QEMU, but not sure on how usable it is for real usage though

Yeah, we should reopen this

**Comment by LeapofAzzam-backup** [comment]
I only need it for QEMU, not for my phone

**Comment by xeffyr** [comment]
@LeapofAzzam-backup You can get prebuilt binaries from Debian package.
