### ISSUE TITLE
Compiled QEMU becomes very slow at welcome screen

### ISSUE THREAD

**Issue by mjuned47** [termux/termux-packages#6651]
Android version : 7

I have compiled qemu 5.1 on termux using clang provided by termux
I have applied hard-core path patch from termux-packages repo
Building and Installation is fine
But when i boot windows xp on this compiled qemu ,it becomes very slow on and after welcome screen
I have tried windows xp x64 , windows 95 , it boots fine.
The file which it cause issue is windows xp 32bit (sp3). I have booted this xp before it was working fine but now its not.
I have tried even limbo emulator, same issue.
After this , I remove my compiled qemu and install qemu provided by termux ,even same issue on this one too

Can you help me in this?

**Comment by WMCB-Tech** [comment]
Emulation of *Windows XP 32-bit* is slow for me compared to *64-bit* edition of Windows XP

QEMU emulation depends on your devices speed, although you may try specifying `tb-size`

`-accel tcg,tb-size=512`

**Comment by mjuned47** [comment]
I have compiled qemu with spice support .
Definitely 32bit emulation is slow but in my case pointer becomes very slow(moving) which was not happen before for same winxp file.
My qemu build with spice support :
https://github.com/mjuned47/qemu-termux

You can test and check this issue

**Comment by MTSYuki** [comment]
Does Limbo is a modified version of QEMU? I've successfully installed Dawn Small Linux.
It runs, a little slow, and seems stable. 

My phone is 32-Bit, 2GB RAM.

AFAIK, Emulating old versions of Windows is gonna be slow because the lack of ARM architecture support. (A x86 or x64 OS running on ARM need a strong CPU power)

**Comment by mjuned47** [comment]
No , i tried limbo just because to see if the same issue persist on it
And yes same issue on limbo too(which is not modified)

**Comment by xeffyr** [comment]
Expect no more than 1-3 frames per second on emulated graphical OS. Emulation of graphics require more computing power than emulation of headless machine. That's completely normal, don't forget that QEMU is **emulator**. I don't see any issue there.

***

And if there really exist the issue which causes slow down, it won't be fixed. QEMU, specifically the TCG/emulator part, is a very complex thing. I have no wish to spend weeks on debugging it.

**Comment by xeffyr** [comment]
Additional input on few moments:

> But when i boot windows xp on this compiled qemu ,it becomes very slow on and after welcome screen

This indicates that something heavy is running in background.

> I have booted this xp before it was working fine but now its not.

So WinXP worked fine before with same QEMU version and suddenly performance issues occurred? If so, I suggest to get a fresh image as current one could be corrupted (e.g. because of incorrect shut down).

**Comment by mjuned47** [comment]
Sorry but this is happening to every 32bit os ,64bit os working fine.
