### ISSUE TITLE
Add mp4box and gpac package

### ISSUE THREAD

**Issue by superbonaci** [termux/termux-packages#6708]
Request to add the package mp4box (GPAC), which is a multimedia processor similar to ffmpeg.
https://github.com/gpac/gpac/wiki/MP4Box

**Comment by Randrianasulu** [comment]
ver. 1.0.1 from github compiles and runs out of the box on termux/android 10 (32-bit arm)

**Comment by superbonaci** [comment]
> ver. 1.0.1 from github compiles and runs out of the box on termux/android 10 (32-bit arm)

Could you please post the full list of commands to get the source code, compile and install?

**Comment by Randrianasulu** [comment]
On Sunday, November 21, 2021, superbonaci ***@***.***> wrote:

> ver. 1.0.1 from github compiles and runs out of the box on termux/android
> 10 (32-bit arm)
>
> Could you please post the full list of commands to get the source code,
> compile and install?
>

I downloaded source code via github releases page

https://codeload.github.com/gpac/gpac/tar.gz/refs/tags/v1.0.1

then unpacked it via
'tar -xf'
then 'cd gpac-1.0.1'
and from there just run make (it calls configure automatically)

after this binaries were in bin/

(sorry, when termux closes due to mem pressure while making space for
browser on 2gb ram tablet  some bash history never made it to file, it
seems)
