### ISSUE TITLE
Replace `libdav1d` by `libaom`

### ISSUE THREAD

**Issue by toorich** [termux/termux-packages#6799]
## Requesting new package

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description

Compare to `libdav1d`, `libaom` can encode AV1 videos.
**Link to home page and sources**

1. Home page:
2. Source code:https://aomedia.googlesource.com/aom/

**Additional information**
If `libaom` can be added, then `libdav1d` can be removed.

**Comment by louie-github** [comment]
AV1 encoding at this point is quite slow, even on PCs, so it wouldn't be worth it, IMO, to try to install `libaom` (the slowest, albeit highest quality AV1 encoder) on Android phones.

`libdav1d` is very useful because it can decode AV1 much faster than `libaom` can. Most people using Termux would probably not want to *encode* AV1, but might need to *decode* AV1 video.

But, that's just my opinion. YMMV.

**Comment by tomty89** [comment]
For the record there's also rav1e, neither that or dav1d is mutually exclusive to aom.

**Comment by leapofazzam123** [comment]
Yeah, librav1e can be used instead. So, we don't need to replace libdav1d with libaom.

**Comment by landfillbaby** [comment]
libaom added, with ffmpeg supporting both libaom and libdav1d. if anyone really wants librav1e open a new issue
