### ISSUE TITLE
Termux opens .docx files without asking the user

### ISSUE THREAD

**Issue by friciwolf** [termux/termux-packages#6927]
**Problem Description**
As the title suggests, the F-Droid version of Termux opens .docx and .xlsx files automatically instead of the built-in Drive Preview app, which makes life with the app very hard. The Google Play version worked fine.

**Expected behavior**
Upon opening a docx file, the system should ask the user which app he/she would like to open the document with.

**Additional information**
OS: Android 10

**Comment by agnostic-apollo** [comment]
Check [here](https://github.com/termux/termux-app/issues/1905#issuecomment-842647559).

**Comment by friciwolf** [comment]
Unfortunately the issue persists even with no defaults defined in the settings section.

The funny thing is, that completely removing Termux and reinstalling it does not produce the usual "pick your application to open this file" prompt as it is usually is with other apps the case.

The device is a Nokia 7 Plus with pure android, btw.

**Comment by agnostic-apollo** [comment]
>The funny thing is, that completely removing Termux and reinstalling it does not produce the usual "pick your application to open this file" prompt as it is usually is with other apps the case.

Then this is likely your rom issue. `Reset app preferences` (not `Clear Defaults` of Termux) might work.

**Comment by friciwolf** [comment]
Well, it could be, however I can't see why my rom treats only termux differently; resetting all app preferences under android 10 does not seem to be available.
In the end, I resolved my issue by installing JuiceSSH, which does what I really partially needed termux for.

**Comment by friciwolf** [comment]
Couldn't it be, that any of these lines trigger the issue? I'm not really at home in android development, but associating Termux with all available file extensions seems to be overkill to me...

https://github.com/termux/termux-app/blob/master/app/src/main/AndroidManifest.xml#L138-L142

**Comment by agnostic-apollo** [comment]
> resetting all app preferences under android 10 does not seem to be available.

It may be in a different place, but should be available. Check `Settings` > `System` > `Reset options` (Do not erase all data!)

https://www.nokia.com/phones/en_pk/support/nokia-7-plus-user-guide/reset-your-phone

>but associating Termux with all available file extensions seems to be overkill to me...

It's not overkill, its the standard way. Check [here](https://github.com/termux/termux-app/pull/2098#issuecomment-851422735). It's needed so that termux is shown in the share menu only for those matching files.

**Comment by friciwolf** [comment]
Found it! Unfortunately after resetting all default application actions, it still defaults to termux... :/

**Comment by friciwolf** [comment]
Whatever the reason behind this, trusting your expertise I'll leave it now as it is, and will use an ssh-client to access my remote devices from now on.
Thank you for all the offered help though! :)

**Comment by agnostic-apollo** [comment]
May its because termux is the only application installed that directly matches the `docx` intent filter, so android directly opens termux. Try installing another app that supports `docx`, like WPS, OpenSuite or [MiXplorer](https://www.apkmirror.com/apk/pishrodevs/mixplorer-hootanparsa/) file manager for which `HTML Viewer` matches the `docx` with `pathPattern`.

**Comment by friciwolf** [comment]
very well then, I'll just go with Google Docs and Sheets -- thank you all the help though, with them, it works as expected!

**Comment by agnostic-apollo** [comment]
Great, you are welcome. Will look into fixing it from termux side if possible in future.
