### ISSUE TITLE
extra-keys-style=none do not remove extra keys bar

### ISSUE THREAD

**Issue by vldmrrr** [termux/termux-packages#7036]
**Problem description**

Added the following line to ~/.termux/termux.properties:
```extra-keys-style=none```
Issued comand termux-reload-settings, closed and reopened termux.
Expected extra keys bar to be hidden, but it was sill shown.

```
$ termux-info
Application version:
0.114
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.4.146 #2 SMP PREEMPT Thu Feb 4 17:08:34 CST 2021 aarch64 Android
Device manufacturer:
Planet
Device model:
Cosmo_Communicator
```

**Comment by agnostic-apollo** [comment]
The [`none` value](https://github.com/termux/termux-app/blob/v0.113/app/src/main/java/com/termux/app/terminal/io/extrakeys/ExtraKeysInfo.java#L234) changes the style of extra keys, like it would show `UP`, `DOWN`, etc instead of arrows. It does not disable the extra keys. To disable extra keys, long hold on the `KEYBOARD` toggle in the left drawer.
