### ISSUE TITLE
How to access the usb storage (OTG) using the Termux?

### ISSUE THREAD

**Issue by iChitti** [termux/termux-packages#7037]
Hello,
I am kind of Novice in this field but. I am really curious about termux and the way it works.
So I am trying to access the usb storage just like we access the internal storage like `cd /storage/emulated/0/...` Or `cd /sdcard/...`.
I've tried some of the fix but didn't worked for me.
And I also tried the following fix:
[https://wiki.termux.com/wiki/Termux-usb](url)

Everything seems to work fine but after executing:
`termux-usb -e ./usbtest /dev/bus/usb/001/002`
It's giving me this error:
```
usbtest.c:12: int main(int, char **): assertion "!libusb_init(NULL)" failed
/data/data/com.termux/files/usr/libexec/termux-callback: line 3: 29227 Aborted                 $TERMUX_CALLBACK "$@"
```

**So any help from the experts is appreciated.**
### Thank you!

**Comment by xeffyr** [comment]
termux-usb is not right thing to access USB storage. Also Termux doesn't provide utilities or any capabilities to have a **write** access to such kind of storage.

You need to be root in order to write files to USB drives.

Overview about supported storage types and their capabilities: https://wiki.termux.com/wiki/Internal_and_external_storage

**Comment by Grimler91** [comment]
See also https://github.com/termux/termux-app/issues/71, https://github.com/termux/termux-app/issues/303, https://github.com/termux/termux-app/issues/1376

**Comment by iChitti** [comment]
Seems like there is No Way to access USB storage currently.
But thanks for yours Respnoses.
Your responses make me feel the questions can be answered.

**Comment by oneindelijk** [comment]
I tried this too. 
Using the explorer on Android, through the details of a file on the USB OTG, I found the path which was something like /mnt/media_rw/<PARTITION_UUID>/
I then granted termux extra permissions in the settings "allow apps to access all storage device internal and external".
That didn't grant termux access to read from this path though.
Perhaps I need to run the 'termux-setup-storage' again with the USB OTG connected and mounted

**Comment by oneindelijk** [comment]
Ooh, that actually worked. Great!
Now I can use a script to transfer the video files from the DJI Avata over the USB OTG to my linux computer.
On Linux, the Avata is seen as a USB device, but there seems to be no way to access the files (because I think I read somewhere that it is an ethernet device)

**Comment by jorexdeveloper** [comment]
> I tried this too. Using the explorer on Android, through the details of a file on the USB OTG, I found the path which was something like /mnt/media_rw/<PARTITION_UUID>/ I then granted termux extra permissions in the settings "allow apps to access all storage device internal and external". That didn't grant termux access to read from this path though. Perhaps I need to run the 'termux-setup-storage' again with the USB OTG connected and mounted

I have tried these steps but no luck

**Comment by AlainKnaff** [comment]
As described on the udroid link above, the trick is to get the storage device mounted under /storage via fuse (in addition to /mnt/media_rw). In this spot, it can be accessed by Termux.

The following command, executed as user shell (via adb shell over USB cable) sets up the device up so that both secondary SD card and USB sticks are mounted under /storage with fuse:

sm set-force-adoptable on

After this, these devices can be accessed from Termux. /storage directory is unreadable, but names are displayed just fine with df.

Setting only applies to devices inserted after command has been issued. Setting is remembered across reboots

Tested with stock Android 14 on a Pixel 7a, and with LineageOS 20 on a Galaxy Tab S3.

**Comment by freebrowser1** [comment]
Same here.

It does require a root shell, as a standard shell is access denied.
```
Nothing 2a:~$ ls -al /mnt/media_rw/*
ls: cannot access '/mnt/media_rw/*': Permission denied
Nothing 2a:~$ sudo bash
.../files/home # ls -al /mnt/media_rw/
total 0
drwxr-x---  3 root     external_storage  60 Jul 15 21:09 .
drwxr-xr-x 16 root     system           340 Jul  9 22:38 ..
drwx------  2 media_rw media_rw          40 Jul  9 22:38 usbotg
.../files/home # ls -al /mnt/media_rw/usbotg/
total 0
drwx------ 2 media_rw media_rw         40 Jul  9 22:38 .
drwxr-x--- 3 root     external_storage 60 Jul 15 21:09 ..
.../files/home #
```
Nothing 2a, Android 14 stock.

**Comment by Adhitech512** [comment]
Guys I run termux-setup-storage event after connecting the drive. But unfortunately I am able to access the folder external-1 but the files and folders on the usb is not seen I think it is creating a seperate storage area inside the drive
