### ISSUE TITLE
Texlive is not installing correctly

### ISSUE THREAD

**Issue by virtual-designer** [termux/termux-packages#7088]
I installed `texinfo-bin` with the command `apt install texinfo-bin` but texinfo programs are not working as expected. I typed `htlatex [filename]` but it said that there was a problem with the tex binary. I've also tried installing `texinfo` but it did not work.

Please fix `texinfo` package.

**Comment by Grimler91** [comment]
> I installed texinfo-bin with the command apt install texinfo-bin but texinfo programs are not working as expected. I typed htlatex [filename] but it said that there was a problem with the tex binary

You need to install texlive through the texlive-installer package, or through texlive-full. Texlive-bin contains quite a lot of symlinks to scripts provided by the rest of texlive

> I've also tried installing texinfo but it did not work.

What does this mean? What does not work, the installation or the package? What did you run and what output did you get? 
Texinfo seem to work for me.

**Comment by virtual-designer** [comment]
I'm sorry for the wrong spelling `texinfo`, it is actually `texlive`.

**Comment by Grimler91** [comment]
> When I run texi2pdf (command from texinfo), I see that it says check your tex installation.

Again, what did you run and what output did you get? Without seeing any of the log messages I can only guess what the issue is.

Most likely it requires some additional texlive packages. I am guessing you have installed texlive and texlive-bin, which gives you a very bare-bone texlive installation (you can compile pdfs but basically all non-essential packages are missing). Installing texlive-full, or using the texlive-installer package to install all of texlive, probably fixes the issue.
