### ISSUE TITLE
Shell autocompletion for Taskwarrior not working

### ISSUE THREAD

**Issue by rc2dev** [termux/termux-packages#7183]
**Problem description**
Shell autocompletion for Taskwarrior doesn't work, on Zsh or Bash.

**Steps to reproduce**
Type `task <TAB>`.

**Expected behavior**
A list of Taskwarrior commands should be printed.

**Additional information**
Completions are available at `$PREFIX/share/doc/task/scripts`.

For zsh, I could fix it by linking `$PREFIX/share/doc/task/scripts/zsh/_task` to `$PREFIX/share/zsh/site-functions`.

Edit: Fix typo.

**Comment by mrshu** [comment]
@rc2dev I took a stab at figuring out how to create a patch for this but ran into some trouble.

Namely
- `$PREFIX` in my case already contains the `usr/` part of the path, so I was able to find the completions at `$PREFIX/share/doc/task/scripts`
- it turns out that the `scripts` folder does have subfolders like `fish/`, `bash/` and `vim/` but a ZSH one was missing

This was on version `2.6.1` of Taskwarrior. Would you mind sharing a bit more info on your setup, so that we can find out where the differences come from?

Thanks!

**Comment by rc2dev** [comment]
Hi @mrshu.

I stopped using Taskwarrior on Termux a while ago, but I just installed it again and indeed the `zsh/` directory is now missing. But [it is still present upstream](https://github.com/GothenburgBitFactory/taskwarrior/tree/develop/scripts).

For the record, when I opened this issue, my Taskwarrior version was 2.5.3 and Termux 0.114.

In regard to $PREFIX, this was a typo on my part. It indeed already includes the `usr/` part (fixed).

**Comment by mrshu** [comment]
Thanks a bunch @rc2dev! 

> I stopped using Taskwarrior on Termux a while ago
Just out of curiosity, what did you end up using instead? (In other words, is there something a bit better that I am missing :slightly_smiling_face: )

I guess I'll end up using Taskwarrior for quite a bit anyway, so your response is very helpful (and I'll probably try to resolve this issue in a bit).

Thanks again!

**Comment by xtkoba** [comment]
Ah now I understand the point. Just the same kind of issue as #10521 and #10534. As of version `2.6.2`, compdef for Zsh seems to be properly installed, but not for Bash or Fish.
