### ISSUE TITLE
After apt update..

### ISSUE THREAD

**Issue by Auxilus** [termux/termux-packages#762]
Please add something which will tell us which packages are newly added to repository when we exec `apt update` .

**Comment by Neo-Oli** [comment]
Would a page on the termux.com website with an RSS feed also work? Because there is an old, open pull request to add that feature at https://github.com/termux/termux.github.io/pull/14 with a preview available [here](https://oliverse.ch/share/termux.com/new-packages.html). Maybe this could work for you? You could set it up with a Feed reader or use IFTTT to have it send you an email when a new package is released

**Comment by Auxilus** [comment]
I am imagining like when I exec the `apt update` in Termux terminal then after exec it will print or simply echo the names of newly added packages (I'm not even expecting the date of release etc...Just names are fine...)
Would that be included...?

**Comment by GreenJoey** [comment]
apt, Termux's package manager already does it. After `apt update` if any upgrade is it would show you how many packages can be upgraded and `apt list --upgradable` to show you which packages can be upgraded

**Comment by Auxilus** [comment]
No not like this..
I said I wanna get "which packages are newly ADDED TO THE REPO" not the upgradables.

**Comment by tuyunlei** [comment]
you can use vim to know what's new added.
In vim typed: `:r!apt list`,and saved it as 'old'
After a short of time, you can do it as 'new'.Then use `diff old new`to get the diffrence with two files.

**Comment by BKubi** [comment]
@Auxilus Your point is great since knowing newly added packages will help you know which packages you might need
