### ISSUE TITLE
Package request : libusb-1.0.0

### ISSUE THREAD

**Issue by bajabaq** [termux/termux-packages#763]
Depends on libudev1
Created disabled package/ basic build.sh 

Great Work

**Comment by vaites** [comment]
I compiled and tested it with a package I wanted (OpenSC) but needs root permissions to access USB...

**Comment by tadfisher** [comment]
It looks like upstream is working on Android support: https://github.com/libusb/libusb/pull/242

What would the best course of action for Termux integration be? I imagine that augmenting `termux-api` to request permissions for USB devices would be a necessary step, but actually providing API support is a bit more involved, because important features like device scanning, hotplug detection, and enumeration are only available through the Java APIs on non-rooted devices.

At this point, a full-blown fork might be necessary to support libusb in a sane way. I imagine a stub library that passes through to `termux-api` calls for actual implementation would work, or an additional Termux:USB app and API could keep this complexity out of the core.

**Comment by posix4e** [comment]
I think it would be huge if we could support password managers like trezo. termux api on top of it could  be nice but I think double checking that existing android apps can use it is really enough for me to consider this done/done. I'd probably breakout termux-api

**Comment by Grimler91** [comment]
Libusb is now available from [termux' root repo](https://github.com/termux/termux-root-packages).
libusb/libusb#242 looks interesting, we should definitely keep an eye on that and related threads.
