### ISSUE TITLE
Some LLVM tools are missing

### ISSUE THREAD

**Issue by HertzDevil** [termux/termux-packages#7952]
The binaries in [`packages/libllvm/llvm.subpackage.sh`](https://github.com/termux/termux-packages/blob/master/packages/libllvm/llvm.subpackage.sh) do not match the full list of tools on the [official documentation](https://llvm.org/docs/CommandGuide/index.html). In particular there is no `FileCheck`.

**Comment by buttaface** [comment]
I think that is for testing LLVM itself and has never been included by us. It is listed under "Developer Tools" in your second link, only one of which we include.

Looking into it now, we probably build it every time we update the libllvm package, but since [LLVM doesn't install it by default](https://github.com/llvm/llvm-project/blob/c71fbdd87b356c6d43dbc26a4d7113d9cbb93fe7/llvm/CMakeLists.txt#L216), we don't include it either.

**Comment by buttaface** [comment]
@Wetitpig has put together an `llvm-tools` package for this: you can download [the latest LLVM 14 packages in a zip file from the latest CI run](https://github.com/termux/termux-packages/actions/runs/2102144858), remove your existing LLVM 13 packages with `apt remove libllvm`, and install these with `dpkg -i *14.0.0_aarch64.deb`. Test them out and let us know of any problems on #9714.

**Comment by xtkoba** [comment]
Closing as fixed. Thanks.
