### ISSUE TITLE
[Package]: Python3.9.7 aarch64 deb file

### ISSUE THREAD

**Issue by Abu0Ali** [termux/termux-packages#8012]
### Package description

Hi, sorry if this is not the right place to post my issue, I have searched alot on multiple resources on how to install python 3.9.7 in termux but I couldn't find anything only old version of python and others steps but it required to root my phone 

Could someone help me to find python3.9.7 package using Termux or simply a deb file for python3.9.7 aarch64.

When I tried to install python using $pkg install python it installed python 3.10

Or is there other sources similar to Termux-pod which include python 3.9.7 

Thanks and sorry again if this not the right place 

### Source code URL

https://github.com/Termux-pod/termux-pod

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
We don't provide older versions. Even if you would manage to find an old deb with python3.9 it would most likely not work due to dependencies being updated since that python version was compiled. 

To get python3.9 you would have to compile it yourself, either on device or by cross-compiling from ubuntu or termux's docker image, see the wiki on how to do that:

https://github.com/termux/termux-packages/wiki/Build-environment
https://github.com/termux/termux-packages/wiki/Building-packages
