### ISSUE TITLE
[Package]: Main

### ISSUE THREAD

**Issue by yogesh-hacker** [termux/termux-packages#8228]
### Package description

Please make termux again easy and useful because it's not easy like old one. I can't able to install package and update the package. So please make the old one unless you will loose many users please fix those technical issues instead of changing the repository if no so make a by default repository so we don't need to change it. That's it 

### Home page URL

https://yogesh-hacker.github.io/hackerindia.in

### Source code URL

https://yogesh-hacker.github.io/hackerindia.in

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment]
Does not make sense at all.

**Comment by sk0kanik** [comment]
@yogesh-hacker see https://github.com/termux/termux-packages/issues/6726 and https://wiki.termux.com/wiki/Hacking#Why_Termux_discourages_hacking

**Comment by Grimler91** [comment]
> easy and useful 

> easy like old one

No idea what this means.

> those technical issues

Which technical issues?

> I can't able to install package and update the package

Why not? What device do you have and what error(s) do you get. See requested information in [bug report template](https://github.com/termux/termux-packages/issues/new?assignees=&labels=bug+report&template=01-bug-report.yml&title=%5BBug%5D%3A+).

Maybe you are using an old version of termux, or maybe you just have outdated packages. Hard to tell without any information.

**Comment by yogesh-hacker** [comment]
Repository issue

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/issues/6726 tells why it is not possible to fix that. We don't own Bintray. It is a third party service and if it goes down, we can't do anything with that.

Another story is with Google Play. We no longer can submit updates here due to issues with new SDK. https://github.com/termux/termux-packages/wiki/Termux-and-Android-10

Switch to F-Droid build, hopefully this is not so hard as running `termux-change-repo`.
