### ISSUE TITLE
[Bug]: aapt package does not compile for i686 format

### ISSUE THREAD

**Issue by Maxython** [termux/termux-packages#8385]
### Problem description

[i686 compilation github action link](https://github.com/Maxython/termux-packages-pacman/runs/4653418043?check_suite_focus=true)

### What steps will reproduce the bug?

empty commit

### What is the expected behavior?

successful compilation

### System information

github action

**Comment by xtkoba** [comment]
https://github.com/termux/termux-packages/blob/e410863adc3073203d7c328eef13dd61f271f512/packages/aapt/build.sh#L105

Apparently my commit https://github.com/termux/termux-packages/commit/653a110ddba96a1b6b8e8421d53e25169cc2302c interacts badly with https://github.com/termux/termux-packages/commit/e410863adc3073203d7c328eef13dd61f271f512. But I still believe that `-fPIC` should be in `CFLAGS` (and `CXXFLAGS`) and not in `CPPFLAGS`, because it is for code generation and not for preprocessor.

The fix is trivial though.
