### ISSUE TITLE
[Bug]: gcc file compiled drop msg "is not executable by this user"

### ISSUE THREAD

**Issue by ivam3** [termux/termux-packages#8446]
### Problem description

I written a little program in C language with VIM text editor and then compiled it with gcc from nodejs package, I bought permission but when I tried to run it a message "The file './namefile' is not executable by this user" dropped. I was trying with flags "-g" for making object file but it's the same. Btw, a few hours before I know this everything worked fine.

In fact: the file compiled into the same OS and arch cannot be running on it 

### What steps will reproduce the bug?

![Screenshot_20220104-011251_Termux](https://user-images.githubusercontent.com/27752315/148024299-fc6bd112-57bd-44c0-8b53-acd427d0b7c5.jpg)

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.4.177-22602103 #1 SMP PREEMPT Fri Oct 15 00:57:06 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A305G
```

**Comment by AspiringITSecSpec323** [comment]
Did I mess everything upz I'm sorry if I did I'm still learning this whole thing On Jan 3, 2022 11:33 PM, Ivam3 ***@***.***> wrote:
Problem description
I written a little program in C language with VIM text editor and then compiled it with gcc from nodejs package, I bought permission but when I tried to run it a message "The file './namefile' is not executable by this user" dropped. I was trying with flags "-g" for making object file but it's the same. Btw, a few hours before I know this everything worked fine
What steps will reproduce the bug?

What is the expected behavior?
No response
System information
termux-info:
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.4.177-22602103 #1 SMP PREEMPT Fri Oct 15 00:57:06 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A305G

**Comment by Grimler91** [comment]
> gcc from nodejs package

? what is your output of `gcc --version`?

**Comment by Grimler91** [comment]
Does it work if you switch to a bash shell?

**Comment by AspiringITSecSpec323** [comment]
ElaborateOn Jan 4, 2022 12:34 AM, Henrik Grimler ***@***.***> wrote:

gcc from nodejs package

? what is your output of gcc --version?

**Comment by ivam3** [comment]
![Screenshot_20220104-031224_Termux](https://user-images.githubusercontent.com/27752315/148036016-d897f4f4-d685-4ab1-90f1-90f99ce85667.jpg)

**Comment by Grimler91** [comment]
The permissions are weird, why is the group owner `everybody`, and why does clang create a program with rwxrwx rather than just rwx..

Where is this directory, is it in termux's home directory or have you symlinked it to some other place (what does `realpath ~/Desktop/practice/rev_engineering` say)? 
Is u0_a331 your termux user (what does `whoami` say)?

**Comment by ivam3** [comment]
I found the solution ... when i compiled in external sdcard the issue is present, i think it was provoke for permissions to use file in it, I moved it to HOME directory and repeater the process again and the issue disappeared.

![Screenshot_20220104-032147_Termux](https://user-images.githubusercontent.com/27752315/148038818-caed6905-2716-437e-ba18-f0695d48f995.jpg)

**Comment by ivam3** [comment]
@Grimler91 it's not root(my device isn't rooted) required to create files or directories or execute those if are storage in external sdcard and it's the 1st time I had issues with it ... so thank you very very much to support me
