### ISSUE TITLE
minor build issues in docker image

### ISSUE THREAD

**Issue by its-pointless** [termux/termux-packages#847]
You can't ./build-all.sh and have it not exceed space limit on the default base size in docker which is 10g. Probably needs a bit of a warning on that.
building aria2 arm arch tries to link with libluspc++ . Editing configure.ac is neccesary 
pulseaudio runs asking for symbol glob ... requires linking libandroid-glob to work.
libandroid-support package seems to pull in libgnustl_shared ... odd

**Comment by vishalbiswas** [comment]
any package built on a fresh /data will include libgnustl_shared

**Comment by fornwall** [comment]
- About docker size: Seems to be an issue with devicemapper (which debian uses by default?) but not aufs as storage driver (which ubuntu 16.10 uses by default?). http://www.projectatomic.io/blog/2016/03/daemon_option_basedevicesize/ seems to indicate that ones needs to restart the docker daemon with e.g. `--storage-opt dm.basesize=50G`, remove the docker image if created and start again. It would be better if possible to specify it when creating the image.

- aria2 arm build failure due to libsupc++.so: The documentation on Android standalone toolchain (https://developer.android.com/ndk/guides/standalone_toolchain.html) says `To use these features in conjunction with GNU libstdc++, you must explicitly link with libsupc++. To do so, use -lsupc++ when linking binaries. [...] You do not need to do this when using the STLport or libc++ library.` As Termux still uses gnustl while awaiting libc++ to stabilize (hopefully in the next NDK release) using -lsupc++ should be necessary, so not sure why failling?

- pulseaudio&glob: Do we know what pulseaudio uses glob for, should it be enabled by using libandroid-glob?

- libandroid-support&libgnustl_shared: Only c++ code should link to libgnustl_shared by default, and libandroid-support.so doesn't use c++ so doesn't link against it. But libgnustl_shared is setup under /data by build-package.sh as part of setting up the general toolchain (as it in general doesn't know if a requested package uses C++ or not).
