### ISSUE TITLE
downloading packages

### ISSUE THREAD

**Issue by KRWCLASSIC** [termux/termux-packages#8477]
when I try to download any package I get an error

error:

$ pkg install x11-repo
Testing the available mirrors:
[*] https://dl.bintray.com/termux/termux-packages-24: bad
[*] https://grimler.se/termux-packages-24: ok
[*] https://main.termux-mirror.ml: ok
[*] https://termux.mentality.rip/termux-packages-24: ok
Picking mirror: https://termux.mentality.rip/termux-packages-24
Get:1 https://termux.mentality.rip/termux-packages-24 stable InRelease [14.0 kB]
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Get:4 https://termux.mentality.rip/termux-packages-24 stable/main aarch64 Packages [335 kB]
Err:5 https://dl.bintray.com/grimler/game-packages-24 games Release
  502  Bad Gateway
Err:6 https://dl.bintray.com/grimler/science-packages-24 science Release
  502  Bad Gateway
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

how to fix it?

**Comment by sk0kanik** [comment]
#6726

**Comment by altamash9161** [comment]
How to fix it ,pls reply

**Comment by ssaagamemer** [comment]
Do not use Termux app from Google Play. It is deprecated.
Use Termux application from F-Droid, here is the link: https://f-droid.org/en/packages/com.termux/. Google Play variant is deprecated, doesn't receive updates and contains issues as well as outdated repository URLs.

Before migrating to F-Droid Termux version, uninstall the application and all add-ons like Termux:API, Termux:Styling, Termux:Widget and others. This is a required step because of signature mismatch between F-Droid and Google Play variants. If you need to back up data before uninstalling app, you can use suggestions from https://wiki.termux.com/wiki/Backing_up_Termux

just read #6726
