### ISSUE TITLE
Update failed : Writing more data then expected

### ISSUE THREAD

**Issue by StephaneJuban** [termux/termux-packages#863]
Hi,

I'm following [this tutorial](https://medium.freecodecamp.com/building-a-node-js-application-on-android-part-1-termux-vim-and-node-js-dfa90c28958f#.u3ggcxb13) to install Termux on my tablet MQ Aquaris M10.
When I do the first command : `apt update && apt upgrade` it fail.

> Failed to fetch http://termux.net/dists/stable/main/binary-aarch64/Packages   Writing more data than expected (230113 > 229435) [IP: xxxxx]

I tried with option `Acquire::http::No-Cache=True` with the same result.

`wget http://termux.net/dists/stable/main/binary-aarch64/Packages` works fine

Thanks

**Comment by StephaneJuban** [comment]
Just found a [similar issue here](https://plus.google.com/105320182048381120888/posts/g65gS69p27j)...

**Comment by fornwall** [comment]
@StephaneJuban Are you still having this issue if you rerun `apt update && apt upgrade` now?

**Comment by StephaneJuban** [comment]
it's working now. Unbelievable, it was not 20min ago. Did you do something ?

**Comment by fornwall** [comment]
I explicitly evicted the relevant files from the cloudflare cache.

The Termux repository uses cloudflare as a content distribution network, to distribute load and have nice access times across the world.

Each time Release and Packages files are changed (due to adding or updating packages) they are evicted from the cloudflare cache by the deployment script. Unfortunately, it seems that sometimes some part of the cloudflare distribution network still caches the files (so that some parts of the world gets stale files), and needs additional calls to the cache eviction API.

I'll look at improving this for the future, perhaps by adding multiple calls to the cache eviction API with some delay between them to better ensure cache consistency across all networks.

**Comment by StephaneJuban** [comment]
Ok I get it. Thanks for the explanations and for the help !
