### ISSUE TITLE
aptitude (package request)

### ISSUE THREAD

**Issue by mklein994** [termux/termux-packages#865]
From the website:
>aptitude is a featureful package manager for Debian GNU/Linux systems, based on the renowned apt package management infrastructure. aptitude provides the functionality of dselect and apt-get, as well as many additional features not found in either program.

http://aptitude.alioth.debian.org/doc/en/

**Comment by vishalbiswas** [comment]
last release was more than 2 years ago.

**Comment by mklein994** [comment]
Thanks; I didn't think to check. It was good while it lasted.

**Comment by mklein994** [comment]
Actually I take that back. 0.8.6 was released 2 weeks ago: git://anonscm.debian.org/aptitude/aptitude.git see commit 4137f1a5

**Comment by vishalbiswas** [comment]
Sorry, the wikipedia page is outdated!

**Comment by Rudloff** [comment]
Building aptitude requires libapt-pkg-dev which is not available in Termux.

**Comment by pschwede** [comment]
I second the request for aptitude.

**Comment by Protagores** [comment]
Any progress on this?

I tend to have a number of heavy outdated packages installed in my environment which only stay there because they’re marked as manually installed, and I can’t afford starting from scratch every time I need an up-to-date environment. Aptitude makes it handy to control which packages should be considered automatic dependencies eligible for autoremove once they’re no longer needed, allowing me to keep my Debian testing/unstable system lean and non-conflicting most of the time. I’d pretty much appreciate something like this for Termux too.

**Comment by KevinBlue18** [comment]
I wish there is an update for this because I love this on Ubuntu.

**Comment by SamB** [comment]
Yeah, aptitude was the first thing I reached for when I wanted to browse through the available packages ...

**Comment by rpil2** [comment]
i would still like to use aptitude

**Comment by xeffyr** [comment]
@rpil2 We are going to [change](https://github.com/termux/termux-app/pull/1427) packaging format. No further work for apt package manager and its add-ons will be done.

**Comment by rpil2** [comment]
@xeffyr i didnt understand your link, but i found []https://github.com/termux/termux-app/issues/1072)(https://github.com/termux/termux-app/issues/1072), which i think says

-  google is forcing termux is going to be radically redesigned
- after the redesign, we will now longer be able to install things via apt
- or even start programs ?

this seems like it will annoy, alienate and/or confuse a lot of users.

I appreciate this is not your 'fault' but i suggest you start telling users now - ie on the website, wiki, release notes, etc etc now, as seems like it is going to make termux unusable for some.

**Comment by mklein994** [comment]
Is there a wiki entry or something that can describe this change in detail, how it will affect end users?

**Comment by Grimler91** [comment]
@mklein994 we only have this short entry in the gh wiki: https://github.com/termux/termux-packages/wiki/Termux-and-Android-10. https://github.com/termux/termux-app/issues/1072 contains more details (and quite a lot of rants), apart from that all discussion on how to proceed has happened on gitter: https://gitter.im/termux/dev (search for android 10). And, of course, the current proposed solution is shown in the PR @xeffyr linked.

**Comment by mralusw** [comment]
I haven't quite followed all the interesting links, but at this point, apt works (notwithstanding @xeffyr comment about "no further work"), aptitude doesn't, and there is no decent console front end for apt on Termux.

For example, it's quite annoying to upgrade only a few of the upgradeable packages, since apt (and pkg, I assume) "helpfully" marks the targets of `apt install` as manually installed

**Comment by xtkoba** [comment]
Let's leave this open unless it is disallowed by the packaging policy.

**Comment by xloem** [comment]
It's not hard to make termux packages if anyone wants to start. We could maybe add work to it over the years until it happens. You can copy the build.sh file from another package in the termux-packages tree.

**Comment by bidyut1153** [comment]
Can you add aptitude?
