### ISSUE TITLE
[Package]: add systemd for termux 

### ISSUE THREAD

**Issue by ExtinctDrift19** [termux/termux-packages#8782]
### Package description

Systemd full information link https://systemd.io

### Home page URL

https://systemd.io/

### Source code URL

https://github.com/systemd/systemd

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment]
Not possible with all or most android kernels, see https://github.com/systemd/systemd/blob/main/README.

Termux-services and runit will have to do: https://wiki.termux.com/wiki/Termux-services

**Comment by SDRausty** [comment]
This information may be very usefull in this thread.  Please correct me if it is not.

[TermuxArch](https://github.com/TermuxArch/TermuxArch) is using [docker-systemctl-replacement](https://github.com/gdraheim/docker-systemctl-replacement/) for many years now successfully in Termux PRoot.  It is an elective modification.  

Not everbody wants to replace systemd, nor do they need to, but some users do want a replacement.  

There have not been any complants regarding [`systemctl3.py`](https://github.com/gdraheim/docker-systemctl-replacement/blob/master/files/docker/systemctl3.py) since it was adopted.  There were requests before it was considered to be an important part of Termux development.  

Is this a potential resolution for [Package]: add systemd for termux?

**Comment by ExtinctDrift19** [comment]
yes
