### ISSUE TITLE
[Package]: tinygo

### ISSUE THREAD

**Issue by j0hnd3v** [termux/termux-packages#8819]
### Package description

Go compiler for small places. Microcontrollers, WebAssembly (WASM/WASI), and command-line tools. Based on LLVM.                                                   

### Home page URL

https://tinygo.org/

### Source code URL

https://github.com/tinygo-org/tinygo

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by wasmasmr** [comment]
I would also be interested in this. As mentioned [here](https://github.com/tinygo-org/tinygo/blob/release/BUILDING.md) there are dynamically and statically linked build options available. The dynamically linked build currently links against LLVM 13 so either we would need to request it to be packaged for termux or provide a LLVM 14 patch for the tinygo package (the official sources don't support LLVM 14 yet for the dynamically linked build) which is the termux LLVM version.

The static build method should already support LLVM 14 so that would probably be the easiest approach at this time. I tried to build tinygo on my phone with this method but the build process is so heavy that my phone kept freezing up. The build system could handle it but maybe the dynamic method would be preferred after all because of the lower resource usage.

If someone has successfully built tinygo on termux I would be interested in hearing how they managed to pull it off.

**Comment by sohaha** [comment]
Is there no progress yet?

**Comment by truboxl** [comment]
I will give a try now that https://github.com/tinygo-org/tinygo/pull/3064 is merged
