### ISSUE TITLE
Should packages be served on HTTPS instead of HTTP?

### ISSUE THREAD

**Issue by franciscod** [termux/termux-packages#89]
Currently, accessing https://apt.termux.com gives a certificate error and also doesn't correctly serve the packages as in http://apt.termux.com.

Additionally:
- the `bootstrap-$ARCH.zip` package including the base filesystem and essential binaries is downloaded via HTTP on `termux-app` [(see here)](https://github.com/termux/termux-app/blob/bce65f7db140c4ee6de01680743bca31a9d6a081/app/src/main/java/com/termux/app/TermuxInstaller.java#L187)
- the `apt` package has its repo set to HTTP [(see here)](https://github.com/termux/termux-packages/blob/4a70323e838cb373eb75f8efd0ce09e71831e4f1/packages/apt/build.sh#L51)

What do you guys think? HTTPS is a good idea for me, but maybe there's additional security that I'm not aware of.

**Comment by fornwall** [comment]
Yes, especially the bootstrap zip should be served over https (later on apt-installed packages have their gpg signatures checked which prevents tampering). Leaving this open to fix soon.

**Comment by franciscod** [comment]
Happy to hear that :)

**Comment by fornwall** [comment]
In version 0.23 of the Termux app (being released later today or tomorrow) there has been a switch to https for the bootstrap package.

Apt-fetched packages are still using http, to avoid depending on the additional `apt-transport-https` package and enable caching proxies. This may be changed in the future, but I think we are secure for now since the initial (now securely fetched) bootstrap zip contains a GPG key which apt uses to validate the integrity of fetched packages before installing.

**Comment by franciscod** [comment]
Great news!
