### ISSUE TITLE
[Bug]: github action: valgrind package not compiling

### ISSUE THREAD

**Issue by Maxython** [termux/termux-packages#8910]
### Problem description

https://github.com/Maxython/termux-packages-pacman/actions/runs/1788948661

### What steps will reproduce the bug?

[after this commit](https://github.com/termux/termux-packages/commit/c08631bf7188335eade966bc3ebdbe1ee3fd8faa#diff-411c87c4c43bee70e5324d7e00cc325e5c721b4b274790e730b823c294af272e)

### What is the expected behavior?

successful compilation

### System information

it is github action

**Comment by Grimler91** [comment]
Partial fix in https://github.com/termux/termux-packages/pull/8429

**Comment by xtkoba** [comment]
The build failure for x86_64 target in PR #8429 is due to `$($CC -m32 -print-libgcc-file-name)` different from `$($CC -m64 -print-libgcc-file-name)` (or just without `-m64`).

A possible workaround would be to configure with `--enable-only64bit` (as is currently specified for aarch64 target), though I doubt it is useful in practice, as it may be common to run 32-bit binaries on x86_64.

A proper fix would be to modify Makefiles to specify the correct compiler-rt builtin library for each of 32-bit and 64-bit builds.
