### ISSUE TITLE
termux-chroot breaks git on 32-bit arm

### ISSUE THREAD

**Issue by iexos** [termux/termux-packages#898]
Hi,

after executing termux-chroot, I cannot modify my git repositories anymore located in the home directory.

output of `git add FILE`:

```
error: unable to create temporary file: Bad file number
error: FILE: failed to insert into database
error: unable to index file FILE
fatal: updating files failed
```

I am using zsh. Sometimes adding the files works, but not commiting.

**Comment by fornwall** [comment]
@iexos Thanks for reporting! What is the output of running `uname -a`?

@michalbednarski Are you interested at investigating this one? Short testing indicates that the above problem breaks on 32-bit arm and not 64-bit arm.

**Comment by iexos** [comment]
`uname -a`:

` Linux localhost 3.4.67-cyanogenmod-gedbec95 #1 SMP PREEMPT Sun Oct 11 04:59:50 PDT 2015 armv7l Android `

And it is true, it does not happen on my aarch64 device, which also uses a much newer ROM.

**Comment by michalbednarski** [comment]
Yep, working on it

It appears that `openat(AT_FDCWD, "non_existent_directory/some_file", ...)` fails with `-EBADF` instead of `-ENOENT` under PRoot

(Could reproduce this on Nexus 7 with stock ROM, however this bug doesn't occur on emulator; both have Linux from 3.4 line)

PRoot upon failed path translation sets `r0` to `-ENOENT` and does `ptrace(PTRACE_SET_SYSCALL, ..., SYS_tuxcall)` in order to skip syscall and then continues process; however actual syscall overwrites `r0` with another status code. This will be fixed by catching syscall exit as well and setting status after syscall has finished, but I have yet to find under which circumstances this has to be done.

Right now following workaround can be used (however, it will degrade performance of PRoot):
```
PROOT_NO_SECCOMP=1 termux-chroot
```

**Comment by fornwall** [comment]
The proot package has been updated to version `5.1.104` with the fix by @michalbednarski.

Update to it with `packages up` and thanks for reporting!

**Comment by iexos** [comment]
Works like a charm, thank you! :)
