### ISSUE TITLE
OpenSSH uses hardlinks for ControlMaster

### ISSUE THREAD

**Issue by gnoack** [termux/termux-packages#91]
Hi,

I'm trying to use the OpenSSH client with ControlMaster (cached connections), but it can't bring that up because `ssh` tries to use hard links, which are disallowed on Android M:

    muxserver_listen: link mux listener /data/data/com.termux/files/home/path/to/pipe.DKLFLDJ
        => /data/data/com.termux/files/home/path/to/pipe: Permission denied

 * Code where the error is happening: https://github.com/openssh/openssh-portable/blob/master/mux.c#L1300
 * Android issue: https://code.google.com/p/android-developer-preview/issues/detail?id=3150

Is this feasible to fix?  (I would have reported to a different project, but couldn't figure out where your patches are coming from; I'm assuming you've patched OpenSSH yourself to run on Android?)

The ControlMaster feature is interesting on Android in particular because you can let the channel time out if your port forwards seem unused and you can save some battery.

Thanks for your project, I really enjoy having this on my phone!  Installing all this Unix software in different ways seems like a pain. :)

—Günther

**Comment by fornwall** [comment]
> Is this feasible to fix? (I would have reported to a different project, but couldn't figure out where your patches are coming from; I'm assuming you've patched OpenSSH yourself to run on Android?)

Yes, this should hopefully be fixable! [The patches](https://github.com/termux/termux-packages/tree/master/packages/openssh) are as you say local to the project, and a fix should probably be committed and used in Termux first before being submitted to the upstream project (if it's clean and general enough for inclusion upstream, that is).

> Code where the error is happening: https://github.com/openssh/openssh-portable/blob/master/mux.c#L1300

An initial patch could perhaps be to use `stat-then-rename`? It would loose the atomic guarantee of `link-then-unlink` since another process may have created a file between `stat` and `rename` which will be overwritten, but perhaps it's good enough for getting initial functionality up in the Termux package?

The `renameat2` with `RENAME_NOREPLACE` would probably work with atomicity preserved, but I don't think Android supports that.

**Comment by fornwall** [comment]
I've patched mux.c to use `stat-then-rename` for now, so that ControlMaster works! You can update to the new `7.1-1` version of the openssh package with

    apt update && apt upgrade

Let me know if there is any problem!

**Comment by gnoack** [comment]
Awesome, thanks a lot for fixing!

**Comment by gnoack** [comment]
Confirmed in daily use over the last few days; works like a charm. :)
