### ISSUE TITLE
[Bug]: MPV fails with linking error

### ISSUE THREAD

**Issue by mhmdanas** [termux/termux-packages#9174]
### Problem description

Running MPV in any way fails with the following error:

```
CANNOT LINK EXECUTABLE "mpv": cannot locate symbol "EVP_MD_CTX_init" referenced by "/system/lib64/libsqlite.so"...
```

This issue started today or yesterday. Unfortunately, I don't remember more than that. All packages are up to date.

This has been reported before (https://github.com/termux/termux-packages/issues/9169), but I was unable to make a comment there since the issue was locked. That's why I created a new issue instead.

### What steps will reproduce the bug?

Running MPV in any way, e.g. `mpv --help`.

### What is the expected behavior?

That MPV works.

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.113-23309353 #1 SMP PREEMPT Fri Dec 17 20:27:37 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A515F
```

**Comment by Grimler91** [comment]
Works fine for me, also on aarch64, android 11, so only seems to happen on some devices.

Probably similar to https://github.com/termux/termux-packages/issues/7188

**Comment by mhmdanas** [comment]
Hmm, that's odd. If any extra information is needed I'll provide it to the best of my ability.

**Comment by thunder-coding** [comment]
```
~ $ LD_LIBRARY_PATH=/system/lib64/ mpv
CANNOT LINK EXECUTABLE "mpv": cannot locate symbol "EVP_ripemd160" referenced by "/data/data/com.termux/files/usr/lib/libarchive.so"...
```
Seems like LD_LIBRARY_PATH is the culprit

**Comment by xtkoba** [comment]
In the author's environment `/system/lib64/libsqlite.so` seems to depend on `/system/lib64/libcrypto.so`, which is not the case for me.

Also I do not understand why `libsqlite.so` appears here, as the `mpv` package does not depend on `libsqlite`, either directly or indirectly.

A possible workaround might be to install the `libsqlite` package, and if necessary add `$PREFIX/lib` to `LD_LIBRARY_PATH`, so that `/system/lib64/libsqlite.so` is masked and never loaded.

**Comment by xtkoba** [comment]
`mpv` references the following 4 symbols from `libandroid.so`:

* `ANativeWindow_fromSurface`
* `ANativeWindow_getHeight`
* `ANativeWindow_getWidth`
* `ANativeWindow_release`

Are these necessary?

**Comment by xtkoba** [comment]
Getting rid of dependency on `libandroid.so` does not fix the issue. `mpv` also depends on `libOpenSLES.so` that depends on `libwilhelm.so` that depends on `libandroid_runtime.so` that depends on `libsqlite.so`.

**Comment by xtkoba** [comment]
Just an idea of workaround. Copy `/system/lib64/libcrypto.so` to `$PREFIX/lib/` and rename it to, say `libsystem_crypto.so`. Copy `/system/lib64/libsqlite.so` to `$PREFIX/lib/` without renaming it, then edit the `DT_NEEDED` entry using `patchelf` (substitute `libsystem_crypto.so` for `libcrypto.so`). Add `$PREFIX/lib` to `LD_LIBRARY_PATH`.

Not sure if this actually works.

**Comment by thunder-coding** [comment]
An another workaround would be to add SONAME to libcrypto.so and libssl.so, so that the linker always picks up the correct shared libraries for the target executable. i.e. libcrypto.so.3 instead of just libcrypto.so

Anyways this seems to be either a bug in the dynamic linker on some devices or the shared object libraries shipped by the OS containing RUNPATH (My device doesn't have RUNPATH set for any of the libraries in /system/lib64)

**Comment by thunder-coding** [comment]
@mhmdanas, can you help us in testing whether the workaround which we have proposed works?

Here are the steps:-

1. Download artifacts from https://github.com/thunder-coding/termux-packages/actions/runs/1914063032 for your architecture

2. Extract the zip file.

```
unzip ~/storage/path/to/artifact
tar --extract -f debs-<arch>-xxxxxxx.tar
```

You will get a debs folder in your current directory

3. Install the debs

```
cd debs
apt install ./*.deb
```

4. Try running MPV now, it should work. If it doesn't share what error it ends up with

**MAKE SURE YOU TAKE A BACKUP OF YOUR ENVIRONMENT FIRST**

**Comment by mhmdanas** [comment]
@thunder-coding seems to work, thanks all! Now I can finally listen to my music again. :)

**Comment by thunder-coding** [comment]
> @thunder-coding seems to work, thanks all! Now I can finally listen to my music again. :)

Thanks for testing out. Now, since you have installed debs from a unstable source, your other packages depending on OpenSSL are likely broken. You need to reset your prefix, in order to resolve this problem. (That's why I recommend having a backup).

Packages depending on OpenSSL need to be rebuilt after the workaround is merged. Let me see if I can get this done today itself. (Don't worry, this time I won't break curl. But other packages will be broken for a few hours)

**Comment by mhmdanas** [comment]
> Now, since you have installed debs from a unstable source, your other packages depending on OpenSSL are likely broken. You need to reset your prefix, in order to resolve this problem. (That's why I recommend having a backup). But mpv will break after that.

That doesn't really matter to me, since I mostly use Termux for MPV. However, thanks for the note anyway.

**Comment by thunder-coding** [comment]
> That doesn't really matter to me, since I mostly use Termux for MPV. However, thanks for the note anyway.

You might need to do this when updating your packages incase you are having broken curl.
