### ISSUE TITLE
Library issue libncurses.so on AARCH64 architecture.

### ISSUE THREAD

**Issue by bharat226g** [termux/termux-packages#94]
I have a phone with 64bit arm processor (AARCH64 architecture) on android 5.0.2 lollipop. Whenever i use command line apps like `nano`, `vim` that depend on libncurses , i get error like   
for eg: with nano,   

`CANNOT LINK EXECUTABLE: could not load library "libncurses.so" needed by "nano"; caused by "libncurses.so" is 32-bit instead of 64-bit.`   

Please use aarch64 compatible libraries as well.
![termux-libncurses](https://cloud.githubusercontent.com/assets/13498578/11810875/adffeda0-a357-11e5-98ea-422da269ac09.png)

termux version: 0.22

**Comment by fornwall** [comment]
Are you running CyanogenMod or another version that bundles nano and vim themselves? Because it looks like you are running system versions (verify by running `which vim`), which clash with the libraries that Termux has setup.

You can read about it at: https://github.com/termux/termux-packages/wiki/Common-problems.

Unfortunately providing 64-bit packages (which is coming :+1: !) won't help much here, since we still have a version difference between the shared libraries that the system binaries needs and the shared libraries that Termux provides.

So the alternatives are:

1. Install the Termux versions of the programs (e.g. ´apt install nano`).
2. Reset `LD_LIBRARY_PATH` before running system binaries as explained in the linked resource above.
