### ISSUE TITLE
[Package]: FlatPak

### ISSUE THREAD

**Issue by T-Dynamos** [termux/termux-packages#9573]
### Package description

Linux application sandboxing and distribution framework

### Home page URL

https://github.com/flatpak/flatpak

### Source code URL

https://github.com/flatpak/flatpak/releases/download/1.13.2/flatpak-1.13.2.tar.xz

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

I tried compiling it but got error of gpgme-pthread 
```
checking for gpgme-pthread >= 1.1.8... no
configure: error: Need GPGME_PTHREAD version 1.1.8 or later
    ~/flatpak-1.13.2                         ✘ 1   52s
```

**Comment by wmcbtech30** [comment]
Duplicate #1278

Any specific reason why we need flatpak? we don't have plans to re-package termux packages into flatpak package format and you cannot run apps from flathub in termux because of incompatibilty

Another reason is sandboxing. it will set access control, write files on system location and device access (e.g. controllers) which eventually needs root

**Comment by T-Dynamos** [comment]
For telegram

**Comment by wmcbtech30** [comment]
Again even if they're confined. you cannot run apps from flathub that were made specifically for standard linux distributions

> you cannot run apps from flathub in termux because of incompatibilty even if they're confined
