### ISSUE TITLE
Cannot run root on termux...

### ISSUE THREAD

**Issue by NickVendetta** [termux/termux-packages#978]
When i run su its ok but when i type name of file example python2 setup.py its says not found....

**Comment by NickVendetta** [comment]
Welcome to Termux!

Online help:     https://termux.com/help
Community forum: https://termux.com/community
IRC channel:     #termux on freenode
Gitter chat:     https://gitter.im/termux/termux
Mailing list:    termux+subscribe@groups.io

Search packages:   packages search <query>
Install a package: packages install <package>
Upgrade packages:  packages upgrade
Learn more:        packages help
$ cd /
$ cd sdcard
$ ls
10k_most_common.txt
Android
Audio
Contact
DCIM
Document
Download
HDC
LOST.DIR
Lenovo
Movies
Music
Pictures
SHAREit
Telegram
Video
WEPCrack.py
WhatsApp
admin-panel-finder
com.facebook.orca
com.kingroot.kinguser
com.kingstudio.purify
krsdk-b105006-stock-conf
mp3
niemlpscrk.sh
nifbpscrk.pl
niwbspscrk
niwppscrk
tencent
tmpCloseTime.dat
toprange
torshammer
trlocker_debug.txt
$ python2 WEPCrack.py wlan0
+------------------------+

You must be root.
$ su
root@A5000:/storage/sdcard0 # python2 WEPCrack.py wlan0
k_shell/10145:2080: python2: not found
127|root@A5000:/storage/sdcard0 #

**Comment by tinydynamite00** [comment]
To my knowledge, executing scripts from internal/external storage is not possible due to Android's permissions model. They need to be run from the Termux userspace.

I haven't looked at the <code>su</code> script in Termux in a while, but have you tried installing/running <code>tsu</code>? It's a wrapper script for su which preserves  environment variables, e.g. LD_LIBRARY_PATH required by Termux to function properly for root.

Also, you may want to have a look at «termux-sudo», the work of @kennethho here: 
https://gist.github.com/kennethho/bc7502dcf6c0b4a53ef85758f797fc8b

**Comment by NickVendetta** [comment]
I has install/running tsu...but it not work even i run on termux userspace..

**Comment by Grimler91** [comment]
@NickVendetta it's saying that it doesn't find python2, i.e. python2 isn't found in PATH. Try executing it with the full path instead: `/data/data/com.termux/files/usr/bin/python2`

(I don't think wepcrack.py will work on android though)

And please refrain from giving error reports consisting solely of the words "it doesn't work", this tells us absolutely nothing.
